### ISSUE TITLE
Update Settings call not sending sid cookie

### ISSUE THREAD

**Issue by jde** [coralproject/talk#100]
### Expected behavior

When we update settings from the admin app, the front end should send the cookie.

### Actual behavior

The cookie isn't in the header, so the backend is sending a 401.

### Steps to reproduce behavior

Log into the admin app.
Click Settings.
Click Save Settings.
See the 401.

**Comment by wyattjoh** [comment]
The fetch call should include the option `credentials: 'same-origin'` if it doesn't already.

**Comment by jde** [comment]
Fixed!
