### ISSUE TITLE
Ability to invite team members to join Talk

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1011]
Story: As a Talk admin, I want to be invite my moderation team to create Talk accounts, so I don't have to do this manually

AC:
- Admin emails a link (directly from the Talk admin) to create an account
- User gets a special link to create an account, the invitee need to add a Username and Password
- Automatically at Moderator permission level
- If email already exists, show a nice message letting the admin know the user is already in the system

Also 2 ways to invite team members - 1) during initial install and then 2) from the Talk admin continuously

Designs/flows:

![first-time install_success](https://user-images.githubusercontent.com/1077300/31177196-243928b2-a90d-11e7-83d7-cd2ff5df875b.png)
![email invite - user leaves the second invite blank](https://user-images.githubusercontent.com/1077300/31177198-26ba972e-a90d-11e7-9341-7c2bbae4ee21.png)
![email invite sent user skips the email address field](https://user-images.githubusercontent.com/1077300/31177202-29f195e6-a90d-11e7-90ca-409be3e49cac.png)
![email invite sent user skips the username field](https://user-images.githubusercontent.com/1077300/31177206-2deed38e-a90d-11e7-9507-c6e0ad44b913.png)
![email invite success](https://user-images.githubusercontent.com/1077300/31177215-31f94374-a90d-11e7-93ce-2b67ceda1229.png)

**Comment by gerardogalvez** [comment]
No Invite another team member button during install?

**Comment by kgardnr** [comment]
@gerardogalvez yes we want to include this too!

**Comment by tcmal** [comment]
Model RecruitmentKey:
  - Hash
    - Random hex, 32 long.
  - Role targeted
  - Email
  - Username

Routes:
  - GET `/recruit/:key`
    - Enter Password & double check email+role
    - Submits to `/api/v1/recruit/:key`
  - POST `/api/v1/recruit/:key`
    - Email auto-confirmed, redundant.
    - Whoever created the link gets an email
    - Redirects to `/admin`

Views: 
  - Using Recruitment key view
  - Initial invite view (end of setup)
  - Generate more invite(s) from admin panel
    - Link somewhere

Does this look about right?

**Comment by kgardnr** [comment]
Thanks @tcmal! Our team is just wrapping up GDPR support, but we will get back to you on this by next week!

**Comment by wyattjoh** [comment]
Will be resolved in v5.
