### ISSUE TITLE
[Plugin] Slackbot for Talk

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1016]
AC:
- Slackbot that automatically posts new comments to a Slack channel
- This would be useful for small newsrooms and blogs

**Comment by vickychijwani** [comment]
I'd like to try tackling this if it's not taken :smile:

My current plan is to try to create a Talk server-side plugin (assuming the plugin API is flexible enough to support it), which, given a [Slack Webhook URL](https://api.slack.com/incoming-webhooks), posts all new comments to it as soon as they arrive.

**Comment by wyattjoh** [comment]
That sounds great @vickychijwani! Check out https://github.com/coralproject/talk/blob/ef49d9a3d2acc4d2fc03b00e0c872dfbc57f005a/docs/_docs/04-04-plugins-server.md for some documentation on the server side plugins.
