### ISSUE TITLE
Make Community people search better

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1020]
AC:
- Make full text search? (From Wapo: Eg., when looking for all usernames with “Reyna” in them, I can’t search for Reyna.  Must search for “Erik Re” to get them all.  Looks like the search is a like, not a contains.  Or something.)

**Comment by wyattjoh** [comment]
Right now we do a prefix search against `username` and `email`. Possible improvements can be made to make the search better. See https://github.com/coralproject/talk/blob/ff9ae035224865ee2ed5ae30100a5632fd9d41e2/services/users.js#L626-L658

**Comment by kgardnr** [comment]
Fixed in #1093
