### ISSUE TITLE
Make columns sortable in Community > People

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1021]
AC:
- Currently these columns are not sortable
- Be able to toggle sort chronologically
- Have to consider large sets of data, and how this would work with pagination

**Comment by gerardogalvez** [comment]
Sortable with a button like the one in the Moderate section? I noticed that clicking in the column headers sorts the list according to the column.

You can see in the attached gif that clicking on Account Creation Date sorts them by creation date. The same happens with Status, and Username and Email.

![2017-10-07 16 15 03](https://user-images.githubusercontent.com/8509232/31311852-bfd47c08-ab7a-11e7-9636-31bf7b017c0b.gif)

**Comment by kgardnr** [comment]
@gerardogalvez yes, it's sort of working there. I think making it obvious that the columns are sortable - perhaps with a small icon. And also showing the mouse as a pointer so it's obvious it's clickable.

**Comment by gerardogalvez** [comment]
@kgardnr Do you think something like this would be clear enough? I could submit a PR with it.
![2017-10-10 17 37 26](https://user-images.githubusercontent.com/8509232/31414090-e15c6dd6-ade1-11e7-975e-7a91449097e7.gif)

**Comment by wyattjoh** [comment]
Does this sort work when you have more than one page of data?

**Comment by gerardogalvez** [comment]
@wyattjoh I'll take a look a it today? What would the expected behavior be, sort every row or only the ones in the current page?

**Comment by wyattjoh** [comment]
The expectation is for large organizations with many users, it would sort across all users, not only one visible. Likely, the graph query should be adjusted to take some ordering parameters.
