### ISSUE TITLE
Quiet logs on production mode

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1022]
Example from The Washington Post:
`bundle.js:967 WARNING: heuristic fragment matching going on!`

**Comment by wyattjoh** [comment]
To be more specific, this is related to logging from the client code.

**Comment by nikoferro** [comment]
Hey, if this one is not taken, i would like to contribute to the project :) 
Just to double check, does this means suppressing all logging on the client side (on production mode), or are there any logs that should still appear after the change and just hide warnings and errors?

**Comment by wyattjoh** [comment]
From my read of this warning, it's coming from an external package.

My best guess at a direction to take is to remove all `console.log` statements at build in production mode. Feel free to take a stab at if you like @nikoferro =D

**Comment by nikoferro** [comment]
@wyattjoh sorry for the late reply, been disconnected the last few days. I ll take a shot at this one!
