### ISSUE TITLE
Password reset flow should match designs

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1024]
How it looks currently:

![screen shot 2017-05-04 at 9 01 39 am](https://user-images.githubusercontent.com/1077300/31180251-0f43d6ba-a916-11e7-8751-e3d9df82ef54.png)

How it should look:
[Reset PW_Email address not found (2).pdf](https://github.com/coralproject/talk/files/1356051/Reset.PW_Email.address.not.found.2.pdf)
[Reset PW_incorrect PW.pdf](https://github.com/coralproject/talk/files/1356053/Reset.PW_incorrect.PW.pdf)
[Reset PW_successful.pdf](https://github.com/coralproject/talk/files/1356054/Reset.PW_successful.pdf)

**Comment by rocketsalander** [comment]
I'll like to check this one but you guys have a contribute.md?

**Comment by wyattjoh** [comment]
We do @SioJL13, check out https://github.com/coralproject/talk/blob/master/CONTRIBUTING.md

**Comment by lancekruegger** [comment]
@SioJL13, have you cracked into this yet? If you decide you'd like to focus on something else let me know! :-)

**Comment by lancekruegger** [comment]
@SioJL13, I've submitted a potential fix, if you want to get the credit feel free to speak up, and to the contributors, disregard my PR. 😄
