### ISSUE TITLE
Add more shortcuts for Moderators

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1025]
AC:
 - Tab to switch through mod queues
 - Ctrl-Z to undo actions
 - Ctrl-F to bring up search

**Comment by gerardogalvez** [comment]
I'd like to take a look at this!

**Comment by kgardnr** [comment]
Great @gerardogalvez! Welcome :)

**Comment by gerardogalvez** [comment]
@kgardnr Hi! I noticed that switching between queues with tab would sometimes focus the address bar in the browser and in my opinion it felt weird while switching queues, so I used T for now. I already have the Search and Switch Queues shortcuts, but the undo one seems more complicated that the other ones, maybe include it in a separate issue?
