### ISSUE TITLE
[Plugin] Social Share

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1026]
Story: As a comment reader, I want to be able to easily share my favorite comments through social media as well as permalinks 

AC:
- Should be a plugin
- Create Share button that easily shares an article on social media
- Twitter, Facebook to start
- Clicking on the icon in the popup prompts that social site's share dialogue

Button added to the right comment actions slot:
![coral_talk_share_button](https://user-images.githubusercontent.com/1077300/31282755-6ba5e948-aaab-11e7-9737-b4f454966fc0.png)

Dialogue opens when clicked:

![coral_talk_share_dialogue](https://user-images.githubusercontent.com/1077300/31282775-7a758d66-aaab-11e7-883a-456a6c9d77d0.png)

**Comment by sagarvd01** [comment]
where do you want to add this plugin?

**Comment by kgardnr** [comment]
Hi @sagarvd01! You can either host it in your own repo, or you could submit it to our core `plugins` directory.

@cvle do you have any preference for where this sort of plugin might live?

**Comment by sagarvd01** [comment]
Hi @kgardnr you mentioned that you're a comment reader and want to share comments and permalinks to social media. my question is on which site? because each site have different structure. From which site you want to share comments?

**Comment by kgardnr** [comment]
Hi @sagarvd01 I've attached some designs above to explain more how this should function - let me know if you have more questions!

**Comment by sagarvd01** [comment]
Hi @kgardnr the layout is clear but there are many comment services like disqus. each of them have different structure. In which platform you want this button to work? I mean in disqus or some other services like that?

**Comment by kgardnr** [comment]
Hey @sagarvd01! This is a feature suggestion for OUR comments platform called Talk - that's the repo you're in right now 😝

**Comment by AnneTheAgile** [comment]
@kgardnr maybe this story could be broken up into two parts so that it is more agile? eg
- as a commenter I would like to have a permanent Url visible on each remark so I can find it again
- as a commenter I would like a button to speed up social sharing of a link so I don't have to go to another page
//on WSJ there are already links, so maybe that part is done?

**Comment by kgardnr** [comment]
Hi @AnneTheAgile! Thank you for this feedback! Yes, we already have a permalink link, it looks like this:

<img width="637" alt="permalink_share" src="https://user-images.githubusercontent.com/1077300/34211564-789c394e-e567-11e7-9651-8cc9704c5508.png">

So the story here is enhancing that link to make it easy to share (like on Twitter and Facebook) as per the image attached above.

What do you think?

**Comment by kgardnr** [comment]
Hey @AnneTheAgile and @sagarvd01 if either of you still wants to work on this, just make sure you follow the upgrade instructions for v4.0.0: https://coralproject.github.io/talk/migration/4/
