### ISSUE TITLE
Bulk approve/reject actions for Moderators 

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1027]
AC:
- Ability to Select All comments and make an action to reject or approve
- This functionality would be located on the User History drawer

Design:
![select all comments](https://user-images.githubusercontent.com/1077300/31180677-23444234-a917-11e7-9184-0a0da65fee33.png)

**Comment by facuesr** [comment]
Hi @kgardnr I'd like to work on this feature.

**Comment by kgardnr** [comment]
That sounds great @facuesr! We'd love to have you help with this :)

**Comment by kgardnr** [comment]
Fixed in #1104
