### ISSUE TITLE
Ability to search comments by keyword

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1028]
Story: As a moderator, I want to search for particular words in all the comments, so that I can see if they're being used frequently to troll/attack people 

AC:
- A moderator can perform boolean searches - add a "by: user" to find if a certain user is writing the same word a lot
- A moderator can select and reject comments from the search results

**Comment by MuraraAllan** [comment]
How we are working over this repository ? 
Pull Request Race or pick and done?

I would like to get this one if pick and done :)

**Comment by kgardnr** [comment]
Hi @MuraraAllan -- welcome! You can just express you intention to pick up an issue here in the comments like you did :)
