### ISSUE TITLE
Moderation nav and queue bars stop at 1280px

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1029]
### Expected behavior

Width is correct but should have overflow colors

### Actual behavior

Admin navigation bars cut off at 1280px

**Comment by tylerbrewer2** [comment]
@kgardnr I can work on this, but want to get more clarification. Are you saying you want the colors in navigation bars to extend full width but the content within to remain at 1280px?

**Comment by kgardnr** [comment]
@tylerbrewer2 welcome! That sounds great. Let me get @IAmSamHankins to confirm the above for you.

**Comment by theysamtheirs** [comment]
hey @tylerbrewer2 thanks for your interest! yep! that is exactly what we need. unfortunately when we had implemented this nav, we didn't take into account any excess widths or overflow!

**Comment by tylerbrewer2** [comment]
thanks @IAmSamHankins! Should have a PR tonight
