### ISSUE TITLE
UI to customize CSS

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1030]
AC:
- Be able to update basic CSS styles via the Admin so you don't have to be a developer to customize your own Talk
- Button colors, fonts, what else?

**Comment by Barathwaja** [comment]
@kgardnr so as an admin you need a UX way of setup so that you can drag and drop or change color or size etc so that reflects all other users .. Right?

I'll sneek peek on this but not sure how well it will work.

Any installation details you got?

**Comment by vickychijwani** [comment]
How would this interact with the existing "Custom CSS URL" option on `/admin/configure`? Both options are useful in different contexts:

- Custom CSS styles (this issue) is useful for designers and developers to quickly customize the look-n-feel
- Custom CSS URL is useful for (possibly) sharing share the same custom stylesheet across multiple Talk deployments

**Comment by wyattjoh** [comment]
Do you think that we can expand this feature @kgardnr?

**Comment by kgardnr** [comment]
Apologies @vickychijwani - this feature needs to be fleshed out a bit more. I'll add more details tomorrow! Thank you!
