### ISSUE TITLE
Call override CSS after other CSS in embed

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1034]

**Comment by ppatel221** [comment]
Hey, I've fixed a bug similar to this before. Is it okay if I take over?

**Comment by kgardnr** [comment]
Sure!

**Comment by ppatel221** [comment]
Can you help me get started with this? How can i get this on my local?

**Comment by okbel** [comment]
Hey @ppatel221! Here are the installation and configuration guides. https://coralproject.github.io/talk/installation-from-source/ 

Let me know if you have any questions!

**Comment by kgardnr** [comment]
Hey @ppatel221! Did you still wanna look into this? If so, make sure you go through the upgrade instructions for 4.0.0 https://coralproject.github.io/talk/migration/4/ - let us know if you need anything!

**Comment by jmuzsik** [comment]
Hi! I'd be willing to do this

**Comment by kgardnr** [comment]
Fixed
