### ISSUE TITLE
When a user is suspended and tries to post, show them an informative error message

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1035]
AC:
- Currently says: "An unexpected error has occurred".
- Should say: "Your account is currently suspended. It will be reactivated in [TIME]. Please contact us if you have any questions."

**Comment by fernandezpablo85** [comment]
I'd be happy to work on this if it's still available.

**Comment by kgardnr** [comment]
@fernandezpablo85 yes it is! Welcome and thank you! :)

**Comment by kgardnr** [comment]
Hey @fernandezpablo85 how's it going with this? Can we help or support you in any way?

**Comment by fernandezpablo85** [comment]
Sorry, I had to travel for work and I'm having trouble finding free time to
setup the dev environment :(. If there's someone else that can tackle it
faster feel free to unassign me and give the issue to him/her.

**Comment by kgardnr** [comment]
No worries @fernandezpablo85! Thanks for letting us know, but feel free to take your time and get to this when you can too :)

**Comment by facuesr** [comment]
Hi @kgardnr , hope you are doing well!! Can I take a look at this?

**Comment by kgardnr** [comment]
Sure that sounds great!

**Comment by kgardnr** [comment]
Hey @facuesr did you still want to work on this by chance? If so, make sure you go through the upgrade instructions for 4.0.0 https://coralproject.github.io/talk/migration/4/ - let us know if you need anything!
