### ISSUE TITLE
Readers and commenters should always be notified when an action has failed

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1038]
This applies to the stream-side for:
- Reactions
- Tagging
- Flagging
- Changing settings

**Comment by PepeFranco** [comment]
I will take a look at this

**Comment by PepeFranco** [comment]
Hey @kgardnr I just submitted pull request #1081 for flagging. 

When it comes to reactions it seems there is already notifications to users if I am not mistaken.

https://github.com/coralproject/talk/blob/7600ce8d262d22db40b9d931f1f55acbd675ad8f/plugin-api/beta/client/hocs/withReaction.js#L266

Same thing with tagging

https://github.com/coralproject/talk/blob/7600ce8d262d22db40b9d931f1f55acbd675ad8f/plugin-api/beta/client/hocs/withTags.js#L60

And for settings Im not sure where to look at. Can you point me in the right direction?

Thanks!

**Comment by kgardnr** [comment]
Hi @PepeFranco! For the settings, it should be if they try and Save any settings in the Configure tab. Thank you for submitting that PR, we will review it shortly.

**Comment by kgardnr** [comment]
Fixed in #1081
