### ISSUE TITLE
Better error message for 1 character comments 

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1043]
This happens when a commenter tries to post a comment with only 1 character.

Currently it says: *Sorry! An unexpected error occurred.*

Should say: *Comments should be more than one character, please revise your comment and try again.*

**Comment by wyattjoh** [comment]
Error is thrown from: https://github.com/coralproject/talk/blob/ab1f1dee3e1110e276724c103bf681054b78b7e2/graph/mutators/comment.js#L237-L240

**Comment by dusty-wil** [comment]
Hiya, if this issue is still available, I'd be happy to take a look at it!

**Comment by kgardnr** [comment]
@dusty-wil sure is! Welcome and thank you!

**Comment by dusty-wil** [comment]
Thanks, @kgardnr! When I try to duplicate this, the error I get is "Your comment must have something in it" ... rather than "Sorry! An unexpected error occurred." I can still look at changing the error message to what's suggested in your original post, if you'd like.

**Comment by kgardnr** [comment]
Oh I see - you're right! Yes, could you update the error message to the above? I think it sounds better :) Thank you @dusty-wil!

**Comment by dusty-wil** [comment]
Thanks @kgardnr, PR sent. I think I accidentally scheduled the "Merge branch 'master' into master" in my PR as well... sorry, didn't mean to do that

**Comment by kgardnr** [comment]
No worries, @dusty-wil! Thank you!

**Comment by kgardnr** [comment]
Fixed in #1062
