### ISSUE TITLE
When I've already reported a comment, the Reported button shouldn't then be clickable

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1044]
It's not clickable, but it looks like it should be; just need to change the mouseover behavior

**Comment by devAmoghS** [comment]
@kgardnr This is my first time on Hacktoberfest. Will be happy to help you :)

**Comment by kgardnr** [comment]
Great @devAmoghS! Welcome!

**Comment by devAmoghS** [comment]
@kgardnr how should i proceed after I am done cloning the repo ?

**Comment by kgardnr** [comment]
@devAmoghS so you'll want to create a new branch on your forked version of the repo, and then once you're done, you can submit a PR.

Here's a great guide from Github via https://opensource.guide/how-to-contribute/:

=====

- [Fork the repository](https://guides.github.com/activities/forking/) and clone it locally. Connect your local to the original “upstream” repository by adding it as a remote. Pull in changes from “upstream” often so that you stay up to date so that when you submit your pull request, merge conflicts will be less likely. (See more detailed instructions [here](https://help.github.com/articles/syncing-a-fork/).)
- [Create a branch](https://guides.github.com/introduction/flow/) for your edits.
- Reference any relevant issues or supporting documentation in your PR (ex. “Closes #1044.”)
- Include screenshots of the before and after if your changes include differences in HTML/CSS. Drag and drop the images into the body of your pull request.
- Test your changes! Run your changes against any existing tests if they exist and create new ones when needed. Whether tests exist or not, make sure your changes don’t break the existing project.
- Contribute in the style of the project to the best of your abilities. This may mean using indents, semi-colons or comments differently than you would in your own repository, but makes it easier for the maintainer to merge, others to understand and maintain in the future.

**Comment by kgardnr** [comment]
Hey @devAmoghS, how's it going with this? Is there anything we can do to help or support you?

**Comment by blackcathacker** [comment]
@kgardnr gonna give this one a try as well if thats alright.
