### ISSUE TITLE
If the Edit Timeframe Window is set to > 59 seconds, display time remaining in minutes instead of seconds

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1046]
Currently, the edit timeframe window is always displayed in seconds. We should be clever about this and display in minutes and seconds when it's more appropriate.

E.g. "300 seconds" should display as "5 minutes"

This would only be the case in displaying this on the Comment Stream to the commenter. We can keep the Configuration setting in seconds to be 100% precise.

**Comment by Rishabh04-02** [comment]
I'd like to work on the issue.

**Comment by kgardnr** [comment]
Hi @Rishabh04-02! That sounds great, welcome and thank you!

**Comment by holmberd** [comment]
I'm sorry to butt in, but I ended up writing a PR for it, see https://github.com/coralproject/talk/pull/1058

**Comment by Rishabh04-02** [comment]
@kgardnr Please review #1059

**Comment by kgardnr** [comment]
Hi @Rishabh04-02 and @holmberd! Thank you both for your efforts! I'm going to have to go with Risha's PR, Dag, because he did claim the issue first. I do hope you both continue to contribute to Talk, we would love to have you both involved :)

**Comment by holmberd** [comment]
Haha no worries. Surprisingly similar solution ;)

**Comment by kgardnr** [comment]
Fixed in #1059
