### ISSUE TITLE
Add "Undo Reject Comment" to in-stream moderation actions

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1047]
Story: As a moderator, I would like to undo a comment rejection right after I've rejected it, so I can undo a mistake

AC:
- If I'm logged in as an Admin or Moderator, I have access to the Moderation Actions dropdown on each comment
- If I click Reject Comment, the comment immediately becomes tombstoned
- We want to add an Undo button there on the tombstone in case a Moderator makes a mistake 

![pasted image at 2017_09_05_02_38 pm](https://user-images.githubusercontent.com/1077300/31190891-63913046-a934-11e7-8f4b-e854b31e40fc.png)

And for reference, here is the Reject button which already exists:

![reject - instream](https://user-images.githubusercontent.com/1077300/31190918-751df272-a934-11e7-98e0-4c51f3cb0444.png)

**Comment by devonjs** [comment]
hi @kgardnr can i take a look at this one? mind if I take some time to get my environment up and follow-up with some questions?

**Comment by kgardnr** [comment]
Sure @devonJS! That would be great - welcome! Let us know any questions you have.

**Comment by devonjs** [comment]
@kgardnr just a quick update, got my environment up tonight, will have to play around the admin dashboard a bit

**Comment by kgardnr** [comment]
Awesome @devonJS, let us know if there's anything we can do to help or support ya! :)

**Comment by devonjs** [comment]
@kgardnr got some of this working, do you have a preferred timeout for the undo tombstone to disappear?  or should it persist until the user navigates away?  Also, would this.props.data.refetch() be the appropriate way to reload the comments in the moderation container?  it seems to work, but does a little flash when reloading.

**Comment by devonjs** [comment]
@kgardnr added PR at #1117

**Comment by devonjs** [comment]
@kgardnr updated in-stream undo #1149

**Comment by kgardnr** [comment]
Fixed in #1149
