### ISSUE TITLE
When a story is set to "Premoderate links", the comments with links detected should go to Reported queue

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1048]
### Expected behavior

The comment should go to Pre-Mod Queue.

### Actual behavior

The comment is going to the Reported Queue.

### Steps to reproduce behavior

1. Go to Configuration on a story/article
2. Click "Pre-moderate comments containing links" and hit Save
3. Enter a comment with a link, e.g. "www.google.com"
4. See that the comment goes to Reported; it should go to Pre-Mod

**Comment by MisaOgura** [comment]
I'll take this one as well, as it's quite related to https://github.com/coralproject/talk/issues/1049

**Comment by kgardnr** [comment]
Great @MisaOgura! Thank you!

**Comment by kgardnr** [comment]
Hey @MisaOgura how's it going? Is there anything we can do to help or support you?

**Comment by MisaOgura** [comment]
@kgardnr hey I think I'm not experienced enough with graphql to tackle this... I'll step down from this and the other one so others can take over, sorry about it 😞
