### ISSUE TITLE
When premod is turned on site wide, it should show that pre-mod is on in the individual stream setting as well

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1049]
### Expected behavior

If "Pre-mod" is on site-wide, it should show in each individual stream's settings.

### Actual behavior

It's not reflecting the global setting in the individual settings.

### Steps to reproduce behavior

1. Turn on "Pre-mod" via Admin > Configure > Moderation Settings
2. Go to an individual article and click on the Configure tab
3. See that the "Pre-mod" setting is unchecked; it should be checked

**Comment by MisaOgura** [comment]
Hey @kgardnr really like the project, it's really neat!

I'm interested in taking this up and would like to clarify the requirement:

The pre-mod checkbox of the "coral talk" (this is a default article, I suppose?) correctly reflects the config set on admin, on refresh.

Am I correct to understand that the pre-mod checkbox should be checked _without_ a refresh on the individual articles, once it's changed on the global config?

**Comment by MisaOgura** [comment]
I'll start working on this 👍

**Comment by kgardnr** [comment]
Welcome @MisaOgura! That sounds great!

**Comment by MisaOgura** [comment]
I'm no longer working on this one, please feel free to tackle this. sorry @kgardnr 😞 really nice project though 👍

**Comment by kgardnr** [comment]
Awww that's a bummer @MisaOgura! If you change your mind or want us to recommend something else that might be interesting, just let us know - thanks for your support and interest!! 🎉

**Comment by AnneTheAgile** [comment]
@kgardnr I see here that the variable 'moderation' is used but not  defined anywhere previously in this file. 
https://github.com/coralproject/talk/blob/9e486f3a9dfeca857a55c8a19819fb960378284c/graph/mutators/comment.js#L393
Would there be global variables lurking? Or would this indicate the fix is to initialize 'moderation'?

**Comment by kgardnr** [comment]
Hi @AnneTheAgile! It's a configuration variable yes called `PREMOD` - you can see that here:

https://github.com/coralproject/talk/blob/99daa0b2c92e140894545b1820d5df680f29a5f5/graph/typeDefs.graphql#L244

**Comment by kgardnr** [comment]
Hey @AnneTheAgile! If you still wants to work on this, just make sure you follow the upgrade instructions for v4.0.0: https://coralproject.github.io/talk/migration/4/

**Comment by kgardnr** [comment]
This is fixed
