### ISSUE TITLE
SPIKE: Host all assets ourselves?

### ISSUE THREAD

**Issue by jde** [coralproject/talk#105]
Should we host all of our assets ourselves?

If so, how should we publish them?

**Comment by wyattjoh** [comment]
+1 for hosting it ourselves. We'll control the environment + versions + integrity. If the user wants to worry about performance they can put cloudfront in front of it to add a cache layer.

**Comment by riley** [comment]
👍 definitely host it ourselves. we'll save ourselves a lot of headaches with dumb stuff that randomly comes up. And I don't think a big publisher is going to want to depend on npr's hosting for pym.js (just as one example) in prod.

**Comment by kgardnr** [comment]
Will be addressed here: https://www.pivotaltracker.com/story/show/135142971

**Comment by impronunciable** [comment]
Which assets are we talking about?

**Comment by riley** [comment]
stuff like pym.js and materialize.css

**Comment by wyattjoh** [comment]
Seems that a MDL css lib that is externally loaded is causing the following issue: https://github.com/coralproject/talk/issues/107

**Comment by jde** [comment]
At this point we are only loading external fonts. Loading without them falls back to defaults which are acceptable to me.

Should we host fonts / use defaults?
