### ISSUE TITLE
Send a user an Email Notification if they are banned

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1050]
Story: As a commenter, I want to be notified by email if I've been banned, so I can proactively be aware of what's happening

AC:

- Same flow as with a Suspension -- > upon being Banned, a user is sent an email
- Subject: "[Talk] Your account has been banned"
- Message: "In accordance with The Coral Project’s community guidelines, your account has been banned. You are now longer allowed to comment, flag or engage with our community."

**Comment by moyamanuel** [comment]
Hello @kgardnr,

I'm trying to get up to speed with the codebase so I can start contributing. Can you explain how the ban system works?

**Comment by kgardnr** [comment]
Hi @moyamanuel - welcome!

Sure thing.

So a moderator can ban a user from the comment stream (visible only to Admins and Mods):

<img width="676" alt="ban_user_stream" src="https://user-images.githubusercontent.com/1077300/31192295-ca54ff16-a938-11e7-9eda-d6a2f32a089e.png">

Or they can click on the Actions dropdown on a particular user in the Admin - the 2 options there are Ban and Suspend.

<img width="705" alt="suspend" src="https://user-images.githubusercontent.com/1077300/31192297-cc7e0ac6-a938-11e7-865b-dec9cbfb8d34.png">

When the user is banned, they're no longer allowed to post comments or take actions on the site, and they see a message at the top of their stream saying they're banned.

The only way to un-ban a user is for a moderator to go to the Community > People page, find the user, and set their status back to Active.

We would also like them to receive an email telling them they're banned.

**Comment by kgardnr** [comment]
@moyamanuel added some more details above!

**Comment by moyamanuel** [comment]
Awesome, thank you for the explanation, @kgardnr. I'll submit a PR shortly.

**Comment by kgardnr** [comment]
Great @moyamanuel! 🎉

**Comment by varunzxzx** [comment]
May I know the file where the user schema gets updated to 'BANNED'

**Comment by blackcathacker** [comment]
@kgardnr Gave this one a try. See PR #1137.

**Comment by kgardnr** [comment]
Fixed in #1137
