### ISSUE TITLE
Auto-approve reported usernames of Admins, Moderators, and Staff members

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1051]
Story: As a moderator, I want usernames of admins, mods and staff members to be auto-approved, so I don't have to ever moderate them

AC:
- If someone flags a username of an admin, moderator, or staff member, the username is not shown as Reported, and the username does not to go to Flagged Usernames queue in Community

**Comment by holmberd** [comment]
I wouldn't mind taking a look at this.

**Comment by kgardnr** [comment]
That would be awesome @holmberd!

**Comment by kgardnr** [comment]
@holmberd Did you still wanna look into this? If so, make sure you go through the upgrade instructions for 4.0.0 https://coralproject.github.io/talk/migration/4/ - let us know if you need anything!

**Comment by kgardnr** [comment]
This is fixed!
