### ISSUE TITLE
Support for Own User Database/ Login?

### ISSUE THREAD

**Issue by adamdpate** [coralproject/talk#1055]
It looks like the documentation is currently in the process of being updated, but I didn't see anything about integrating _talk_ with my own database and user authentication tokens. Is it possible to pass authenticated user tokens into the _talk comment system_ and use my current user login? Or does talk only work if users create an account through the talk signup? 

I'm hoping to modify talk to be used within a webapp, but that may be too far from the intended use case. Love what you've done so far though -- excited to see where the project goes regardless!

**Comment by kgardnr** [comment]
Welcome @adamdpate! Thanks, this is a great question.

So yes, for custom auth/login, you will need to create your own auth plugin and attach it to your database. Here's our own auth-plugin you can certainly reference, or use as a template to make your own: https://github.com/coralproject/talk/tree/master/plugins/talk-plugin-auth 

We also support a ton of token customization via Advanced Configuration here: https://coralproject.github.io/talk/advanced-configuration/ 

And yes, we're working on updating the docs around all this, but here are some helpful release notes and PRs that might come in handy for you as well:

- https://github.com/coralproject/talk/releases/tag/v3.1.0 check out the JWT section
- https://github.com/coralproject/talk/pull/831
- https://github.com/coralproject/talk/pull/845

**Comment by kgardnr** [comment]
And PS - thank you for the kind words! <3

**Comment by wyattjoh** [comment]
To be specific (and this will be added to the docs soon), you have to implement the https://github.com/coralproject/talk/blob/ef49d9a3d2acc4d2fc03b00e0c872dfbc57f005a/docs/_docs/04-04-plugins-server.md#field-tokenusernotfound `tokenUserNotFound` hook for your server plugin which will turn an auth token into a user.

You must also pass the token that you want to use with auth through to the talk embed. If you created the talk embed like this:

```js
var embed = Coral.Talk.render(document.getElementById('coralStreamEmbed'), {
  ...
});
```

You can call:

```js
embed.login(<token>);
```

Or pass it initially by setting:

```js
var embed = Coral.Talk.render(document.getElementById('coralStreamEmbed'), {
  ...
  auth_token: <token>
});
```

And the existing login flow will handle the rest. More docs to come, but I hope this gets you started @adamdpate.

**Comment by adamdpate** [comment]
Perfect, those links look like a great place to start. Just wanted to see if this was supported before diving in. I'll be keeping a look out for the new documentation.
