### ISSUE TITLE
404 - on documentation

### ISSUE THREAD

**Issue by raphaelpor** [coralproject/talk#1064]
Hi folks!

I can't access some URL's on the new documentation, like [this](https://coralproject.github.io/talk/docs/plugins/client/).

Could someone help me?

**Comment by kgardnr** [comment]
Hey @raphaelpor, we're in the midst of rewriting our docs. Were you looking for documentation on plugins, because you can find that here: https://coralproject.github.io/talk/plugins/

This is the docs root: https://coralproject.github.io/talk/

Let me know if that helps!

**Comment by raphaelpor** [comment]
Hey @kgardnr!

Thanks for your help.
But now, I can't find a documentation for the Rest API of Coral Talk. 😕 
Do you know where is it?

**Comment by wyattjoh** [comment]
Here's our existing REST API Docs @raphaelpor: https://github.com/coralproject/talk/blob/ef49d9a3d2acc4d2fc03b00e0c872dfbc57f005a/docs/swagger.yaml

Bear in mind, as we're improving our GraphQL schema, we'll eventually deprecate most if not all of the existing REST endpoints.

**Comment by raphaelpor** [comment]
Thanks @wyattjoh!
