### ISSUE TITLE
Setup Debugger for Coral/talk!

### ISSUE THREAD

**Issue by Goyapa** [coralproject/talk#1069]
Setup debugger for attaching client and server to the running process in VS Code

tl;dr
@gabelula @cvle @okbel @wyattjoh
Does anyone use VS Code and could please share his/her `launch.json`.

```
.vscode/launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Client",
            "type": "chrome",
            "request": "launch",
            "sourceMaps": true,
            "url":"http://localhost:3000/admin",
            "webRoot": "${workspaceRoot}/talk/dist/coral-admin/bundle.js.map"
        },
        {
            "name": "Server Attach to Process",
            "type": "node",
            "request": "attach",
            "processId": "${command:PickProcess}",
            "port": 3000
        }
    ],
    "compounds": [
        {
            "name": "Server/Client",
            "configurations": ["Server Attach to Process", "Client"]
        }
    ]
}

```
Client Launch configuration does not find souremaps.
I tried different files and folders...
And I would like to change from launch to attach.

Server configuration is crashing.
I tried different settings with and without --inspect.
```
.nodemon.json
{
  "inspect": true,
  "verbose": true,
  "ignore": ["test/*", "client/*", "dist/*", "plugins/*/client"],
  "ext": "js,json,graphql"
}

```

Thank you in advance.

**Comment by wyattjoh** [comment]
We currently don't use debugging tools server side @Goyapa. We also don't provide any debugging config as we wanted to remain editor agnostic. If you are able to discover a working configuration, feel free to post the result here and we'll look at integrating it.
