### ISSUE TITLE
Failed to load resource when Privacy Badger extension is enabled.

### ISSUE THREAD

**Issue by gabelula** [coralproject/talk#107]
### Expected behavior

All styles should be loaded correctly in the Chrome browser with the privacy-badger enabled.

### Actual behavior

There is a 'Failed to load resource: net::ERR_BLOCKED_BY_CLIENT' error when trying to load some styles.

**Comment by wyattjoh** [comment]
Can you see what is necessary to reproduce this? I would assume that only resources that are considered "trackers" would be blocked...

**Comment by gabelula** [comment]
Yes. Right now is https://code.getmdl.io/1.2.1/material.indigo-pink.min.css

<img width="1280" alt="screen shot 2016-12-19 at 9 43 47 am" src="https://cloud.githubusercontent.com/assets/28330/21322845/bfcf4c92-c5cf-11e6-99df-d7e5091d8aa2.png">

**Comment by wyattjoh** [comment]
This will be resolved by https://github.com/coralproject/talk/issues/105

**Comment by gabelula** [comment]
Yes. Perfect!
