### ISSUE TITLE
Edit message and buttons don't show on Windows/IE11

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1071]
### Expected behavior

It should look like this:

#### === Edit Countdown ===

<img width="663" alt="editing_working_correctly" src="https://user-images.githubusercontent.com/1077300/31283549-dc63380a-aaad-11e7-81b0-5b13d55f93d6.png">

#### === Close Dialogue after Timeout ===

<img width="657" alt="close_edit_working" src="https://user-images.githubusercontent.com/1077300/31283820-98ed4178-aaae-11e7-8f06-1bb25d69cdad.png">

### Actual behavior

Instead it looks like this:

#### === Edit Countdown ===

![coralstaging](https://user-images.githubusercontent.com/1077300/31283479-ae910542-aaad-11e7-8661-715494129228.PNG)

#### === Close Dialogue after Timeout ===

![closeoff](https://user-images.githubusercontent.com/1077300/31283881-d02ab828-aaae-11e7-866a-cfc98ca72f7d.PNG)

### Steps to reproduce behavior

1. Running IE11 on Windows, go to a comment stream
2. Post a comment
3. Click 'Edit'
4. You should see the above

**Comment by facuesr** [comment]
Hi! I'll take a look on this.
