### ISSUE TITLE
Invite Friends feature

### ISSUE THREAD

**Issue by cloudkompute** [coralproject/talk#1074]
A user clicks "Invite Friends" link
A dialog box appears
The user inputs a list of email addresses separated by comma and clicks a Send button 
The system sends an email to all the user's friends (probably the user's email address in the From field)
A friend clicks the Invitation link and the system takes him/her to the Sign Up page.

Thanks and Regards to the development team

**Comment by wyattjoh** [comment]
We currently don't have plans for this feature on our roadmap, we'll update this ticket if that outlook changes.
