### ISSUE TITLE
Server Side Rendering (SSR) feature

### ISSUE THREAD

**Issue by cloudkompute** [coralproject/talk#1075]
Does the system support SSR feature as of now? If not, can it be implemented? This feature has been implemented in the following popular boilerplates ...

https://github.com/zeit/next.js
https://github.com/kriasoft/react-starter-kit

**Comment by wyattjoh** [comment]
We don't have any plans for now to support SSR unfortunately no. It's quite a re-engineer from our current implementation. I'll update this ticket in the future if our outlook changes.
