### ISSUE TITLE
Upgrade to React Router version 4

### ISSUE THREAD

**Issue by cloudkompute** [coralproject/talk#1076]
Currently it is supporting version 3

Probably, we'll need to upgrade the "history" package to 4.x too.

**Comment by kgardnr** [comment]
Hey @coooolers, thanks for the suggestion! Would you be interested in taking this on?

**Comment by cloudkompute** [comment]
I won't be able to do it for a couple of reasons. There is a lot of work involved in it as this is a huge project. This exercise should be done by a developer who already knows about the inner workings of the system. Secondly, I do not have that much of experience. 

Thank you for asking me though.

**Comment by wyattjoh** [comment]
As mentioned, this will require quite a lot of work to implement. Our team is not prioritizing upgrading without gain at the moment, so I'll close this issue for now and update when that changes.
