### ISSUE TITLE
No need to explicitly bind "this" to a component

### ISSUE THREAD

**Issue by cloudkompute** [coralproject/talk#1077]
Make use of babel plugin : transform-class-properties which allows us to use arrow functions that automatically binds "this" to a component. 

and by doing so, we can get rid of such kind of statements in the code:

this.handleSave = this.handleSave.bind(this);
this.handleInput = this.handleInput.bind(this);
this.handleCancel = this.handleCancel.bind(this);

**Comment by kgardnr** [comment]
@okbel or @cvle do you have an opinion on this?

**Comment by alinhle** [comment]
We already use arrow functions to bind to this on the frontend. There mind be some older code that still does the bind manually and can easily be refactored to use the arrow functions.

**Comment by okbel** [comment]
Hello @coooolers! Thanks for the suggestion but we plan on doing this progressively in each refactor or PR.
