### ISSUE TITLE
Cannot update roles in community screen

### ISSUE THREAD

**Issue by jde** [coralproject/talk#110]
### Expected behavior

Toggling roles in the community screen should update the user.

### Actual behavior

Changing to Moderator or Administrator does nots ave (I get a 200 response but refreshing shows that the change hasn't stuck)
Changing to the empty role throws a 500.

![unspecified-2](https://cloud.githubusercontent.com/assets/259957/20689380/23d3dfc0-b593-11e6-8ff8-62b0bdfd1b64.png)

### Steps to reproduce behavior

Log in as an admin
Try to change the role of a user
Refresh
see the role revert
Try to set to the 'blank role' or no role
See the 500

**Comment by wyattjoh** [comment]
Seems that the backend is trying to send back a blank role, hence the message.

**Comment by wyattjoh** [comment]
Currently as well, the roles are implemented as an array of roles rather than a single role. The FE needs to implement the ability to remove and add specific roles rather than simply "setting" the role which is what's being done now. The BE doesn't have a method for this yet, but I'd expect to see something like:

```js
...

router.delete('/:user_id/role/:role_name', authorization.needed('admin'), (req, res, next) => {
  User.removeRoleFromUser(req.params.user_id, req.params.role_name)
          .then(() => {
            res.status(204).end();
          })
          .catch((err) => {
            next(err);
          });
});

...
```

**Comment by jde** [comment]
Where to put the functionality to set a single role is an interesting question.

My instinct is to create an endpoint that clears a users roles then adds the one that is sent, effectively modeling the single role behavior.

The other option is to handle this on the front end, but asking the front end to send multiple requests to remove and add seems inefficient.

**Comment by wyattjoh** [comment]
As multiple roles can have different responsibilities (Even with overlapping responsibilities) I think that the model that we have supports this already.

I spoke with Emma regarding the UX/UI for this and I had suggested changing the role change screen to be similar to the "add a label" component for Github issues, where a dropdown shows all the possible roles, and you click to enable/disable them.

This wouldn't be multiple requests as again, a user could have multiple roles.

**Comment by jde** [comment]
I like that solution more. Moving this to a pivotal story: https://www.pivotaltracker.com/story/show/135814307
