### ISSUE TITLE
Configuration option "Pre-moderate new commenters"

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1102]
Story: As an admin, I want to pre-moderate commenters who are commenting for the first time, so that I can ensure healthy dialogue in my community

AC:
- Setting on Configuration>Moderation Settings with checkbox to "Pre-moderate new commenters". This should go below the "Enable pre-moderation" setting.

<img width="624" alt="premod_new_commenters" src="https://user-images.githubusercontent.com/1077300/31553249-bfdb524c-b031-11e7-841a-2542e8711a94.png">

- When this setting is ON, a new commenters first comment automatically is sent to pre-moderation, with the pre-moderation notification showing on the comment stream
- When this comment is approved, the commenter can comment as per normal
- Users that are designated "Staff" are excluded from pre-moderation always

**Comment by J-Wicks** [comment]
Can I give this a shot?

**Comment by kgardnr** [comment]
Yes indeed! And reach out if you need any help Jeremy!

**Comment by J-Wicks** [comment]
Thanks! I'll let you know if I get stuck!

**Comment by J-Wicks** [comment]
@kgardnr Quick question - Do you have any suggestions for how to implement the new user premod? My first thought is to add a "premod user" setting on the user model, initialize it to true, and then switch it to false when the first comment is approved. My thought is that it could be useful in the future to selectively premod users.

**Comment by kgardnr** [comment]
@J-Wicks I like that idea - because then in the future, if say a newsroom wanted to pre-mod the users first X comments, it would be easy to make that a setting and it would just switch to false whenever that X was hit.

I'll see if @cvle, @okbel or @wyattjoh have any other additional thoughts on this too!

**Comment by wyattjoh** [comment]
Already implemented via the Trust system.
