### ISSUE TITLE
Configuration option "Hide Reports from Unreliable Flaggers"

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1103]
Story:

AC:
- Setting in Configuration > Moderator Settings (this should go under Pre-mod Comments with Links setting)

<img width="631" alt="unreliableflaggers_setting" src="https://user-images.githubusercontent.com/1077300/31553408-501d7cae-b032-11e7-8371-999de4447783.png">

- Turning this setting ON ensures that Reported comments from commenters noted as "Unreliable" do not show in the Reported queue

**Comment by blackcathacker** [comment]
I'd like to give this one a shot.

**Comment by kgardnr** [comment]
Awesome @blackcathacker! Let us know if you need help or have questions 💯

**Comment by blackcathacker** [comment]
I do have questions. Once into this one, its a lot more complicated than I anticipated. The query to fetch the mod-queues simply takes an action-type, which is FLAG in this case. That query on the back-end simple looks at the current counts stored in the comment model(maintained at the time of the action). In order for this config option to work either the query on the backend needs to take into account the user data for each action or the front-end needs to do a lot more manual filtering to determine which queue an item should appear in...or is there an easier way I don't see yet? Would appreciate any thoughts or ideas... I'll keep plugging away, just afraid I'll go off in the weeds and come up with something far more complicated than necessary.

**Comment by kgardnr** [comment]
Ah, this might be a little tricky you're right @blackcathacker - do you wanna still take a stab or pick something a little smaller as your first pr?

**Comment by kgardnr** [comment]
@blackcathacker we have a bunch of issues marked "good first issue" which should be good intros to get used to working with the codebase too! https://github.com/coralproject/talk/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by blackcathacker** [comment]
Without some guidance on how you'd like the query refactored, I'll try to pull off an easier issue. Thanks!
