### ISSUE TITLE
Talk security issues in Firefox

### ISSUE THREAD

**Issue by jtnelson** [coralproject/talk#1105]
From a user:

I'm starting some tests with Talk. Maybe I've lost it on docs, the Talk just runs on HTTPS? Because I've been testing it locally and I've received "SecurityError: The operation is insecure." on some actions (embed on another page, login etc).

Can I disable this security verification on development env or something like this?

NOTE: This only happens in FF and not Chrome.

**Comment by wyattjoh** [comment]
This may be a result of having the incorrect `TALK_ROOT_URL` variable. I'll investigate anyways.
