### ISSUE TITLE
Dependencies installation being killed

### ISSUE THREAD

**Issue by gcjbr** [coralproject/talk#1114]
yarn or npm install will produce the same error

`npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated chalk@2.0.1: Please upgrade to Chalk 2.1.0 - template literals in this version (2.0.1) are quite buggy.
npm WARN deprecated validate-commit-msg@2.14.0: Check out CommitLint which provides the same functionality with a more user-focused experience.
Killed.............] | fetchMetadata: sill resolveWithNewModule parse-asn1@5.1.0 checking installable status`

I'm running this on Ubuntu 16

**Comment by wyattjoh** [comment]
This looks like it may be a RAM issue, `yarn install` typically consumes a lot of it.

**Comment by gcjbr** [comment]
> This looks like it may be a RAM issue, yarn install typically consumes a lot of it.

Uhnnn ... 

I'll edit package.json in chunks and try it .

I'll report back

**Comment by kgardnr** [comment]
Any luck @souljacker?

**Comment by sidzan** [comment]
I am also having same issue. i am using a test server just for demo which has 512MB RAM, which is low but should be okay for test , but i am unable to use `npm install` to install the packages.

Is there any solution except editing package.json into chunks ?

**Comment by wyattjoh** [comment]
Ensure you are installing the dependancies using yarn. If possible, you can add a swap partition to help prevent a system panic from installing the dependancies.

**Comment by gcjbr** [comment]
No luck here, guys. Tried to split package.json in smaller chunks of dependencies, but it will still be killed.


`[1/5] Validating package.json...
[2/5] Resolving packages...
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning validate-commit-msg@2.14.0: Check out CommitLint which provides the same functionality with a more user-focused experience.
warning wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
[3/5] Fetching packages...
info fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "babel-loader@7.1.2" has unmet peer dependency "babel-core@6 || 7 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0-rc".
warning "license-webpack-plugin@1.0.0" has unmet peer dependency "webpack-sources@>= 1.0.0".
warning "babel-jest@21.2.0" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-alpha || ^7.0.0-beta || ^7.0.0".
[-----------------------------------------------------------------------------------------------------------------------] 0/1659Killed`

**Comment by wyattjoh** [comment]
Best suggestion @souljacker would be to increase the size of the VM that you're using to host the application, add more swap space (https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04) or use our pre-built Docker images available https://hub.docker.com/r/coralproject/talk/

**Comment by kgardnr** [comment]
Hey @souljacker were you able to get it up and running by any chance?

**Comment by gcjbr** [comment]
@kgardnr As @wyattjoh suggested, it was my DO box swap space. I increased it, then yarn was able to proceed a bit further, but then stopped again. I guess it would have worked if I kept increasing my box size and power, but at that point I just gave up using it. I think it's too much resources usage for what I need

**Comment by kgardnr** [comment]
@souljacker have you tried using the pre-built Docker images? What size of Droplet are you using?

**Comment by wyattjoh** [comment]
The prebuilt docker images have all the dependencies pre-built, and should actually work better in most circumstances.

**Comment by kgardnr** [comment]
Hey @souljacker, happy 2018! Were you able to get this working on your end?

**Comment by kgardnr** [comment]
Hi @souljacker can you upgrade to the latest version (v4.0.0), and let us know if you're still experiencing this problem? The step by step upgrade instructions are here: https://coralproject.github.io/talk/migration/4/

In the meantime, I will close this ticket but feel free to re-open it if you're still experiencing issues!
