### ISSUE TITLE
startup, logging troubleshooting docs

### ISSUE THREAD

**Issue by MrBryan** [coralproject/talk#1134]
I compiled from source, I configured (on port 3590) I started it up, this is the output I get:

![image](https://user-images.githubusercontent.com/1721891/32094030-529050f2-bab3-11e7-94e6-0258234fd079.png)

If I connect with a local browser to the config address at 127.0.0.1:3590 or any other port I assign, it refuses to connect. I can't find anywhere in any docs on where log files or any further troubleshooting can take place... Help?!!  :D

**Comment by wyattjoh** [comment]
The output from logs is a bit vauge, it's a problem we're working on. Try setting your `DEBUG=talk:cli:serve` and monitoring the output. You should see a line that says something like:

```
API Server Listening on ...
```

**Comment by MrBryan** [comment]
Thanks! looks like it was on port 3001 in spite of the config options I set in .env  But now the admin/install is a blank screen.

I do get something at 127.0.0.1:3001 which shows the local web config is running, but nothing on admin or admin/install

![image](https://user-images.githubusercontent.com/1721891/32119648-c376ccae-bb0a-11e7-92d4-10c6e7670133.png)


![image](https://user-images.githubusercontent.com/1721891/32119846-543397f4-bb0b-11e7-9535-a7866768d76e.png)

**Comment by MrBryan** [comment]
AHA. I found looking at the page source that there were references to my configured port, 3590... so changing that to the port that Talk assigned to itself anyways let me load the admin page :)

**Comment by MrBryan** [comment]
I'll file a bug report  for the port preference being ignored in .env then.
