### ISSUE TITLE
Plugins Defined Through Env Variable May Not Be Available During Reconciliation

### ISSUE THREAD

**Issue by meddy** [coralproject/talk#1135]
### Expected behavior
In development, using a `.env` file,  if we rely on the env variable `TALK_PLUGIN_JSON` to define the plugins the app will use, the `plugins` cli app with the `reconcile` command should reference the plugin configuration defined in `TALK_PLUGIN_JSON` when the parent `yarn` command is executed. (`yarn` will run `package.json` install, and then `package.json` postinstall where `reconcile` is called).

### Actual behavior
The default plugin configuration is referenced instead. The issue is that the `commander.js` script expects a `config` cli argument to define if a `.env` file should be loaded or not. The `package.json` postinstall value does not specify one.

### Steps to reproduce behavior
1. Delete `plugins.json` file if it exists
1. Define plugins in `.env` using `TALK_PLUGIN_JSON` value
1. Run `yarn`
1. See that the incorrect plugins were "reconciled"

**Comment by wyattjoh** [comment]
This is actually expected beheviour @meddy. In production, it is the expectation that the environment variables are not defined in a `.env` file, rather, they are provided by the process manager or the runtime environment already.

If you are deploying with source, you can run your application with this simple systemd service file:

```
[Service]
WorkingDirectory=/opt/talk
ExecStart=/usr/bin/yarn start
Restart=always
User=talk
Group=talk
Environment=NODE_ENV=production
EnvironmentFile=/etc/talk/env

[Install]
WantedBy=multi-user.target
```

Or if using Docker Compose, you can use the `env_file` directive.

**Comment by meddy** [comment]
Thank you for the reply @wyattjoh . Yeah this issue is related to development. Really it's more of an inconvenience than anything, but I also thought it may potentially be an inconsistency. For development I typically run Talk from source, rather than docker, thus the .env file.

**Comment by wyattjoh** [comment]
For developement, I recommend placing your desired plugin configuration in the `plugins.json` file, so that the plugin reconciler will function as desired. This is already excluded from source control, so no issues should arise from it. When running the application in development, `yarn dev-start` will pre-select the `.env` file as the configuration value.

**Comment by meddy** [comment]
ty
