### ISSUE TITLE
tokenUserNotFound hook not recognised?

### ISSUE THREAD

**Issue by kardamom** [coralproject/talk#1136]
Like @adamdpate in #1055, I also need to integrate Talk with my existing user database/login/registration flow.

I have talk up and running. I can pass through my own auth_token and see that talk successfully extracts my user id. 

I've written a stub server plugin to implement the tokenUserNotFound hook. My plugin is loaded at startup. When I try to login, I can see that the function lookupUserNotFound is called: https://github.com/coralproject/talk/blob/b7137fbcd4c759f031ec9da86d249f35b076583d/services/users.js#L907

But I cannot for the life of me get Talk to recognise my hook and add it to tokenUserNotFoundHooks. I've tried a range of ways of structuring the plugin. It currently looks like this:

```
ls -R talk-plugin-sso-auth                                      
index.js server

talk-plugin-sso-auth/server:
notfound.js
```

talk-plugin-sso-auth/index.js:                        
```javascript
const notfound = require('./server/notfound.js')

module.exports = { notfound };
```

talk-plugin-sso-auth/server/notfound.js:
```javascript
module.exports = { tokenUserNotFound: async ({jwt, token}) => {
    console.log("NOT FOUND")
  }
};
```

I've looked at the code and this hook does seem to be a special case. E.g. it's not part of `hookSchemas` in plugins.js.

React/Javascript is not my expertise, so apologies if I've missed something obvious.

By the way, Talk is the fourth - and I hope final! - commenting system I've landed on. My co-founder and I are very impressed by your goals, philosophy and indeed implementation.

**Comment by wyattjoh** [comment]
To resolve your issue, you should import it like this:

`talk-plugin-sso-auth/server/notfound.js`

```js
module.exports = { tokenUserNotFound: async ({jwt, token}) => {
    console.log("NOT FOUND")
  }
};
```

`talk-plugin-sso-auth/index.js`

```js
const { tokenUserNotFound } = require('./server/notfound.js')

module.exports = { tokenUserNotFound };
```

Note that the exported object from your plugin (in `talk-plugin-sso-auth/index.js`) must export an object with a key of `tokenUserNotFound` and your code above exported the following:

```js
{
  notFound: {
    tokenUserNotFound: async () => {
      // ...
    },
  },
}
```

Let me know if that helps!

**Comment by kardamom** [comment]
Great, thank you - that worked and I can see my log message when I try to sign in.

I guess this was just basic Javascript, so thanks for indulging me.
