### ISSUE TITLE
Talk Setup for HTTP sites

### ISSUE THREAD

**Issue by dra777** [coralproject/talk#1157]
Are there any settings or setup needed to be done for Talk to work on an HTTP site?

When stories from HTTP page go in to the /admin/stories it gives me a blank title and NaN/NaN/NanN for the publish date. Testing the embed on HTTPS works otherwise

Thanks

**Comment by kgardnr** [comment]
Hey @dra777! You can run Talk without https locally, is that what you're doing in this case? Make sure you check our docs that will give you details about configuration variables (see the Required ones - you will need those to run Talk) - and you will also need to add the domain during the Install, or by going to Configuration>Tech Settings.

Docs here: https://coralproject.github.io/talk/
Required configuration: https://coralproject.github.io/talk/configuration/
About whitelisting your domain: https://coralproject.github.io/talk/#running

**Comment by wyattjoh** [comment]
When deployed however, you require HTTPS to run the site. Talk takes advantage of options like secure cookies to protect end users from inspection, which requires that cookies can only be set on sites protected with SSL.

There are no plans to support deploying sites in production in non HTTPS environments.

**Comment by dra777** [comment]
Hi @wyattjoh and @kgardnr ,

The Talk platform I've set up is running on HTTPS. But it's being called/embedded on a non-SSL website. Would there be any changes needed to be done with the setup?
 
I've added this to the env variables:

TALK_HELMET_CONFIGURATION={"hsts": false}

Thanks for the help and quick response!

**Comment by kgardnr** [comment]
@dra777, you will need to upgrade the website you embed Talk on to be https - this is best practice, ensures your site won't be blocked by all the popular web browsers, but also otherwise you will get mixed content warnings if you have https and http assets on the same page.

**Comment by dra777** [comment]
Thanks @kgardnr !

Hopefully, we are able to move our site to HTTPS asap. But in the meantime, I'm stuck dealing with HTTP website until early next year i think. sigh

**Comment by kgardnr** [comment]
You can make the business case for https because of security of course - but also mention that https sites are now actively being lower ranked by google and other search engines, as well as throw warnings (this site is not secure!) in all the latest browsers (most will even prevent you from accessing the site, or soon will). If you need help or guidance, let us know, we can help point you in the right direction 😊

#httpseverywhere ❤️🎉🌈

**Comment by dra777** [comment]
Thank you very much! 😄
