### ISSUE TITLE
Accessing Environment Variables From Client Comment Stream Embed

### ISSUE THREAD

**Issue by meddy** [coralproject/talk#1168]
### Expected behavior
It would be helpful to have a system to dynamically make certain environment variables available within the client app. This is needed for things like public api keys.

### Actual behavior
A small subset of environment variables, `TALK_PLUGINS_JSON`,` TALK_THREADING_LEVEL`, `TALK_DEFAULT_STREAM_TAB`, and `TALK_DEFAULT_LANG`, are available through the Webpack define plugin at build time. Another subset of configuration values can be loaded from the stream.ejs HTML template.

One possible solution is to have a naming convention that identifies which environment variables should be dynamically made available either build time or run time. For example, in create-react-app all environment variables prefixed with `REACT_APP_` will be available in the client app. Talk could do something similar, `TALK_PUBLIC_` => `TALK_PUBLIC_GOOGLE_CLIENT_ID`.

### Steps to reproduce behavior
Try to access an environment variable not a whitelist.

**Comment by wyattjoh** [comment]
Love the idea. I'll update this ticket when we've taken a look.

**Comment by wyattjoh** [comment]
Question @meddy, would it be sufficient to have access to these in the DOM of the loaded page or is it necessary to access this at build time?

The issue is when using the docker `*-onbuild` tags, we have to specify which params are passed in, and can't wildcard them. Passing them in the page would resolve this issue.

**Comment by meddy** [comment]
Yeah, that would work.

**Comment by wyattjoh** [comment]
We added support for this in https://github.com/coralproject/talk/commit/a43c173a125423557f93ee51a1891b7ea4d7700a where any variable `TALK_CLIENT_*` is made available via the `staticConfigSelector`
