### ISSUE TITLE
Using auth_token on Coral.Talk.render gets 401 Error on signout

### ISSUE THREAD

**Issue by dra777** [coralproject/talk#1169]
Hi,

#1055, #1136 
I'm testing out auth_token when embedding Talk:

`Coral.talkStream = Coral.Talk.render(document.getElementById('coralStreamEmbed'), {
  ...
  auth_token: <token>
});`

It signs me in, but i get errors on Chrome console when i click sign out:

POST http://127.0.0.1:3000/api/v1/graph/ql 401 (Unauthorized)
bundle.js:30 Error: Server response was missing for query 'undefined'.

On terminal, I get:

'status: 401,
translation_key: 'AUTHENTICATION',
metadata: { message: 'token was revoked' }'

I also don't see the token on localStorage and under Cookies.

This issue doesn't happen when doing:

`Coral.talkStream.login(<token>);`

on Chrome console.

Please advise. Thanks for the time

**Comment by wyattjoh** [comment]
When you use the auth_token method for connecting to Talk's auth system, Talk does not persist cookies/local storage to keep the token. Because Talk runs inside an iFrame, it's not possible without creating a popup (the original auth system) to get permission to save data to cookies/localStorage.

When you click "Sign Out", can you check to see what the network requests being sent were?

**Comment by dra777** [comment]
Hi @wyattjoh,
I'm not sure if I'm doing this right but here are the network requests I see:

Request URL:http://127.0.0.1:3000/api/v1/auth
Request Method:DELETE
Status Code:204 No Content
Remote Address:127.0.0.1:3000
Referrer Policy:no-referrer-when-downgrade

Request URL:http://127.0.0.1:3000/api/v1/graph/ql
Request Method:POST
Status Code:401 Unauthorized
Remote Address:127.0.0.1:3000
Referrer Policy:no-referrer-when-downgrade

Attached is a screenshot of the payload of the request that got 401:

![screen shot 2017-11-17 at 10 37 14 am](https://user-images.githubusercontent.com/33562574/32967997-bc653e08-cb83-11e7-933a-d6715f3bc97f.png)

Thank you for the help and clarification!

**Comment by wyattjoh** [comment]
What is the response body from that request?

**Comment by dra777** [comment]
Hi @wyattjoh 

The response was:

`{"message":"authentication error occured","error":{"message":"authentication error occured","status":401,"translation_key":"AUTHENTICATION","metadata":{"message":"token was revoked"}}}`

**Comment by kgardnr** [comment]
Hey @dra777, thanks for this!

Are you looking to contribute to Talk as a 3rd party developer, or to set Talk up for your newsroom or blog? That will help us figure out the best way to support you here.

**Comment by dra777** [comment]
Hi @kgardnr,

Sorry for the late response. I'm trying to set it up on WordPress blog locally. I've removed the sign out option on the embed as I've realized I don't really need it since I'm logging in and authenticating using Wordpress. So when they log out on WordPress, they should also be logged out on Talk.
