### ISSUE TITLE
Getting error on admin panel in fresh install

### ISSUE THREAD

**Issue by amalfra** [coralproject/talk#1207]
### Expected behavior
I should be able to access admin panel when navigated to /admin
### Actual behavior
stuck in blank page due to js error
![selection_001](https://user-images.githubusercontent.com/4033256/33980689-f719578a-e0cf-11e7-9037-824cfdfa4e9d.png)
### Steps to reproduce behavior
I just brought up talk using docker image as mentioned here: https://coralproject.github.io/talk/index.html

**Comment by wyattjoh** [comment]
It looks like the `ROOT_URL` parameter set in configuration references `127.0.0.1:3000` rather than `localhost:3000`. Try accessing the dashboard there, or changing the `ROOT_URL` parameter to `http://localhost:3000`.

**Comment by amalfra** [comment]
@wyattjoh Thanks, it works now!
