### ISSUE TITLE
Live stream WebSocket connection fails

### ISSUE THREAD

**Issue by gakhov** [coralproject/talk#1229]
While all other functionality of CoralTalk works quite good for me, the WebSockets requests to `/api/v1/live` fails (doesn't matter if user is logged in or not)

### Expected behavior

Websocket connection for the live stream `/api/v1/live` is established

```
HTTP/1.1 101 Switching Protocols
```

### Actual behavior

```
HTTP/1.1 400 Bad Request
```

### Steps to reproduce behavior

Well, with WebSockets it's always a bit tricky to reproduce the issue. My initial problem occurred with  Nginx as a proxy, but I've simulated the exact same behavior with `curl` to avoid possible misconfiguration in Nginx.

##### Start  a new Docker container from the latest image

```
/usr/bin/docker run --net talk-net -m 0b --dns 8.8.8.8 --dns 8.8.4.4 -e NODE_ENV=development -e DEBUG='*' -e TALK_MONGO_URL=mongodb://mongo/test -e TALK_REDIS_URL=redis://redis/0 -e TALK_ROOT_URL=https://example.com/test/ -e TALK_PORT=7777 -e TALK_JWT_SECRET=topsecret -e TALK_FACEBOOK_APP_ID=12121212 -e TALK_FACEBOOK_APP_SECRET='qwqwqw' -p 7777:7777 -v /var/log --restart=always --name talk-7777 coralproject/talk:latest
```
##### Simulate the WebSocket connection.

Note: This is just simulation with `curl`, but I also tried such `curl` requests to TheWashingtonPost LIVE_URI and there it works perfectly and returns 101 as expected. However, in my case, it fails from `curl` similarly as from the browser via Nginx.

```
curl -v -i -N -H "Connection: Upgrade" -H "Upgrade: WebSocket" -H "Host: example.com" -H "Origin: https://example.com" -H "Sec-WebSocket-Version: 13" -H "Sec-WebSocket-Protocol:graphql-ws" -H "Sec-WebSocket-Key: EzOCSkK0tb70THZhGp/CpA==" -H "Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits"  http://127.0.0.1:7777/api/v1/live
```

The response is:

```
* Connected to 127.0.0.1 (127.0.0.1) port 7777 (#0)
> GET /api/v1/live HTTP/1.1
> User-Agent: curl/7.38.0
> Accept: */*
> Connection: Upgrade
> Upgrade: WebSocket
> Host: example.com
> Origin: https://example.com
> Sec-WebSocket-Version: 13
> Sec-WebSocket-Protocol:graphql-ws
> Sec-WebSocket-Key: EzOCSkK0tb70THZhGp/CpA==
> Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
> 
< HTTP/1.1 400 Bad Request
HTTP/1.1 400 Bad Request
< Connection: close
Connection: close
< Content-type: text/html
Content-type: text/html
< Content-Length: 11
Content-Length: 11

< 
Bad Request* Closing connection 0
```
##### Weirdness

If I subscribe to the container's logs I don't see that the `/api/v1/live` actually was hit by the request. Also, there are no expected debug lines from https://github.com/coralproject/talk/blob/master/graph/subscriptions.js

If I remove, for instance, `Connection` header (to transform my request to not a WebSocket one), then I clearly see 404 response and the log shows that that endpoint was hit.

Not sure if it's an issue at all or maybe I just missed something, so please advise! Thank you.

**Comment by wyattjoh** [comment]
We have many newsrooms using Talk in Docker successfully at this point, so I'm just guessing that the curl request is unable to properly simulate the websocket handshake.

What I would recommend, is that your nginx config contains something along the lines of:

```
server {
  ...

  location / {
    proxy_pass http://127.0.0.1:7777/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}
```

Which is assuming that you have Talk running on port 7777. That's the configuration that we have in production for our own blog at https://blog.coralproject.net/ where we have it running in a Docker container.

**Comment by gakhov** [comment]
Weird... This is how my Nginx is configured as well. The `curl` was just a simulation, as I said. But both of them fail with the same 400 Bad Request.

Also weird that I don't see `/api/v1/live` requests in the container's logs (neither when I call via Nginx, nor via curl), but all other requests are there. Is this something that you experience in your production configuration as well? Does that `curl` directly to the container's port fail for you as well?

Thank you

**Comment by wyattjoh** [comment]
I was able to run your curl command directly from our console and it worked:

```*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 7777 (#0)
> GET /api/v1/live HTTP/1.1
> Host: example.com
> User-Agent: curl/7.52.1
> Accept: */*
> Connection: Upgrade
> Upgrade: WebSocket
> Origin: https://example.com
> Sec-WebSocket-Version: 13
> Sec-WebSocket-Protocol:graphql-ws
> Sec-WebSocket-Key: EzOCSkK0tb70THZhGp/CpA==
> Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
>
< HTTP/1.1 101 Switching Protocols
HTTP/1.1 101 Switching Protocols
< Upgrade: websocket
Upgrade: websocket
< Connection: Upgrade
Connection: Upgrade
< Sec-WebSocket-Accept: j8aYgxgU2cLjW0lObS2lp+MvUNw=
Sec-WebSocket-Accept: j8aYgxgU2cLjW0lObS2lp+MvUNw=
< Sec-WebSocket-Protocol: graphql-ws
Sec-WebSocket-Protocol: graphql-ws

<


{"type":"ka"}```

Perhaps you need to setup the Talk DB first before that works? It's a weird situation.

**Comment by wyattjoh** [comment]
I was able to run your curl command directly from our console and it worked:

```*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 7777 (#0)
> GET /api/v1/live HTTP/1.1
> Host: example.com
> User-Agent: curl/7.52.1
> Accept: */*
> Connection: Upgrade
> Upgrade: WebSocket
> Origin: https://example.com
> Sec-WebSocket-Version: 13
> Sec-WebSocket-Protocol:graphql-ws
> Sec-WebSocket-Key: EzOCSkK0tb70THZhGp/CpA==
> Sec-WebSocket-Extensions:permessage-deflate; client_max_window_bits
>
< HTTP/1.1 101 Switching Protocols
HTTP/1.1 101 Switching Protocols
< Upgrade: websocket
Upgrade: websocket
< Connection: Upgrade
Connection: Upgrade
< Sec-WebSocket-Accept: j8aYgxgU2cLjW0lObS2lp+MvUNw=
Sec-WebSocket-Accept: j8aYgxgU2cLjW0lObS2lp+MvUNw=
< Sec-WebSocket-Protocol: graphql-ws
Sec-WebSocket-Protocol: graphql-ws

<


{"type":"ka"}```

Perhaps you need to setup the Talk DB first before that works? It's a weird situation.

**Comment by gakhov** [comment]
Thank you, then I will try to start with completely fresh system to check where it was misconfigured in my case. I'll let you know if find something that can useful for other users.

**Comment by gakhov** [comment]
Thank you again for the input. I think, finally, I've figured out that was the reason and I have an explanation why it worked for you, but not for me.

## The problem

The problem was my `TALK_ROOT_URL` isn't root URL, so it had a `/test/` subpath:
```
TALK_ROOT_URL=https://www.expample.com/test/
```
In my configuration, I didn't specify `TALK_ROOT_URL_MOUNT_PATH=TRUE` that by default is `FALSE`.

Thus, all non-WebSocket requests are rooted to `/api/v1`, `/client/....` without prefix `/test/` (as it stated in the documentation https://github.com/coralproject/talk/blob/master/docs/_docs/02-02-advanced-configuration.md#talk_root_url_mount_path)

However, WebSocket requests use `${MOUNT_PATH}api/v1/live` and are rooted to `/test/api/v1/live` in any case. That was why my `curl` to `/api/v1/live` didn't work and I didn't see the requests in the logs ... there were no listeners for such path. Maybe 404 Not Found in that case could be more helpful, but it seems that since non-WebSocket requests listened to `/api` path as well, they were just ignored and couldn't understand the request (400 bad Request) because of `Connection: Upgrade`.

## The solution

Here is my final setup that works for me, including Nginx rules (for the case when you have to split `TALK_ROOT_URL` and `TALK_WEBSOCKET_LIVE_URI` but use the same host, as me for the development):

#### Talk environment
```
'TALK_ROOT_URL=https://example.com/test/',
'TALK_WEBSOCKET_LIVE_URI=wss://example.com/test-live/api/v1/live',
'TALK_PORT=7777',
...
```
#### Nginx

```
  upstream talk.test {
     server     127.0.0.1:7777  fail_timeout=10s;
  }

  location /test/ {
    proxy_pass            http://talk.test;
    proxy_set_header      Host $host;
    proxy_set_header      X-Real-IP $remote_addr;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header      Proxy "";
  }

  location /test-live/api/v1/live {
    rewrite ^/test-live/(.*)$ /test/$1 break;
    proxy_pass            http://talk.test;
    proxy_http_version    1.1;
    proxy_set_header      Upgrade $http_upgrade;
    proxy_set_header      Connection $conection_upgrade;
  }

```
Hope it makes sense for you and could be useful for others as well.

## The question

@wyattjoh Doesn't it seem like an inconvenience that `ROOT URL` ignores the `${MOUNT_PATH}` in this case, but `LIVE URI` doesn't?

Thank you

**Comment by kgardnr** [comment]
Hi @gakhov, can you upgrade to the latest version (v4.0.0), and let us know if you're still experiencing this problem? The step by step upgrade instructions are here: https://coralproject.github.io/talk/migration/4/

**Comment by michaelfavia** [comment]
Just started from scratch with docker-compose install and can confirm WS connects correctly FWIW.

**Comment by midnightfreddie** [comment]
@gakhov Thanks that helped me. Agreed, a 404 response would have saved me a lot of time as I was focusing on the request headers and not the url. I have Talk 4.4.2 and `TALK_ROOT_URL=https://<domain-name>/coraltalk/` with nginx as the gateway routing /coraltalk/ to / on the back end. But the websocket endpoint is unintuitively at /coraltalk/api/v1/live on the back end whereas the other REST requests are at /api/v1/live on the back end, so I had to adjust nginx's route for the websocket. I didn't need to set  `TALK_WEBSOCKET_LIVE_URI` for Talk, though.
