### ISSUE TITLE
Not able to open login window using the embed object.

### ISSUE THREAD

**Issue by rajeshraazi** [coralproject/talk#1233]
Trying to adding a login button which opens the talk internal login popup on click.

Here is my code:

var ctalk = Coral.Talk.render(document.getElementById('coral_talk_61862106'), {talk: '<server address>'});
ctalk.login();

Please share how can we externally open the talk login window using object 'ctalk'.

**Comment by kgardnr** [comment]
Hi @rajeshraazi, thanks for writing! Are you trying to include a login button somewhere outside of Talk, is that it?

**Comment by rajeshraazi** [comment]
@kgardnr - Yes, I am trying to place it outside talk configurable based embed; at a click of button on top of my page. Right now comments are calling using iframe based code.

**Comment by kgardnr** [comment]
Are you integrating it into another auth system of some sort? Or you just wanna have a one-off login button?

**Comment by rajeshraazi** [comment]
@kgardnr  - I am using Talk integrated login/signup which is part of Coral talk package.

**Comment by kgardnr** [comment]
Oh awesome. I'm actually not sure if this is supported at the moment. We are about to go on break for the holidays, so I can check back with the team first week of January and see what they say.

In the meantime, were you able to get the out of the box install of Talk up and running successfully? If you can share where you're hosting it, we'd love to see!

**Comment by rajeshraazi** [comment]
@kgardnr  - Is there any way that I can call it using configured events like?:
myObj = Coral.Talk({}); //Object initiated.
myObj.trigger('loginWindow') - will open login dialogue.

**Comment by kgardnr** [comment]
I don't think so right now - we have everything managed inside the embed/iframe. You can access certain elements of the graph, but I'm not sure about the login functionality.

**Comment by rajeshraazi** [comment]
@kgardnr - We are currently hosted it under private machine(pre-production). I will share you the link once it goes live. Thanks..Happy holidays.

**Comment by kgardnr** [comment]
Awesome @rajeshraazi - we will be back in touch in January! :)

**Comment by kgardnr** [comment]
Happy 2018 @rajeshraazi, just wanted to follow up on this with you!

**Comment by rajeshraazi** [comment]
@kgardnr  - Very happy new year 2018.
Here is our integration - https://talk.businessinsider.in and still looking the way to get all properties and events(login/user  info/register etc.) just outside the scope of that iframe.

As below line give us flexibility to access few object properties.
Coral.Talk.render(document.getElementById('coral_talk_61862106'), {talk: ''});

**Comment by kgardnr** [comment]
Hey @rajeshraazi! Just wanted to share with you our latest version of v4.0.0 is released. The step by step upgrade instructions are here: https://coralproject.github.io/talk/migration/4/

Let us know if you have any issues! Happy to have you and your team on board!
