### ISSUE TITLE
Can't log in using http & iOS 11.2.1, v3.8.2 on Safari, Firefox or Chrome

### ISSUE THREAD

**Issue by jheasly** [coralproject/talk#1235]
### Expected behavior
After submitting proper credentials, user is authenticated.

### Actual behavior
No error, but no authentication either.

### Steps to reproduce behavior
Try to log in using Safari, Firefox or Chrome and iOS 11.2.1 into a v3.8.2 install over http.

**Comment by kgardnr** [comment]
@jheasly unfortunately we don't support http at all in production; you must use https.

**Comment by jheasly** [comment]
Oh. Is that in the docs?
(And is it likely the issue?)

**Comment by kgardnr** [comment]
I don't think we specifically call it out in the docs, but I will add it! I'm sure that's the issue.
