### ISSUE TITLE
Incorrect URL for "Ask Readers a Question" in the Configure tab

### ISSUE THREAD

**Issue by gakhov** [coralproject/talk#1241]
### Expected behavior

_Configure Comment Stream_ -> _Ask Readers a Question_ should call  `/${MOUNT_PATH}/client/0.js`

### Actual behavior

_Configure Comment Stream_ -> _Ask Readers a Question_ calls  `/client/0.js`

### Steps to reproduce behavior

1. Setup a CoralTalk Instance

```
'TALK_ROOT_URL=https://example.com/test/',
'TALK_ROOT_URL_MOUNT_PATH=TRUE',
'TALK_PORT=7777',
```
2. Initialize the instance (`/test/admin/install`)
3. Create a test page that is accessible under `https://example.com/test/` with content:

```
...
<div id='coralStreamEmbed'></div>
<script src="https://example.com/talk/embed.js" async onload="
  Coral.Talk.render(document.getElementById('coralStreamEmbed'), {
    talk: 'https://example.com/talk/'
  });
"></script>
...
```

4. Navigate to `https://example.com/test/` and login as superuser
5. Click the `Configure` tab
6. Under _Configure Comment Stream_ click on checkbox _Ask Readers a Question_
7. See that handler for the checkbox calls `https://example/client/0.js` that returns 404 because the actual script is under `https://example/client/test/0.js`

**Comment by wyattjoh** [comment]
This is related to this line here:

https://github.com/coralproject/talk/blob/0af8a3115477a96ea58761f669276a71f2cb1d1e/webpack.config.js#L39

We might be able to patch it without requiring a rebuild however.
