### ISSUE TITLE
The "suggest edits" button at the top of the page requires I fork the project.

### ISSUE THREAD

**Issue by DHorse2** [coralproject/talk#1248]
Talk
[Commenter Features](https://coralproject.github.io/talk/commenter-features/)
Suggest Edits button

### Expected behavior
I expected to arrive at the issues page (here)

### Actual behavior
https://github.com/coralproject/talk/edit/master/docs/_docs/03-02-product-guide-commenter-features.md

You need to fork this repository to propose changes.
Sorry, you’re not able to edit this repository directly— you need to fork it and propose your changes from there instead.

### Steps to reproduce behavior
Follow the above link (Commenter Features) and click the suggest edits button.

**Comment by kgardnr** [comment]
Hey @DHorse2, you can submit a pull request directly on Github without having to fork the project, by:

1. Clicking Suggest Edits
2. Make the edits in the markdown file on your screen
3. Add a subject to explain the changes you're making (as well as any other useful information)
4. Click "Commit Changes"

Here's an example for you:

<img width="1025" alt="suggest_edits" src="https://user-images.githubusercontent.com/1077300/34680680-be9968d6-f467-11e7-9f99-82d10da92dd3.png">

Thank you for contributing!
