### ISSUE TITLE
Implementation staff are not creating issues/feature requests here. It's an issues issue.

### ISSUE THREAD

**Issue by DHorse2** [coralproject/talk#1249]
### Expected behavior
The various feature requests found on the TI site implementation were not created here.

### Actual behavior
Andrew politely acknowledged the feedback. He probably made some notes. ;)

### Steps to reproduce behavior
You can observe the issue here:
The Intercept
[Comment Sections Are Essential for News Sites. We’re Making Changes to Improve Ours.](https://theintercept.com/2017/12/18/comments-coral-project/)

BTW I was going to submit the bugs / feature requests I collected at TI here to be efficient. I am a commenter on the site.

**Comment by kgardnr** [comment]
Hi @DHorse2, thank you! We do collect feedback from all of our newsrooms and from their readers and commenters, but we don't necessarily log every single piece of feedback until we've had a discussion with the newsroom and with our team/product folks to determine what we will be acting on. We track work in progress, ideas, bugs and backlog items here: https://www.pivotaltracker.com/n/projects/1863625. You can see we have a ton of stuff on our plate :) 

Thank you for logging the other issues though, we always appreciate feedback from passionate commenters - we're building these products for you!
