### ISSUE TITLE
Add "responding to X" (user) when comment nesting is flattened or always add this info.

### ISSUE THREAD

**Issue by DHorse2** [coralproject/talk#1250]
### Expected behavior
When I am reading a long thread of comments I need to know which commenter is being responded to. The conversation in the threads completely lose context.
### Actual behavior
Users on the TI site are now adding the specific person they are responding to at the top of their comment. When they remember.
### Steps to reproduce behavior
You can observe this on most any article.

**Context:**
[Commenter Features](https://coralproject.github.io/talk/commenter-features/)

> Threading
Talk supports by default 3 levels of threading, meaning each top-level comment has a depth of 3 replies; replies beyond that are not nested below the 3rd level. You can adjust this using the TALK_THREADING_LEVEL configuration variable. We don’t recommend deep threading because it can cause issues with styling, especially on mobile.

**Comment by DHorse2** [comment]
@ehalferty your enhancement is perfectly acceptable and addresses the largest complaint in the community. Please allow me to provide some technical feedback on the issue directly related to user experience.

In short this solution:
If CommentNesting > MaxNesting Then Dispaly RespondingTo

This addresses user confusion over who a reply is addressed to when nesting is no longer a visual clue. However, this can be viewed in broader terms of when does the user become confused and loose track of the mental stack of comment replies (nested comment authors?) These following other metrics are correlated to the broader issue:

- 1. The number of comments seen since viewing the parent comment.
- 2. The elapsed time passed.
- 3. The total number of words (or lines) separating the two comments. (Amount read?)
- 4. The number of words typed or number of replies the user made in between.
- 5. The number of off-site links followed.

Some of them are interesting (causes of confusion/display triggers) although not really practical to implement, the elapsed time one is fairly straight forward. Over several months I saw confusion mentioned a number of times. It may have been mentioned 10 times re Coral so it is clearly important.

As a commenter, evaluator and fact checker, I personally find it impossible to keep track of deeply nested comment threads without the presence of RespondingTo. On numerous occasions I have returned to comments section after more than one hour elapsed.

UI Note: Newspapers want control over the style and what's displayed for numerous reasons. RespondingTo, Link copy, Share and other features can optionally be part of a hover or ellipse button. As long as it is easily available to the user their experience is not compromised in an important way.

I'll close this by noting the following about this change. It is structured, predictable and addresses the problem (for the user) and uses values already present in the application. Sounds good.

Regards, Dave Horsman

**Comment by DHorse2** [comment]
**ignore this note** **(off topic)**
I had some problems with the comment software writing the above.  The comment did not actually post though it showed on this page. Also, note the problem I had above adding and removing bullets when I pasted text and re-added the bullets trying different formats. I used the text edit control not Markdown.

**Comment by wyattjoh** [comment]
Sent back to design for v5/v6.
