### ISSUE TITLE
Replies (?count?) not showing for my posts in My Profile

### ISSUE THREAD

**Issue by DHorse2** [coralproject/talk#1251]
### Expected behavior
Showing if there are replies to posts is standard comments UI.

**Comment by kgardnr** [comment]
@DHorse2 this should be showing there, we show counts of Reactions and counts of Replies in My Profile:

<img width="538" alt="reply_count_my_profile" src="https://user-images.githubusercontent.com/1077300/34681261-54c01b6a-f469-11e7-8d48-af39228e6830.png">

Are you not seeing this on TI?

**Comment by DHorse2** [comment]
Thanks @kgardnr. No I am not seeing this on TI and thought surely that would be an option in Talk.

Would I contact TI directly about this. It is their implementation options apparently.

**Comment by kgardnr** [comment]
Yes, don't worry, I'll talk to the TI team about this and report back @DHorse2!

**Comment by DHorse2** [comment]
Thank you. I am getting a better understanding of how you are working with TI and their launch. I will **spend some time in the Pivotal Tracker and hold off a bit on posting more issues.** I plan to lobby TI and Andrew to open up a topic on the Coral Site specific to their experience and community.  ;-)

**Comment by kgardnr** [comment]
Awesome @DHorse2, sounds like a plan!

**Comment by kgardnr** [comment]
Also for this particular issue, I confirmed with their dev team that this will also be fixed in the new release this week :)
