### ISSUE TITLE
View Conversation button does not navigate to my post. 

### ISSUE THREAD

**Issue by DHorse2** [coralproject/talk#1252]
### Expected behavior
In the commenters user interface.
My Profile
My Comments
View Conversation button
Navigation should end with my comments showing
### Actual behavior
Navigation show the comment you replied to.
(This is good in that number of comments should be "loaded" and gives context.)
I must repeatedly click the "show more replies" button to locate my comment.
This would not be an issue except it is the only way to look for replies.

Alternatively you could navigate to the post from "My Comments".
Therefore, navigating to the reply I responded to would require scrolling up.
However, this means the entire conversation is visible.
See the topic "complaints re Show More Replies"

**Comment by kgardnr** [comment]
@DHorse2 yes - this is a known issue on TI that we discovered last week. We are working with TI to get this fixed.

**Comment by kgardnr** [comment]
@DHorse2 confirmed with the TI team that this will be fixed in the new upgrade which should come out this week! :) Thanks for reporting this.
