### ISSUE TITLE
complaints re Show More Replies

### ISSUE THREAD

**Issue by DHorse2** [coralproject/talk#1253]
### Expected behavior
There have been a number of complaints about the need to be **constantly be clicking Show More Replies.**
### Steps to reproduce behavior
Many users on TI's site prefer to have all the comments loaded so that it is searchable.
As the design appears to be paging data to the browser the normal solution to this is:
1) Display more comments per browser load. Is this adjustable?
2) Detect the scrolling to the bottom and load more comments similar to other SPA's.

**Comment by kgardnr** [comment]
Hey @DHorse2, thanks, yes we did hear this feedback too. It's a point that will be discussed with TI.

As it stands now, the reason we made that product decision was to help with load times on the browser and to aid in readability. But we can circle back on that and I can update you when we know.

**Comment by kgardnr** [comment]
We've added support for this as an env variable, closing this ticket!
