### ISSUE TITLE
How to handle redirects

### ISSUE THREAD

**Issue by Jetbo** [coralproject/talk#1268]
Story: As a client, I want to be able to generate streams with custom `asset_id` uuids or by a group of `asset_url`s in order to handle redirects.

Example:
An editor creates a page with a comment stream at `www.somedomain.com/coral-tak-is-cool` and notices there's a typo in the slug later.  The page already has comments and decent traffic, but they would prefer a better url for SEO.  They create a 301 from `www.domain.com/coral-tak-is-cool` to `www.somedomain.com/coral-talk-is-cool` (with the same page content), but end up with a new comment stream since the url changed.

This could be handled by an outside system, but it feels more like a potential core feature.

**Comment by wyattjoh** [comment]
You can handle this with a plugin that hooks into the graph which is what I've seen in the past as a great solution to this.

I'll update when I find that code 😄

**Comment by wyattjoh** [comment]
Updates! We just open sourced a plugin for exactly this!

https://github.com/coralproject/talk-plugin-custom-asset-id

Let me know if that fits your needs 😄

**Comment by Jetbo** [comment]
Yup, this will work beautifully, thank you so much!

**Comment by yannick-fernand** [comment]
hi we are using talk v6 version and we also need this feature. how do we do ?
