### ISSUE TITLE
Race Condition Sending Messages To Comment Stream

### ISSUE THREAD

**Issue by meddy** [coralproject/talk#1282]
### Expected behavior
Calling the stream embed public methods, such as `embed.login(token)`, are handled as expected.

### Actual behavior
The bootstrap logic of the [coral embed app](https://github.com/coralproject/talk/blob/master/client/coral-embed-stream/src/index.js#L56) is asynchronous, and there isn't an obvious way to determine if the embed is ready to receive messages from the parent window. A problem can occur if you call `login` immediately after calling `render`, as noted [here](https://github.com/coralproject/talk/blob/master/client/coral-embed/src/index.js#L44).

Messages such as login that are explicitly handled may not have those [handlers](https://github.com/coralproject/talk/blob/master/client/coral-embed-stream/src/index.js#L34) assigned yet. The events end up being swallowed.

A potential solution is to emit an event from the child window when the embed context has finished being configured, so that the parent window knows the embed is ready to receive messages. Listening for the dispatched action `ADD_EXTERNAL_CONFIG`, may mostly solve that, but I don't think that was the intention. It would be nice to have the the stream embed public api return a promise to abstract that logic.

### Steps to reproduce behavior
Call `embed.login(token)` after `embed.render(...)`, so that pym messages are sent before the embed context is done being configured.

**Comment by wyattjoh** [comment]
For the use case you're describing, you should instead use the `access_token` as an option on the 

```js
Talk.render(/*...*/, { access_token: 'YOUR ACCESS TOKEN', /*...*/ })
```
which will pass the access token to the embed on init. The `login()` method is designed to login the user _after_ the user has already rendered the stream.

**Comment by meddy** [comment]
Thank you for that info @wyattjoh . That makes sense. Unfortunately for my situation we are using the talk-wp-plugin which controls and handles the render call automatically for articles. I will confer and see if we can figure out a way to make it so that can be handled manually when needed, so that we can pass in the authentication token like you mentioned.
