### ISSUE TITLE
Is there an avatar button for the top of a page? Ie. with number of notifications/replies.

### ISSUE THREAD

**Issue by DHorse2** [coralproject/talk#1285]
### Expected behavior
As a commenter, when I arrive on a Talk site I want my avatar showing at the top of the page.
### Actual behavior
?Does this exist as an option/embed?
### Steps to reproduce behavior
n/a

**Comment by wyattjoh** [comment]
We currently only offer avatar support through integration with an external authentication system. See our [Avatar Plugin Recipe](https://github.com/coralproject/talk-recipes/tree/master/plugins/avatar) for answers on how to support this.

We don't however show the avatar at the top as you indicated, but would show it beside the comments using that recipe.
