### ISSUE TITLE
How do [I] communicate to your staff?

### ISSUE THREAD

**Issue by DHorse2** [coralproject/talk#1289]
I got this post:
Wyatt Johnson <notifications@github.com>
Tue 2018-01-16, 2:02 PM
coralproject/talk;Subscribed;

What does this PR do?
When a reply is made against a comment that is not visible or has been deleted, the comment will be rejected.
**How do I test this PR?
Create a comment.
In another tab, reject that comment.
In the first tab, try replying to that comment.**
See the error!
Tracking: https://www.pivotaltracker.com/story/show/153522862

That's correct but not adequate,
As a tester, do it in this order too:
Create a comment. Post
In the new tab, try replying to that comment. Do not post.
In another tab, reject that comment.
In the new tab, post your reply

Apologies, I can't figure the system out.
Regards, David G. Horsman
[David G. Horsman](mailto:david_horsman@hotmail.com)

**Comment by losowsky** [comment]
Hi David

What are you trying to do?

Thanks

Andrew

**Comment by losowsky** [comment]
If you got that message via email, it's probably because you clicked on 'subscribe' on the right hand side on an existing PR.

**Comment by losowsky** [comment]
(If you're trying to improve the Pivotal ticket, thanks for the heads up! We're on top of it.)

**Comment by DHorse2** [comment]
Yes I was trying to improve/add a task (Id#153522862) . Could you see that above scenario I had a problem with gets covered. Many thanks.

**Comment by kgardnr** [comment]
Hi @DHorse2! Just to let you know, we've accounted for your feedback in that story, it will be included in release 4.1.0, which will come out in a few weeks or so. Thank you for your input!

**Comment by DHorse2** [comment]
Thanks Kim that's great. My post felt a little disruptive to me. I'm giving some thought to how to communicate (as a commenter) without interrupting a development team using Pivotal.

Twitter: https://twitter.com/DHorse1
Facebook: https://www.facebook.com/DHorse1
Gmail: mailto:dhorse2@gmail.com
Hotmail: mailto:david_horsman@hotmail.com
________________________________

**Comment by kgardnr** [comment]
No, it's great @DHorse2 we love to receive feedback and we're always using Github so that definitely works for us! We try to reply within a few days max, depending on the week :)

**Comment by DHorse2** [comment]
Well that helps with my own task. Lol, excuse the tag. I'm working at #CommentsSoftwareEnhancement(s). As a #TechnologyEvaluator. So I will post again in the same fashion but only when it is relevant. Keep up the good work. 😊

Twitter: https://twitter.com/DHorse1
Facebook: https://www.facebook.com/DHorse1
Gmail: mailto:dhorse2@gmail.com
Hotmail: mailto:david_horsman@hotmail.com
________________________________

**Comment by kgardnr** [comment]
Hahaha, thank you!
