### ISSUE TITLE
Login/Register with Facebook

### ISSUE THREAD

**Issue by leeeandroo** [coralproject/talk#1304]
After some changes a few days ago ([commit reference](https://github.com/coralproject/talk/commit/8f1d9f051e306314d4c77c067b1879cd86c9dc12#diff-f6c0c59286f493f642ae6f4af30d49fc)), the functionality to register/login with Facebook does not work anymore. 

### Expected behavior
I can click on Sign in with facebook/Sign up with Facebook and the system create/authenticate the user.

### Actual behavior
Right now, If I click on this, nothing happens.

### Steps to reproduce behavior
- Enable the plugin `talk-plugin-facebook-auth`;
- Add `TALK_FACEBOOK_APP_ID` and `TALK_FACEBOOK_APP_SECRET` on your configuration;
- Run the application and try to register using your Facebook account;

### Possible solution

After close the facebook popup and I can see a `JSON parse error`.

It's saving a not valid JSON object on localStorage: `{&quot;err&quot;:null,&quot;data&quot;:{ ... ` instead of `{"err":null,"data":{" ... `. 

After changed the way of storing the auth object ([see here](https://github.com/coralproject/talk/commit/8f1d9f051e306314d4c77c067b1879cd86c9dc12#diff-a8ec96df3b5d2d7e676ef7955d017808)), before save this value on `localStorage`, we need to transform it as a valid JSON again:

My first suggestion is to add it on this file (`/public/javascripts/auth-callback.js`):

`localStorage.setItem('auth', JSON.stringify(JSON.parse(document.getElementById('auth').innerText.replace(/&quot;/g,'"'))));`

Does it make sense?

**Comment by kgardnr** [comment]
Hi Leandro! Are you running a version of master in production? We highly recommend using our releases instead.

That said, can you point us to the website this is happening on so we can try and reproduce? Thanks!

**Comment by leeeandroo** [comment]
Hi Kim,

You are right, I'm using the `latest` docker image. I've changed to the `4.0.0` and It works again.
Unfortunately I can't send to you the website because right now I'm running it locally. 

This problem happens only on the master. If this is WIP, then you can ignore my issue. But the solution proposed code fix this, if you think It's a good way to solve it.

Thanks!

**Comment by kgardnr** [comment]
Yes please only use designated versions. Master should only be used for
development. Thanks!

**Comment by kgardnr** [comment]
Also make sure you ran all the migrations and following the upgrade path
for 4.0.0. If you have it working locally I assume you did but just wanted
to check.

**Comment by wyattjoh** [comment]
Hey @leeeandroo, this is a confirmed bug. Will update when we have a fix.

**Comment by wyattjoh** [comment]
Hey @leeeandroo, I've created this PR https://github.com/coralproject/talk/pull/1305 that should resolve the issue. If you are able to test that it resolves the issue, we should be good :)

**Comment by leeeandroo** [comment]
Hi @wyattjoh, I can confirm it works!

Thanks,
