### ISSUE TITLE
External Plugins issue

### ISSUE THREAD

**Issue by caeugusmao** [coralproject/talk#1307]
Hi,

I am trying to install an external client plugin in talks project. I tried to install my plugin from my internal repository and when I ran **./bin/cli plugins reconcile**, the follow error was returned:

```
yarn add --ignore-scripts talks-globo-external@1.0.0
error An unexpected error occurred: "https://registry.yarnpkg.com/@coralproject/eslint-config-talk/-/eslint-config-talk-0.1.0.tgz: Request failed \"404 Not Found\"".
/Users/carlos.gusmao/workspace/node/talk/bin/util.js:66
  throw err;
  ^
Error: Could not install external plugins, errors occured during install
    at reconcileRemotePlugins (/Users/carlos.gusmao/workspace/node/talk/bin/cli-plugins:170:15)
    at Command.reconcilePluginDeps (/Users/carlos.gusmao/workspace/node/talk/bin/cli-plugins:272:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
After this, I tried other approach to install. I tried through "npm" passing my repository and it worked but when I loaded my page, I received a syntax error, caused by react syntax.

```
Uncaught Error: Module parse failed: Unexpected token (6:4)
You may need an appropriate loader to handle this file type.
| const MyPluginComponent = () => {
|   return (
|     <div className={styles.myPluginContainer}>
|         teste
|     </div>
```
After this I tried to install through npm, a pre-built plugin, with webpack passing throught babel-loader before install in "talks", but It didn't work too. The "talks" didn't recognize "slots" in my component.

How is the right way to install external plugins in talks project? Pre-built npm modules or not? Should I change some options in webpack config in "talks" project to support this?

Thanks for help,

Carlos

**Comment by wyattjoh** [comment]
Hi @caeugusmao!

I think you might have been caught by a few weird issues. The 404 is a common issue on yarnpkg.com unfortunately, so re-trying that process should help it out.

When specifying an external plugin, you should only need to include:

```js
{
  "server": [
    // ...
  ],
  "client": [
    // ...
    {"my-external-npm-package": "^semver"}
}
```

And it should load correctly when you run the cli tool.
