### ISSUE TITLE
Slack integration users list command throws error, v4.0.0

### ISSUE THREAD

**Issue by jheasly** [coralproject/talk#1314]
### Expected behavior
Return list of users in order to find or create a moderator user that can be used as the basis for the token
### Actual behavior
`./bin/cli users list` (and `cli-users list`) produces this error:
```
/usr/src/app # cli users list

/usr/src/app/bin/util.js:66
  throw err;
  ^

TypeError: Cannot read property 'join' of undefined
    at data.users.nodes.map.user (/usr/src/app/bin/cli-users:164:38)
    at Array.map (<anonymous>)
    at Object.source (/usr/src/app/bin/cli-users:163:33)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
/usr/src/app # 
```
### Steps to reproduce behavior
At first step of Slack integration run `./bin/cli users list` (or `docker-compose run --rm talk cli users list`).

**Comment by wyattjoh** [comment]
This was fixed already, and should be released in 4.1.
