### ISSUE TITLE
Probes / Health checks

### ISSUE THREAD

**Issue by TBeijen** [coralproject/talk#1340]
### Expected behavior

``/probes/liveness`` returning a 200 OK as long as the talk process runs and handles requests (so is not in crashed state without the process having terminated)

``/probes/readiness`` returning a 200 OK as long as the application operates correctly, meaning it can reach required components like redis and mongodb.

### Actual behavior

No dedicated health check uri, so resorting to checking ``/`` accepting a 404, or checking admin endpoints like ``/admin/moderate`` which doesn't seem quite right either. These types of workarounds will also likely pollute logs and monitoring output.

### Steps to reproduce behaviour
N/A

----

Proposed probose follow the Kubernetes model:

* https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
* https://www.ianlewis.org/en/using-kubernetes-health-checks

This would fit Kubernetes setups but also other types of load balancers that can be configured to use either one.

It looks like we can start doing this in one of our own plugins, then if we're satisfied we can port it to talk and issue a PR.

**Comment by wyattjoh** [comment]
You can hit the `/api/v1/` route to get the "current version" sent back to you.

```
$ curl http://localhost:3000/api/v1
{"version":"4.1.0"}
```

Does that satisfy your requirements? It will respond when the application is alive and accepting requests as it will exit when the process cannot start.

**Comment by TBeijen** [comment]
Yes, that would do for our current needs. It looks like a good monitoring endpoint. 
We're not (yet) using Kubernetes so will cross that bridge when we get there. 

So, I'd be ok with closing it. Would also be ok with keeping it open if there's other parties interested in probes following the Kubernetes pattern. But considering we're for now covered it won't be on the top of our priority list now.

On a sidenote: What would be the best way to 'explore' the api? (As there seems little to no documentation)

**Comment by wyattjoh** [comment]
We're in the process of moving all our REST based API's over to GraphQL, which you can browse (in development) at: http://localhost:3000/api/v1/graph/iql
