### ISSUE TITLE
i18n framework should use English as a fallback for missing translations

### ISSUE THREAD

**Issue by hellp** [coralproject/talk#1357]
## Expected behavior

When a new version of Talk is released, containing new translatable strings (i.e. code using `t('foo.greeting')`), and these strings have entries in `en.yml` (e.g. `foo.greeting: Hello`), then using Talk in a different language for which the language files have not been completely updated, these new strings should appear as English in the UI.
## Actual behavior

Currently the translation key is shown to the user (e.g. 'foo.greeting Fabian!')

In my opinion this approach does not scale when Talk is translated into more and more languages. On each release the whole Talk core team needs to wait for all languages to catch up with their translation files – or accept that users might see these ugly keys until the tranlations are ready.

---

## Proposal

I propose implementing a fallback logic in `coral-framework/services/i18n.js`.

### Scenario: A German Talk instance is visited by a Spanish user

1. Talk is configured with `defaultLanguage == 'de'`. The user's browser requests `es`, but the requested string has not yet been translated into Spanish.
1. The i18n framework would now cascade through the translation objects like this: `es -> de -> en` (`browserLanguage --> defaultLanguage --> fallbackLanguage`).
1. It would return the first available translation that it finds: ideally ES, maybe DE, definitely EN. Never the key.
1. (Actually there would be a fourth fallback, the one to return simply the key, just as it works right now. But this would be considered a bug. It should be logged; CI could check it and reject code that introduces new translatable strings without a translation in the fallback language.)

### Advantages:

- A scalable solution for a Talk with more and more supported languages.
- No more ugly keys in the UI.
- Translators have time to adapt their translation files (post-release) in their local/custom setup, and ideally contribute to upstream Talk. Of course, **ideally** all translations would be ready before a new release, but…

### Disadvantages:

- The site could appear in a language mix of up to 3 languages (user, site-default, fallback).
- To mitigate this we could remove `defaultLanguage` from the cascade, so that if the user-wanted language is not available, only text in the `fallbackLanguage` appears, which would mean max. 2 languages in the UI. My guess would be that it is more likely that a non-EN internet user who visits a non-EN website which is at the same time not in their language, would rather see texts in EN than the language of the website owner.
- (Minor) Missing translations might be not that obvious anymore.
- (Minor) Translators might have less incentive to "deliver on time".

**Comment by hellp** [comment]
I'm putting this here for discussion. I haven't found the time to implement this yet. I assume that it could be done in a 30-50 lines change PR in i18n.js.

But first I wanted to hear if this is actually desired or if you even have considered switching to a more sophisticated translation framework. Personally I do not have experiences with i18n in the nodejs world. The current YAML-based solutions seems okay-ish for the beginning (I mean, it's really easy to do and understand), but not very flexible and scalable if more people work on more languages for Talk.

**Comment by wyattjoh** [comment]
We certainly have plans to use a more sophisticated framework in the future, just a matter of time :)

We've implemented your suggestion! https://github.com/coralproject/talk/pull/1359

**Comment by hellp** [comment]
Wow, that was quick :) Looks like my 30+ lines guess was also a bit conservative. Thank you!
