### ISSUE TITLE
Re your development team performance...

### ISSUE THREAD

**Issue by DHorse2** [coralproject/talk#1375]
As an observer (commenter, evaluator) doing this on a time available basis (30 min / week),
### Expected behavior
Measurable, observable improvement in features and bug issues.
Ownership.
Clear communications.
### Actual behavior
I don't see any problems so far.
### Steps to reproduce behavior
Compliment staff on doing a good job.

Good job.
This issue is closed.

**Comment by kgardnr** [comment]
Thank you for the kind feedback @DHorse2! Have a great weekend!
