### ISSUE TITLE
Signing up via Facebook silently fails if user with same name already exists

### ISSUE THREAD

**Issue by kitwestneat** [coralproject/talk#1376]
When a user signs up to Talk via Facebook, a new user is created with the username in the format <Firstname>_<Lastname>. If a user already exists with that username, the sign up will silently fail, with only a error message in the browser console.

**Comment by kitwestneat** [comment]
One possible solution might be to add a random number to the autogenerated name if there is collision.

**Comment by kitwestneat** [comment]
I had a patch to fix the error message part of this bug, but the auth system keeps changing too fast, so I'll put that on hold. 

I'll work on adding a random number because this seems like a pretty bad bug actually. It makes it impossible for two people with the same name to sign up using FB or Google.

**Comment by wyattjoh** [comment]
Fixed in #1427
