### ISSUE TITLE
 TALK_ROOT_URL must be provided

### ISSUE THREAD

**Issue by shyam528** [coralproject/talk#1379]
Have  set the  TALK_ROOT_URL from terminal, still getting error  TALK_ROOT_URL must be provided

**Comment by kgardnr** [comment]
Hey @shyam528! Do you have a .env file set up with the required configuration set: https://coralproject.github.io/talk/configuration/

**Comment by shyam528** [comment]
Yeah, it's working now..

**Comment by kgardnr** [comment]
Ok great! Thanks @shyam528! Welcome aboard!

If you're interested in using Talk for a specific newsroom, let us know cause we can help you with integration and training. And same if you're looking to contribute as a developer. We're here for you!
