### ISSUE TITLE
View Context link doesn't work on Comments held in Reported because of Trust

### ISSUE THREAD

**Issue by jheasly** [coralproject/talk#1385]
### Expected behavior
In cases where a comment lands in `Reported` because of a low `Trust` score, the `View Context` link should either **1.)** take you to the spot in the comment tree the comment would appear, or **2.)** the `View Context` link should be disappeared (because there is no context to see as the comment hasn't been posted yet).

### Actual behavior
Clicking the `View Context` link just causes the comment rendering to hang (assuming it's because there's no comment context to show as the comments not been posted).

### Steps to reproduce behavior
Click the `View Context` link of a comment `Reported` due to `Trust`.

**Comment by jheasly** [comment]
Also, we do have comments hidden by default, but this doesn't seem to cause any problems w/ the `View Context` link on flagged/reported comments.

**Comment by kgardnr** [comment]
This is an interesting edge case - thank you for finding this @jheasly! We will discuss with the team and get back to you on this.

**Comment by wyattjoh** [comment]
Fixed in v5.
