### ISSUE TITLE
Live updates on version 4.2.1

### ISSUE THREAD

**Issue by leeeandroo** [coralproject/talk#1386]
### Expected behavior
When one user send a comment, all users with the page opened in the same story show a live update message that there is a new comment.

### Actual behavior
On this new version, there is no notification on embed stream. On `4.2.0` It works.

### Steps to reproduce behavior
- Run talk on version `4.2.1`
- Open two different browsers with the same story opened
- Send a comment
- Check if there is new comment in another window without need to refresh page

Any tip about how to fix it?

**Comment by kgardnr** [comment]
Thanks for reporting this @leeeandroo, we are reviewing now!

**Comment by kgardnr** [comment]
This is a bug @leeeandroo, we have a hotfix (4.2.2) going out shortly. Thanks so much for reporting this!
