### ISSUE TITLE
Add WYSIWYG/Rich Text Editor for Comments

### ISSUE THREAD

**Issue by aguilarm** [coralproject/talk#1389]
Hi!  I'm most likely going to use Coral Talk to replace an existing Drupal commenting system, and one thing I'm interested in adding is a WYSIWYG editor of some sort.  Drupal uses CKEditor, so I've had a go at adding that to Talk.

I've forked talk and [made a branch here](https://github.com/favish/talk/tree/ckeditor).

I noticed that this is already on your roadmap.  I'd like to get feedback on this or perhaps chart a path to get editors into Talk core.

A few things I've encountered that I'm unsure of

- I used context to pass settings from the `Root` gql object down to the `Draft` component for the `CustomCSSUrl`, when I added WithFragments to it I got nada.  This is the first project I've used graphql on and I'm sure my approach could be improved here.

- I sanitize the user input before save in `createPublicComment` before the word filter is applied.  The allowed tags are replicated here and in the CKEditor settings on the `Draft` component.  I'll need to provide either a sane default set or expose it in the Talk admin interface to edit and save it in a useful format for both of these.

- I added placeholder config as `wysiwygEditor` which could be added to the base settings of Talk in case we'd like the editor to be swappable.  That also potentially means we should instead be approaching this by creating a plugin API for swapping the text editor out and place most of my work with CKEditor into a plugin?

Thoughts on this?

**Comment by okbel** [comment]
Hey Mika! Woah! It feels good to replace Drupal right? haha :)
I'm currently working on this one -  https://www.pivotaltracker.com/story/show/150495261 

There are a couple of constraints: 
- It needs to be a plugin (So we can choose whether to turn it on or off)
- The editor has to be lightweight (Mobile is key for us)
- We can consider HTML/Markup/other options but as long as it's a safe option

I took a look and my advice here would be that you build a plugin for it. 
Here are some resources that will help you through it:

[Our Talk Recipes](https://github.com/coralproject/talk-recipes) - Here we have a couple of recipes to build plugins.
[Talk Core Plugins](https://github.com/coralproject/talk/tree/master/plugins) - The plugins in our core
[Our Docs: Plugins](https://coralproject.github.io/talk/plugins/) - Our Docs
 
I'm taking a look at [CKeditor](https://github.com/codeslayer1/react-ckeditor). Give it a shot and let us know how it goes! We will end up with two great Rich Text Editor plugins :)

**Comment by aguilarm** [comment]
@okbel 

Cool, noticed your [pull request](https://github.com/coralproject/talk/pull/1391) creating a slot to replace the textarea, that looks great!

I can most likely use that to add in CKEditor or try out pell.  I suppose I can come back to this once that  PR has been merged and adjust my implementation to a plugin now that the slot will be in core.

**Comment by okbel** [comment]
Sure! Feel free to come back or pull that branch and try making it with CKEditor. 

Thanks for your interest on making Talk awesome (:
