### ISSUE TITLE
Creating users via CLI?

### ISSUE THREAD

**Issue by kardamom** [coralproject/talk#1392]
I see the ability to create a new user via bin/cli-users was removed as part of this commit: https://github.com/coralproject/talk/commit/62603395089af8859c9c3b89837811270b0beebe

Is there another way I can create a user outside the web client?

The trouble is I've integrated my own auth system, which uses my integer ids as talk profile ids, rather than email addresses. This is fine for non-admin users but I need a couple of admin accounts to be able to login to the moderation console. (Which requires an email address.)

**Comment by kgardnr** [comment]
Hey @kardamom, thanks for writing! You can create users via your own Sign Up flow on the stream, and then change their role to an Admin by using:

`bin/cli users set-role <USERID> ADMIN`

You can find the USERID by using:

`bin/cli users list`

Let me know if that helps! 

Also we'd love to know where you're using Talk!

**Comment by kardamom** [comment]
Thanks @kgardnr - I've managed to do that, but as it stands I don't pass the email address to talk when I create a user in my plugin. And that address is required to login to the moderation console. I could of course rewrite my code to use email rather than an internal id as the talk profile id, but I'd rather not have to.

I'm using Talk for a so-far stealth startup :) I was planning on writing up how I got it all to work on Google Cloud - anywhere particular I should post that? StackOverflow?

**Comment by kardamom** [comment]
I realise that if I manage to do what I want - create an admin user with an email address in the talk db, but leave my own users identified by my own ids - that the admin user then won't be able to login to my site and be automatically logged in to talk, but that's fine by me - I'm happy having moderators in a separate system.

**Comment by kgardnr** [comment]
Ohhhh hmm... could you show me where your stream is embedded so I can take a look?

**Comment by kardamom** [comment]
Is that a bad 'hmm'?

I can't show you, sorry - the site is in development, pre-beta, locked down.

I could share my plugin code if that helps.

I'm considering propagating the email address. Though that'll entail more work to keep each address in sync if they're changed on my site.

**Comment by kgardnr** [comment]
Ha, no just a thinking "hmm".

Yeah we would definitely recommend using email addresses then - it's a key part of Talk currently.
