### ISSUE TITLE
Feature Idea: Live updates in premod and for comment owner

### ISSUE THREAD

**Issue by leeeandroo** [coralproject/talk#1396]
As a commenter, I'd like to have live updates if my comment was approved by moderation. 
We are using our moderation API, then on `post` from `createComment`, we approve/reject comment according of the API response.

### Expected behavior
When I send my comment it will start by PREMOD. Then the application ask API and setStatus to `ACCEPTED` or `REJECTED` using the response from an external API. If the comment was approved, then all connected users will receive a live update with a new comment.

### Actual behavior
When I publish the event `commentAdded`, just the other users received the update, not the owner of the comment. 

Is it possible to publish an event that all users are subscribed?

Also, If we use PREMOD without external API, can we receive notification that there is new comment if the moderator approves the comment while user connected on Talk stream? Now users just get the new comments If they refresh the page.

Thanks,

**Comment by kgardnr** [comment]
Hey @leeeandroo, we don't have any plans currently to allow commenters to see if their comment was approved or rejected in real-time. 

Good point on making pre-mod approved comments update the stream in real-time. I'll bring this up with the team!

**Comment by kgardnr** [comment]
Hey @leeeandroo this is now support in v5, so I'm closing this issue
