### ISSUE TITLE
New comments show immediately in the comment stream when premod is on

### ISSUE THREAD

**Issue by jde** [coralproject/talk#141]
### Expected behavior

When premod is set and a user enters a comment they should not see the comment and see a message saying that the comment is in for moderation.

### Actual behavior

The comment is shown.
No message is shown.
On refresh, the comment disappears (as it should.)

### Steps to reproduce behavior

Make sure premod is on.
Leave a comment.
See the behavior described above.

**Comment by wyattjoh** [comment]
Wait until https://github.com/coralproject/talk/pull/137 merges then test to see if this resolves it. Note that comments that are created when `{moderation: pre}` is set in settings will have the status of `premod`. Comment created when `{moderation: post}` is set in settings will have no status.

**Comment by gabelula** [comment]
I just merged #137 and is not fixing it.

Also, the comment is shown AND the message is also shown at the bottom of the page.

**Comment by gabelula** [comment]
Fixed.
