### ISSUE TITLE
tokenUserNotFound hook isn't firing

### ISSUE THREAD

**Issue by tc-mccarthy** [coralproject/talk#1416]
### Expected behavior
I have created a plugin with the following structure:
```
├── index.js
└── server
    └── notfound.js
```

#### index.js
```
const { tokenUserNotFound } = require('./server/notfound.js')
module.exports = { tokenUserNotFound };
```

#### notfound.js 
```
module.exports = {
	tokenUserNotFound: async({ jwt, token }) => {
		console.log("NOT FOUND");
	}
};
```

when firing `embed.login(<token>)` I expect my node console to light up with a "NOT FOUND" so that I can move on to enhancing this process to create the user based on the login information in my website's database.

### Actual behavior
express is returning a 204 and the nodejs console doesn't light up NOT FOUND.

**Comment by tc-mccarthy** [comment]
I figured it out. The issue was that my token wasn't verifying correctly and so it was never bubbling up to the Passport JWT strategy.

When generating your own token, [your payload needs to include](https://tools.ietf.org/html/rfc7519#section-4.1.3):

```
{
    iss: "<TALK URL>",
    aud: "talk",
    ...
}
```

**Comment by davisshaver** [comment]
@tc-mccarthy I'm running into something similar https://github.com/coralproject/talk/issues/1567. Any tips for how you validated the token? I can't find where to start tracking the bubble up.
