### ISSUE TITLE
if an error occurs while scraping, an asset should be rescraped at a later date

### ISSUE THREAD

**Issue by kitwestneat** [coralproject/talk#1417]
As an admin, I don't want talk to use invalid asset data. 

The current behavior is that if Talk is triggered on a post that is not yet public, the asset gets added with the title Page Not Found. It does not seem to be rescraped by Talk until a refresh is manually triggered. 

The behavior I expect is that Talk would not set the asset data if the scrape results in an error. Alternatively, if there were an API call that could be triggered to rescrape a specific asset, then it could be integrated into our CMS.

**Comment by wyattjoh** [comment]
While we currently don't have an exposed API for triggering a rescrape, it would be simple enough to add the following plugin (roughly sketched):

```js
const authz = require('middleware/authzorization');
module.exports = {
  router: router => {
    router.post(
      '/api/v1/assets/:id/scrape',
      authz.needed('ADMIN'),
      async (req, res, next) => {
        const { services: { Scraper } } = req.context;
        const { id } = req.param;

        try {
          // Create the scrape job.
          await Scraper.create({ id });

          res.status(204).end();
        } catch (err) {
          return next(err);
        }
      }
    );
  },
};

```

**Comment by kgardnr** [comment]
Hey @kitwestneat, we're adding this to core as well - wanna take a look? https://github.com/coralproject/talk/pull/1418/files

**Comment by kitwestneat** [comment]
That looks like it could work. Ideally we'd have it be a server to server call. Is there a good/recommended way to do that?

**Comment by wyattjoh** [comment]
Of course! You can generate a token using the cli, and then use that token to issue the graph call to the server (via cURL or other).

**Comment by kitwestneat** [comment]
ok great, it seems to be working. just out of curiosity, do you know if there are other Talk installations using wordpress? I'm surprised this hasn't been an issue for other folks.

**Comment by wyattjoh** [comment]
There are, but we don't have any metrics.
