### ISSUE TITLE
Event service no longer exists, not sure how to trigger on events now

### ISSUE THREAD

**Issue by kitwestneat** [coralproject/talk#1426]
We have a plugin that relies on the USER_NEW event, but it looks like events are completely gone in master. Is there a replacement planned, or any alternate method to trigger when a new user is created?

**Comment by kgardnr** [comment]
Hey @kitwestneat are you pulling directly from master and running that in production?

**Comment by kgardnr** [comment]
We will be making changes to the event service with 4.3.0 which will add notifications. Here's the PR you can review: https://github.com/coralproject/talk/pull/1350

If you're running off master, you might get breaking changes, as we push new code there nearly hourly some days :)

We recommend you use the releases which are tested and documented.

**Comment by kitwestneat** [comment]
we aren't running it on master, but we are developing against it. I'll check out the PR, thanks!

**Comment by kgardnr** [comment]
Gotcha! Ok, great - let us know if you have any questions!

**Comment by kitwestneat** [comment]
It looks like the user creation event is not part of the pubsub subscription endpoints. Are there plans to add that functionality back in through some other method?

**Comment by wyattjoh** [comment]
The subscription should be available with the referenced PR. An example of how to plugin to that is also provided in the PR details @kitwestneat 😄

**Comment by kitwestneat** [comment]
great, thanks!
