### ISSUE TITLE
DockerHub coralproject/talk has a broken link to install instructions.

### ISSUE THREAD

**Issue by smarkwell** [coralproject/talk#1429]
#### Do you want to request a **feature** or report a **bug**?

Bug

#### Intended outcome:

Docker documentation on DockerHub should be accurate

#### Actual outcome:

The link to INSTALL.md is broken and not in GitHub
This should either be pointed to existing documentation such as https://coralproject.github.io/talk/installation-from-docker/ or new documentation

#### How to reproduce the issue:
Visit https://hub.docker.com/r/coralproject/talk/
Click INSTALL.md

#### Version and environment

N/A

**Comment by wyattjoh** [comment]
It should be updated! We've just recently been moving our docs, see https://docs.coralproject.net/talk/installation-from-docker/.
