### ISSUE TITLE
Story title never gets assigned for posted comments

### ISSUE THREAD

**Issue by ollyd** [coralproject/talk#1459]
#### Do you want to request a **feature** or report a **bug**?
bug

#### Intended outcome:

When moderating comments in the admin console, I expect to be able to see the story headline from which the comment was posted. This should come from the `asset_title`, but that variable never gets assigned.  

#### Actual outcome:

Until recently, the 'Story' field remained blank, but with a recent change it now falls back to showing the `asset_url` when there's no `asset_title`.
<img width="671" alt="screen shot 2018-03-21 at 2 07 51 pm" src="https://user-images.githubusercontent.com/796938/37693027-f7ea0ea6-2d10-11e8-8199-a3f7c3bb482a.png">

#### How to reproduce the issue:

* post a comment
* find that comment in the admin console
* check the 'Story' value. It will be either blank or show a url rather than the story title.
   
#### Version and environment

Talk version 4.2.2
Chrome version 64.0.3282.186 (Official Build) (64-bit)

**Comment by wyattjoh** [comment]
I wasn't able to replicate the error on master right now. Check your server logs to see if you have any errors related to asset scraping, and that the URL is publicly accessible.

**Comment by ollyd** [comment]
Yeah you're right, it turns out that we need to use a proxy for the scraper to access our site. Happy to close this.

Out of curiosity, do you know the rationale for using a scraper to get the title?

**Comment by wyattjoh** [comment]
A scraper lowers the burden for adopting the system, as most newsrooms don't have full control over their CMS, they can't push in asset metadata. Good to know you found the issue though!
