### ISSUE TITLE
Move linting to webpack config

### ISSUE THREAD

**Issue by okbel** [coralproject/talk#147]
### Problem
Linting is sometimes omitted or it takes a lot to run. Running it with webpack will decrease the wait and improve the developer experience.

### Solution

This could easily be arranged by adding this to our webpack.config file.

```js
      {
        enforce: 'pre',
        test: /\.js$/,
        loader: 'eslint-loader',
        exclude: /node_modules/
      },
```

This way we can remove the linting hooks, only leaving the tests.

Thoughts?

**Comment by wyattjoh** [comment]
I think we can definitely add this to the webpack pipeline but it makes sense to me to keep the project wide linting in place as a "catch-all".

**Comment by jde** [comment]
+1 to keeping our linting rules in a single place since they apply to both FE and node code. @okbel, how much faster would it be to have linting in webpack? Do you think the performance gains you speak of are worth forking the linting rules?
