### ISSUE TITLE
Crash on double embed.logout(), resulting from DELETE /api/v1/auth without authorization header

### ISSUE THREAD

**Issue by TBeijen** [coralproject/talk#1472]
Talk version: 4.2.2
Steps to reproduce: Calling ``embed.logout()`` twice.

----

When calling ``.logout()`` twice on the object returned by ``Coral.Talk.render()``, the application crashes

First call issues a request to backend that translates to (copied as curl, irrelevant headers removed for readability):

```
curl 'http://127.0.0.1:5000/api/v1/auth' -X DELETE 
-H 'Content-Type: application/json' 
-H 'Accept: application/json' 
-H 'Cache-Control: no-cache' 
-H 'Authorization: Bearer <my-token>' 
```

Backend request from second ``.logout()`` has no Authorization header:
```
curl 'http://127.0.0.1:5000/api/v1/auth' -X DELETE 
-H 'Content-Type: application/json' 
-H 'Accept: application/json' 
-H 'Cache-Control: no-cache' 
```

And results in Talk crashing with following error:

```
TypeError: Cannot read property 'exp' of undefined
    at HandleLogout (/Users/tibobeijen/projects/repos/coral-talk-nunl/talk/services/passport.js:189:22)
```

**HTTP status code**

Now about the returned status code of the second DELETE request. There's quite some debate that can be googled. Examples:

* https://evertpot.com/idempotence-in-http/
* https://stackoverflow.com/a/24713946/334320

So... One could say there are arguments to returning a ``404`` in the second DELETE. On the other hand, a ``404`` implies something going wrong and also: We're not specifying the resource to be deleted in a true RESTful way, but instead imply it via the ``Authorization`` header.

I'd say any DELETE request without header returning a ``204`` would be pragmatic and consistent with the ``204`` returned by the first request.

**Proposed fixes**

* Prevent ``DELETE /api/v1/auth`` request without ``Authorization`` header to crash app.
* (Optionally) Prevent frontend from handling ``.logout()`` when already logged out.

**Comment by kgardnr** [comment]
This will be fixed in 4.3.0. 🎉
