### ISSUE TITLE
Set a useragent on story metadata grabber

### ISSUE THREAD

**Issue by icco** [coralproject/talk#1480]
#### Do you want to request a **feature** or report a **bug**?

Bug

#### Intended outcome:

Search our logs for requests made by coral talk to get metadata of stories. I'd expect to be able to find something like Coral Talk in the useragent string of requests made.

#### Actual outcome:

We don't collect IPs (for a variety of reasons), so UserAgent is the only piece of data I have to search for Talk. I couldn't find any of the requests because of this

#### Version and environment

Talk 4.1 running inside docker on AWS

**Comment by icco** [comment]
Right now the useragent is `"https://github.com/blakeembrey/popsicle"`, as talk is using an old version of metascraper which still does the scraping:  https://github.com/microlinkhq/metascraper/blob/1.0.7/lib/index.js#L26-L32

The current docs (https://metascraper.js.org/#/?id=usage) suggest you scrape yourself, thus being able to set the user-agent when you scrape at https://github.com/coralproject/talk/blob/master/jobs/scraper.js#L11-L19

**Comment by icco** [comment]
Also, is there a way to force coral to rescrape all of our stories?

![screen shot 2018-03-23 at 3 59 39 pm](https://user-images.githubusercontent.com/20201/37851414-22825326-2eb5-11e8-93d5-08a81dea5d0c.png)

We have this currently on one of our dev servers because of an auth issue.

**Comment by wyattjoh** [comment]
Love. This. Idea.

I'm prepping a PR to resolve this, and upgrading our metascraper!

**Comment by wyattjoh** [comment]
If you want to force a scrape now, you can run `./bin/cli assets refresh 1yr` to force the re-scrape. Checkout the scraper PR #1481 that should make your suggested improvements!
