### ISSUE TITLE
Feature Idea: Add prometheus metrics

### ISSUE THREAD

**Issue by icco** [coralproject/talk#1508]
#### Do you want to request a **feature** or report a **bug**?

Feature

#### Intended outcome:

I'm trying to get metrics about how our system is performing. Things like comments per minute, requests per second, request latency, request error counts. Total comments. Stuff like that.

#### Actual outcome:

There is no metrics system implemented.

#### Version and environment

I'm currently running talk 4.1.0

**Comment by wyattjoh** [comment]
We definitely have this on our roadmap! Already a Prometheus fan, so this seems achievable.

**Comment by icco** [comment]
Awesome, we're rolling it out across our infra, so if it just showed up, that'd be awesome :D

**Comment by kgardnr** [comment]
As a sidebar this would be an awesome plugin - maybe there is an existing npm package or other library we could hook into?

**Comment by aguilarm** [comment]
[There is a node prometheus client](https://www.npmjs.com/package/prom-client) :heart_eyes:.  Hook up for basic metrics appears to be just a few lines, supporting custom metrics also pretty straightforward.

**Comment by kgardnr** [comment]
@icco check it outtttttt https://github.com/coralproject/talk-plugin-prom

**Comment by kgardnr** [comment]
Bumping the above comment for @icco (who just returned from his honeymoon! 🎉 congratulations!)

I'll close this as we now have Prometheus support via https://github.com/coralproject/talk-plugin-prom

**Comment by icco** [comment]
Woot, thanks!
