### ISSUE TITLE
Adding more admin accounts for moderation

### ISSUE THREAD

**Issue by larrylizhao** [coralproject/talk#1514]
#### Do you want to request a **feature** or report a **bug**?
Feature

#### Intended outcome:
To have more than one admin accounts for moderation.

#### Actual outcome:
Currently I can only have one account to login and do the moderation. In the login page, can not find the entry to register another account.
<img width="1280" alt="talk admin" src="https://user-images.githubusercontent.com/9674627/38533536-47708f4a-3cac-11e8-9239-2598a2e1f2bb.png">

#### How to reproduce the issue:
We can see current status at CORAL_ROOT_LINK/admin/install.

#### Version and environment
Talk version: coralproject/talk:4.2.2
On Mac: macOS Sierra

**Comment by kgardnr** [comment]
Hi @larrylizhao! Apologies for delay here.

We don't currently have a way to invite more admins - but what you can do is have them sign up for accounts on the stream and then upgrade their role in the Community tab.

**Comment by larrylizhao** [comment]
@kgardnr I see, I'll try to do it that way, thanks!
