### ISSUE TITLE
Talk iframe not displayed when cookies disabled in Firefox

### ISSUE THREAD

**Issue by cecilebertin** [coralproject/talk#1520]
#### Do you want to request a **feature** or report a **bug**?

Report a bug

#### Intended outcome:

I was trying to find out, why we have so little comments on https://internethealthreport.org/2018/

The comment section should still show when disabling cookies.
<img width="360" alt="capture d ecran 2018-04-11 a 14 21 47" src="https://user-images.githubusercontent.com/21285660/38643977-e40b6536-3d93-11e8-8f3d-2fe5ae201421.png">

#### Actual outcome:

Nothing was displayed.
<img width="360" alt="capture d ecran 2018-04-11 a 14 20 57" src="https://user-images.githubusercontent.com/21285660/38643989-ea4262ec-3d93-11e8-8239-63f0a0e75104.png">

#### How to reproduce the issue:

1. In the Firefox preferences, in the Privacy & Security panel, go to the History section.
2. In the drop-down menu next to Firefox will, choose Use custom settings for history.
3. Remove checkmark next to Accept cookies from websites
4. Go to a page with a comment section using Talk. (https://internethealthreport.org/2018/spotlight-understanding-fake-news/) and observe

#### Version and environment

Firefox 58.0.1 (64 bits)
The issue does not happen in Chrome or Safari

**Comment by cadecairos** [comment]
Here's the JS error thrown in console when cookies are disabled in Firefox:

```
TypeError: t is null[Learn More] bundle.5cae070d173d9586ed5c.js:1:461896
	pe https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:461896
	./client/coral-framework/services/i18n.js https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:462590
	o https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:385
	./client/coral-framework/utils/index.js https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:476469
	o https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:385
	./client/coral-embed-stream/src/containers/Embed.js https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:49044
	o https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:385
	./client/coral-embed-stream/src/index.js https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:73765
	o https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:385
	multi babel-polyfill /tmp/build_f4a7f0446ded403ccab53a6901455d4a/client/coral-framework/helpers/publicPath /tmp/build_f4a7f0446ded403ccab53a6901455d4a/client/coral-embed-stream/src/index https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:2331327
	o https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:385
	<anonymous> https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:1454
	<anonymous> https://talk.mofoprod.net/static/embed/stream/bundle.5cae070d173d9586ed5c.js:1:2

```

**Comment by wyattjoh** [comment]
Thanks for the report @cecilebertin! We have a fix in the works that'll be merged and released soon!

**Comment by wyattjoh** [comment]
The issue should be resolved in our latest release https://github.com/coralproject/talk/releases/tag/v4.3.2
