### ISSUE TITLE
Extra user information in each comment

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#1524]
Hello

 I am creating a plugin and I want get more  informations about the user in each comment. Today I have only {id, username}. I wold like have user.profiles.metadata.displayName that was created by my plugin. 

Thanks in advance

**Comment by wyattjoh** [comment]
If you include the `displayName` into the comment, you can also override the resolver for the username to have it substitute in the `displayName`:

```js
const { get } = require('lodash');
module.exports = {
  resolvers: {
    User: {
      username: user => get(user, 'metadata.displayName', user.username)
    },
  },
};
```

See our [server side plugin api](https://docs.coralproject.net/talk/api/server/#resolvers) for other features like that. If you want to include more information in the graph request, that's a different story.

**Comment by cristiandean** [comment]
It's work! Thank you!
