### ISSUE TITLE
Add author_id index?

### ISSUE THREAD

**Issue by icco** [coralproject/talk#1529]
#### Do you want to request a **feature** or report a **bug**?

Bug

#### Intended outcome:

I was looking at the mongodb atlas and it suggested adding an index, I normally expect to see no indexes suggested.

#### Actual outcome:

This list of recommended indexes.

<img width="1135" alt="screen shot 2018-04-16 at 12 57 42 pm" src="https://user-images.githubusercontent.com/20201/38833396-60e3a4da-4193-11e8-944e-67d431675f77.png">

#### Version and environment

Talk 4.2.2 on Amazon ECS, Mongo DB instance running on MongoDB Atlas

**Comment by wyattjoh** [comment]
Great point! We do create indexes in Talk, but as we aren't database admins, it would be premature of us to add indexes where we haven't verified the gain for the end user.

Given your details, we're happy to add the index 😄.

Expect a PR to land soon to add the index, feel free to accept Atlas's suggested index create step.
