### ISSUE TITLE
Feature Idea: (temporarily) disable commenting site-wide (read-only switch)

### ISSUE THREAD

**Issue by hellp** [coralproject/talk#1540]
- As an admin I want a switch in the settings interface that disables commenting on the whole site, i.e. existing comments will remain readable but writing new comments (also replies) would not be allowed.
- Additionally I want to provide a short text that will appear instead of the comment input field. (E.g. "Commenting has been temporarily disabled.")

Use cases:

- technical issues in the automated moderation back-end (when using premod)
- all of the moderation team is sick
- other "worst-case" scenarios that temporarily may affect a whole site (shitstorms etc.)

From the user's POV this would be very similar to the per-asset close commenting feature Talk already has.

---

We are currently trying to implement this as a plugin, but it appears to be not possible to do it with plugin-only code. Any interest to have this in core?

**Comment by kgardnr** [comment]
Same here @hellp! Will get back to you on this.

**Comment by losowsky** [comment]
Thanks @hellp! We think this would be a good thing to add to core. We'd suggest adding another text box, like the "closed comments message" for after the time limit expires on keeping comments open, for writing the message.

Let us know what you need from us!
