### ISSUE TITLE
Is Category Moderation Possible?

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#1553]
Hello, I would like to know if there is a possibility of filtering comments by assets categories in the Coral Talk administration. Is there any feature that allows you to add a certain moderator to moderation of comments only from a particular category? Like for example:

Comments of ** sports ** are moderated by ** Moderator 1 **.
Comments for ** entertainment ** are moderated by ** Moderator 2 **.

Thank you.

**Comment by wyattjoh** [comment]
We've discussed it as a feature, but we haven't planned the feature yet.
