### ISSUE TITLE
[RFC] [WIP] WordPress single sign-on integration

### ISSUE THREAD

**Issue by davisshaver** [coralproject/talk#1567]
Exploring use of `auth_token` in the [WP Plugin](https://github.com/coralproject/talk-wp-plugin). 

...

Any ideas or tips appreciated!

**Comment by wyattjoh** [comment]
My best recommendation for you is to first use Talk's default login from the admin, and grab the token from localStorage after you login, and head over to https://jwt.io and drop that token in there. From there, you can see lots of fields lile the `iss`, `aud`, and otherwise. You'll also see the signing method used, and can verify that the secret you've passed to your custom PHP JWT generator can be used to verify the JWT there.

**Comment by wyattjoh** [comment]
It's likely that the token isn't validating correctly, hence why the `tokenUserNotFound` hook isn't firing.

**Comment by davisshaver** [comment]
Thanks for the help @wyattjoh, I got around to this again today and wanted to share some notes. I grabbed the token from my localStorage as suggested, but I was not able to get it to verify with the environment secret. I was just wondering if you had any ideas why this might be..

Here is example from staging environment:

token: ```eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4ZDIwNjYyYy1mYTRlLTRkM2UtOTliNi1hODYxZmNlOTdjMzQiLCJpYXQiOjE1Mjc4NDYwODQsImV4cCI6MTUyNzkzMjQ4NCwiYXVkIjoidGFsayIsImlzcyI6Imh0dHBzOi8vdGFsay5waGlsbHlwdWJsaXNoaW5nLmNvbSIsImp0aSI6IjZmZjQ5NjQ3LWM3NjAtNDZkYi05YjUwLWQzNjdiZmUwNzVjZCJ9.Du2oXyy4uJKrVioO8yvhm-amsuE9PXg7ySbJIsy2S_0```

secret:
```5655cd54876c97a51bde17141b5d00894b04e47ec97be49a6e48dcfd7fc8d7ed```

**Comment by davisshaver** [comment]
@wyattjoh Sorry this was my mistake. I hadn't been using the site you recommended. I was using https://www.jsonwebtoken.io/. This service gives different results than jwt.io.

**Comment by wyattjoh** [comment]
Hi @davisshaver! Check out our updated documentation on JWT's, and ensure the JWT you generate matches the configuration given to Talk: https://docs.coralproject.net/talk/integrating/authentication/#create-jwt-token

It's also important to note that users that already exist in the database, will not trigger the `tokenUserNotFound` hook.

**Comment by davisshaver** [comment]
@wyattjoh Picking this up again. I've got the JWT token validating correctly and am passing it to the embed code. It looks like the token is being handled by passport `authentication.js` middleware. Is this expected? I can't see my log statement firing.

```javascript
// talk-plugin-wp-signin/index.js
const { tokenUserNotFound } = require('./server/notfound.js')
module.exports = { tokenUserNotFound };

// talk-plugin-wp-signin/server/notfound.js
const debug = require('debug')('talk:plugin:wp-plugin');

module.exports = {
    tokenUserNotFound: async ({jwt, token}) => {
        debug("NOT FOUND")
    }
};

// plugins.json
{
    ...,
    server: [
        ...,
         "talk-plugin-wp-signin",
    ]
}
```

**Comment by davisshaver** [comment]
Here's my embed code...

```
	<script src="http://localhost:3000/static/embed.js" async onload="
		Coral.talkStream = Coral.Talk.render(document.getElementById('coral_talk_1386995325'), {
			talk: 'http://localhost:3000',
			auth_token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI1YmEzYTliOThmZGZkIiwiaXNzIjoiaHR0cDpcL1wvbG9jYWxob3N0OjMwMDAiLCJhdWQiOiJ0YWxrIiwic3ViIjoiZGF2aXNzaGF2ZXJAZ21haWwuY29tIiwiZXhwIjozNjAwfQ.U00Rq9wXmPTVPoOtgMotH55wpuGlQGJuw9j6NfB0KBo',
		});
	"></script>
```

The secret I'm using for testing is `5655cd54876c97a51bde17141b5d00894b04e47ec97be49a6e48dcfd7fc8d7ed`. This validates as,

```json
{
  "jti": "5ba3a9b98fdfd",
  "iss": "http://localhost:3000",
  "aud": "talk",
  "sub": "davisshaver@gmail.com",
  "exp": 3600
}
```

Relevant `.env`,

```
TALK_JWT_SECRET=5655cd54876c97a51bde17141b5d00894b04e47ec97be49a6e48dcfd7fc8d7e
TALK_JWT_AUDIENCE="talk"
TALK_JWT_ISSUER="http://localhost:3000"
```

The plugin appears to be loaded correctly.
```
  talk:plugins loading internal plugin 'talk-plugin-wp-signin' from '/Users/davisshaver/talk/plugins/talk-plugin-wp-signin/index.js' +0ms
```

**Comment by davisshaver** [comment]
could passport/facebook auth be interfering with sso?

**Comment by davisshaver** [comment]
Nevermind, it was the `exp`. Didn't realize, this isn't how long the token should be valid but rather epoch time of expiration.

**Comment by davisshaver** [comment]
Ok, I've got this working for WordPress single sign-on. Here's a gist, would love a sanity check... https://gist.github.com/davisshaver/5a41a84de339f1612067119c9930998d

One specific question, are there any plans to expose the display name in the embed? I didn't see how to make this happen.

**Comment by davisshaver** [comment]
@kgardnr Is this supported in v5? Why is ticket closed?

**Comment by kgardnr** [comment]
Hey @davisshaver I think you will find that auth/SSO is very improved and simpler to implement in v5, would love your feedback! v5 official release is coming first week of September 🎉

**Comment by davisshaver** [comment]
Sounds good, sorry! Didn't see your comment before I posted.
