### ISSUE TITLE
Talk integration with Firebase

### ISSUE THREAD

**Issue by unnisathyarajan** [coralproject/talk#1574]
Is Integration with an existing Firebase for authentication possible?

**Comment by wyattjoh** [comment]
We currently don't have an integration with Firebase no, but you can feel free to implement one yourself with our [Integrating Authentication](https://docs.coralproject.net/talk/integrating/authentication/) docs.

**Comment by kgardnr** [comment]
Also if you want to submit this as a new auth plugin, we would be happy to
review it and share it with the Talk community! Several folks have asked
about integrating with Firebase.

Thanks Unni!
