### ISSUE TITLE
Feature Idea: Moderator notes on users

### ISSUE THREAD

**Issue by mkonikov** [coralproject/talk#1575]
Our moderators would like the ability to be able to write internal notes about different users so they can refer back to them and gain some context when reviewing future comments.

The `userProfile` slot seems to be the best option for that.

Any thoughts on best way to implement or if this is something other Talk users would appreciate?

**Comment by kgardnr** [comment]
@mkonikov - thanks! I think this would be a great addition to add to core, and other newsrooms have requested it. 

I'll ask @IAmSamHankins to give some input here on placement and UX - probably the user drawer would be the best place.

**Comment by theysamtheirs** [comment]
hi @mkonikov -- this is definitely something we've had requested and something we've been considering. totally agree with that place being in the `userProfile` user drawer.

initial thoughts would be that it could be another tab (after `all` `rejected` and `account history`) that gives the moderators to enter notes at the top (as if it's own comment stream on that user) and lists the notes in reverse chronological order listing the moderator who left the note along with the date/time it was left. also probably some kind of marker/dot/indicator alerting moderators that there are in fact notes on this user. would love to know/hear your thoughts!

**Comment by kgardnr** [comment]
We've added this to v5 🎉 Closing this issue
