### ISSUE TITLE
Scraper without external access

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#1602]
Hello,

We have a Talk Application running in a server without external access and can't use a proxy to access our website. What do we can do to save the metadata without use the Talk scraper? Is there some way to pass metadata as params?

If this possibility doesn't exist, can I disable the scraper and take the Stream by asset URL? 

Thank you!

**Comment by mkonikov** [comment]
To answer the latter question, you could disable the scraper running it with `yarn start --disabled-jobs scraper` (More here: https://github.com/coralproject/talk/pull/1439)

**Comment by cristiandean** [comment]
Thank you!
