### ISSUE TITLE
Creating middleware for default routes [question]

### ISSUE THREAD

**Issue by thor27** [coralproject/talk#1605]
Hi!

I'm developing a plugin that needs to create a middleware on /api/v1/graph/ql
But since all default routes are inserted after the plugins we can't do that.

We moved up plugin insertion (lines 136-137 to line 108) on **/routes/index.js** to acomplish that:

```js
// Mount the plugin routes.
router.use(require('./plugins'));

// Attach the authentication middleware, this will be responsible for decoding
// (if present) the JWT on the request.
router.use('/api', require('./api'));
```

What do you think about this change?

**Comment by hjanuschka** [comment]
i want this too :)

i want to log statusCode's and request time. like this


```javascript

  router.use(function(req, res, next) {
    var startAt = process.hrtime();
	onHeaders(res, function onHeaders () {
        var diff = process.hrtime(startAt)
        var time = diff[0] * 1e3 + diff[1] * 1e-6
        res.setHeader("X-KRN-Took", time)
        res.setHeader("X-KRN-STATUS", res.statusCode)

	})
    next();
  })

```


not sure if moving up the `router.use(require('./plugins'));`  is the right approach, any ideas?

**Comment by hjanuschka** [comment]
maybe we can get another hook, beside letting the route hook where it is on `app.` level?
theny it would be easy to register app wide middleware, and not changing/breaking existing code ?

**Comment by hjanuschka** [comment]
ahhh nevermind, ther is a app hook :)
just export app inside your plugin 👍 https://github.com/coralproject/talk/blob/master/app.js#L23

**Comment by thor27** [comment]
We actually dropped this plug-in for now, so I don't have this need anymore, but thanks for the info, if we need this again we are going to do that as you said.
