### ISSUE TITLE
[Question] Disable websocket support

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#1615]
Our website has huge daily access and keeping websocket enabled is becoming too network intensive. We would like to be able to disable websocket for at least a first version in production.

As for now we can't do that. What do you think about having an option to completelly disable websocket on client and server? We can send a pull request with this feature if you think that this behaviour would be desired.

Thanks

**Comment by wyattjoh** [comment]
Without websockets, a refresh would be required to load any new content. It's something we can certainly explore for sure though.

**Comment by cristiandean** [comment]
Yes, we are going to lose freshness in favor of network stability for a first moment. A pull request for that is valid?

**Comment by wyattjoh** [comment]
I'm worried that a PR might get too big if it were to disable websockets. Our code is quite tightly coupled to the fact that subscriptions "just work". A PR would we welcome, but would likely consume quite a bit of time to write + review (just a fair warning ;))

**Comment by cristiandean** [comment]
Hello, I'm working on this PR and I came across a question.
I would like to use this setting to disable the websocket in the application client, more precisely in this section:

```
window.TalkEmbed = Coral.Talk.render(document.getElementById('coralStreamEmbed'), {
    talk: '{{ BASE_URL }}',
    asset_url: '{{ asset_url }}',
    asset_id: '{{ asset_id }}',
    websocket: {{ websocket_enable }},
```

My question is, what is the best way to get this setting? More precisely in the file **client/coral-framework/services/client.js**.

**Comment by kgardnr** [comment]
I'm closing this as we won't be including this in v4.x, but we will consider it for v5.
