### ISSUE TITLE
[Question] Confirm email from external providers

### ISSUE THREAD

**Issue by leeeandroo** [coralproject/talk#1619]
On the last release 4.0.0, now Talk ask for email and password and create a local provider to external users.

If it's enabled, Talk send the confirmation email to the user.
I'd like to know if you are planning to block user to do actions on Talk until confirm email if its enabled on Admin.

Are you interested on a PR of it?

Thanks,

**Comment by kgardnr** [comment]
Hey @leeeandroo we should already support this - and it's enabled if the org selects "Require Email Confirmation" in the Config - are you seeing different behavior?

**Comment by leeeandroo** [comment]
@kgardnr on my tests I'm receiving the confirmation email and all the flow is working - remove confirmation when after changed email, confirm the new one - but I can comment before confirm my new email.

I only see the validation if email is confirmed when I try to login with local provider.

Am I missing something?

Thanks

**Comment by kgardnr** [comment]
So you have "Require Email Confirmation" turned on; this is worked as expected with local accounts (can't comment, react until you verify), but not external (can comment, react even though not verified).

Is that correct?

**Comment by leeeandroo** [comment]
Exactly. 

My idea is to show a message like when user is banned and block all the actions. On this restricted message, we can show a button to user request confirmation email again like on login attempt.

**Comment by kgardnr** [comment]
Yes! This makes sense then - external accounts should function like local ones. This was probably an oversight on our part. We would love if you would contribute this, @leeeandroo! Thank you!~

**Comment by kgardnr** [comment]
Hey @leeeandroo! Actually hold on this, talked with the team and there are some requirements we need to solve in order to complete this.

So let's leave it as-is for now. We will circle back in near future!

**Comment by kgardnr** [comment]
I'm going to close this as we won't be providing this right now - external providers don't guarantee providing an email address. So local accounts should be the ones to require email, etc.
