### ISSUE TITLE
[Question] Comment Body in notification

### ISSUE THREAD

**Issue by mkonikov** [coralproject/talk#1647]
Is there a specific reason notifications do not include the body of the comments?

https://github.com/coralproject/talk/blob/master/plugins/talk-plugin-notifications-category-reply/index.js#L101
Shouldn't be hard to throw up a PR to add but wondering if there's a specific reason it does not.

**Comment by kgardnr** [comment]
We made this decision based on data privacy and based on safeguarding from harassment. If in the future a commenter decides to remove their comments from the site, we don't want that data to live in someone's email. And if someone is being harrassed through comment replies, before a moderator is able to delete the comment etc, we don't want awful comments to live in that commenters inbox for all time.

We won't be supporting comment body in notification emails.
