### ISSUE TITLE
Network error: Network_request failed with status 403 - "Forbidden"

### ISSUE THREAD

**Issue by nevernervous** [coralproject/talk#1659]
I would like to use Talk project.
I installed it on my server and added embed code to my page.
But when load page, it shows 403 error.
This is my test url.
http://qwikleads.com/test2

Please help me.
Regards

**Comment by wyattjoh** [comment]
If you take a look at the network tab on that site, you can see that it's not actually hitting Talk, it's hitting some other service that's asking for a recaptcha. I'd take a look at why that's happening, as that's unrelated to Talk.

**Comment by nevernervous** [comment]
Thanks, @wyattjoh 
I have another issue.
This is my docker file.

 version: '2'
services:
  talk:
    image: coralproject/talk:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=development
      - TALK_MONGO_URL=mongodb://mongo/talk
      - TALK_REDIS_URL=redis://redis
      - TALK_ROOT_URL=http://127.0.0.1:3000 ( I set it with my domain but not working, too)
      - TALK_PORT=3000
      - TALK_JWT_SECRET=password
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data
volumes:
  mongo:
    external: false
  redis:
    external: false

After running `docker-compose up -d`, docker container of talk is restarting continuously.
![image](https://user-images.githubusercontent.com/31775195/40625457-369b1276-62e5-11e8-8d19-cff4191edd37.png)

I will be glad if you could help me with this.

Regards.

**Comment by wyattjoh** [comment]
What do the logs say when you run `docker-compose logs talk`?

**Comment by nevernervous** [comment]
Here are the logs.

talk_1   | Error: Cannot find module 'nunjucks'
talk_1   |     at Function.Module._resolveFilename (module.js:547:15)
talk_1   |     at Function.Module._load (module.js:474:25)
talk_1   |     at Module.require (module.js:596:17)
talk_1   |     at require (internal/module.js:11:18)
talk_1   |     at Object.<anonymous> (/usr/src/app/app.js:2:18)
talk_1   |     at Module._compile (module.js:652:30)
talk_1   |     at Object.Module._extensions..js (module.js:663:10)
talk_1   |     at Module.load (module.js:565:32)
talk_1   |     at tryModuleLoad (module.js:505:12)
talk_1   |     at Function.Module._load (module.js:497:3)
talk_1   | error Command failed with exit code 1.
talk_1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by wyattjoh** [comment]
This was a bug that was resolved in #1660, try pulling the docker image again and re-trying. For more reliable releases, set your tag to something other than `latest`.

**Comment by kgardnr** [comment]
Hey @nevernervous were you able to get this working for you?

**Comment by nevernervous** [comment]
Hi, @kgardnr 
I didn't use docker image. Just build the project from the source code and it works well now.
This is the really fantastic project.

**Comment by kgardnr** [comment]
@nevernervous wonderful! And thank you for the kind words! 💖
