### ISSUE TITLE
Feature idea: view or sort stories in admin by number of pending comments received

### ISSUE THREAD

**Issue by clintabrown** [coralproject/talk#1669]
#### Do you want to request a **feature** or report a **bug**?

Feature

#### Intended outcome:

Moderators wish to be able to view which stories are receiving a large amount of new comments (mainly PREMOD but possibly also SYSTEM_WITHHELD status) so more attention can be paid to them.

This could take the form of -

- In Stories the total for each status type is displayed alongside the story
- In Stories the View Options becomes a slot so new sort plugin(s) can be created based on these status type totals

We are happy to implement this feature but would again appreciate if you could a) validate the idea and b) if in favour offer any suggestions on implementation.

**Comment by clintabrown** [comment]
Hi @kgardnr - any update on thoughts around this feature?

**Comment by kgardnr** [comment]
Hey @clintabrown! Yes, we think being able to sort Stories by most comments would be a great addition. Do you want to suggest how you might implement this, and we can give some feedback for you?

**Comment by kgardnr** [comment]
Hey @clintabrown we'll be adding some similar stories to this in our next release of v5.

(PS we should talk about getting you upgraded)
