### ISSUE TITLE
Feature idea: Implement http proxy support for the scraper

### ISSUE THREAD

**Issue by lytvynenko** [coralproject/talk#1679]
#### Add optional http proxy agent to scraper's fetch configuration.

fetch-node module doesn't support http proxies out of the box. The recommended solution is provide http proxy adapter as an agent. (https://github.com/bitinn/node-fetch/issues/79). 

That shouldn't be a major change. Effectively we'll just introduce one extra dependency `https-proxy-agent` (https://github.com/TooTallNate/node-https-proxy-agent) and will add extra parameter to fetch request if `HTTP_PROXY` env. variable is set.

**Comment by wyattjoh** [comment]
This was actually implemented in #1674!
