### ISSUE TITLE
Why do you tag user-detail branch?

### ISSUE THREAD

**Issue by smic1909** [coralproject/talk#1683]
This is a general question:

I saw that you are tagging the `user-detail` branch and I am wondering why. Basically the `master` branch should be tagged. Maybe you can shed some light into the dark.

**Comment by kgardnr** [comment]
Hey @smic1909 can you explain more? I don't understand your question.

**Comment by smic1909** [comment]
Sry, my fault. The app I used mixed somehow branch names. All fine.

**Comment by kgardnr** [comment]
No worries @smic1909! 👍
