### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by pwats** [coralproject/talk#1689]
#### Do you want to request a **feature** or report a **bug**?

Bug

#### Intended outcome:

Read the initial message indication there are no comments yet ("There are no comments yet, why don’t you write one?")

#### Actual outcome:

It should be 2 sentences instead of one. The correct message should read: "There are no comments yet. Why don’t you write one?"

#### How to reproduce the issue:

Go to a comment stream that has yet to receive any comments and ready the message displayed there. 

#### Version and environment

4.4.1

**Comment by kgardnr** [comment]
Fixed in #1687 which will be released in 4.5.0
