### ISSUE TITLE
Can't find Sign in option  when install Talk from source

### ISSUE THREAD

**Issue by nevernervous** [coralproject/talk#1693]
I saw that talk-plugin-auth is default plugin.
When I install Talk from docker I can use the sign-in feature but when tried with source code, I can't find it.

**Comment by kgardnr** [comment]
Can you:

- check the logs?
- check the console and network when you load the page?
- make sure you have `talk-plugin-auth` enabled in your plugins.json or that it is in the plugins.default.json if you're using that?

Question - is there any reason you don't want to continue using the Docker route? It's the one we recommend for production installs anyway, and you say it's working. I'm not sure why you'd be reverting to Source.

**Comment by nevernervous** [comment]
There are any errors on the console.
And talk-plugin-auth is in plugins.default.json.
I want to add talk-plugin-akismet and talk-plugin-slack-notifications.

**Comment by kgardnr** [comment]
Anything from the logs? Can you send a screenshot of what you're seeing?

**Comment by nevernervous** [comment]
![image](https://user-images.githubusercontent.com/31775195/41465602-66530ff6-70d1-11e8-8cf8-524f4be88849.png)

**Comment by nevernervous** [comment]
I can see the `Sign In to comment ` button when using docker.
![image](https://user-images.githubusercontent.com/31775195/41465671-aa1a2936-70d1-11e8-9727-6cf8f74b2778.png)

**Comment by wyattjoh** [comment]
Try the following:

```bash
rm plugins.json
rm -rf node_modules dist
yarn
yarn build
```

And start your server again. It was likely a plugin configuration error.
