### ISSUE TITLE
Refresh JWT token to get an access to GQL APIs.

### ISSUE THREAD

**Issue by IvanDreamer** [coralproject/talk#1707]
Hello! 

Does anyone know how to refresh JWT token after it was issued from the "cli"? 

For example I generate a token with 
`./bin/cli token create ${USER_ID} example-token`
but after some time it will expire and I need to get a new one without generating it again by hand.

**Comment by wyattjoh** [comment]
Tokens issued by the CLI should not have an expiry associated with them. When you paste the token into https://jwt.io/ does it have an exp claim?

**Comment by IvanDreamer** [comment]
@wyattjoh thank you for your reply! 

> Tokens issued by the CLI should not have an expiry associated with them.

In theory it would be perfect, but in practice it expires in 12h (I think). I need to check tomorrow morning. 

> When you paste the token into https://jwt.io/ does it have an exp claim?

I did it, and it does not have that claim. 

Today my token works (I generated the forth one  a few hours ago), but I can send tomorrow what failed response says.

**Comment by IvanDreamer** [comment]
@wyattjoh Thank you for your patience. Even after 6 days my token is still alive. But it was not before. The only difference was I had a different version of Talk. When I opened the request I updated it to the latest. Maybe that was the issue. 

I think now we can close it. **And thank you for your help!** 👍

**Comment by wyattjoh** [comment]
Not a problem!
