### ISSUE TITLE
[Admin] Jumping queue when do actions

### ISSUE THREAD

**Issue by leeeandroo** [coralproject/talk#1711]
#### Do you want to request a **feature** or report a **bug**?
BUG

#### Intended outcome:
As a moderator, I'd like to moderate comments and maintain the vertical position on the queue, to not lost which comment I'm working on.

#### Actual outcome:
When moderators are approving and rejecting comments, sometimes they lost the position of the comment. At some circumstances, if you click on `approve` or `reject`, it tends to set the comment item as selected and the queue jumps.

I'm attaching a screen cast showing this problem:

[panel moderation - jumping in reported lane.zip](https://github.com/coralproject/talk/files/2144520/panel.moderation.-.jumping.in.reported.lane.zip)

Any idea about how to fix it? Is it a expected behavior?

#### How to reproduce the issue:
* Access the Admin
* Go to reported queue
* Try to approve/reject some comments
* See the window changing the position while you do these actions

#### Version and environment
4.1.1

**Comment by kgardnr** [comment]
Hey @leeeandroo, we have this in our backlog but it hasn't been prioritized: https://www.pivotaltracker.com/story/show/154368509

If you'd like to take this on, that would be great!

**Comment by kgardnr** [comment]
@leeeandroo this is fixed in our upcoming v5 release!
