### ISSUE TITLE
SSO implementation: tokenUserNotFound not working

### ISSUE THREAD

**Issue by activeoblique** [coralproject/talk#1723]
After reading the [documentation](https://docs.coralproject.net/talk/integrating/authentication/), I have been having trouble with the tokenUserNotFound plugin. Upon login, I generate a token for users and store it in my local database.
<img width="656" alt="screen shot 2018-07-03 at 10 59 07 am" src="https://user-images.githubusercontent.com/30766679/42229282-afb4d8be-7f18-11e8-8297-b1ba59fb6a32.png">

I then insert the token into the Coral embed. To rule out the possibility of an invalid token value, I injected a token value from the talk-token-example.
<img width="742" alt="screen shot 2018-07-03 at 11 33 17 pm" src="https://user-images.githubusercontent.com/30766679/42229649-827acb82-7f19-11e8-831a-d2c317f4f8b6.png">

For my plugin, index.js
```
const { tokenUserNotFound } = require('./server/notfound.js')

module.exports = { tokenUserNotFound };
```

And in my server folder, notfound.js
```
module.exports = { tokenUserNotFound: async ({jwt, token}) => {
    console.log("NOT FOUND")
  }
};
```
These are the logs I get from the Docker container where my Talk is set up.
<img width="880" alt="screen shot 2018-07-03 at 11 38 38 pm" src="https://user-images.githubusercontent.com/30766679/42230190-ec8788fc-7f1a-11e8-8c91-dbc92d0eca68.png">

I was unsure how storing the JWT in my local database vs. the GET/POST requests worked out, so I haven't implemented the GET/POST methods demonstrated in the talk-token-example.

**Comment by wyattjoh** [comment]
The only situation that `tokenUserNotFound` wouldn't trigger would be:

1. The token is not signed correctly (using the wrong secret)
2. The token is invalid (does not contain the correct or matching claims, check [here](https://docs.coralproject.net/talk/integrating/authentication/#create-jwt-token) for that)
3. The referenced User already exists

From what it looks like, you're setting `exp` to an expiry time from now, which actually, isn't correct. According to the spec, you need to set it to the unix timestamp of the expiry.

**Comment by activeoblique** [comment]
I changed my token setup to (imported all the settings from talk-token-example config.js file, so values should be same):
<img width="743" alt="screen shot 2018-07-04 at 4 55 10 pm" src="https://user-images.githubusercontent.com/30766679/42267252-15a4bab2-7fab-11e8-91d2-f2d51710a6e2.png">

However, logs are still hanging on "token sent via onConnect ..." and the hook never fires. I have changed my local settings and my Coral docker-compose file so that the secret values are identical. And I have tested my generated token values in the curl request of the talk-token-example and they receive a response.
<img width="1416" alt="screen shot 2018-07-04 at 4 59 38 pm" src="https://user-images.githubusercontent.com/30766679/42267502-c1d3c346-7fab-11e8-829a-12538a3d1e3b.png">

**Comment by wyattjoh** [comment]
Can you copy/paste the generated JWT's that you are generating here with your example values?

It's also important to note that the `subject` of the token is the users foreign ID.

**Comment by activeoblique** [comment]
generated 1: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIxIiwiaWF0IjoxNTMwNzI0NTAyLCJleHAiOjE1NTIzMjQ1MDIsImF1ZCI6InRhbGsiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.jKn98FEIzuafldEqz0i6rYin6Mf9p-y3idBuI1LMOHY`

generated 2:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIxIiwiaWF0IjoxNTMwNzI0NzA4LCJleHAiOjE1NTIzMjQ3MDgsImF1ZCI6InRhbGsiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.fZaS5t1Z5PiUrrqVrB4BajE7Mxd74T446VqPpdgX0sg`

generated 3:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIxIiwiaWF0IjoxNTMwNzI0OTQ5LCJleHAiOjE1NTIzMjQ5NDksImF1ZCI6InRhbGsiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAifQ.QpqPQo1TvOWxb6upvGuQQTiVbxj2YCHjWmJAhLKWwM4`

My local database has 3 different types of ID for each user, so I should just pick one and use it? I just tried to copy the values for each option from the talk-token-example config.js

**Comment by wyattjoh** [comment]
I'd recommend setting the `subject` option in the `jwt.sign` to the user ID rather than adding a new `userID` claim as the above generated tokens have.

Note that if the user lookup was successful, as in, the user indicated by the id already exists in the database, then Talk won't ever fire the `tokenUserNotFound` hook, as, the user was found.

## Configuration

Those tokens look correct to me. Ensure of course that your:

```
TALK_ROOT_URL=http://localhost:3000
```

And that the secret passed to these tokens is the same secret that is passed to Talk itself.

## Debugging

If you set `DEBUG=talk*` and don't see a line:

```
added plugin ${plugin.name} to tokenUserNotFound hooks
```

printed, after you attempt to login, then ensure that the plugin is loaded via the `plugins.json` under the `server` clause.

**Comment by activeoblique** [comment]
I changed the `subject` to have the value `user._id` from the local database. I checked that the root url and the secrets are correct.

I don't see that line, but I checked that my plugin is under the `server` clause in the `plugins.default.json` (there is no `plugins.json` in the Coral docker container). These are the logs from Docker after I log into the Coral embed:
<img width="708" alt="screen shot 2018-07-05 at 2 54 43 am" src="https://user-images.githubusercontent.com/30766679/42291562-0a6c79b0-7fff-11e8-9e95-bf1771b41423.png">

**Comment by wyattjoh** [comment]
You should set the `sub` claim (or `subject` if you're using the third parameter to `jwt.sign`) to `user.id`, which is different than `user._id` which is set from Mongo. We set our own UUID's as identifiers on the `id` field, which is used by Talk to get the user.

Also, from the looks of the logs you posted, it looks like the token was issued via the http response. Check the network tab in your web browser to see that the token was indeed set.

**Comment by kgardnr** [comment]
Hey @activeoblique were you able to get this working?
