### ISSUE TITLE
Unable to refresh JWT token using login() method

### ISSUE THREAD

**Issue by lytvynenko** [coralproject/talk#1728]
In our integration we have to use short live 10 min expiry JWT token.  Auth library provides a callback for token refresh event in which we are calling `embed.login(token)` method ( `embed = Coral.Talk.render...`) 
 
#### Do you want to request a **feature** or report a **bug**?
**Bug**

#### Intended outcome:
The `embed.login(token)` call supposed to update authorization header for consecutive API calls. 

#### Actual outcome:
Talk keep using the token provided during widget initialisation ( in `Coral.Talk.render`)  

#### How to reproduce the issue:
1. Initiate a widget on the webpage passing JWT token as option:
``` javascript
window.coralEmbed = Coral.Talk.render(document.getElementById('coral_talk_stream'), {
    talk: 'https://server-url.com',  
    asset_url:'http://asset-url.com',
    asset_id:'ASSET_ID',
    auth_token: 'JWT_TOKEN'
  });

```
2. Obtain a brand new token and call `login(new_token)`

``` javascript
window.coralEmbed.login('NEW_JWT_TOKEN');
```

3. Check API calls in the Chrome DevTools Network tab  - Talk keeps using the original token as Authorization header. 

#### Version and environment
Coral Talk v.3.4.2, AWS Linux, Google Chrome 67

**Comment by wyattjoh** [comment]
Thanks for the report @lytvynenko! A fix should be included in our next release (4.6.0). Stay tuned!
