### ISSUE TITLE
How to write a hook for "Respect" action.

### ISSUE THREAD

**Issue by IvanDreamer** [coralproject/talk#1738]
Hello! 

I was adapting  "slack" notification plugging for my notification service. I made it work, but now I cannot figure out how to catch respect action in the same manner. 

```
module.exports = {
  RootMutation: {
    createComment: {
      async post(root, args, context, info, result) {
.....

```
Could someone give an advise what would be an analog of "createComment" for respect Action?

**Comment by IvanDreamer** [comment]
Fuh, I've found it.

It's described here:

https://github.com/coralproject/talk/blob/66445aae59c980d38b9ac732f94f2cf43fb3b94e/plugin-api/beta/server/getReactionConfig.js#L125-L130

**Comment by kgardnr** [comment]
Awesome! If you want to contribute that plugin back to the community, let us know and we'll add it to our plugin directory: https://docs.coralproject.net/talk/plugins-directory/
