### ISSUE TITLE
The assetMetrics not working in GraphQL

### ISSUE THREAD

**Issue by tkleandro** [coralproject/talk#1763]
#### Do you want to request a **feature** or report a **bug**?
Bug

#### Intended outcome:

In version 4.5 the assetMetrics in GraphQL it's not working anymore, works fine in version 3.5.

#### Actual outcome:

The message was returned from GraphQL:
Cannot query field "assetMetrics" on type "RootQuery". Did you mean "assets"?

#### How to reproduce the issue:

Run the query:
{"query": "query CoralAdmin_Dashboard($from: Date!, $to: Date!) {\n assetsByActivity: assetMetrics(from: $from, to: $to, sortBy: ACTIVITY, limit: 5) {\n ...CoralAdmin_Metrics\n  }\n}\n\nfragment CoralAdmin_Metrics on Asset {\n  id\n  title\n  url\n  created_at\n  commentCount\n }\n","variables": { "from": "2018-06-27T15:19:17-03:00", "to": "2018-07-27T15:19:17-03:00" }, "operationName": "CoralAdmin_Dashboard" }

#### Version and environment

Version 4.5

**Comment by wyattjoh** [comment]
In 3.5.1, we included a dashboard that showed some details on assets/comments and their current counts/metrics. In 3.8.1, we removed the dashboard, and as such, deprecated those GraphQL edges.

If you would like to restore the functionality for those feature, you can do so by implementing a plugin that performs the necessary mongodb queries. You can look at the codebase at [3.7.1](https://github.com/coralproject/talk/tree/v3.7.1) for some helpful code bits to use!
