### ISSUE TITLE
Multiple streams or tabs in one view

### ISSUE THREAD

**Issue by cw00dw0rd** [coralproject/talk#1771]
#### Do you want to request a **feature** or report a **bug**?
I think this may be something that can be accomplished through a plug-in but may be a feature request if it can't.

#### Intended outcome:

I would like to have multiple streams available where the 'All Comments' tab is. Our site involves event planning and we would like to have two tabs, one tab would be for discussion of the event and then another tab would be for reviews of the event.

#### Actual outcome:

Currently, based on the info I am able to get from the documentation I don't see where I could implement another stream/tab. 
If this is indeed the case, possible fixes:

1. Looking a the [Docs](https://docs.coralproject.net/talk/api/client/#components-1) the Tab Bar seems to be able to be configured through creating a plug-in (I believe) and I am happy to explore that and do that on my own if that seems like functionality that could be achieved through a plug-in.
2. Allow for custom sorting and labeling. Such as, if I could add a sort option for 'discuss' or 'review' and add an appropriate label so that when the associated sorting option is selected only the comments with that label display and when new comments are added they receive the currently selected label. 
3. Any other option that you think could achieve what I am looking to do. :smile: 

Any feedback you have on this sort of functionality would be greatly appreciated.

**Comment by AndyatFocallocal** [comment]
Also interested

**Comment by kgardnr** [comment]
We will be building some similar features to this in the coming months for v5, so closing the issue, and stay tuned! 🎉
