### ISSUE TITLE
Performance drop when updating application

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#1773]
Hello,

I recently upgraded Coral Talk from version 4.4.0 to version 4.5.1 and got a considerable performance drop. I wonder if anyone else in the community witnessed this same behavior and are aware of the possible cause.

The average cpu consumption doubled as can be seen in the image below.

![screen shot 2018-07-31 at 17 16 25](https://user-images.githubusercontent.com/25023177/43484964-44742f26-94e6-11e8-9f8d-1ba5218292f9.png)

**Comment by wyattjoh** [comment]
Hey @cristiandean! Are you able to run the server with a debugger attached to grab a CPU profile before and after the upgrade so we can dive down?

**Comment by kgardnr** [comment]
Hey @cristiandean can you check out the latest release and see if that helped resolve these issues you were seeing too?
