### ISSUE TITLE
Feature Idea: Allow comment editing permanently

### ISSUE THREAD

**Issue by aguilarm** [coralproject/talk#1774]
Looks like currently there is no way to allow users to edit their own comments indefinitely besides perhaps a very large number in for `Edit Comment Timeframe` in admin.

While entering a large number there sort of works, editing a comment still shows the Edit window in minutes/seconds and it's a huge number that no longer really makes sense.  Further, the elements for this do not have generic/plain class names and only have the generated ones, so hiding it is a bit obtuse.

At the very least I'd like to add generic class names to the Edit Window elements so I can hide it easily and live with the large number.

Ideally the whole behavior would be toggle-able (I could turn off the Edit Window and users would then be able to edit indefinitely, similar to the way closing comments after x weeks works in admin).

**Comment by kgardnr** [comment]
Hey @aguilarm, we won't be moving in this direction, but we do have some improvements for Edit Comment coming in our upcoming v5 release!
