### ISSUE TITLE
Feature Idea: Restrict some moderators access to stories

### ISSUE THREAD

**Issue by franciclo** [coralproject/talk#1779]
Hi, in our case, some authors should moderate only the stories they are assigned to.
I think this would also be useful for organizations consisting of different teams, where each team produce their own content, in a multi-tenant scenario or when you invite a specialized person to moderate about specific topics.
Is this something that could be resolved with a plugin?
Is this feature interesting for you? If it is we could try to implement it.

**Comment by wyattjoh** [comment]
I feel that that particular feature would require too deep of a change in the way we handle moderation systems at present. We're making some big changes for v5, so we'll keep this feature in mind as we're developing it.

**Comment by franciclo** [comment]
Thanks, looking forward to v5!

**Comment by kgardnr** [comment]
@franciclo this will be addressed in v5! It's on our roadmap!
