### ISSUE TITLE
Feature Idea: Customize styles in Admin panel

### ISSUE THREAD

**Issue by franciclo** [coralproject/talk#1780]
We would like to customize styles in the Admin panel, only css (logo, colors, spaces, typography).
The custom css only affects the iframe, something like that to the admin would be perfect.
We are thinking of overriding styles inside the Docker container, as a workaround, is there a simpler way?

**Comment by wyattjoh** [comment]
Currently, there isn't a way to do so, but the current custom CSS feature could be pretty easily extended to add a new field for admin css stylesheets.

**Comment by franciclo** [comment]
It was implemented in #1237 but then it was removed (don't know when precisely), but that was for using the same css file, having a separate css file as you mention could be better.

**Comment by kgardnr** [comment]
@franciclo if you'd like to pick this one up, feel free, we'd love to add it.

**Comment by kgardnr** [comment]
Featured added in #2279
