### ISSUE TITLE
Fetch assets like Font Awesome from first-party

### ISSUE THREAD

**Issue by theel0ja** [coralproject/talk#1781]
Why is assets, like Font Awesome & Source Sans Pro font downloaded from third-parties, while it's completely unnecessary.

They're open source and should be downloaded from first-party. You already download lots of CSS & JS first-party.

Source Sans Pro can be downloaded from here: https://google-webfonts-helper.herokuapp.com/fonts/source-sans-pro?subsets=latin

Material Icons can be downloaded from here: https://github.com/google/material-design-icons

Code:
https://github.com/coralproject/talk/blob/9539073eb8c0cc38de1b6029a96ab17a671bdb18/views/templates/base.njk#L18-L21

**Comment by wyattjoh** [comment]
The benefit of having these assets served from third parties here is to lift the burden of serving these files off of Talk. Most browsers will additionally have the assets cached already, often resulting in no network requests.
