### ISSUE TITLE
ie11/edge ignores default_lang

### ISSUE THREAD

**Issue by lelorelo** [coralproject/talk#1801]
#### Do you want to request a **feature** or report a **bug**?
bug

#### Intended outcome:

coral should appear in german, which has been defined with `TALK_DEFAULT_LANG=de`

![bildschirmfoto 2018-08-14 um 10 54 11](https://user-images.githubusercontent.com/7877754/44082025-787d444a-9fb0-11e8-9970-f497414ac313.png)

#### Actual outcome:

coral appears in english, but only in **IE11 and Edge**

![bildschirmfoto 2018-08-14 um 10 53 52](https://user-images.githubusercontent.com/7877754/44082036-7c63a48c-9fb0-11e8-9689-eaf06604a1b3.png)

#### How to reproduce the issue:

it happens only with **IE11 and Edge**, in other browsers coral appears in german.

#### Version and environment

talk v4.5.1
**IE11 and Edge**

**Comment by wyattjoh** [comment]
What's likely happening is that you have english set or enabled on those browsers. If you want Talk to only ever be rendered in German, you can set the [TALK_WHITELISTED_LANGUAGES](https://docs.coralproject.net/talk/advanced-configuration/#talk-whitelisted-languages) environment variable to `de`, which would ensure that only that language is available.

**Comment by lelorelo** [comment]
it didnt work out for me

i added `TALK_WHITELISTED_LANGUAGES` and nothing changed

### i solved it this way:
**Dockerfile**
```Dockerfile
FROM  coralproject/talk:latest
RUN yarn global add nodemon

ENV NODE_ENV=development
# does NOT work
ENV TALK_DEFAULT_LANG=de
ENV TALK_WHITELISTED_LANGUAGES=de

# works
RUN apk update && apk add bash
ADD krn_talk_setup.sh /krn_talk_setup.sh
RUN chmod a+rwx /krn_talk_setup.sh
RUN /krn_talk_setup.sh

RUN yarn add -W nunjucks
RUN cli plugins reconcile && \
            yarn && \
            yarn install && \
            yarn build && \
            yarn cache clean

CMD ["yarn", "start"]
```

**krn_talk_setup.sh**
```bash
#!/bin/bash
set -x

#remove languages -> everything is german now
cd /usr/src/app/locales
for x in *.yml
do
	if [ "$x" != "de.yml" ];
	then
		rm $x;
		ln -s de.yml $x;
	fi
done
```
