### ISSUE TITLE
share-comment button-text is not in language-file

### ISSUE THREAD

**Issue by lelorelo** [coralproject/talk#1802]
#### Do you want to request a **feature** or report a **bug**?
bug

#### Intended outcome:

the copy-button should also be available with i18n for various languages

#### Actual outcome:

the copy button shows `Copy` no matter what language is set

![image 5](https://user-images.githubusercontent.com/7877754/44083396-26be4290-9fb4-11e8-958f-05337a666ba4.png)

#### How to reproduce the issue:

change languages, there is no change

#### Version and environment

talk v4.5.1
all browsers

**Comment by kgardnr** [comment]
Solved in https://github.com/coralproject/talk/pull/1804
