### ISSUE TITLE
Updating a user with auth_token

### ISSUE THREAD

**Issue by alexandrebodin** [coralproject/talk#1806]
#### Do you want to request a **feature** or report a **bug**? 

**feature**

#### Intended outcome:
I'm using the `tokenUserNotFound` hook to create a user from a token in the talk database.

I have my own database of users and I'd like to be able to change a coral username when it's username
changes in the original database.

Is there currently a way to do that ?

Thanks a lot for your help and this project !

**Comment by lytvynenko** [comment]
Hi Alexandre, 
 From my knowledge there is no out-of-box functionality to achieve your goal. Although you can get some directions from this plugin recipe: https://github.com/coralproject/talk-recipes/blob/master/plugins/avatar/index.js. (particularly commented `router` part).

**Comment by alexandrebodin** [comment]
Thanks, for the answer ! 

I ended up overriding the passport jwt auth and implement my own logic. way simpler than using `tokenUserNotFound` and a lot more flexible :) I would recommend putting sth about that in the docs maybe.

**Comment by kgardnr** [comment]
Hey @alexandrebodin if you'd like to share that with us, we can include it in the docs - or you're welcome to add it yourself. Thanks!

**Comment by alexandrebodin** [comment]
I'll write sth up sure :D
