### ISSUE TITLE
where to start with SSO implementation?

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/talk#1807]
Hi there,

I am trying to implement SSO with our external api/DB. 
We have our own authentication system and our own database of users.
I understand that we need to use SSO to sync the user of our website with the Talk authentication this way user does not need to sign in again in talk separately. 
I found only these two pages in documentation:

[https://docs.coralproject.net/talk/api/server/#tokenusernotfound](url)

and this page:

[https://docs.coralproject.net/talk/integrating/authentication/](url)

But it is a bit confusing and I found the documentation a bit abstract. I am confused in which folder should I add the following snippet of code:

`tokenUserNotFound: async ({jwt, token}) => {
  let profile = await someExternalService(token);
  if (!profile) {
    return null;
  }

  let user = await UserModel.findOneAndUpdate({
    id: profile.id
  }, {
    id: profile.id,
    username: profile.username,
    lowercaseUsername: profile.username.toLowerCase(),
    roles: [],
    profiles: []
  }, {
    setDefaultsOnInsert: true,
    new: true,
    upsert: true
  });

  return user;
}`

Should I add it as a new plugin? if yes how to create a new pluign?
If not which folder should I start with? This one: plugins/talk-plugin-auth?

If you can provide a little bit more guidance where to start, that would be awesome.

**Comment by kgardnr** [comment]
Hey @hminaeeBrunswicknews! Yes, it would be a new plugin you'd build with that code included in the `index.js` file.

You would need to replace `someExternalService` with your Auth or Identity API/Service.

You can generate a plugin template via the CLI, by running: `bin cli plugins create`

You would name your plugin something like `talk-plugin-auth-brunswick-news` and include it in your `plugins` folder and in your `plugins.json` file.

More info:

https://docs.coralproject.net/talk/integrating/authentication/
https://docs.coralproject.net/talk/api/server/
https://docs.coralproject.net/talk/api/server/#tokenUserNotFound
https://docs.coralproject.net/talk/building-basic-plugin/

**Comment by hminaeeBrunswicknews** [comment]
Thanks @kgardnr ,

I cannot see plugin Json file (I mean this part that you mentioned"and in your plugins.json file.")in the talk repo. 
Where can I find it?

**Comment by kgardnr** [comment]
We have a default one here: https://github.com/coralproject/talk/blob/master/plugins.default.json 

If you don't create a `plugins.json`, it will default to that one. If you want to use custom plugins, you can create a `plugins.json` in your root directory. 

More info here: https://docs.coralproject.net/talk/plugins/

**Comment by hminaeeBrunswicknews** [comment]
Thanks a lot for answering,

I used the docker and everything is ,managed through that.
So I only have the following :
![image](https://user-images.githubusercontent.com/24658315/44363219-f1e3f480-a499-11e8-9cd9-c7a80fdb3ba3.png)


in a file called 
docker-compose.yaml

Now if I need to make the change I think I need to use git to get the code and then change it and point the docker to the customized code. For that do I need to update the docker-compose.yaml?

**Comment by kgardnr** [comment]
If you're using Docker, it will pull the code from Docker Hub.

Since you're using custom plugins, actually, you'll need to follow the instructions using the Onbuild image: https://docs.coralproject.net/talk/installation-from-docker#onbuild

**Comment by kgardnr** [comment]
From those docs:

> This means that you can create a repository for your organization that simply includes the above Dockerfile, a directory of plugins, and a plugins.json file which specifies the activated plugins, and you can deploy Talk easily to your containerized infrastructure.

**Comment by hminaeeBrunswicknews** [comment]
Thanks,

so before, I had the docker-compose.yaml and I was running docker-compose up -d.
Now for the new build approach  I need to run this:

docker build -t my-awesome-talk-image --build-arg TALK_DEFAULT_LANG=es

 but do I need to run it on any yaml config file? 
When I run it I get the following:

![image](https://user-images.githubusercontent.com/24658315/44372282-8873de00-a4b9-11e8-8f18-68b28d33e14d.png)

I am confused on what repo or yaml file should I run the above command?
Or should I download the repo and make changes and some how run the above command pointing to the updated repo?

**Comment by hminaeeBrunswicknews** [comment]
Thanks,

so here is what I did:

I downloaded the repo and made necessary changes to the code and then I ran the following:

docker build -t my-awesome-talk-image --build-arg TALK_DEFAULT_LANG=es ./talk

I saw that docker started creating an image. 
Now the problem is how to point the docker compose to point to this image.
Here is what I had before using only the default image 

![image](https://user-images.githubusercontent.com/24658315/44402349-db847a00-a527-11e8-9a72-00d35271854f.png)


I think the part that is specified by red line is pointing to the default docker image.
But now I need to pint it to the new customized image I created by this command:
docker build -t my-awesome-talk-image --build-arg TALK_DEFAULT_LANG=es ./talk
 
Can you please shed light on this?

**Comment by hminaeeBrunswicknews** [comment]
Thanks @kgardnr 

I think I got the docker piece working with my code.
I am trying to generate the plugins with what you mentioned:

> You can generate a plugin template via the CLI, by running: bin cli plugins create 


but when I run it I get : Command not found

Should I install anything or should I be in a specific folder?
