### ISSUE TITLE
bin cli plugins create for creating tokenUserNotFound is not working 

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/talk#1811]
Hi there ,

I am using the docker on build to build the customized version of talk adding USERNOTFOUND plugins.
Here is another thread in this forum showing how I got here:

[https://github.com/coralproject/talk/issues/1807](url)

After running the docker pointing to my project now I am at the point to generate the template for tokenUserNotFound. 

As suggested here 

https://docs.coralproject.net/talk/building-basic-plugin/

I am trying to run: 

./bin/cli-plugins create

but I get no such a file or directory.

Here is the different combination I have tried:
![image](https://user-images.githubusercontent.com/24658315/44407816-6750d300-a535-11e8-81e0-e1b4816d0904.png)

Is there any specific folder I should run it to be able to create template?

**Comment by kgardnr** [comment]
Run this in the ROOT folder:

`./bin/cli-plugins`

You'll see a menu of info.

Run this to create a plugin:

`./bin/cli-plugins create`

<img width="571" alt="plugin_cli" src="https://user-images.githubusercontent.com/1077300/44418148-996a3100-a545-11e8-8a4a-85dccc11d719.png">

**Comment by kgardnr** [comment]
Note you also have to have Talk up and running here for this to work. You'll also need to install the dependencies that this and everything else relies on.

**Comment by hminaeeBrunswicknews** [comment]
I checked I have the talk server running and also I updated the node and yarn I installed.
After that when I run this: ./bin/cli-plugins in the root folder I get this:

 
![image](https://user-images.githubusercontent.com/24658315/44418846-dc310680-a54f-11e8-8cc7-4f307ace7bef.png)

**Comment by wyattjoh** [comment]
It looks like the dependencies aren't installed, run `yarn` in the `talk` directory to install dependencies.

**Comment by hminaeeBrunswicknews** [comment]
Yes that worked.
Thanks @wyattjoh  and @kgardnr
