### ISSUE TITLE
Feature Idea: Support for PM2 within the docker container

### ISSUE THREAD

**Issue by angelo-hub** [coralproject/talk#1816]
It would be useful if we could support PM2 within the docker container, and accept PM2 configuration files for better uptime and full utilization of the deployed instances.

Implementing PM2 is documented [here](http://pm2.keymetrics.io/docs/usage/docker-pm2-nodejs/) could help avoid outages, unhandled exceptions, and increase performance through allowing users to configure a cluster configuration if they so choose.

**Comment by angelo-hub** [comment]
@kgardnr If this needs extra hands, I'd be glad to work on it!

**Comment by wyattjoh** [comment]
I love the idea. Taking a look at this, will keep you posted!

**Comment by angelo-hub** [comment]
Hey @wyattjoh  following up, any updates on if it's possible/worth doing?

**Comment by wyattjoh** [comment]
Hey @AngefloMusic! I think it’s a neat idea! I want to take an initial stab, as I wanted to ensure existing implementations won’t be that affected by creating a third docker image just with pm2.

It may also be a possibility to create a third party package that sources from the `coralproject/talk:*-onbuild` image and publishing it on docker hub.

**Comment by wyattjoh** [comment]
We've determined that we'd rather rely on existing tools like k8s to power this behaviour rather than including another library for it. If there's more interest we'll revisit!
