### ISSUE TITLE
How can I add a plugin in heroku?

### ISSUE THREAD

**Issue by KaitoHH** [coralproject/talk#1821]
I used one-click button to deploy talk in heroku. Now I want to add some internal plugin, how can I do this?
I tried editing `TALK_PLUGINS_JSON` env variable but it seemed no effect. I tried either containing only my needed plugin in `TALK_PLUGINS_JSON` or containing needed and default plugin but they were no use.

Another question is, if I want to add a plugin, for example, `talk-plugin-notifications`, should I include it in `server` or `client`? or both?

**Comment by kgardnr** [comment]
Hey @KaitoHH! To determine if a plugin requires `server`, `client`, or both, you can find out in our plugins directory - https://docs.coralproject.net/talk/plugin/talk-plugin-notifications

Note, for notifications, you'll need to add more plugins for the categories you want to enable - you can find this by searching the directory for `notifications-category`. You can also enable digests - search `notifications-digest`.

The best way to manage plugins is to follow these instructions (from our Onbuild docs: https://docs.coralproject.net/talk/installation-from-docker#onbuild)

```This means that you can create a repository for your organization that simply includes the above Dockerfile, a directory of plugins, and a plugins.json file which specifies the activated plugins, and you can deploy Talk easily to your containerized infrastructure. The versioning of our Docker tags as well lets you do something like:```

`FROM coralproject/talk:4.5-onbuild`

**Comment by KaitoHH** [comment]
@kgardnr Thanks for the reply! I have successfully created my own Dockerfile and deployed to heroku! Here is a suggestion. Since user can not choose whether a plugin should be placed in `server`, `client`, or both, just remove `server` and `client` in `plugins.json` and let `talk` automatically determine is maybe a good choice.

**Comment by kgardnr** [comment]
Hey @KaitoHH, yes we have some plans around that - thanks for the suggestion!
