### ISSUE TITLE
See Total number of unmoderated posts

### ISSUE THREAD

**Issue by hjanuschka** [coralproject/talk#1824]
from our moderator:
> We need to see how many comments are left in „unmoderated“ or „reported“ – Is it possible to see the blue banner „xy comments more“ permanently? Is it then viewable how many comments are left?

is there a plugin slot we can use to provide the totalnumber of non-moderated

**Comment by kgardnr** [comment]
@clintabrown this is similar to what we were discussing yesterday.

@hjanuschka Clint proposed a way to see how many unmoderated comments were on each story, showing this maybe in the Stories tab.

@erikreyna might also be interested in something like this.

Thoughts?

**Comment by hjanuschka** [comment]
having it on the story list too would be also great like `total` / `totalUnreviewed` / `totalReject`


and of course in the tabs too, i think our mods basically need it to see how many are in review, and want to see a light at the end of the tunnel.

**Comment by kgardnr** [comment]
@hjanuschka this feature is brought back in our upcoming v5 release, closing this for now!
