### ISSUE TITLE
Comment Search

### ISSUE THREAD

**Issue by hjanuschka** [coralproject/talk#1825]
from our moderator:
> When a comment is moderated, it’s gone forever because it is really difficult to search for it in the backend. Is a feature planned where we can filter timespans (day/hour/minute)?
 

is there a roadmap / milestone, or should we go the "build your own plugin" way - for adding search/filter functionality

**Comment by kgardnr** [comment]
@hjanuschka we don't have this on our roadmap, but we'd love to hear more what you're thinking - we can provide feedback on your design for how you might implement filtering by timespan. Our concern with something like this is the impact it could have on performance potentially.

Let us know what you're thinking.

**Comment by hjanuschka** [comment]
havent yet finished thinking about it :/ - let you know once we start doing it (might take a few weeks).
about the performance, not sure about graphQL in general, but doing it mongo side, the filtering, and even fulltext search, should not be the big problem.


i ll try to find the resources to work on it, and would start trying todo it in graphQL - not sure if i succeed. 


some ideas:
(mainly based on our old comment-system-backend)

  -  filter all comments - in all states/tabs, in a time frame from lets say.: `01.12.2018 00:00 - 03.12.2018 05:00` by providing 2 datepicker components.
    - the `created_at` should be enough to do a filter like this.
  - add fulltext index mongo side, and provide a way to search for a comment.
  - search by asset-url - as we have a lot of articles, and searching by title is not always enough.

**Comment by kgardnr** [comment]
@hjanuschka, we will be adding this in our upcoming v5 release, closing this for now!
