### ISSUE TITLE
Reported Comments, in pre-moderated setup

### ISSUE THREAD

**Issue by hjanuschka** [coralproject/talk#1826]
we are running in 100% pre-moderated setup. so every single comment is reviewed by a human.
however sometimes, due to many different reasons, like "short comment, no direct context, in reply's" - it sometimes happens that a comment is approved that should not be public.

there are many users out there, who actually would  report it, but it seems the reporting functionality is like disabled, as the moderators "accepted" - is like the god-mode.

in a way it is a feature, in another it is a bug, any advice on how to get reported comments working in that setup - without reinventing the wheel and doing a custom plugin?

**Comment by hjanuschka** [comment]
same goes for reported-users, but we are fine with the fact that reporting users is useless. atleast for now. as they have the "SET" state via tokenNotFound - and there isnt even a functionality to change nicknames.

**Comment by kgardnr** [comment]
@hjanuschka this will be addressed in v5
