### ISSUE TITLE
503 on logout

### ISSUE THREAD

**Issue by hjanuschka** [coralproject/talk#1828]
we are expierencing 503/502 on loggout.
running in auth_token only mode.

```
Aug 29 06:49:13 192.168.239.36 haproxy[8]: 172.18.0.2:35386 [29/Aug/2018:06:49:13.568] coral coral_nodes/coral5-1 0/0/0/10/10 500 502 - - ---- 471/470/469/17/0 0/0 "DELETE /api/v1/auth HTTP/1.0"
```

seems to be down here: https://github.com/coralproject/talk/blob/f2857a8085b8f3b4757ad7a93698d0b90ce28824/services/passport.js

we are using "Coral.render" - and "Coral.login(TOKEN)"  + "coral.loggout()"

i installed http://sentry.io - but for whatever reason, it doesnt bubble up the exceptions and that way i don't see them.

having the following `app`  hook, inside my plugin:

```javascript
module.exports = async function(app) {
  if(process.env.USE_SENTRY) {
    Raven.config('https://XXXXXXXXX@sentry.krone.at/16', {
      release: process.env.KRN_SENTRY_RELEASE,
      environment: process.env.KRN_SENTRY_ENV,
      serverName: process.env.KRN_MY_HOSTNAME
    }).install();
	  app.use(Raven.requestHandler());

    app.get('/sentry', function mainHandler(req, res) {
       throw new Error('Broke!');
    });

    app.use(Raven.errorHandler());
  }
}
```

when curl'ing the `/sentry` route, it successfully throws an exception and reports it to sentry.

any advice why built-in errors do not reach the `Raven.errorHandler()` ?

**Comment by hjanuschka** [comment]
ok one problem `app.use(Raven.errorHandler());`  needs to be at the very bottom of all routes.

could'nt find a hook :(

**Comment by wyattjoh** [comment]
I'm curious if the token that you're passing to it contains a `jti` claim?

**Comment by hjanuschka** [comment]
you are right, havent set jti, found it out the hard-way, we recently added `exp` - to the token.

once exp, is set, and no jti is set, you immediatly get "token revoked".
adding jti fixed this, so going to have a look at the 503's if they are fixed too.
