### ISSUE TITLE
script12030 IE11/Edge Websocket timeout

### ISSUE THREAD

**Issue by hjanuschka** [coralproject/talk#1834]
we are having troubles with those IE users, dont ask, we still have alot of them.

`SCRIPT12030: WebSocket Error: Network Error 12030`

this might be a hint: https://stackoverflow.com/questions/48789032/microsoft-edge-websockets-script12030-error-after-30secs

we already set `TALK_KEEP_ALIVE=15s`
but still having issues on IE.

reproduce:
  - go find a windows VM 👎 
  - open IE11 
  - go to https://www.krone.at/1763743
  - open debugger F12 (i think)
  - wait ~30seconds
  - see error message

any idea?

**Comment by wyattjoh** [comment]
If you're seeing those types of disconnections @hjanuschka, it may be the case that the loadbalancers/routes inbetween you and the Talk instance is terminating the connections. As long as the client reconnects, it should still work fine right?

Does the connections reconnect after you see that error?

**Comment by hjanuschka** [comment]
it does not seem to reconnect, just shows "network error" and/or "query returned undefined.

as said its weird it is only happening in IE/Edge - and a couple of FF (having a teamviewer session with a user, tomorrow)

**Comment by hjanuschka** [comment]
ok i found the error.


we are using nginx->haproxy->coral


the IE issue did not happen, in a lab-scenario when we directly went to coral.
increasing `proxy_*_timeout` in nginx and `timeout server|client|keepalive`  in haproxy fixed it.

having no set a value of 86400s 👍
