### ISSUE TITLE
Feature Idea: Allow timestamp on moderation side to be configurable so it can support absolute time instead of relative time

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1836]
#### Do you want to request a **feature** or report a **bug**?

Feature

#### Intended outcome:
Talk supports a slot for the timestamp on the stream-side: https://github.com/coralproject/talk/search?q=commentTimestamp&unscoped_q=commentTimestamp

We would like to have this slot on the mod side. 

So "4 weeks ago" would show as "Date Time"

<img width="687" alt="rel_time" src="https://user-images.githubusercontent.com/1077300/44921266-12207880-ad10-11e8-8fbb-6698310223a3.png">

#### Actual outcome:
Currently, you can only display relative time for comments in moderation, aka "1 hour ago".

**Comment by hjanuschka** [comment]
how about: https://github.com/coralproject/talk/pull/1841

**Comment by kgardnr** [comment]
Fixed in #1841
