### ISSUE TITLE
Feature Idea: Show ALL unmoderated pre-mod comments in that thread in View Context

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1838]
#### Do you want to request a **feature** or report a **bug**?

Feature

#### Intended outcome:
Moderation of comment streams in pre-moderation is difficult and needs more context for the moderators to make decisions.

Currently, we do show comments that are in pre-mod to admins, via the View Context View, but only show the singular comment and their parent. We should show all comments in that thread that are either approved or in pre-mod.

#### Actual outcome:

Currently, we only show the individual pre-modcomment and its parent.

<img width="607" alt="premod_admin_view" src="https://user-images.githubusercontent.com/1077300/44925605-dc35c100-ad1c-11e8-92a6-f5066991d32d.png">

**Comment by kgardnr** [comment]
@clintabrown @hjanuschka @leeeandroo - here's a suggested feature to solve some issues around moderators lacking comment context when they're moderating a pre-mod thread. Thoughts welcome!

**Comment by hjanuschka** [comment]
idea sounds great, it is meant to review in frontend, right? my mods actually fully work in the backend, in zen mode using almost shortcuts only, would be nice - if there is a shortcut to unfold context for example.

review in frontend is too hard on our side, too many stories in too many different locations and some of them even on different platforms.

i think our ideal solution would be to:
hitting "Leader+c" for example,

  - replies
    - shows top comment
    - shows article context
    - shows previous 2 comments
 - comment
   - show's article context


where article context could be the title, the url and maybe the extraction of a custom `og:` tag, like `og:coral`. we than could set the first paragraph to it.

**Comment by wyattjoh** [comment]
I think we would ideally love to have the context viewable in the admin panel, we just never got around to developing that part 😅! We already scrape assets to extract metadata, see the assets collection for what we collect, so that can already be displayed inline if we wanted to.

**Comment by hjanuschka** [comment]
great, i think i am going for it. just have too get used to the graphql.

**Comment by kgardnr** [comment]
This will be addressed in v5
