### ISSUE TITLE
How to control publication date in the talk admin? (defaults to 1/1/1970)

### ISSUE THREAD

**Issue by soosap** [coralproject/talk#1849]
I have deployed the talk service and in the dashboard under `/admin/stories` I see the stories. All good.

Just for `Publication Date` I am not sure how to control that. It get set to `NaN/NaN/NaN` in development and to `1/1/1970` after it is deployed. Is there a parameter or something that I need to use to control the publication date?

**Comment by himynameissebbo** [comment]
Hey! 
The date must be a valid ISO date, e. g. `2018-09-10T16:19:30.232726+00:00`. Further you need to pass the `publication_date` attribute when adding a asset to talk.

You'll find some details over there: https://docs.coralproject.net/talk/integrating/asset-management/

**Comment by soosap** [comment]
Ok thanks that's exactly what I was looking for :)
