### ISSUE TITLE
Asset URLs with request parameters do cause incorrect context links

### ISSUE THREAD

**Issue by paulwellnerbou** [coralproject/talk#1851]
#### Do you want to request a **feature** or report a **bug**?

**bug**

#### Intended outcome:

If the asset URL contains request parameters already, the generated context URL is wrong as it appends another `?`, see https://github.com/coralproject/talk/blob/b9d88251e6cd45da61f1e46ef43ed12a6d47000a/client/coral-admin/src/routes/Moderation/components/Comment.js#L171 or https://github.com/coralproject/talk/blob/f2857a8085b8f3b4757ad7a93698d0b90ce28824/client/coral-admin/src/components/UserDetailComment.js#L115

#### Actual outcome:

An url with two `?` is generated, e.g. http://example.com/article?id=1234?commentId=...

#### How to reproduce the issue:

Using canonical URLs or asset URLs with request parameters.

#### Version and environment

Latest version and master.

**Comment by hjanuschka** [comment]
i think it is going to be fixed with this https://github.com/coralproject/talk/pull/1819
can you confirm/verify this?

**Comment by paulwellnerbou** [comment]
@hjanuschka, thank you! Did not discover this PR.
Yes, it fixes this issue.
