### ISSUE TITLE
SSO implementation: redundant additional information pop up when trying to sign external user

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/talk#1856]
#### Do you want to request a **feature** or report a **bug**?
Bug

#### Intended outcome:

Trying to sign in external user using talk SSO
![image](https://user-images.githubusercontent.com/24658315/45165486-4f32b200-b1cb-11e8-95ec-358480c016af.png)
#### Actual outcome:

![image](https://user-images.githubusercontent.com/24658315/45119515-0975db00-b132-11e8-8120-87c13384961c.png)

**More explanation:**
I use the following code as suggested in the following thread:
[https://github.com/coralproject/talk/issues/1845](https://github.com/coralproject/talk/issues/1845)
to use TokenNot found plugin for loging external  users.
Here is my code:

```
const fetch = require('node-fetch');
//const { SLACK_WEBHOOK_URL, SLACK_WEBHOOK_TIMEOUT } = require('./config');
const UserModel = require('../../../models/user');
module.exports = {
	tokenUserNotFound: async ({jwt, token}) => {
	  let data={"displayName":"hmmminaee992","email":"minaee992.hamed@yahoo.com"};

      const user = await UserModel.findOneAndUpdate(
        {
          id: jwt.sub,
        },
        {
          id: jwt.sub,
          username: data.email,
          lowercaseUsername: data.email.toLowerCase(),
          profiles: [
            {
              provider: 'brunswicknews',
              id: jwt.sub,
            },
          ],
          status: {
            username: {
              status: 'SET',
              history: [
                {
                  status: 'SET',
                },
              ],
            },
          },
          metadata: {
            displayName: data.displayName,
	    email: data.email
          },
        },
        {
          setDefaultsOnInsert: true,
          new: true,
          upsert: true,
        }
      );
	  return user;
	}
};
```
and everything goes through. I am able to see that plugin is triggered and user is returned.
However on the client the first time calling the talk server with a token I get this window pop up in my talk attached to the website:

![image](https://user-images.githubusercontent.com/24658315/45119515-0975db00-b132-11e8-8120-87c13384961c.png)

Then when I add the email and password in the pop up and submit after that the token is always recognized and works well and pop up is never shown anymore . Here is what I see after I enter my email and password in that pop and as you can see my username is shown as an display name(I added display name specifically to the user object I pass but for some reason the username is still shown and not the display name):

![image](https://user-images.githubusercontent.com/24658315/45165486-4f32b200-b1cb-11e8-95ec-358480c016af.png)

The whole point of using SSO is to avoid that pop up screen asking for additional email and password info.

Is there any way I can avoid that popup windows ? or this is something we cannot avoid it all?
 
#### How to reproduce the issue:

Insert the above code in the tokenUserNotFound and call the talk server with the following script on your client page:

```
   Coral.Talk.render(document.getElementById("comment-talk-"+this.props.storyId), {
            talk: path.COMMENT_DOMAIN,
            auth_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MzYzMzkxNDUsImV4cCI6MTU1NzkzOTE0NSwiYXVkIjoidGFsayIsImlzcyI6Imh0dHBzOi8vY29tbWVudDMuc3RnMi5kZXYtdGVsZWdyYXBoam91cm5hbC5jb20vIiwic3ViIjoiNiIsImp0aSI6IjkzOTQ0NTU5LTQ3MmYtNGU1NS05MDJiLWZkNDYzZDBlMGViYSJ9.WyN7btMJmWBs7KVo14Hpldje-TzOLCmxf4x6graERP4"
        });
```
#### Version and environment
4.6.1

**Comment by wyattjoh** [comment]
@hminaeeBrunswicknews: you should disable the [talk-plugin-local-auth](https://docs.coralproject.net/talk/plugin/talk-plugin-local-auth) plugin, that's what's prompting the user for the email.
