### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by deepaksisodiya** [coralproject/talk#1857]
#### Do you want to request a **feature** or report a **bug**?

question

#### Intended outcome:

In my website, There is session based authentication.
But I am unable to find docs related to that.
The one here https://docs.coralproject.net/talk/integrating/authentication/ has only token related docs

**Comment by wyattjoh** [comment]
You can use your session based auth to create a token, and pass that to Talk to exchange for user details when logging in the user following the authentication documentation you linked.

**Comment by deepaksisodiya** [comment]
@wyattjoh Can you explain a bit more please

**Comment by wyattjoh** [comment]
You'd likely have to create a service on your application, that given a persons login status, issue a JWT token for that user. Pass that token into the embed then to sign in the user via the SSO docs.

**Comment by deepaksisodiya** [comment]
Closing this issue, implemented the SSO
Thanks @wyattjoh
