### ISSUE TITLE
Customize permissions for adding tags to comments

### ISSUE THREAD

**Issue by himynameissebbo** [coralproject/talk#1861]
#### Do you want to request a **feature** or report a **bug**?
question

**Question:**
As stated in #1859 I try to add some default tags to comments. I installed the pre-hook (see ticket) sucessfully but face another problem now. I'd like to add the tags to every incoming comment with the pre hook. This works fine when the user has an admin role (ADMIN, MODERATOR etc.). But it fails with NO_AUTH when the user just have the Commentor role as implemented:

```javascript
    case types.ADD_COMMENT_TAG:
    case types.REMOVE_COMMENT_TAG:
      return check(user, ['ADMIN', 'MODERATOR', 'STAFF']);
```

Is it possible to adjust the user permissions for this specific action somehow via a plugin?

**Env:**
4.5 + Docker Image

Thank you again for any help!

**Comment by wyattjoh** [comment]
You can certainly do that currently!

Check out: https://github.com/coralproject/talk/blob/13cc80bd356a8f2a3839ff4ea12010404dd152e6/plugins/talk-plugin-offtopic/index.js

For an example of how the OFFTOPIC tag is configured to use permissions.

**Comment by saerdnaer** [comment]
We tried that, but the config you linked had no effects. The plugin you linked only contains frontend code for the client, the underlaying problem is that the backend does not check that configuration – compare 

https://github.com/coralproject/talk/blob/master/graph/mutators/tag.js#L39-L41
https://github.com/coralproject/talk/blob/c19d4a433a0e1ab3453994affdfa5ed03becd6f8/graph/mutators/tag.js#L39-L41

As of now I see no code that bypasses that `context.user.can(ADD_COMMENT_TAG)` check  based on individual tag's basis.

**Comment by wyattjoh** [comment]
The OFFTOPIC tag works when the comment is initially created, not for adding a tag after the fact. Take a look through the entirety of the OFFTOPIC plugin itself:

https://github.com/coralproject/talk/blob/f2857a8085b8f3b4757ad7a93698d0b90ce28824/plugins/talk-plugin-offtopic/client/containers/OffTopicCheckbox.js

Which adds the tag before the comment is posted, so it doesn't actually hit that permission check for the mutator, instead it hits: https://github.com/coralproject/talk/blob/f2857a8085b8f3b4757ad7a93698d0b90ce28824/graph/mutators/comment.js#L16

The logic there is a bit complex, but it's well described here:

https://github.com/coralproject/talk/blob/c19d4a433a0e1ab3453994affdfa5ed03becd6f8/models/schema/tag.js#L11-L45

**Comment by saerdnaer** [comment]
Thanks for the clarification. In our case we actually allow generic tags without a general restriction as implemented here:
https://github.com/coralproject/talk/blob/f2857a8085b8f3b4757ad7a93698d0b90ce28824/services/tags.js#L120-L124

so we would have to add a global config option do disable that check, e.g.

```javascript
if ( !Settings.select('tags.default-allow-all') && !user.can(ADD_COMMENT_TAG) )
```

**Comment by wyattjoh** [comment]
Based on your initial question in #1859, it seems like you wanted to add tags to a comment when the user creates the comment. If that's the case, then it shouldn't need modifications to the tag system to allow it.
