### ISSUE TITLE
How to do for each article

### ISSUE THREAD

**Issue by deepaksisodiya** [coralproject/talk#1865]
#### Do you want to request a **feature** or report a **bug**?

Question

#### Intended outcome:

Loading the comment section for each article.

#### Actual outcome:

Description

I have pages where first article is server render and when user scroll then all the other article is served by front end.

I have page dynamic article page, lets say **Article.vuejs**. In this page I am generating adding div with dynamic ids like <div id={dynamic} /> ok
and loading the comments for each article. comments sectio loading perfect. But this the same comment that comes for first article. I want to have different article section for different article.

the script i am loading is

Coral.Talk.render(document.getElementById(id), {
        talk: 'http://127.0.0.1:3000/'
});

Is there is a way we can do this.

#### Version and environment

latest

**Comment by deepaksisodiya** [comment]
Got it. There is **asset_url** key in the **config** to do this.
Docs need to improve a lot. I have to see the source code for this.

**Comment by wyattjoh** [comment]
Documentation is always a work in progress, glad to see you discovered the solution!
