### ISSUE TITLE
Check tags on an asset returns false (lodash / has)

### ISSUE THREAD

**Issue by himynameissebbo** [coralproject/talk#1867]
#### Do you want to request a **feature** or report a **bug**?
bug

#### How to reproduce the issue:
Within `services/tags.js` there is the function

```javascript
static async getAll({ id, item_type, asset_id = null }) {
...
}
```

which checks if global tags in the `settings` property for an asset are set. But even the property `settings.tags` is set for the asset the if condition  

```javascript
if (asset && has(asset, 'settings.tags') {
	return get(asset, 'settings.tags');
}
```

returns false.  When I remove lodash `has` everything works as expected:

```javascript
if (asset && asset.settings && asset.settings.tags) {
	return get(asset, 'settings.tags');
}
```
I checked lodash with the incoming object outside of Talk and it worked fine. 

Did anyone experience such a problem as well? Otherweise I would state an PR.

#### Version and environment
4.6.2, Docker image

**Comment by wyattjoh** [comment]
Nice catch! I was able to verify with the following table test:

```js
const { has } = require('lodash');
const AssetModel = require('./models/asset');

const assets = [
  null,
  {},
  { settings: null },
  { settings: {} },
  { settings: { tags: null } },
  { settings: { tags: [] } },
  { settings: { tags: ['STAFF'] } },
];

it('computes the same boolean', () => {
  assets.forEach(asset => {
    const model = new AssetModel(asset);

    expect(has(asset, 'settings.tags')).toEqual(has(model, 'settings.tags'));
    expect(Boolean(asset && asset.settings && asset.settings.tags)).toEqual(
      Boolean(model && model.settings && model.settings.tags)
    );
  });
});
```

It seems to be related to how the silly mongoose handles property access... I'll submit a PR shortly addressing this.
