### ISSUE TITLE
Querying Multiple Assets without logging in

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1876]
Question from [our Community](https://community.coralproject.net/t/querying-multiple-assets-without-logging-in/975):

The front pages of many sections on our website display comment counts for multiple articles. I need to be able to query all the IDs on those pages at the same time. This will greatly reduce the number of network calls performed, allowing the page to load faster.

This is from the GraphQL Documentation:

```
assets(query: AssetsQuery): AssetConnection
All assets. Requires the ADMIN role.
```

```
asset(id: ID, url: String): Asset
Find or create an asset by url, or just find with the ID.
```

Is there another option that will let me query multiple IDs at once without requiring Talk authentication?

**Comment by wyattjoh** [comment]
Currently in Talk v4, it is not possible without the introduction of a plugin which performs the requested queries on the database.

## 🚨Warning 🚨 

In Talk v4, querying the Asset comment count (depending on the cache status) may or may not take some time to complete. We're working towards a solution in Talk v5 to support this, but for now, we strongly advise if you are implementing a plugin with a custom route, to cache the request made by your server to Talk to ensure that it isn't hitting Talk too much.

**Comment by wyattjoh** [comment]
cc: @lriggle-strib

**Comment by lriggle-strib** [comment]
@wyattjoh Thanks for the info, this is helpful.
