### ISSUE TITLE
Adding plugins to Talk

### ISSUE THREAD

**Issue by jimm-tampabay** [coralproject/talk#1881]
Talk seems to have installed well.  We can use email for logins and comments are flowing.  

The issue is adding plugins beyond the defaults.  I started trying to implement google-auth and was getting no where.  I had tried following the thread from community, but they were going from source and we used docker-compose for install.  

I backed off google-auth to try something simpler and added like to `plugins.json`.  I have run `cli plugins reconcile` and it shows all packages (including like) as local and up to date.  

However, even `docker-compose stop` / `docker-compose up –d` doesn’t enable like.  

Any suggestions as to where I have gone off the track?

**Comment by kgardnr** [comment]
@wyattjoh the question was hidden in the <-- --> commented text.

**Comment by wyattjoh** [comment]
If you want to customize the default set of plugins available, you need to base your images off of the `*-onbuild` image tags, see: https://docs.coralproject.net/talk/installation-from-docker/#onbuild

You can essentially change your `docker-compose.yml` to something like this:

```yaml
version: '2'
services:
  talk:
    build:
      context: ./talk
# ...
```

Where you have a file `talk/Dockerfile`:

```Dockerfile
FROM coralproject/talk:4-onbuild
```

**Comment by jimm-tampabay** [comment]
I'm sorry that I messed up that message, I need to spend some time with a help page for git issues.  I do git pretty well with code, clones, branches, tags, pulls,etc from the cli.  Never saw that issues page before and didn't find it user friendly. ;- )

Jim


________________________________

**Comment by wyattjoh** [comment]
Not a problem @jimm-tampabay! I just missed the message, was the comments https://github.com/coralproject/talk/issues/1881#issuecomment-422182691 able to help?

**Comment by kgardnr** [comment]
No worries @jimm-tampabay! Let us know if the `*-onbuild` solution works for you!

**Comment by jimm-tampabay** [comment]
The relevant files are posted below
If I stop Talk and run 
docker build -t new-talk ./
it will create a completely new talk
but none of the plugins from plugins.json
the .env variables are available
I'm not sure where I am going wrong.

docker-compose.yml

version: '2'
services:
  talk:
    build:
      context: ./
    image: coralproject/talk:4.5
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=development # remove this line in production
      - TALK_MONGO_URL=mongodb://mongo/talk
      - TALK_REDIS_URL=redis://redis
      - TALK_ROOT_URL=https://talk.tampabay.com
      - TALK_PORT=3000
      - TALK_JWT_SECRET=password
      - TALK_SMTP_FROM_ADDRESS=us@gmail.com
      - TALK_SMTP_HOST=smtp.gmail.com
      - TALK_SMTP_PASSWORD=XXXX
      - TALK_SMTP_PORT=587
      - TALK_SMTP_USERNAME=sptimes.webmaster@gmail.com
      - TALK_GOOGLE_CLIENT_ID=XXXX.apps.googleusercontent.com
      - TALK_GOOGLE_CLIENT_SECRET=XXXX
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data
volumes:
  mongo:
    external: false
  redis:
    external: false
***********************************************
Dockerfile-onbuild

FROM coralproject/talk:4.5-onbuild


ONBUILD ARG TALK_ADDTL_COMMENTS_ON_LOAD_MORE=10
ONBUILD ARG TALK_ASSET_COMMENTS_LOAD_DEPTH=10
ONBUILD ARG TALK_REPLY_COMMENTS_LOAD_DEPTH=3
ONBUILD ARG TALK_THREADING_LEVEL=3
ONBUILD ARG TALK_DEFAULT_STREAM_TAB=all
ONBUILD ARG TALK_DISABLE_EMBED_POLYFILL=FALSE
ONBUILD ARG TALK_DEFAULT_LANG=en
ONBUILD ARG TALK_WHITELISTED_LANGUAGES
ONBUILD ARG TALK_PLUGINS_JSON
ONBUILD ARG TALK_WEBPACK_SOURCE_MAP


ONBUILD COPY . /usr/src/app


ONBUILD RUN cli plugins reconcile && \
            yarn && \
            yarn build && \
            yarn cache clean
***************************************
plugins.json

{
  "server": [
    "talk-plugin-featured-comments",
    "talk-plugin-local-auth",
    "talk-plugin-profile-data",
    "talk-plugin-respect",
    "talk-plugin-google-auth"
  ],
  "client": [
    "talk-plugin-auth",
    "talk-plugin-author-menu",
    "talk-plugin-featured-comments",
    "talk-plugin-flag-details",
    "talk-plugin-ignore-user",
    "talk-plugin-local-auth",
    "talk-plugin-member-since",
    "talk-plugin-moderation-actions",
    "talk-plugin-permalink",
    "talk-plugin-profile-data",
    "talk-plugin-respect",
    "talk-plugin-like",
    "talk-plugin-sort-most-replied",
    "talk-plugin-sort-most-respected",
    "talk-plugin-sort-newest",
    "talk-plugin-sort-oldest",
    "talk-plugin-viewing-options",
    "talk-plugin-google-auth"
  ]
}

**Comment by jimm-tampabay** [comment]
I have tried to install from source on a clean new server instance.  Followed the install instructions and everything ran with no errors.  Ran yarn watch:server and get the following output and "talk is not setup" error.  Does anyone see my mistake?

yarn run v1.9.4
$ nodemon --config .nodemon.json
[33m[nodemon] 1.17.5[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching: *.* bin/cli bin/cli-serve[39m
[32m[nodemon] starting `npm-run-all --parallel generate-introspection start:development`[39m
$ WEBPACK=TRUE NODE_ENV=test ./scripts/generateIntrospectionResult.js
$ NODE_ENV=development ./bin/cli-serve -j -w
Outputted result of introspectionQuery to /home/jimm/talk/client/coral-framework/graphql/introspection.json
Outputted result of introspectionQuery to /home/jimm/talk/docs/source/_data/introspection.json
Sep 24 08:23:29 talk[2675] INFO:  serve (./serve:97): [32mSetup is currently available, migrations not being checked[39m
[32m  version: "4.6.3"[39m
[32m  origin: "jobs"[39m
Sep 24 08:23:29 talk[2675] INFO:  Object.entries.forEach (./jobs/:15): [32mStarting job[39m
[32m  version: "4.6.3"[39m
[32m  origin: "jobs"[39m
[32m  taskName: "mailer"[39m
Sep 24 08:23:29 talk[2675] INFO:  module.exports (./j/mailer:144): [32mNow processing jobs[39m
[32m  version: "4.6.3"[39m
[32m  origin: "jobs:mailer"[39m
[32m  taskName: "mailer"[39m
Sep 24 08:23:29 talk[2675] INFO:  Object.entries.forEach (./jobs/:15): [32mStarting job[39m
[32m  version: "4.6.3"[39m
[32m  origin: "jobs"[39m
[32m  taskName: "scraper"[39m
Sep 24 08:23:29 talk[2675] INFO:  module.exports (./j/scraper/:82): [32mNow processing jobs[39m
[32m  version: "4.6.3"[39m
[32m  origin: "jobs:scraper"[39m
[32m  taskName: "scraper"[39m
Sep 24 08:23:29 talk[2675] ERROR: onTick (./p/t/s/connect:144): [31mcould not handle user deletions[39m
[31m  err: Error: Talk is currently not setup. Please proceed to our web installer at $ROOT_URL/admin/install or run ./bin/cli-setup. Visit https://docs.coralproject.net/talk/ for more information on installation and configuration instructions[39m
[31m  [1m    at new ExtendableError (./errors.js:8:18)[22m[39m
[31m  [1m    at new TalkError (./errors.js:23:5)[22m[39m
[31m  [1m    at new ErrSettingsNotInit (./errors.js:276:5)[22m[39m
[31m  [1m    at loadFn (./services/settings.js:16:11)[22m[39m
[31m      at <anonymous>[39m
[31m  version: "4.6.3"[39m
[31m  origin: "graph:context"[39m
[31m  traceID: "5084150e-fc87-42d0-81c4-8b3bdff2ba8b"[39m
Sep 24 08:23:29 talk[2675] INFO:  onListening (./serve:74): [32mAPI server started[39m
[32m  version: "4.6.3"[39m
[32m  origin: "jobs"[39m
[32m  port: 3000[39m
Sep 24 08:23:29 talk[2675] INFO:  server.listen (./serve:131): [32mWebsocket server started[39m
[32m  version: "4.6.3"[39m
[32m  origin: "jobs"[39m
[32m  port: 3000[39m

**Comment by jimm-tampabay** [comment]
BTW, after getting this error I did run ./bin/cli-setup (no error) and then reran yarn watch:server with the same results

**Comment by kgardnr** [comment]
Hey Jim can you make sure you’re setting your .env file correctly? See the
Required Configuration section of the docs. Looks like your Talk root url
may not be set.

**Comment by jimm-tampabay** [comment]
Here is a copy of .env, other than the email connection it should be the same as the .env file in the instructions.

NODE_ENV=development # remove this line in production
TALK_MONGO_URL=mongodb://127.0.0.1:27017/talk
TALK_REDIS_URL=redis://127.0.0.1:6379
TALK_ROOT_URL=https://127.0.0.1:3000
TALK_PORT=3000
TALK_JWT_SECRET=password
TALK_SMTP_FROM_ADDRESS=XXXX@gmail.com
TALK_SMTP_HOST=smtp.gmail.com
TALK_SMTP_PASSWORD=XXXX
TALK_SMTP_PORT=587
TALK_SMTP_USERNAME=XXXX@gmail.com

**Comment by jimm-tampabay** [comment]
Hey, I just noticed that the talk url is https, I will change that and try again

**Comment by jimm-tampabay** [comment]
no luck, I stopped mongo and redis, changed the .env talk url to http from https, reran yarn build (no errors) restarted mongo and redis, ran yarn watch:server and got the same error.

**Comment by jimm-tampabay** [comment]
here is the current .env
NODE_ENV=development # remove this line in production
TALK_MONGO_URL=mongodb://127.0.0.1:27017/talk
TALK_REDIS_URL=redis://127.0.0.1:6379
TALK_ROOT_URL=http://127.0.0.1:3000
TALK_PORT=3000
TALK_JWT_SECRET=password
TALK_SMTP_FROM_ADDRESS=XXXX@gmail.com
TALK_SMTP_HOST=smtp.gmail.com
TALK_SMTP_PASSWORD=XXXX
TALK_SMTP_PORT=587
TALK_SMTP_USERNAME=XXXX@gmail.com

**Comment by wyattjoh** [comment]
Once you've started Talk, navigate to http://127.0.0.1:3000/admin and follow the installation prompts. The "error" warning you that Talk is not setup is just letting you know that Talk needs to be installed before it can run (like how Wordpress needs to install in order to start).

**Comment by kgardnr** [comment]
@jimm-tampabay I'm going to close this as resolved. Let us know if you run into any more trouble, and we're happy to help!
