### ISSUE TITLE
Cannot remove "Not you? Sign out" in the Talk client 

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/talk#1882]
Hi,

I am using SSO custom authentication and everything is fine but in the UI when the user is authenticated through SSO it is not logical to have the "Not you? Sign out"
I want to remove that piece. 

![image](https://user-images.githubusercontent.com/24658315/45642886-0662df00-ba90-11e8-8514-5a8c304c3b3f.png)

I tried using css as follows:

```
.talk-stream-auth-userbox{
    display: none;
}
```
This hid the "Sign out" but not the  "Not you?". To hide the "Not you?" section, since it  is in the same html tag for "Signed in asHamed_Minaee_2555. ...."  the whole section needs to be hidden  and this way the "Signed in asHamed_Minaee_2555. " will be hidden as well which is not what I wanted.

Is it possible to remove it in any better way?

**Comment by wyattjoh** [comment]
You should remove the plugin `talk-plugin-auth` from your `plugins.json` which will hide all of those prompts :)

**Comment by hminaeeBrunswicknews** [comment]
@wyattjoh  Thanks for answering,

I removed the plugin and here is the content of my plugin.json:
```

{
  "server": [
    "talk-plugin-featured-comments",
    "talk-plugin-profile-data",
    "talk-plugin-respect",
    "talk-plugin-auth-brunswick-news"
  ],
  "client": [
    "talk-plugin-author-menu",
    "talk-plugin-featured-comments",
    "talk-plugin-flag-details",
    "talk-plugin-ignore-user",
    "talk-plugin-member-since",
    "talk-plugin-moderation-actions",
    "talk-plugin-permalink",
    "talk-plugin-profile-data",
    "talk-plugin-respect",
    "talk-plugin-sort-most-replied",
    "talk-plugin-sort-most-respected",
    "talk-plugin-sort-newest",
    "talk-plugin-sort-oldest",
    "talk-plugin-viewing-options"
  ]
}
```

But still I see the "Not you. sign out?" in the UI. Any idea?

**Comment by kgardnr** [comment]
Can you also paste the client side plugins you have?

**Comment by hminaeeBrunswicknews** [comment]
@kgardnr Where should I find it? 
Is there any other json file rather than plugin.json?

**Comment by kgardnr** [comment]
In your `plugins.json` you should have client and server plugins listed, here is an example: https://github.com/coralproject/talk/blob/master/plugins.default.json

**Comment by hminaeeBrunswicknews** [comment]
@kgardnr 

Sure. Here is the client part:

```
 "client": [
    "talk-plugin-author-menu",
    "talk-plugin-featured-comments",
    "talk-plugin-flag-details",
    "talk-plugin-ignore-user",
    "talk-plugin-member-since",
    "talk-plugin-moderation-actions",
    "talk-plugin-permalink",
    "talk-plugin-profile-data",
    "talk-plugin-respect",
    "talk-plugin-sort-most-replied",
    "talk-plugin-sort-most-respected",
    "talk-plugin-sort-newest",
    "talk-plugin-sort-oldest",
    "talk-plugin-viewing-options"
  ]
```

**Comment by kgardnr** [comment]
That copy is definitely in `talk-plugin-auth`, so maybe you've copied this over to your own auth plugin. Check the code there and see if it's in your plugin.

Otherwise, make sure when you remove plugins, you trigger a rebuild of the code, so it removes it.

**Comment by hminaeeBrunswicknews** [comment]
@wyattjoh @kgardnr 

I removed the auth-token and then after I had to use yarn build to have that working.
However still the issue stays: if I remove the talk-plugin-auth I get the following:

![image](https://user-images.githubusercontent.com/24658315/45723393-6f794e00-bb87-11e8-820a-f09e54a8e994.png)


If I add that I get the following ;

![image](https://user-images.githubusercontent.com/24658315/45723133-270d6080-bb86-11e8-9e1b-fbc90f0ea5c8.png)


but what I am trying to achive is the following:

![image](https://user-images.githubusercontent.com/24658315/45723426-a5b6cd80-bb87-11e8-8626-1dfa0e993c78.png)
As you see still the text saying "Signed in as ..." exists but "Not you?. Sign out?" should be removed
How can I achieve this?

**Comment by kgardnr** [comment]
Can you send a copy of your auth plugin to support@coralproject.net, and we can take a look?

**Comment by wyattjoh** [comment]
I would actually recommend in that case @hminaeeBrunswicknews that you simply include that text before the embed of Talk.

With the SSO authentication mode, it is assumed that the auth state is managed externally, hence why it also hides the name of the user authed.

**Comment by hminaeeBrunswicknews** [comment]
@kgardnr Please check it. It is sent with thanks

**Comment by hminaeeBrunswicknews** [comment]
@wyattjoh  Thanks for the answer
