### ISSUE TITLE
Trouble adding tags to a new user account

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#1892]
I'm having issues when adding a tag to a new user that's going to be created. In my `tokenUserNotFound` plugin, I'm doing a check on the data returned from my auth application to see if the user is a subscriber. If they are, I am trying to add a tag to their account to indicate that.

Here is the data being assembled:

```js
let now = moment().format('YYYY-MM-DD HH:mm:ss');
let newUser = {
  id: profile.id,
  username: profile.username,
  lowercaseUsername: profile.username.toLowerCase(),
  role: 'COMMENTER',
  profiles: [
    {
      id: profile.email,
      provider: 'local',
      metadata: {
        confirmedAt: now,
      },
    },
  ],
  tags: [],
  status: {
    username: {
      status: 'SET',
      history: [
        {
          assigned_by: null,
          status: 'SET',
          created_at: now,
        },
      ],
    },
    banned: {
      status: false,
      history: [],
    },
    suspension: {
      until: null,
      history: [],
    },
  },
};

//If the user is a subscriber, add that status as a tag
if (profile.isSubscriber) {
  newUser.tags.push({
    name: 'SUBSCRIBER',
    permissions: {
      public: true,
      self: false,
      roles: [],
    },
    models: ['USERS'],
    created_at: now,
  });
}
```

As far as I can tell there's nothing explicitly wrong with any of that, but when the user is inserted into the database, the tag, and nothing else, ends up malformed:

<img width="900" alt="screen shot 2018-09-19 at 3 26 32 pm" src="https://user-images.githubusercontent.com/7051012/45779388-7d2ee200-bc20-11e8-91da-5d664cbffaa6.png">

When the new user goes to comment, the following error is encountered:

```
Error: Cannot return null for non-nullable field TagLink.tag.
```

What fields am I missing in the tag itself?

**Comment by wyattjoh** [comment]
The reason that it isn't working here, is because you're pushing the wrong structure onto the model.

https://github.com/coralproject/talk/blob/7b0213299a5cd3d201da5ff4d95ac84353fdd917/models/schema/user.js#L195

Tags on a user are in the form of a `TagLink`:

https://github.com/coralproject/talk/blob/7b0213299a5cd3d201da5ff4d95ac84353fdd917/models/schema/tag_link.js#L9-L27

Where `TagSchema` is what you expected. So instead, the code should be:

```js
// If the user is a subscriber, add that status as a tag.
if (profile.isSubscriber) {
  newUser.tags.push({
    tag: { // <-- Notice the addition of the tag here? We're just nesting what you already had inside it to match the expected schema for the User.
      name: 'SUBSCRIBER',
      permissions: {
        public: true,
        self: false,
        roles: [],
      },
      models: ['USERS'],
      created_at: now,
    },
  });
}
```

**Comment by lriggle-strib** [comment]
@wyattjoh That did the trick, thank you so much!
