### ISSUE TITLE
How to associate the custom url with the comment made by the use 

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/talk#1902]
Hello,

I am not sure if this is a feature idea or it was already implemented in talk.
When user post a comment lets say in the page with the following URL: http://localhost:3003/miramichileader/100719778

I see the following in the admin page:

![image](https://user-images.githubusercontent.com/24658315/45928454-59b6b080-bf1a-11e8-9a8d-c357d861b233.png)

As is clear the url in which the user made comment, is reflected in the admin page.
but What about the case where the deep link to the story needs to be shown in admin page?
For example the user make a comment in the following url:   **http://localhost:3003/miramichileader/100719778**

But in admin page we want the following link to be shown:

**http://localhost:3003/story/100719778**

Is there anyway to send the url we want to be shown in admin? (or better to say is there anyway to associate the custom url to the comment made by the user)

**Comment by wyattjoh** [comment]
@hminaeeBrunswicknews: There is already a way for when the comment stream embed is added to the page to specify the desired URL to use for associating with Talk (with the `asset_id` option, or setting the Canonical URL `<link rel="canonical" href="https://my/desired/url" />`), so I'm not 100% sure what you mean by a deep link?

It may be required for you to specify the url for the article in each of the embed codes across your site to ensure the correct URL is passed to Talk.

**Comment by hminaeeBrunswicknews** [comment]
@wyattjoh  thanks for answering. 
How can I embed the URL for each news?

Here is the code I have for embedding talk for each news:

```
        Coral.Talk.render(document.getElementById("comment-talk-"+this.props.storyId), {
            talk: path.COMMENT_DOMAIN,
            auth_token: getToken('talkToken')
        });
```

Do you mean adding another parameter like: asset_url: my desired url in  the following?

```
        Coral.Talk.render(document.getElementById("comment-talk-"+this.props.storyId), {
            talk: path.COMMENT_DOMAIN,
            auth_token: getToken('talkToken'),
            asset_url: my desired url
        });
```
