### ISSUE TITLE
yarn watch:server & does not detach the process and after the terminal gets disconnected talk stops working

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/talk#1905]
Hello,

I run talk from source following the instruction here:

[https://docs.coralproject.net/talk/installation-from-source/](https://docs.coralproject.net/talk/installation-from-source/)

So far so good.
When I run the following "yarn watch:server &" talk starts running until the terminal I am running talk on gets closed or disconnect from the server. Then after Talk stops working.
 
As you see I am using & to detach the process from the terminal but not taking effect. Is there any way that the Talk still keeps working even though the terminal is disconnected?

**Comment by wyattjoh** [comment]
In order to have the watch command persist after a terminal disconnect, you'll need to utilize [nohup](https://en.wikipedia.org/wiki/Nohup):

```bash
nohup yarn watch:server &
```

And it should accomplish what you're looking for 😄

**Comment by hminaeeBrunswicknews** [comment]
@wyattjoh 

Here is what I get in nohup.out file when I run it:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event at:
    at lazyFs.read (internal/fs/streams.js:165:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:458:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Is it because I am in development mode?

**Comment by hminaeeBrunswicknews** [comment]
@wyattjoh 

Here is what I get in nohup.out file when I run it:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EBADF: bad file descriptor, read
Emitted 'error' event at:
    at lazyFs.read (internal/fs/streams.js:165:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:458:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Is it because I am in development mode?

**Comment by wyattjoh** [comment]
I honestly have no idea what that is, it's not due to Talk.

**Comment by hminaeeBrunswicknews** [comment]
@wyattjoh 
Thanks a lot. Your answer for sure put me in the right direction.
For some reason ubuntu wants parenthesis around nohup and then it worked.

`(nohup yarn watch:server &) `

So the issue is fixed :)
