### ISSUE TITLE
[Question] Need suggestions on custom auth (for SSO) practices

### ISSUE THREAD

**Issue by deepaksisodiya** [coralproject/talk#1907]
#### Do you want to request a **feature** or report a **bug**?

Question

#### What is your questions?

We wanted to setup Talk to use our custom auth backend for SSO.  We referred available docs and Github issues.

So we did
- setup JWT token generation
- and implemented the tokenUserNotFound hook by modifying talk-plugin-auth code

So far so good and we got our dev setup working with Talk nicely integrated with our custom auth backend.

But as you can imagine maintaining modified Talk's code won't be a good practice. Is there a way to maintain such custom code outside talk very much like most plugin supporting frameworks?

Looking forward to see some suggestions on practices on custom auth code (especially tokenUserNotFound).
Thanks in Advance

#### Version and environment

4.6.3

cc @kgardnr @wyattjoh

**Comment by kgardnr** [comment]
If you use the talk-plugin-auth, then you're opting to use OUR sign-in system. This creates users, helps them sign in, etc. This comes out of the box with Talk so you can simply use our system IF you want to.

But you don't need this.

You want YOUR system to manage YOUR users.

All you need is a way to tell Talk whether these users exist and should log them in.

You don't need the `talk-plugin-auth`. 

You need a plugin to talk to your system, hence, `talk-plugin-auth-scroll`.

So you will need to remove our auth plugin, and use your own in its place:

`talk-plugin-auth-scroll`

inside that folder will be an index.js file with your tokenUserNotFound code.

When one of your users "logs in" to Talk, this code will go to your system, retrieve the user if they exist - or create them if "UserNotFound", and bring that back to Talk to authenticate them.

You can generate a plugin template with the plugin CLI which I linked you to, or you can use other plugins as a guide to how plugins are setup.
