### ISSUE TITLE
[Question] How to hide the comment stream

### ISSUE THREAD

**Issue by deepaksisodiya** [coralproject/talk#1908]
#### Do you want to request a **feature** or report a **bug**?

Question

#### What is your question

We have one article on one page and when user scrolls then the second article loads.
So there are multiple articles for one single page.
And there is one button say **See Comments** to view the comment stream for each article. and on click of the button, **comments stream** will open right side like https://www.nytimes.com/2018/08/27/travel/wedding-shopping-delhi-mumbai-india.html#commentsContainer

What I want is that when user open second article **comment stream** then first article **comment stream** should be close then the new one is open.

Is there any way to hide the current open **comment stream**?

#### Version and environment

4.6.3

cc @kgardnr @wyattjoh

**Comment by kgardnr** [comment]
Thanks for writing @deepaksisodiya! 

If you want to manipulate how and when the embed renders, or is hidden, you'll have to do this with the code on your article page(s).

If you can explain more where you're running into issues here, we might be able to help, but this isn't a feature included in Talk, so it's outside the scope of the support we can provide typically.

**Comment by deepaksisodiya** [comment]
@kgardnr Thank you.
