### ISSUE TITLE
How do stories work?

### ISSUE THREAD

**Issue by freder** [coralproject/talk#1909]
#### Do you want to request a **feature** or report a **bug**?
question

#### Intended outcome:
I just set up a local docker instance, and noticed that under `moderate` a comment's story is the page URL, but under `stories` "nothing" gets displayed.

a few extra questions about stories:
- how can I set `story` to a custom value? 
- assuming stories are identifiers for the _thing_ people comment on – how come this cannot be queried through the graphql API? how would I get all comments that belong to a _thing_, using the API only?

#### Actual outcome:
![screen shot 2018-09-25 at 17 03 21](https://user-images.githubusercontent.com/724844/46023568-3429d280-c0e5-11e8-96cc-3dc431caba7b.png)

#### How to reproduce the issue:
comment on a simple test page:

```
<body>
	<div id="coral_talk_stream"></div>
	<script
		async
		src="http://127.0.0.1:3000/static/embed.js"
		onload="
			Coral.Talk.render(
				document.getElementById('coral_talk_stream'),
				{ talk: 'http://127.0.0.1:3000/' }
			);
		"
	></script>
</body>
```

then go to `stories` tab in the admin.

#### Version and environment
docker-ized version `4.6.3`

**Comment by wyattjoh** [comment]
Asset metadata (title, dates) are scraped from the pages using a packaged called [metascraper](https://metascraper.js.org/).

The URL that Talk will use to scrape from is the URL located in the [canonical](https://yoast.com/rel-canonical/) tag, which you can use to help with de-duplicating articles.

**Comment by freder** [comment]
thanks, @wyattjoh 

adding `<link rel="canonical" href="/bla">` works. – I was wondering though: when exactly does the scraping happen? ~is it done client-side, when instantiating the embed? or is it done by the backend? if the latter is the case, it makes sense that nothing shows up in the admin, because obviously the backend inside the docker container cannot access the host network.~ (**update:** yes, it is done server-side, and I got scraping in docker to work by slightly modifying the official image.)

another thing I noticed is that passing `asset_url` to the embed overrides `<link rel="canonical" ...>`. however, passing `title` has no effect... looking at https://github.com/coralproject/talk/blob/master/client/coral-embed/src/index.js `title` doesn't seem to get used anywhere. you might want to change the `jsdoc` comment, or document the embed in general.

and lastly: I may not be fully familiar with the terminology yet, but I find the naming of things a bit confusing. from using the admin UI and the API, it seems that _stories_, _streams_, and _assets_ are the same thing. is that right?

bonus question: ~how can I create an asset through the API?~ (I'm asking because I'm trying to figure out, how to use `talk` "headlessly", only using the API.) — **update:** I was looking for a `create*` type of mutation, and didn't realize you'd create assets through `asset` queries.

**Comment by kgardnr** [comment]
I'll try to answer all your questions here!

1. Scraping happens when Talk loads on the article page for the first time

2. Not sure what you mean about `title`. Your metadata may be incorrect. Can you send us an example article page to look at?

3. Yes, we do have some overlap between Stories, Streams and Assets - this will be corrected in v5.

Let us know if this helps!

**Comment by freder** [comment]
yes, that helps. thanks, @kgardnr
