### ISSUE TITLE
[Question] How to add user avatar

### ISSUE THREAD

**Issue by deepaksisodiya** [coralproject/talk#1913]
#### Do you want to request a **feature** or report a **bug**?

question

#### Intended outcome:

Trying to add the user avatar
I want to add user avatar like here https://www.nytimes.com/2018/08/27/travel/wedding-shopping-delhi-mumbai-india.html#commentsContainer
is there any way to add the user avatar

#### Version and environment

4.6.3

**Comment by kgardnr** [comment]
Avatar support is one of our Talk Recipes, you can find those here: https://github.com/coralproject/talk-recipes

**Comment by deepaksisodiya** [comment]
@kgardnr Thank you for the link
