### ISSUE TITLE
localStorage on Safari and iOS

### ISSUE THREAD

**Issue by iksteen** [coralproject/talk#1915]
On https://github.com/coralproject/talk/blob/65a166b860357d2b8ca566a273381dcd523e59e3/client/coral-framework/services/bootstrap.js#L49-L50 it is suggested that Safari and iOS do not have a stable `localStorage` API. Is that still true?

If so, do you have a suggestion for the following scenario: We've created a plugin that implements `tokenUserNotFound` to implement SSO from our frontend to the talk embed by providing the `auth_token` config option.

We want to extend this SSO to the admin backend so that when moderators click on the 'Moderate this stream' link they are automatically signed in to the backend. Our initial idea was to just set the `token` setting in the `localStorage` which works on most browsers, but not on Safari and iOS because of this check. Is there an alternative way to provide SSO from the embed to the backend?

**Comment by kgardnr** [comment]
This is addressed in v5
