### ISSUE TITLE
Blank popup after oauth login

### ISSUE THREAD

**Issue by striedinger** [coralproject/talk#1916]
I have encountered an issue when implementing google and facebook as auth providers. I installed the plugins and my settings are correct, however after I login with either the popup goes to a blank screen and I get an error in the console with the following:

'Refused to load the script 'https://ajax.cloudflare.com/cdn-cgi/scripts/2448a7bd/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback'

We are using cloudflare for DNS. Surprisingly, when trying with IE11 it works as expected and I am able to continue and confirm username, email and password.

**Comment by kgardnr** [comment]
Hey @striedinger! Thanks for posting this.

Just confirming that you did set up the callback URLs and allowed domains for both Facebook and Google, via their developers UI?

**Comment by striedinger** [comment]
@kgardnr Yes, everything is setup correctly on google and facebook's side, as I said it works correctly on IE (surprisingly) but on Chrome and Firefox I'm just getting a blank popup when signing on the respective provider's site.

**Comment by striedinger** [comment]
This turned out to be a Cloudflare issue as expected. It can be closed, thanks.
