### ISSUE TITLE
If you change your username, the username field is still editable; it should no longer be editable and should show message saying you can only change username every 14 days

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1917]
#### Do you want to request a **feature** or report a **bug**?

**Bug**

#### Intended outcome:
If you change your username, the field should no longer show as editable; instead it should no longer be editable and show that usernames can only be changed every 14 days.

#### Actual outcome:

Username field still shows as editable

#### How to reproduce the issue:

Go to My Profile and click Edit Profile. Change your Username. After saving, try editing your Username again. It won't save, but it's confusing that the field is still editable.

#### Version and environment
4.6.3

**Comment by meetcric** [comment]
i wanna work on this..

**Comment by jamesallured** [comment]
I'd like to pick this one up! 🙃

**Comment by jamesallured** [comment]
I cannot reproduce this...
