### ISSUE TITLE
Rich text comments add strange characters to the comments download fields in CSV

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1926]
#### How to reproduce the issue:

1. Create a comment using rich text
2. Go to My Profile and click Download My Comments
3. Go to your email and see the CSV file
4. You will find special characters for the rich text comment

**Comment by harrysoer** [comment]
can I try this one @kgardnr?

**Comment by kgardnr** [comment]
We would love for you to, @harrysoer! Let us know if you have questions!
