### ISSUE TITLE
"Copy" button on Share feature  is not copying the permalink

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1927]
#### How to reproduce the issue:

1. Go to an existing comment
2. Click on Share
3. Click "Copy" to copy the permalink
4. Try and paste the link somewhere and it will not paste, it's not being copied to the clipboard

**Comment by moogacs** [comment]
@kgardnr , where can i got to existing comment ?

**Comment by jqueryisamonad** [comment]
@kgardnr this issue's reproducible only on some browsers? All work fine on Chrome 69

**Comment by kgardnr** [comment]
@hovoodd & @moogacs yeah this is so weird, I swear I was able to reproduce this before but now I can't. Might be a moot point then!

**Comment by kgardnr** [comment]
Cannot reproduce this - ack!

**Comment by mkonikov** [comment]
Hey @kgardnr - I encounter this consistently on iOS. Maybe we can reopen and investigate there?
Possibly related to other click event handler issues that previously were reported and fixed on iPad?

**Comment by kgardnr** [comment]
Thanks @mkonikov! Is there any chance you could take a stab submitting a fix for this?

**Comment by mkonikov** [comment]
I'll bring it up at our next grooming meeting and see if we can fit in an upcoming sprint. Thanks @kgardnr!

**Comment by mkonikov** [comment]
With #2159 merged in, I think we can close.
