### ISSUE TITLE
Create a Talk demo on Glitch

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1933]
If you'd like a fun project, let's try and get Talk up and running on Glitch. The goal should be an easy way to launch an instance of Talk.

Glitch: https://glitch.com/ 

AC:

* Make Dockerized version of Talk work with Glitch
* Ability to change the styling

**Comment by leeyspaul** [comment]
Hi! I'd love to take up this issue and contribute if it's up for grabs.

**Comment by kgardnr** [comment]
@leeyspaul it sure is!

**Comment by leeyspaul** [comment]
Awesome! I'll look into this today!

**Comment by leeyspaul** [comment]
Hi @kgardnr! I took a look and got the demo running with the given docker image on my own machine but I'm a little lost as to how to get a dockerized version running on Glitch. 

Would you have any resources or comments on where to start with this?

Thanks!

**Comment by kgardnr** [comment]
Hey @leeyspaul! Unfortunately we don't - it actually might not be possible - https://support.glitch.com/t/installing-docker-in-glitchs-terminal/2816/5

What do you think?

**Comment by leeyspaul** [comment]
Yeah, I actually just saw that today. I was researching and I couldn't find anything. :(

**Comment by kgardnr** [comment]
Hmm.. I wonder if there's any other way we could get an instance of Talk running on Glitch @leeyspaul?

Sending the bat signal to our friends @leeeandroo @hellp @clintabrown @cristiandean @davisshaver @erikreyna @facuesr @PepeFranco @kitwestneat @meddy if they have any ideas - and Happy Hacktoberfest!

**Comment by kitwestneat** [comment]
I think if you follow the install from source instructions it should work. One hiccup is that you'll need to find alternative install methods for Redis and Mongodb. 

Here's someone with some redis tips:
https://support.glitch.com/t/redis-data-persistence/4567/2

It looks like everyone uses mLab for mongodb on glitch. 

I tried it briefly, but it keeps running out of memory on the webpack phase. Perhaps it's possible to precompile it?

**Comment by styfle** [comment]
> The goal should be an easy way to launch an instance of Talk.

If Glitch doesn't work, you can pretty easily deploy any Dockerfile to [Zeit Now](https://zeit.co/now).

1. create the `Dockerfile` in the root of your project
2. install the cli with `npm install -g now`
3. login to your account with `now login`
4. deploy your code with `now --docker`
5. alias the deployment with a pretty url with `now alias talk.example.com`

**Comment by justanotherlad** [comment]
HI! Can I take this issue up?
Is it possible to deploy Talk on Slack?

**Comment by kgardnr** [comment]
@swastikbanerjee07 - we have some Slack integrations, yes!

https://github.com/coralproject/talk-plugin-slack-bouncer
https://github.com/coralproject/talk-plugin-slack-notifications
