### ISSUE TITLE
Option to hide GDPR Features

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1937]
STORY: As a developer, I want to hide the GDPR features from Talk because I have my own GDPR strategies for all user data elsewhere on my site.

AC:
- Disable or hide GDPR features, if I'm handling this elsewhere
- Should be an ENV variable to enable/disable

**Comment by pranay414** [comment]
I would like to take this? What file/files I need to change?

**Comment by fabianmarz** [comment]
@kgardnr, can we please clarify which features are GDPR features and need to be configurable?

I extracted those from the [docs](https://github.com/coralproject/talk/blob/master/docs/source/03-08-gdpr.md#gpdr-feature-overview):

- Download my comment data
- Delete my account
- Add an email to an Oauth/external account
- Change my username
- Change my email
- Change my password

Are those all necessary to be configurable, or should this be limited to specific points? In addition, does it make sense to have a config per feature or a global "show GDPR features" config key? Did you have an internal discussion about this already?

**Comment by kgardnr** [comment]
Hi @pranay414 and @fabianmarz - great questions!

@fabianmarz you summed that up nicely!

So these features can be found in 2 plugins:

1) Change my username, change my email, change my password, add external auth to oauth - `talk-plugin-local-auth`

2) Download my comment data, delete my account - 'talk-plugin-profile-data'

To clarify more, for some newsrooms they want to keep the server-side functionality, so they can write their own plugins to handle this functionality on their side and sync that with Talk - BUT they would then wanna disable the frontend for these plugins (most of the options that appear on My Profile tab).

**Comment by pranay414** [comment]
@kgardnr can you tell me how should I start working on this issue?

**Comment by kgardnr** [comment]
Hey @pranay414! Can you ask some more specific questions so I can be as helpful as I can for you?

Basically, this is adding a configuration in Admin > Settings > Moderation Settings and when it's turned "off", the above features would be hidden on the FE.

**Comment by pranay414** [comment]
@kgardnr Ok I'm not sure what's FE here? Also in which files I need to edit to add these configuration settings?

**Comment by fabianmarz** [comment]
@pranay414, FE = **F**ront **E**nd.

All respect, I'm not trying to offend you, but if you can't figure out yourself which files need to be edited to make this PR done, I don't think it's suitable for you. The simplest first thing to do would be to search for an existing string from the frontend config and see where it's used to point out the necessary files.

There is this global [`config`](https://github.com/coralproject/talk/blob/master/config.js) file where the environment parameters are getting prepared. The other files can be found in the plugin files which @kgardnr mentioned.

**Comment by kgardnr** [comment]
This is a new feature in v5! v5 can be found on the `next` branch, and a formal release is coming in September!
