### ISSUE TITLE
Show a pre-mod notice above any streams that are in premoderation

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1938]
STORY: Admin can set a notice shown above pre-mod streams letting commenters know their comments will not appear right away

AC:
- Configuration in Admin > Configure
- Admin can add message that appears above pre-mod streams
- This message should appear directly above the stream

**Comment by bryce-o** [comment]
Hey, I think this is a great idea. Mind if I work on a solution?

**Comment by kgardnr** [comment]
Hi @bryce-o sorry for the delay responding. We actually added a similar feature in v5.5.0 which is Announcements. You can read about it here: https://github.com/coralproject/talk/releases/tag/v5.5.0
