### ISSUE TITLE
Add filters to Admin > Community > People

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1940]
STORY: As an admin, I want to filter by user status and user role

Filter by: Banned, Suspended, Active
Filter by: Admin, Staff, Moderator, Commenter

**Comment by lsurasani** [comment]
hey! could I take a look at this?

**Comment by kgardnr** [comment]
Hi @lsurasani! Yes, please do! Let us know if you have questions :)

**Comment by lsurasani** [comment]
Thanks! will do.

**Comment by lsurasani** [comment]
looks like somebody already made a PR for this @kgardnr just fyi in case you hadn't seen it: https://github.com/coralproject/talk/pull/1961

**Comment by kgardnr** [comment]
Oh thank you, @lsurasani, I had not seen that - sorry! Feel free to try another one? 

These are some of my favorite ones :)

This is a small one - just adding a badge when a user is a "subscriber" - https://github.com/coralproject/talk/issues/1928

Copy/translation updating with a bit of a twist - https://github.com/coralproject/talk/issues/1920

Some others!

https://github.com/coralproject/talk/issues/1938
https://github.com/coralproject/talk/issues/1943

**Comment by kgardnr** [comment]
Fixed in https://github.com/coralproject/talk/pull/1961
