### ISSUE TITLE
Prevent accounts that are pending delete from commenting, replying, reacting

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1943]
Currently if a user submits an Account Deletion request, during those 24 hours, they can still comment and reply and react. We should prevent them from taking action in the system unless they cancel their Account Deletion request.

**Comment by lsurasani** [comment]
hey @kgardnr I'll take a look at this!

**Comment by kgardnr** [comment]
@lsurasani awesome!

**Comment by lsurasani** [comment]
@kgardnr could you give me some direction on how to start? Do I use these directions: https://docs.coralproject.net/talk/ to run a local instance of it?

**Comment by kgardnr** [comment]
Yep! All the docs are there - that's the best place to start. Our code is heavily commented too, so perusing the code itself is a good place to check out too.

**Comment by lsurasani** [comment]
thanks so much!

**Comment by kgardnr** [comment]
This is addressed in v5
