### ISSUE TITLE
Make Banned/Suspended Word Lists collapsible in Admin > Configure 

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1946]
These word lists can get long (and have some nasty stuff in them) - let's make these collapsed by default so they're hidden on first view of the Configuration pages.

**Comment by DillonSimeone** [comment]
I'm working on this now. Assign this to me, please.

**Comment by jqueryisamonad** [comment]
@kgardnr hi, I work on this issue and have some questions:
1. Lists must be collapsed only on the first view (i.e. we can't save collapsed flag in React's state)?
2. All card must be collapsed or only list? 

Currently, I have something like that:
![image](https://user-images.githubusercontent.com/23063254/46413384-7aa4b000-c729-11e8-9dff-2c74a5ee2f06.png)

**Comment by kgardnr** [comment]
Hi @hovoodd! Thank you so much for this!

Good questions - 

1) Yes, I think we should default to always have them collapsed - these are not updated that often, but viewing this page can become stressful seeing so many negative words

So - 
A) Always collapsed
B) Until someone opens to change or add a word
C) Don't need to collapse on Save
D) Because next time I view this page it will be collapsed 

2) Just the 2 words lists - not the other options

Does that make sense?

**Comment by kgardnr** [comment]
Fixed in #2014
