### ISSUE TITLE
Mod queues performance - only query the queues that the user is viewing

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1949]
Currently all mod queues are being queried on admin page load; we should only query the queue that the user is currently on

**Comment by sladyn98** [comment]
I would like to solve this issue can you guide mea bit more on how to approach it. Thanks

**Comment by kgardnr** [comment]
hey @sladyn98! Great! We'd love to have you on board.

So currently when you load `/admin` it will default go to '/admin/moderate` - this is the Moderate tab, which holds the Moderation Queues.

When you load this page, all the queues query for comments and load them - this is not performant; it should only load the queue that is selected. (I believe it defaults to "New")

Then if you click on another queue, e.g. Rejected, it should load those. If you click another queue, it loads those, and so on.

Let me know if this is helpful!

**Comment by kgardnr** [comment]
This is addressed in v5
