### ISSUE TITLE
Show original comment text for edited comments to mods

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1951]
STORY: As a moderator, I want to see what the original text was on a comment that's edited, so I can see if they've changed from something nasty to something ok

**AC**:
- On Edited comments in Admin, on the comment card, show Original Comment text

**Comment by drasolon** [comment]
Hi, can I work on this one ?

**Comment by kgardnr** [comment]
Yep! Please do!

**Comment by gerardogalvez** [comment]
Is this one taken?

Also, should the moderator only see the original comment or, if a comment has been edited multiple times, all the edits?

**Comment by wyattjoh** [comment]
Ideally, we'd like to see all the previous edits, as they're all stored on the comment. Feel free to take a stab at it @gerardogalvez!

**Comment by gerardogalvez** [comment]
Opened a PR for this: #2299
