### ISSUE TITLE
Changing Stream Status in Admin > Stories should update the UI live so it's not confusing to the user

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#1952]
#### Do you want to request a **feature** or report a **bug**?

Bug

#### Intended outcome:
When you Open or Close stories in a filtered view in the Admin > Stories page, it's not clear that the status has indeed been updated, because the UI doesn't refresh to show this. Gif attached to show how this is currently working.

#### Actual outcome:
It looks like the status was not changed - even though it is updating the status correctly.

#### How to reproduce the issue:
Filter Closed Stories in Admin > Stories list. Change Closed to Open. Notice the UI doesn't update. But if you search again for that Story, it has been updated correctly to Open status.

#### Version and environment
4.6.2 (reproduced also in 4.6.3)

![opening_streams_strib](https://user-images.githubusercontent.com/1077300/46234844-0b544800-c346-11e8-8288-87ea9c50fedd.gif)

**Comment by hamer-iboshi** [comment]
I will work on it.
