### ISSUE TITLE
Question about adding plugin from private repo

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#1958]
In development, I've been adding all of our custom plugins directly in the codebase and then including them in the `plugins.json` file, but as we get closer to deployment, I need to start moving our plugins into repos so they can be called in conjunction to using the `onbuild` Docker method in our actual stage/production environments.

I've been able to add the `talk-plugin-custom-asset-id` plugin successfully, as it is a public plugin that lives in Yarnpkg, but I'm having some issues referencing a private github repository within our organization.

I've added the plugin with the github repo to the plugins.json file, and the first time I run `./bin/cli plugins reconcile` it seems to add the plugin successfully to the `package.json` file...

plugins.json
```json
{
    "server": [
        {
            "talk-plugin-token-user-not-found": "git+ssh://git@github.com/<github repo>#v1.0.1"
        }
    ],
    "client": []
}
```

but if I run the reconcile command a second time, it tells me the plugin is out of date.

```
['1/2'] 🔍 Reconciling plugins...

 +local     (l)  packages in your project
 +external  (e)  packages are external
 +outofdate (oe) packages are external but are out of date
 +missing   (m)  packages are not found

 l  talk-plugin-akismet
 l  talk-plugin-featured-comments
 l  talk-plugin-like
 l  talk-plugin-toxic-comments
 oe talk-plugin-token-user-not-found (package upgrade may be required)
 e  @coralproject/talk-plugin-custom-asset-id
 l  talk-plugin-akismet
 l  talk-plugin-author-menu
 l  talk-plugin-featured-comments
 l  talk-plugin-flag-details
 l  talk-plugin-like
 l  talk-plugin-moderation-actions
 l  talk-plugin-remember-sort
 l  talk-plugin-sort-most-liked
 l  talk-plugin-sort-most-replied
 l  talk-plugin-sort-newest
 l  talk-plugin-sort-oldest
 l  talk-plugin-toxic-comments
 l  talk-plugin-viewing-options

['2/2'] 🚚 Fetching plugins...


success Already up-to-date.
✨ Done in 0.02s.
```

In the GitHub repo itself I have the release tagged as the same version (1.0.1) and the package.json file also contains that version number and the same plugin name:

```json
{
  "name": "token-user-not-found",
  "repository": "https://github.com/<github repo>",
  "pluginName": "talk-plugin-token-user-not-found",
  "version": "1.0.1",
  "description": "Provides support for handling users not found within the Talk database",
  "dependencies": {}
}
```

I feel like I'm missing something small and specific, but I'm unsure the best way to google this issue since it's not a yarn specific issue.

What am I missing?

**Comment by wyattjoh** [comment]
If you're using the onbuild image for compiling Talk, then you should not have a `package.json` in your folder when building, as Talk will amend it's `package.json` during the plugin reconciliation phase of the onbuild image. Instead, specifying only a `Dockerfile`, `plugins.json`, and optionally a `plugins/` folder.

We recommend using git submodules, which for a private Gitlab repo are successfully resolved in CI.

**Comment by lriggle-strib** [comment]
@wyattjoh We are not quite at the stage where we are using the onbuild image, everything for my local development is currently using the from source method (i have been having an endless stream of issues using the docker image locally ever since my work machine was replaced, and honestly I haven't had the time or brainpower to think about it). I'm actually trying to decouple our custom plugins from the full source code repo I've been using for development in advance of trying to switch to using onbuild. 

The plugin still seems to work, it's just the reconcile process produces that weird "package upgrade may be required" message, so I'm not sure if it even really matters. :woman_shrugging:

**Comment by wyattjoh** [comment]
Disregard that message 😄 all it's saying is that it can't determine the version of the plugin, because you didn't specify a version, just a git/url, so it doesn't match!

I'd say it's working alright if it successfully loaded the plugins.
