### ISSUE TITLE
Setting up Talk in development env

### ISSUE THREAD

**Issue by kartikpandey2** [coralproject/talk#1974]
Can anyone help me setting up talk, 
I followed installation from source steps given in https://docs.coralproject.net/talk/
and on running `yarn watch:server`
![screenshot 103](https://user-images.githubusercontent.com/20434963/46575991-bbc4ea80-c9dd-11e8-9ab1-114219733ec8.png)

how to setup Talk .?

**Comment by jqueryisamonad** [comment]
@kartikpandey2 If nothing's working, you can setup project with `docker-compose` in development mode (I don't understand why this is not a default way to start developing).

You need change `Dockerfile` and `docker-compose.yml` in the root directory and start the project with `docker-compose up --build` command ([Installation from Docker](https://docs.coralproject.net/talk/installation-from-docker/)).

Files are almost the same, except a few lines.

`Dockerfile`:
```diff
- ENV NODE_ENV production
+ ENV NODE_ENV development

- CMD ["yarn", "start"]
+ CMD ["yarn", "watch"]
```

`docker-compose.yml`:
```diff
-  image: coralproject/talk:4.5
+  build: .
+  volumes:
+    - .:/usr/src/app
```

**Comment by kartikpandey2** [comment]
@hovoodd  I tried using docker but nothing happens.
Running ` docker-compose ps`
![screenshot 104](https://user-images.githubusercontent.com/20434963/46581448-96c08e00-ca56-11e8-80c2-3f68cab9bfd4.png)
on visiting `127.0.0.1:3000` it says site can't be reached.

**Comment by hovoodd** [comment]
@kartikpandey2 Try to run `docker-compose logs -f` and read logs 😕

**Comment by jqueryisamonad** [comment]
@kartikpandey2 Did you read "Setup" section in docs? 🤔 

> With Talk running, you can now navigate to http://127.0.0.1:3000/admin/install and walk through the initial setup steps.

> During development, ensure you whitelist 127.0.0.1:3000 otherwise the http://127.0.0.1:3000/ page will not load.

**Comment by kartikpandey2** [comment]
@hovoodd  `http://127.0.0.1:3000/admin/install` it also says site can't be reached.

**Comment by jqueryisamonad** [comment]
@kartikpandey2 Maybe logs can help `docker-compose logs -f` 😕

**Comment by fabianmarz** [comment]
@kartikpandey2, what's the issue with the first screenshot? Did you set up the `.env` file properly? As the `TALK_ROOT_URL` you can also try `localhost:3000` if `127.0.0.1:3000` is not working for you.

**Comment by kartikpandey2** [comment]
@fabianmarz  actually issue is on running `yarn watch:server`  nodemon says `[nodemon] clean exit - waiting for changes before restart` and this makes server stop I tried visiting localhost:3000 it says
`site can't be reached`. 
I tried replacing `127.0.0.1:3000` with `localhost:3000` still not working.

**Comment by wyattjoh** [comment]
When you run `yarn start:development`, what's your output @kartikpandey2?

**Comment by kartikpandey2** [comment]
@wyattjoh  output  of `yarn start:development`
![screenshot 111](https://user-images.githubusercontent.com/20434963/46829512-a247e800-cdbb-11e8-909e-7dd37385fa4e.png)

**Comment by wyattjoh** [comment]
If you have installed Talk via the Docker route (as you linked above, and by your image with the Docker output saying that MongoDB + Redis do not have their ports exposed to your host), then you cannot run `yarn watch`.

If you want to install via source, I'd recommend running: 

```bash
docker run -p 127.0.0.1:6379:6379 -d redis
docker run -p 127.0.0.1:27017:27017 -d mongo
```

To start an instance of Mongo + Redis that are exposed.

Also ensure that you have at least version 8 of Node installed.

**Comment by kartikpandey2** [comment]
node -v  `v8.11.4`
i also tried this
![screenshot 112](https://user-images.githubusercontent.com/20434963/46832339-657fef00-cdc3-11e8-8715-8d6282fd51d1.png)

**Comment by wyattjoh** [comment]
Unofficially, we don't support Windows as a development target, and we haven't experienced this issue before here. Can you see if the issue is replicated when using on a Linux box? You can do so pretty easily via Vagrant.

**Comment by oafx** [comment]
I have solved this issue with windows by modifying the run configs in the package.json to use cross-env (to set the env vars) and rimraf (instead of rm) maybe not a clean solution but pretty simple and it works for me

**Comment by wyattjoh** [comment]
Sounds great! We've experienced issues our side during development with cross-env, but I'm glad it solved your issue!

**Comment by oafx** [comment]
hey @wyattjoh would you mind sharing what kind of issues you encountered when working with cross-env?

**Comment by wyattjoh** [comment]
I can't recall specifically, but I believe it was related to the way `cross-env` was forking which caused some of our watcher scripts to fail under some situations.

**Comment by jqueryisamonad** [comment]
@wyattjoh hi, why not just use `docker-compose` for development?

**Comment by brvaland** [comment]
> I have solved this issue with windows by modifying the run configs in the package.json to use cross-env (to set the env vars) and rimraf (instead of rm) maybe not a clean solution but pretty simple and it works for me

@oafx - I am struggling to build docker image for local development on Windows 10 and getting error as below:-
`$ npm-run-all clean generate-introspection
$ rm -rf dist client/coral-framework/graphql/introspection.json docs/source/_data/introspection.json
$ WEBPACK=TRUE NODE_ENV=test ./scripts/generateIntrospectionResult.js
': No such file or directory
error Command failed with exit code 127.`

Are you able to share copy of package.json file ?

**Comment by oafx** [comment]
hi @brvaland,

sorry I was on vacation :) you did manage it by now by yourself, right?

**Comment by brvaland** [comment]
@oafx - still having issue with building docker image on windows 10 with cross-env or without it. did you manage to build docker on windows ? I have pushed all to my repo if you have a chance let me know what i might be missing.

https://github.com/brvaland/talk

**Comment by brvaland** [comment]
@oafx - let me know if you find any issue with my repo.
