### ISSUE TITLE
Comments Mod: Edit comment with admin rights

### ISSUE THREAD

**Issue by himynameissebbo** [coralproject/talk#1978]
#### Do you want to request a **feature** or report a **bug**?
question

### Question
Is it somehow possible out-of-the-box that comments are edited by Admins afterwards? 

So the use case would be that a user adds a comment with malicious content and the Admin team wants to set a note to this comment that it has been edited by an Admin because it's violates the rules.

We're currently already using the pre-mod feature but this would be a further use case.

Any hints are greatly appreciated. Thanks a lot!

#### Version and environment
4.6.2, Docker

**Comment by kgardnr** [comment]
Hi @himynameissebbo! No, we would never allow admins to change the content of a comment.

Why wouldn't you want to remove the comment that violates the rules by rejecting it? You can also Suspend and/or Ban the user - and then the Admin can write a note that is emailed to them (if you have SMTP setup), that explains that they have violated the rules.
