### ISSUE TITLE
Question: Directions for Plugin to display message if user has no displayname set

### ISSUE THREAD

**Issue by oafx** [coralproject/talk#1981]
#### Do you want to request a **feature** or report a **bug**?

question

## Question

Hello,

the site we're trying to include with talk uses an external user database where a displayname isn't mandatory. We solved adding the users via the tokenUserNotFound hook, as described in the docs. We'd now like to notify the user (via some kind of html element or a modal box) that he has to set a displayname in his profile settings to be able to comment. Is there a way to solve this via plugins and some kind of documentation on how to do this? I'd be very grateful for some directions. Thanks a lot!

Kind regards
Christian

#### Version and environment
v4.6.4, Docker

**Comment by wyattjoh** [comment]
You can take a look at the code that we currently use in our auth plugin: https://github.com/coralproject/talk/blob/master/plugins/talk-plugin-auth/client/stream/containers/SetUsernameDialog.js which you can adapt to a plugin of your own design!

Hope that helps!

**Comment by oafx** [comment]
Thanks! I'll have a look
