### ISSUE TITLE
How does scraping work with docker?

### ISSUE THREAD

**Issue by freder** [coralproject/talk#1995]
I have talk running in a docker container. since I don't intend to use the embed, I am developing a custom UI against the talk graphql API. (using talk "headlessly" if you will.)

with the dockerized talk instance not being able to access "the outside world", scraping obviously does not work. assets can be created through the API, but the only information that gets stored that way is `id` and `url`, which is why in the admin essential data is missing.

![image](https://user-images.githubusercontent.com/724844/47017752-5dbda300-d153-11e8-973e-e5518e859c50.png)

I think there should be a way to set _all_ fields through the API only (as in an `updateAsset` mutation), without having to rely on the scraper. – or am I missing s.th.?

**Comment by freder** [comment]
oh, and assets created through the API can be queried directly by their id, but they won't show up in `assets`. is that expected  behavior?

```graphql
  assets(query: {}) {
    nodes {
      id
    }
  }
  
  asset(id: "5a21d624-6409-48af-88d2-02547007f72f") {
    id
    url
    title
    comments(query: {}) {
      nodes {
        id
      }
    }
  }
}
```

↓

```json
{
  "data": {
    "assets": null,
    "asset": {
      "id": "5a21d624-6409-48af-88d2-02547007f72f",
      "url": "http://localhost:3000/comments",
      "title": null,
      "comments": {
        "nodes": [
          {
            "id": "c56747ed-c653-4507-b416-bc79d383e354"
          }
        ]
      }
    }
  }
}
```

**Comment by wyattjoh** [comment]
Few things here!

> with the dockerized talk instance not being able to access "the outside world", scraping obviously does not work. assets can be created through the API, but the only information that gets stored that way is id and url, which is why in the admin essential data is missing.

Currently, Talk performs scraping when it gets the URL for the asset by loading the HTML of the page itself. We have plans in Talk v5 to expose those mutations to ensure you can do as much as you can via the GraphQL API.

In Talk v4, we only exposed the bare minimum that our embed needed to load, favoring instead the use of [server plugins](https://docs.coralproject.net/talk/api/server/) to extend the api for what the organization or user needed.

> oh, and assets created through the API can be queried directly by their id, but they won't show up in assets. is that expected behavior?

It actually would be created in the `assets` edge, but that edge requires an admin token! We detail lots of the permissions quite differently then we're planning to in v5, but you can see the gist of those permissions here: https://github.com/coralproject/talk/blob/master/perms/reducers/query.js

For now, we aren't planning on adding new features to v4 outside of external contributions, as we're focused on getting v5 out.

**Comment by freder** [comment]
thanks @wyattjoh – that clarifies things!

I did in fact end up implementing a custom mutation in a server plugin for now 👍

**Comment by brvaland** [comment]
@freder - I am newbie to talk and server plugin so are you able to share code snippet for custom mutation for asset creation.

**Comment by wyattjoh** [comment]
Take a look here @brvaland: https://docs.coralproject.net/talk/integrating/cms-integration/
