### ISSUE TITLE
Don't mix camel and snake case

### ISSUE THREAD

**Issue by freder** [coralproject/talk#1996]
![image](https://user-images.githubusercontent.com/724844/47019975-9c099100-d158-11e8-8388-949f39a5a4b6.png)

**Comment by kgardnr** [comment]
Hey @freder, we probably won't address this but you're welcome to submit a PR if you'd like!

**Comment by kgardnr** [comment]
hey @freder, this is addressed in v5! Check it out and let us know what you think, you can see v5 in the `next` branch currently 🎉
