### ISSUE TITLE
API: There should be a `createAsset` mutation

### ISSUE THREAD

**Issue by freder** [coralproject/talk#1998]
I find it a bit counterintuitive that the `asset` query is used for retrieving existing but also creating new assets. wouldn't it make sense to have a separate `createAsset` mutation?

that mutation could also accept optional arguments like `title`, etc. (related to #1995)

**Comment by wyattjoh** [comment]
As mentioned in #1995, we have no plans currently to bring this feature to v4, but will provide it in v5.

If you would like to add support for v4, we would welcome a PR adding the support!
