### ISSUE TITLE
Error/data monitoring

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2000]
We are wanting to integrate error monitoring into the Talk application. We use BugSnag and DataDog throughout our technology stack for error and data reporting, like exception notifications.

Two examples:
- Every exception should be reported to bugsnag so our on call tech can diagnose the issue
- When a comment is added to a moderation queue, we send data to DataDog so we can generate alerts if the moderation queue gets too large

What is the recommended way to integrate reporting of this kind into the application, with the understanding that we will be using the docker onbuild method during our deployment process.

**Comment by kgardnr** [comment]
Hey @lriggle-strib! We have info on this here: https://docs.coralproject.net/talk/integrating/event-tracking-metrics/

And we've known several orgs who have integrated with DataDog.

You can also see an example plugin we built for Prometheus here: https://github.com/coralproject/talk-plugin-prom

**Comment by lriggle-strib** [comment]
@kgardnr So far we've only seen examples of the events in the front-end. Can they be integrated into a back end plugin in the same way?

**Comment by wyattjoh** [comment]
Related to your question about errors, Talk v4 doesn't natively support error handlers, but it does emit logs with [bunyan](https://github.com/trentm/node-bunyan), which has a compatible bugsnag stream:

```js
const { logger } = require('services/logging');
const bunyanBugsnag = require('bunyan-bugsnag');
const bugsnag = require('bugsnag');

// Register the bugsnag key.
bugsnag.register('your-bugsnag-api-key');

const stream = bunyanBugsnag({
  bugsnag,
});

// Add the stream that will send all the application error messages off to
// bugsnag.
logger.addStream({
  type: 'raw',
  level: 'warn',
  stream,
});

module.exports = {
  app: () => {
    // Specifying this hook ensures that we will get loaded early.
  },
};
```

Take a look at the [Prometheus plugin](https://github.com/coralproject/talk-plugin-prom) to create a plugin for your provider.

**Comment by lriggle-strib** [comment]
@wyattjoh `bugsnag` and `bunyan-bugsnag` aren't default yarn packages within the Talk application (obviously), and `yarn plugins:reconcile` doesn't add those packages in (also, obviously). Is adding additional yarn packages to the application something that will maintain in the docker environment? Is it just a matter of also specifying the `packages.json` file along with the `plugins.json` file?

**Comment by wyattjoh** [comment]
As per the documentation on [external dependencies](https://docs.coralproject.net/talk/plugins/#plugin-dependencies) you would need to create a folder like `talk-pluigin-bugsnag` that contains a `package.json` containing at least:

```json
{
  "name": "talk-plugin-bugsnag",
  "dependencies": {
    "bugsnag": "^2.4.3",
    "bunyan-bugsnag": "^2.0.0"
  }
}
```

**Comment by lriggle-strib** [comment]
Perfect, thanks!!
