### ISSUE TITLE
JWT Token with base64 encoded secret

### ISSUE THREAD

**Issue by oafx** [coralproject/talk#2002]
#### Do you want to request a **feature** or report a **bug**?
basically a **question** but maybe a **feature** request?  

#### Intended outcome:
due to some kind of tech lock-in i'm currently trying to use a JWT Token that uses a base64 encoded secret (for reference see https://jwt.io/)

#### Actual outcome:
seems impossible. i'm looking for some kind of configuration option that woult take the supplied TALK_JWT_SECRET var and decode it to verify the token. It doesn't seem to be possible to set the TALK_JWT_SECRET var as the manually decoded secret.

#### How to reproduce the issue:
- build a jwt token that uses a base64 encoded secret
- try to verify the token with talk

#### Version and environment
4.6.4 docker

--- 
### original message
https://community.coralproject.net/t/jwt-token-with-base64-encoded-secret/994

Hello everyone,

is there a configuration option to verify the JWT Token with a base64 encoded secret like it is done at jwt.io
It appears I can’t just encode the secret beforehand and set the TALK_JWT_SECRET var to the encoded string.
Would be great if there is some kind of boolean configuration option that I don’t know of that would let me use the plain secret for TALK_JWT_SECRET. Is this possible in some kind of way?

Thanks for the help!
Christian

**Comment by wyattjoh** [comment]
Unfortunately, Talk does not support accepting a base64 encoded secret at this time.

In Talk v5, we'll likely plan to add support for it.

We'd welcome a contribution in the form of a pull request that accepted secrets in a base64 encoded form if the secret itself began with `base64:<my encoded secret>`!

**Comment by oafx** [comment]
hi @wyattjoh!

i'm not very familiar with nodejs coding style/standards but i'd be happy to contribute/open a pull request and to learn **if** you or other talk devs are okay with the possibility of some extra time spent in the case my pr isn't satisfying your quality standards.

Christian

**Comment by wyattjoh** [comment]
After taking a look at the code, it didn't take too long, so I hope you don't mind that I submitted a PR already that will address this in Talk's next release!

See: https://github.com/coralproject/talk/pull/2007

**Comment by kgardnr** [comment]
Addressed in #2007
