### ISSUE TITLE
Unable to remove email subject prefix

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2009]
#### Do you want to request a **feature** or report a **bug**?
Bug

#### Intended outcome:
Set an empty value for `TALK_EMAIL_SUBJECT_PREFIX` so nothing is prepended to email subjects.

#### Actual outcome:
If the var has no value, the default prefix is used (`[Talk]`). If quotes are used to denote an empty string, the quotes end up in the subject.

#### How to reproduce the issue:
Set the `TALK_EMAIL_SUBJECT_PREFIX` env var to each value and then trigger the application to send an email, like suspending a user:
* `TALK_EMAIL_SUBJECT_PREFIX=`
* `TALK_EMAIL_SUBJECT_PREFIX=''`
* `TALK_EMAIL_SUBJECT_PREFIX=""`

<img width="277" alt="screen shot 2018-10-19 at 8 48 02 am" src="https://user-images.githubusercontent.com/7051012/47222330-12d2a400-d37c-11e8-8ae8-29943a35340f.png">

#### Version and environment
4.6.4, but we will be upgrading to 4.6.5 soon.

**Comment by wyattjoh** [comment]
Can you take a look at the #2011 PR? That should resolve the issue!
