### ISSUE TITLE
Feature: Make username change backoff configureable.

### ISSUE THREAD

**Issue by leonkunert** [coralproject/talk#2021]
#### Do you want to request a **feature** or report a **bug**?
**Feature**:
We would like to be able to change the 14 day backoff for changing the username via env var.

#### Intended outcome:
The ability to change the username more or less frequently.

#### Actual outcome:
The username can only be changed every 14 days.

#### How to reproduce the issue:
Try to change the username more than once a day.

#### Version and environment
4.6.5

**Comment by kgardnr** [comment]
Hi @leonkunert, we won't be adding this as a feature - we decided on 14 days as we explicitly do not want to encourage username changes that could be leveraged to intimidate or harass other users. 

We feel 14 days gives enough of a time period to discourage changing a username to be malicious, but still accounts for a user's want or need to change their username.

Thank for taking the time to suggest this though!
