### ISSUE TITLE
Changing username with graphql

### ISSUE THREAD

**Issue by plexdk** [coralproject/talk#2026]
HI,

We are a newspaper located in denmark, providing both print and online news
We are providing an admin page for the user, where they can control their various subscription options and settings - and hereby also comment settings. That means we want to be able to change the users username (displayed in comments), by doing a graphql call, when they change their nickname on the newspapers settings page.

When I try to call a changeUsername() on another user, with an admin user’s token, i get NOT_AUTHORIZED.

I found the following line of code in the source:
if (user.status.username.status !== ‘REJECTED’) {
throw new ErrPermissionUpdateUsername();
}

So I guess its not possible to change the username unless its rejected? Do you have any other suggestions?

Please notice that we use an auth token plugin, for external authentication.

**Comment by plexdk** [comment]
Found another issue with answer. closing

**Comment by fabianmarz** [comment]
@plexdk, could you please link the other issue to help other people finding the solution faster? 😃
