### ISSUE TITLE
Add support to Slack plugin to send Featured Comments to a Slack channel

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#2029]
Idea from nu.nl:
- Ability to send Featured Comments to a specific Slack channel
- Should show new comments once they're Featured
- This is to show others in the newsroom what the best comments are

**Comment by LS05** [comment]
Can I work on this? :)

**Comment by kgardnr** [comment]
Yes please do!

**Comment by LS05** [comment]
@kgardnr Sorry but I can't install Docker on my machine. I don't is convenient to work without Docker :/

**Comment by lytvynenko** [comment]
Hi @kgardnr. Looks like @LS05 is experiencing some issue with initial setup, so i've decided to jump a gun and create a plugin for this use case. You can find code here: https://github.com/lytvynenko/talk-plugin-slack-notifications-category-featured.

**Comment by kgardnr** [comment]
Thank you again @lytvynenko!
