### ISSUE TITLE
If a user has no comments and clicks settings, the loading message persists

### ISSUE THREAD

**Issue by jde** [coralproject/talk#203]
### Expected behavior

If a user has no messages, we should say something along the lines of "You have not commented."

### Actual behavior

Loading message persists.
![unspecified](https://cloud.githubusercontent.com/assets/259957/21457851/4eb48fde-c900-11e6-8522-5dc8a3f17977.png)

### Steps to reproduce behavior

Create a new user (or login as a user who hasn't commented)
Click 'Settings'

**Comment by jde** [comment]
@losowsky, what message should we show when a user has no comments? Or should we leave the area blank?

**Comment by losowsky** [comment]
"You have not yet left a comment"
or "This user has not yet left a comment"
