### ISSUE TITLE
Flag a user to be "Always premoderate their comments"

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#2030]
Idea from nu.nl
- Should be added as an option in Suspend/Ban user drop down
- Once selected, that user's comments should always go to Pre-Mod queue for action before posting on the site
- Status should be removeable by deselecting the option in the drop down

**Comment by vipulbhj** [comment]
Hii, can I take this one ?

**Comment by losowsky** [comment]
Go for it! Thanks Vipul!

**Comment by gerardogalvez** [comment]
@vipulbhj are you looking into this? If not, can I take it?

**Comment by vipulbhj** [comment]
Actually I am not at the moment. So you can take it

**Comment by gerardogalvez** [comment]
@kgardnr I think this issue can be closed now that #2145 is merged.
