### ISSUE TITLE
DisplayName not working - username is still displayed instead 

### ISSUE THREAD

**Issue by mankee10200** [coralproject/talk#2031]
#### Do you want to request a **feature** or report a **bug**?
bug

#### Intended outcome:

Have the displayName be displayed instead of the username. 

#### Actual outcome:

I'm trying to integrate talk into my site and one of my requirements is that the username seen on screen has spaces in it. I've tried doing this through the "username" field, however it does not permit spaces. As an alternative, I've added the displayName field as follows: 

metadata: {            displayName: data.displayName          },
however, I still see the username instead of the displayName on screen, similarly as described in the below post: 

https://github.com/coralproject/talk/issues/1863

The proposed solution in the github issue of using the username instead does not work for me as it does not permit spaces.

**Comment by lytvynenko** [comment]
We've ended up with custom plugin for this case: https://github.com/lytvynenko/talk-plugin-display-name

**Comment by AuroraEscapes** [comment]
When we added this plugin and made these changes we noticed updates to the user are not be saved. The viewing options still work but users can no longer save their notification preferences. @lytvynenko have you experienced this?
