### ISSUE TITLE
Including placeholder twice in Rich Text Plugin

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2034]
#### Do you want to request a **feature** or report a **bug**?
bug

#### Actual outcome:
In the Editor component of the rich text plugin, the placeholder value is being included twice:

* https://github.com/coralproject/talk/blob/master/plugins/talk-plugin-rich-text/client/components/Editor.js#L112
* https://github.com/coralproject/talk/blob/master/plugins/talk-plugin-rich-text/client/components/Editor.js#L122

I don't know that this is causing any actual behavioral issues, but my IDE sure doesn't care for it.

**Comment by kgardnr** [comment]
Hey @cvle could you take a look?
