### ISSUE TITLE
Object doesn't support property or method 'forEach'

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2037]
#### Do you want to request a **feature** or report a **bug**?
bug

#### Intended outcome:
Use the Talk admin

#### Actual outcome:
* Unable to use the moderate portion admin - spinny wheel
* Unable to use any of the admin - spinny wheel (intermittent)

#### How to reproduce the issue:
I've experienced this issue in:
* Chrome (not lately)
* IE 11 (100% of the time)

I was experiencing this with chrome for about a month, I would be unable to use the admin in that browser and had to switch to a different browser. I haven't experienced this lately, so I'm not sure what triggered it to finally start working.

As we get closer to launch, we've started testing in all browsers we support on our site:
* Chrome (Mac, PC)
* Firefox (Mac, PC)
* Safari (Mac)
* Microsoft Edge (PC)
* Internet Explorer 11 (PC)

And consistently, 100% of the time, we are still seeing this error in IE 11. 

#### Version and environment
Talk v4.6.5

**Comment by kgardnr** [comment]
Hey @lriggle-strib I'm trying to replicate this and I just can't seem to - could you provide some more info on the OS version/etc where you're seeing this? Is this a virtual machine or an actual computer? Have you had more than one person experience this? Thank you so much - I'm truly stumped!

**Comment by kgardnr** [comment]
@lriggle-strib and can you confirm you're not seeing this at all on any of the latest versions of Edge?

**Comment by lriggle-strib** [comment]
@kgardnr Here is some additional info:

* Windows 10: v.1709 (16299.726)
   * IE 11
      * Version: 11.726.16299.0
      * Screenshot: <img width="796" alt="2018-10-30 14_22_48-slack - star tribune" src="https://user-images.githubusercontent.com/7051012/47745172-0fc79580-dc51-11e8-8def-dc6cc4b882cf.png">
   * Edge
      * Version: 41.16299.726.0
      * This worked successfully, so I did not grab a screenshot of it

Our IT department has the Windows laptops locked down pretty hard, so we have to wait on them to push updates to the machines rather than being able to go and update them.

If you want the computer make/model I can provide that too. It is a physical machine, not a VM.

Also, yes, we've had multiple people experience it. Everyone here on a Windows 10 machine experiences this problem when using IE.

**Comment by immber** [comment]
Added to PivotalTracker #161655050
