### ISSUE TITLE
Save button for notification preferences

### ISSUE THREAD

**Issue by AuroraEscapes** [coralproject/talk#2040]
#### Do you want to request a **feature** or report a **bug**?
feature

#### Story:
When a user edits settings in their user profile in Talk it isn't obvious they have been saved. or that there isn't something else the user needs to do. 
The admin console has a save button for some features - the behavior can be a bit confusing

**Comment by kgardnr** [comment]
Hey @AuroraEscapes, we're going to make this functionality consistent across the board in our v5. We don't have plans to update this on our side, but folks are welcome to submit a PR if they'd like, so I'll keep this Issue open 😄 thank you!

**Comment by kgardnr** [comment]
This is addressed in v5
