### ISSUE TITLE
Can't run project from source code or docker on Windows 10 x64

### ISSUE THREAD

**Issue by thiennhank9** [coralproject/talk#2041]
#### Do you want to request a **feature** or report a **bug**?
This is a BUG.

#### Intended outcome:

Environment: Windows 10 - 64 bits.
I cloned this source code from "master" branch. Then I build image by docker with below cmd:
`
docker build -t coral2 .
`
It should be worked properly. But it failed to errors.

#### Actual outcome:

Errors below:
----
Done in 63.39s.
yarn run v1.9.4
$ npm-run-all clean generate-introspection
$ rm -rf "dist"
$ WEBPACK=TRUE NODE_ENV=test ./scripts/generateIntrospectionResult.js
': No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "generate-introspection" exited with 1.
error Command failed with exit code 1.
----

You can check my full logs here: 
----
Sending build context to Docker daemon  4.841MB
Step 1/12 : FROM node:8-alpine
 ---> df48b68da02a
Step 2/12 : RUN mkdir -p /usr/src/app
 ---> Using cache
 ---> 0822e1b71fd5
Step 3/12 : WORKDIR /usr/src/app
 ---> Using cache
 ---> ab2c0fe71c40
Step 4/12 : ENV PATH /usr/src/app/bin:$PATH
 ---> Using cache
 ---> 6e3d39e91ee3
Step 5/12 : ENV TALK_PORT 5000
 ---> Using cache
 ---> 948a2841810a
Step 6/12 : EXPOSE 5000
 ---> Using cache
 ---> 30b3134e10dd
Step 7/12 : COPY . /usr/src/app
 ---> 2c148d18779e
Step 8/12 : ENV NODE_ENV production
 ---> Running in 0ccf6a968b23
Removing intermediate container 0ccf6a968b23
 ---> 63760cdfcac1
Step 9/12 : ARG REVISION_HASH
 ---> Running in 0aa9d4b0012c
Removing intermediate container 0aa9d4b0012c
 ---> b0e3b52c86e7
Step 10/12 : ENV REVISION_HASH=${REVISION_HASH}
 ---> Running in d9b144665716
Removing intermediate container d9b144665716
 ---> 21b8a9a0db4f
Step 11/12 : RUN yarn global add node-gyp &&     yarn install --frozen-lockfile &&     yarn build &&     yarn cache clean
 ---> Running in 379acbe4b22c
yarn global v1.9.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "node-gyp@3.8.0" with binaries:
      - node-gyp
Done in 4.68s.
yarn install v1.9.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > hjson-loader@1.0.0" has incorrect peer dependency "hjson@^1.7.4".
warning "react-apollo > enzyme-adapter-react-16@1.1.1" has incorrect peer dependency "react@^16.0.0-0".
warning "react-apollo > enzyme-adapter-react-16@1.1.1" has incorrect peer dependency "react-dom@^16.0.0-0".
warning "react-apollo > enzyme-adapter-react-16 > react-reconciler@0.7.0" has incorrect peer dependency "react@^16.0.0".
warning "react-apollo > enzyme-adapter-react-16 > react-test-renderer@16.4.0" has incorrect peer dependency "react@^16.0.0".
warning " > react-paginate@5.2.3" has incorrect peer dependency "react@^16.0.0".
[5/5] Building fresh packages...
Done in 63.39s.
yarn run v1.9.4
$ npm-run-all clean generate-introspection
$ rm -rf "dist"
$ WEBPACK=TRUE NODE_ENV=test ./scripts/generateIntrospectionResult.js
': No such file or directory
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "generate-introspection" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn global add node-gyp &&     yarn install --frozen-lockfile &&     yarn build &&     yarn cache clean' returned a non-zero code: 1
----

#### How to reproduce the issue:

Using environment Windows 10 x64
Then clone this project from "master" branch.
Ensure installed Docker (Linux container) and Docker is running.
Cd to project's location, then type in cmd:
`docker build -t coral2 .`
#### Version and environment

Latest version of Coral-talk from github - date 10/27/2018.
OS: Windows 10 x64

**Comment by oafx** [comment]
you might want to take a look here: https://github.com/coralproject/talk/issues/1974

while it is stated there that windows as development target isn't officially supported, you might have luck with cross-env and rimraf as described there. Well this doesn't explain why your docker container is failing but maybe try a release tag instead of the master/HEAD?

hope it helps :)

**Comment by brvaland** [comment]
@thiennhank9 - I am getting exactly same error, did you manage to resolve ?

**Comment by immber** [comment]
I've seen this error on mac when using a different version of node. Are you using node Node 8?

**Comment by brvaland** [comment]
@immber - The node version i am using is v10.11.0. Do i have to use Node 8 ?

**Comment by immber** [comment]
@brvaland If you try it with 8.0.0 I suspect you'll have better luck! I also recommend trying nvm if you're not using it already.

**Comment by brvaland** [comment]
Thanks - I am using nvm and tried to get v8.15.1 but still facing the same error. 

I have updated package.json and updated docker-compose and docker file as per https://github.com/coralproject/talk/issues/1974 but now getting error and container keep restarting.

`talk_1   | yarn run v1.12.3
talk_1   | error Couldn't find a package.json file in "/usr/src/app"`

Package.json updated as below
From
`"generate-introspection": "WEBPACK=TRUE NODE_ENV=test ./scripts/generateIntrospectionResult.js",`
`"clean": "rm -rf dist client/coral-framework/graphql/introspection.json docs/source/_data/introspection.json",`
`"build": "NODE_ENV=production parallel-webpack --bail",`

To
`    "generate-introspection": "set WEBPACK=TRUE set NODE_ENV=test ./scripts/generateIntrospectionResult.js",`
`"clean": "rimraf -rf dist client/coral-framework/graphql/introspection.json docs/source/_data/introspection.json",`
`"build": "set NODE_ENV=production parallel-webpack --bail",`

**Comment by immber** [comment]
> I have updated package.json and updated docker-compose and docker file as per #1974 but now getting error and container keep restarting.

Are you trying to run Talk from source, or from docker?

You shouldn't have both a `docker-compose` and a `dockerfile`. If you're running from docker, you should either be using `docker-compose` or using our `onbuild` images and docker strategy as outlined in our docs  https://docs.coralproject.net/talk/installation-from-docker/

You also shouldn't need to edit package.json unless you're specifically accounting for the Windows issue described in #1974 .

**Comment by brvaland** [comment]
I want to run from source via docker. I got Windows 10 machine, so
basically I cloned master branch and updated Dockerfile and added
docker-compose as #1974.

Then I run the command docker-compose build but got error no such file or
directory.

After that I updated package.json and allowed me to build but now error and
container restarting.

How can I run Talk from source on Windows 10.


Sent from my iPhone

On 5 Apr 2019, at 19:07, immber <notifications@github.com> wrote:

I have updated package.json and updated docker-compose and docker file as
per #1974 <https://github.com/coralproject/talk/issues/1974> but now
getting error and container keep restarting.

Are you trying to run Talk from source, or from docker?

You shouldn't have both a docker-compose and a dockerfile. If you're
running from docker, you should either be using docker-compose or using our
onbuild images and docker strategy as outlined in our docs
https://docs.coralproject.net/talk/installation-from-docker/

You also shouldn't need to edit package.json unless you're specifically
accounting for the Windows issue described in #1974
<https://github.com/coralproject/talk/issues/1974> .

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/coralproject/talk/issues/2041#issuecomment-480370797>,
or mute the thread

**Comment by wyattjoh** [comment]
Currently, running Talk via source is not supported in Windows.

You may have luck running it via the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about), but that's not been tested.

Can you provide the exact `Dockerfile` you're using after modifications?

**Comment by brvaland** [comment]
@wyattjoh - Here is the link to files that have changed - https://github.com/brvaland/talk.

**Comment by wyattjoh** [comment]
If you want to use it like that, you'd need to clone Talk to support it, the lines:

https://github.com/brvaland/talk/blob/d0e42dbccf9809b4f46171dcdb6688945a9fae10/Dockerfile#L12-L13

Copy files from your local directory into the Docker container, hence why it's been failing, as none of the files that Talk needs are in that directory.

**Comment by brvaland** [comment]
@wyattjoh - i have cloned talk 4.8.3 but on my github repo i have only uploaded the files that i have changed for your reference, so docker container should have all the files needed.

**Comment by brvaland** [comment]
Also if i try `yarn start:development`

```
PS C:\talk> yarn start:development
yarn run v1.13.0
$ set NODE_ENV=development ./bin/cli-serve -j -w
Done in 0.15s.

```

**Comment by brvaland** [comment]
@wyattjoh - i have found some success using cross-env in package.json and talk works fine on windows using `yarn start` but unable to build docker image getting error as below. Updated files on my repo.

Docker Build Logs 

> PS C:\talk> docker build -t talk .
> Sending build context to Docker daemon   18.3MB
> Step 1/12 : FROM node:8-alpine
>  ---> ee8b4f3c67fa
> Step 2/12 : RUN mkdir -p /usr/src/app
>  ---> Using cache
>  ---> a063406f1f19
> Step 3/12 : WORKDIR /usr/src/app
>  ---> Using cache
>  ---> 4f581e7353f2
> Step 4/12 : ENV PATH /usr/src/app/bin:$PATH
>  ---> Using cache
>  ---> 8c2a1c8cbc17
> Step 5/12 : ENV TALK_PORT 5000
>  ---> Using cache
>  ---> 64e5356e77b5
> Step 6/12 : EXPOSE 5000
>  ---> Using cache
>  ---> 16f2ba8d6910
> Step 7/12 : COPY . /usr/src/app
>  ---> 8c86d8bc7c60
> Step 8/12 : ENV NODE_ENV development
>  ---> Running in 94572b18b9cc
> Removing intermediate container 94572b18b9cc
>  ---> 8b11144fac54
> Step 9/12 : ARG REVISION_HASH
>  ---> Running in 003e86205028
> Removing intermediate container 003e86205028
>  ---> af0fe4d22815
> Step 10/12 : ENV REVISION_HASH=${REVISION_HASH}
>  ---> Running in 5f1556c10657
> Removing intermediate container 5f1556c10657
>  ---> 2910e1773022
> Step 11/12 : RUN yarn global add node-gyp &&     yarn install --frozen-lockfile &&     yarn build &&     yarn cache clean
>  ---> Running in d348078a43e3
> yarn global v1.12.3
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> success Installed "node-gyp@3.8.0" with binaries:
>       - node-gyp
> Done in 4.22s.
> yarn install v1.12.3
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> info fsevents@1.2.4: The platform "linux" is incompatible with this module.
> info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
> [4/5] Linking dependencies...
> warning " > hjson-loader@1.0.0" has incorrect peer dependency "hjson@^1.7.4".
> warning "react-apollo > enzyme-adapter-react-16@1.1.1" has incorrect peer dependency "react@^16.0.0-0".
> warning "react-apollo > enzyme-adapter-react-16@1.1.1" has incorrect peer dependency "react-dom@^16.0.0-0".
> warning "react-apollo > enzyme-adapter-react-16 > react-reconciler@0.7.0" has incorrect peer dependency "react@^16.0.0".
> warning "react-apollo > enzyme-adapter-react-16 > react-test-renderer@16.4.0" has incorrect peer dependency "react@^16.0.0".
> warning " > react-paginate@5.2.3" has incorrect peer dependency "react@^16.0.0".
> [5/5] Building fresh packages...
> Done in 65.16s.
> yarn run v1.12.3
> $ npm-run-all clean generate-introspection
> $ rimraf -rf dist client/coral-framework/graphql/introspection.json docs/source/_data/introspection.json
> $ cross-env WEBPACK=TRUE NODE_ENV=test ./scripts/generateIntrospectionResult.js
> ': No such file or directory
> error Command failed with exit code 127.
> ERROR: "generate-introspection" exited with 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> The command '/bin/sh -c yarn global add node-gyp &&     yarn install --frozen-lockfile &&     yarn build &&     yarn cache clean' returned a non-zero code: 1

**Comment by oafx** [comment]
~not quite sure about this but how did you install cross-env? is it listed as dependency in your package.json or did you install it globally?~ if you keep getting errors that aren't helpful to you while building the docker container you might be more lucky running a clean node:8-alpine image attached to /bin/sh and run the commands of the dockerfile step by step manually (you need to mount the talk files into the container then)

**EDIT:** hrm, just took a look at your repo, and cross-env is listed in your package.json and yarn.lock correctly.. so i'm out of guesses right now, hehe. 

Just as a sidenote - when building the talk docker image locally, I'm building it without cross-env etc. in the package.json as @wyattjoh mentioned some problems with cross-env before.

**Comment by brvaland** [comment]
@oafx - did you manage to build and run the container without cross-env as when i change package.json file to `set` instead of `cross-env` ?

I tried and docker build works but unable to run container as it keeps restarting.
