### ISSUE TITLE
Error after installing notification plugin

### ISSUE THREAD

**Issue by leonkunert** [coralproject/talk#2059]
#### Do you want to request a **feature** or report a **bug**?
Bug

#### Intended outcome:
Installing notification plugin

#### Actual outcome:
The clientside shows an error after switching to the settings tab:
```GraphQL error: Cannot query field "notificationSettings" on type "User". GraphQL error: Cannot query field "notificationsRequireConfirmation" on type "Settings".```

#### How to reproduce the issue:
Install notifications plugin
Login with custom jwt provider
switch to settings tab

#### Version and environment
Talk 4.6.5
- NODE_ENV=development
- TALK_DISABLE_EMBED_POLYFILL=TRUE
- TALK_DISABLE_REQUIRE_EMAIL_VERIFICATIONS_NOTIFICATIONS=TRUE
- TALK_JWT_AUDIENCE=xxx
- TALK_JWT_ISSUER=xxx
- TALK_JWT_SECRET=xxx
- TALK_LOGGING_LEVEL=debug
- TALK_MONGO_URL=mongodb://mongo/talk
- TALK_PORT=3000
- TALK_REDIS_URL=redis://redis:6379
- TALK_ROOT_URL=http://127.0.0.1:3000

**Comment by wyattjoh** [comment]
In the network tab for the request, can you provide the GraphQL error in the response payload?

**Comment by leonkunert** [comment]
Ok I found the issue.
I forgot to add the plugin to the server plugins.
🙈
