### ISSUE TITLE
Query For All Users Without Admin Role

### ISSUE THREAD

**Issue by mankee10200** [coralproject/talk#2062]
#### Do you want to request a **feature** or report a **bug**?
Feature

#### Intended outcome:

Be able to query the mongoDB for all users - this is to be used within a mentions plugin where a user posting a comment can mention/tag any of the other users in the db. I found in the docs: https://docs.coralproject.net/talk/api/graphql the **UserQuery**, however it seems to require the admin role, is there a way to achieve this without this?

**Comment by wyattjoh** [comment]
You could write a plugin that exposes exactly the results you would like, but for privacy reasons, we don't want to expose that permission on the public graph API. That way in your custom plugin, you could write a handler/route that uses the system context to execute the query, which will have permission to do so.
