### ISSUE TITLE
How to add an additional field to embed stream

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2063]
For this particular implementation, I need to add an additional text field that will store a value in the metadata of the comment, and then display it on the comment once it's been saved.

In my plugin I can do the following:
- Create a text field that displays in the embed stream
- Save a static value to the comment's metadata

What I can't do:
- Include the value in the text field on the form submission so it can be saved instead of the static value

What I haven't attempted yet:
- Display the metadata value on the comment in the stream
- Edit the metadata value when the comment is edited

I've tried using a few slots to see if my field will submit, including `commentInputDetailArea`, `draftArea`, and `stream` but the slot I choose doesn't seem to make a difference. Whatever value I put in this text field just doesn't seem to be included in the input object and I'm not sure why.

There isn't much in the way of documentation for this kind of customization, nor are there any plugins that I'm finding that are doing something like this, so I don't really have much to go on.

**Comment by wyattjoh** [comment]
This particular feature you're working on unfortunately has a lot of steps necessary to implement. In order to protect the API from undesired random input, we implemented strict schemas on input/output serialization to ensure that only the fields recognized would be able to pass through to the data layer.

That being said, it is still _possible_ to implement, just complex.

1. Extend `CreateCommentInput` with the custom field
2. Add desired input Ffeld to `draftArea` Slot which passes a `onInputChange` prop
3. Use `onInputChange` to set custom data to send with the mutation
4. Add hook to server to add the new custom data to metadata
5. Add field to graphql and extend Comment type with new field so it can be queried
6. Adapt Comment resolver to expose the new field from the metadata
7. Ask for the new field with a fragment container in a comment slot and render it
8. Adapt all optimistic responses and mutations to handle the new field otherwise it’ll just crash

Unfortunately, this is getting into quite deep territory, and we don't have any working examples of implementing such a feature at this time.

**Comment by lriggle-strib** [comment]
@wyattjoh Ok, that gets me started in the right direction. It looks like the Rich Text Editor plugin actually does something similar. I've got all the pieces in place, but the part I'm getting hung up on right now is actually getting the value into `onInputChange`.

Here's what the rich text plugin is doing:
https://github.com/coralproject/talk/blob/master/plugins/talk-plugin-rich-text/client/components/Editor.js#L17-L22

```javascript
  handleChange = c => {
    this.props.onInputChange({
      body: c.text,
      richTextBody: c.html,
    });
  };
```

When I try and do something similar it fails:

```javascript
  handleChange = c => {
    this.props.onInputChange({
      displayName: c.text,
    });
  };
```

with this error:
```
GraphQLError: Variable "$input" got invalid value {"asset_id":"f58c2d9d-9131-4c41-8470-943cf58c173e","body":"post a comment 4","tags":[],"richTextBody":"post a comment 4","checkSpam":true,"checkToxicity":true}.
In field "displayName": Expected "String!", found null.
```

But when I do this it works:

```javascript
  handleChange = c => {
    this.props.onInputChange({
      displayName: 'abcdefg',
    });
  };
```

I don't seem to be able to do any kind of console.log on the value of `c`, so I can't actually figure out what's in that object before I try and put a value in display name.

Here's the full js of the component:

```javascript
import React from 'react';
import PropTypes from 'prop-types';
import styles from './DisplayNameTextField.css';
import cn from 'classnames';
import TextField from 'coral-ui/components/TextField';
import { t } from 'plugin-api/beta/client/services';

class DisplayNameTextField extends React.Component {
  handleChange = d => {
    this.props.onInputChange({
      displayName: d.target.value,
    });
  };

  render() {
    const PLUGIN_NAME = 'strib-plugin-display-name';
    const value = this.props.input.displayName;

    return (
      <div className={cn(styles.root, `${PLUGIN_NAME}-container`)}>
        <label
          htmlFor={`displayName`}
          className="display-name-text"
          aria-hidden={true}
        >
          {t('comment.display_name_label')}
        </label>
        <TextField
          id={`displayName`}
          className={`${PLUGIN_NAME}-text`}
          placeholder={t('comment.display_name')}
          value={value}
          onChange={this.handleChange}
        />
      </div>
    );
  }
}

DisplayNameTextField.propTypes = {
  id: PropTypes.string,
  label: PropTypes.string,
  input: PropTypes.object,
  onInputChange: PropTypes.func,
  comment: PropTypes.object,
  isReply: PropTypes.bool,
  isEdit: PropTypes.bool,
};

export default DisplayNameTextField;
```

**Comment by wyattjoh** [comment]
If you're building Talk with the `onbuild` images, it is likely stripping the console.log out. To override it, you can instead write`window.console.log` and it should work. We use something similar to send some important messages to the console relating to error.s

**Comment by lriggle-strib** [comment]
Cool that helps. It looks like I'm unable to set data for `onInputChange` because no data is getting sent to it. I'm missing *something* in my plugin, but I'm not sure what.

Rich Text `onInputChange`:
<img width="449" alt="screen shot 2018-11-05 at 12 18 57 pm" src="https://user-images.githubusercontent.com/7051012/48018175-c9ad7e80-e0f5-11e8-9c50-8dce00f39882.png">

My plugin `onInputChange`:
<img width="986" alt="screen shot 2018-11-05 at 1 20 49 pm" src="https://user-images.githubusercontent.com/7051012/48021267-ba323380-e0fd-11e8-9e96-dbe5c7c45d26.png">

**Comment by lriggle-strib** [comment]
@wyattjoh Thanks, this got me really far. My field submits and saves into the database. Yay! What I'm not seeing, however, is the submit behavior that applies to the comment box also applying to my field.

For example, when you submit the form, the comment box changes in appearance and then clears the value so it's ready for the next comment. I haven't been able to figure out what I can use to hook into that for my text field.

------

I also noticed that if I don't have the Rich Text plugin activated, there is no comment box when my plugin is activated. Is that expected behavior?

With RTE: 
<img width="682" alt="screen shot 2018-11-06 at 1 01 40 pm" src="https://user-images.githubusercontent.com/7051012/48087212-5e7ead80-e1c4-11e8-9c06-09c770fa71d1.png">

Without RTE:
<img width="674" alt="screen shot 2018-11-06 at 1 03 00 pm" src="https://user-images.githubusercontent.com/7051012/48087216-62aacb00-e1c4-11e8-94e0-508381b79a17.png">

**Comment by marykenefick** [comment]
@wyattjoh - wondering if you or maybe @kgardnr have any thoughts on the behavior that Lisa is seeing with the new field she's trying to add in?

**Comment by kgardnr** [comment]
@marykenefick and/or @lriggle-strib is this for your Obituaries comment section?

**Comment by marykenefick** [comment]
Hey Kim - Yes, this is for Obits.
