### ISSUE TITLE
Make Talk AMP compatible

### ISSUE THREAD

**Issue by cyberprotz** [coralproject/talk#2071]
#### Do you want to request a **feature** or report a **bug**?
question

#### Intended outcome:
We are using coral talk for our publishing webiste. We have noticed that the guys from the coral project haven't investigated on amp so far ([link](https://community.coralproject.net/t/easy-wordpress-integration/695/15)). Maybe the team from the coral project give us an insight about the plan/roadmap with amp and coral talk.

Thanks in advance!

**Comment by kgardnr** [comment]
Hey @cyberprotz, we would love if you wanted to take this on. We know this is something a lot of newsrooms want, but we simply haven't had the time to investigate. Would you like to take this on?

**Comment by cyberprotz** [comment]
Hi @kgardnr thx for sharing your information. Unfortunatelly we don't have the men power to make talk amp ready/compatible. Perhaps some of the major publisher are able and have the power to do it. I would really appreciate it.

**Comment by jarrett-pon** [comment]
Is amp being currently worked on now? I saw this PR recently: https://github.com/coralproject/talk/pull/2324

**Comment by wyattjoh** [comment]
Preliminary AMP support is being added in our next release yes!
