### ISSUE TITLE
Custom onbuild image size is double the base image

### ISSUE THREAD

**Issue by dberhane** [coralproject/talk#2075]
I am a new Coral Talk user and have a basic understanding of Docker. I’ve successfully installed Coral Talk (v4.6.5) on our development environment. I am now in the process of enabling Plugins.

To enable one extra plugin, I have used the basic docker “onbuild” image Dockerfile, a directory of plugins and a plugins.json file (which lists the activated plugins).

The new image container is working well and could see the new plugin enabled. My only concern is that the new image size is 810MB which is almost of twice the size of the base image (443MB). I’ve only enabled one additional plugin. Should I be concerned about the image size?

**Comment by wyattjoh** [comment]
Thanks for the report @dberhane!

Unfortunately, we're currently blocked on the following yarn bug: https://github.com/yarnpkg/yarn/issues/4764

It seems whenever we run `yarn`, it will touch every file in node_modules each time, which causes issues with how docker detects changed files, thereby increasing the image size.

We're replacing yarn with npm in Talk v5, which does not have this issue.
