### ISSUE TITLE
[Question] Possibility to adjust metascraper rules for Talk

### ISSUE THREAD

**Issue by oafx** [coralproject/talk#2085]
#### Do you want to request a **feature** or report a **bug**?

Question / Feature

#### Intended outcome:

I'd love to adjust or modify the metascraper rules for Talk. Is this possible in some way? My current problem is, that our CMS provider appears to use a meta tag with the name `date` which displays the current time instead of the time the document/asset/storry was published and the scraper appears to favor this time which leads to wrong dates. Therefore I'd love to disable the scraping of the meta tag named `date`.

#### Actual outcome:
I'm not sure how to solve this issue without modifying the talk code. Is there any way around this?

#### How to reproduce the issue:
Have a CMS provider that doesn't use meta Tags as they are intended 😋 

#### Version and environment
4.6.6 docker/win-local

**Comment by oafx** [comment]
Correct me if I'm wrong: Is it possible to overwrite the Scraper via the Connectors/Services?

**Comment by immber** [comment]
There are lots of scenarios where the default "lazy asset creation" functionality might not work exactly right with your particular CMS, so our recommended solution is to implement your own asset creation strategy. The best way to do that would be with a custom plugin to override the "lazy asset creation" scraper that is used by default in Talk, and generate/update assets from your CMS.  

Here's a link to more info on that process from our documentation: https://docs.coralproject.net/talk/integrating/asset-management

For example, The Register-Guard created this custom plugin (and then made it open-source), that allows the embed for Talk to specify an Asset ID to lookup if it already exists, and if not found create with the given ID and URL. https://github.com/coralproject/talk-plugin-custom-asset-id

**Comment by oafx** [comment]
Great! Many thanks for the hint, I will try that!
