### ISSUE TITLE
Building client side codes faster

### ISSUE THREAD

**Issue by eshwarenm** [coralproject/talk#2087]
I was wondering if there is another way to build the client side files without using `yarn build`. 
Is there anyway I can "watch" the changes? 

The `yarn build` takes about 5 mins to complete, so any suggestion for a faster workflow, especially when editing the client files?

**Comment by wyattjoh** [comment]
You can use `yarn watch` actually!

**Comment by eshwarenm** [comment]
After posting this, I found out about `yarn watch`. Will close now. Thanks @wyattjoh !!!
