### ISSUE TITLE
Where are the rejected comments stored?

### ISSUE THREAD

**Issue by nishkalavallabhi** [coralproject/talk#2091]
I am trying to query the GraphQLAPI to get information about comments that are rejected, for an internal project.  I am sending the request from Python (3.6) and here is my code:

```
import requests

mainurl = "XXXXXXXX"
header = {"Content-Type": "application/json"}
temp = "query TempQuery($com: CommentsQuery!){comments(query: $com) {nodes {body, status}} }"
testvars = {
        "com": {"statuses": "REJECTED", "limit":500}
    }
request = requests.post(mainurl, json={'query': temp, 'variables':testvars, "operationName":"TempQuery"}, headers=header)
print(request.json())
if not request.status_code == 200:
    print("Query failed")
```

I get: {'data': {'comments': None}}
If I change the status to "ACCEPTED", I do get a ton of comments in the result json. Where are the rejected comments going? How can I access them? I am using the options from COMMENTS_STATUS Enum (https://docs.coralproject.net/talk/api/graphql/#COMMENT_STATUS).

**Comment by wyattjoh** [comment]
Comments are stored in the database always, including rejected comments! While not documented, the `comments` edge is protected, and requires an ADMIN token in order to hit. You can generate it using the cli tool: https://docs.coralproject.net/talk/configuration-cli-tools/#working-with-access-tokens

```
./bin/cli token create <your user id> <a name for this token>
```

**Comment by nishkalavallabhi** [comment]
@wyattjoh - Thanks for the response! Where do I get the ./bin/cli tool? Should I setup a local instance of talk and this is a part of the installation? Is there any other way to generate this token when I am only accessing the talk URL elsewhere and reading from it?

**Comment by immber** [comment]
Just adding for future reference, that authenticating GraphQL queries is covered in our documentation here: https://docs.coralproject.net/talk/api/overview/#authorizing-a-request

**Comment by immber** [comment]
@nishkalavallabhi The Talk cli tool is already included in the Talk repo. Just nav to your Talk root directory, and launch with `./bin/cli`

If you check out the link I posted above that might help with the question about generating the token, as there are a few ways that you can authenticate an API request to access the protected queries depending on your implementation.

**Comment by nishkalavallabhi** [comment]
@immber - Yes, I saw the link. Thanks. However, I am unable to use the ./bin/cli program as I get the error: 'TALK_ROOT_URL' must be provided. But where?

I tried ./bin/cli-setup, ./bin/cli-settings, ./bin/cli-token, ./bin/cli - none worked. All threw the same error. I followed the error messages to see config.js, and added the ROOT_URL in it, and it now shows:
Error: TALK_JWT_SECRET must be provided in the environment to sign/verify tokens

Is there some available documentation on what are all the things I need to get to set this up? Also, Like I mentioned earlier, I am accessing the Talk data residing somewhere, only to READ content, and possibly only once or twice. I don't want to go through all the setup on my laptop just to do this. Is there another way of getting an access token if I cannot setup cli tools? I don't know where to get these secret tokens from, to get my access token.

**Comment by immber** [comment]
@nishkalavallabhi All of the steps are included in our documentation, however they are designed for someone who is running their own instance of Talk locally. 
I'll reach out to you thru the support channel to work with you directly on getting API access to your hosted instance of Talk!

**Comment by nishkalavallabhi** [comment]
@immber - Thank you for a quick reply! I will look forward for your response. Please let me know if I need to give any information about our organization's instance that I am querying (and how to share that information).
