### ISSUE TITLE
Adding a new field - Making it required

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2093]
Thanks again for all your help last week helping me get my new field to behave properly when submitting a form. One thing I forgot to ask about was making the field required.

I can add `required` as an HTML parameter on the input item, and that doesn't seem to impact the form from submitting. In either case, it produces a `generic` exception that I'm having difficulty catching (specifically, I'm not sure where to catch it at, none of the files referenced in the stack trace are ones that I created).

My next thought was to try and tap into `submitEnabled` so the form itself won't submit without the field being required, but after looking further that doesn't seem to be a tied to a slot in any fashion.

Is there another avenue I should be trying?

#### Stack Trace from submitting the new empty field
```
  express:router graphqlHandler /ql : /api/v1/graph/ql +0ms
GraphQLError: Variable "$input" got invalid value {"asset_id":"f58c2d9d-9131-4c41-8470-943cf58c173e","body":"hello comment","tags":[],"richTextBody":"hello comment","checkSpam":true}.
In field "displayName": Expected "String!", found null.
    at getVariableValues (/Users/riggllm/GitHub/obits-guestbook-platform/node_modules/graphql/execution/values.js:93:15)
    at buildExecutionContext (/Users/riggllm/GitHub/obits-guestbook-platform/node_modules/graphql/execution/execute.js:210:54)
    at executeImpl (/Users/riggllm/GitHub/obits-guestbook-platform/node_modules/graphql/execution/execute.js:124:15)
    at Object.execute (/Users/riggllm/GitHub/obits-guestbook-platform/node_modules/graphql/execution/execute.js:113:150)
    at doRunQuery (/Users/riggllm/GitHub/obits-guestbook-platform/node_modules/apollo-server-core/dist/runQuery.js:122:42)
    at /Users/riggllm/GitHub/obits-guestbook-platform/node_modules/apollo-server-core/dist/runQuery.js:21:56
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by alinhle** [comment]
@lriggle-strib You can prevent the form from submitting by throwing an exception inside the `preSubmit` hook and then render some info to the user. See `components/Editor.js` in the rich text plugin on how to add a `preSubmit` hook.

**Comment by lriggle-strib** [comment]
@cvle Thanks, that's helpful! What ended up working best was having the `preSubmit` hook just ensure the value was a string, regardless of the length, and then throwing an exception in my hooks file because the exceptions thrown from the `preSubmit` hook end up displaying in my browser console.

```javascript
module.exports = {
  RootMutation: {
    createComment: {
      pre: async (_, { input }) => {
        let displayName = input.displayName;

        if (!displayName.length) {
          throw new StribErrMissingDisplayName();
        }

        input.metadata = merge(get(input, 'metadata', {}), {
          displayName: displayName,
        });
      },
    },
    editComment: {
      async pre(_, { edit }) {
        let displayName = edit.displayName;

        if (!displayName.length) {
          throw new StribErrMissingDisplayName();
        }

        edit.metadata = merge(get(edit, 'metadata', {}), {
          displayName: displayName,
        });
      },
    },
  },
};
```
