### ISSUE TITLE
Unable to set language with onbuild image

### ISSUE THREAD

**Issue by richardvenneman** [coralproject/talk#2094]
#### Do you want to request a **feature** or report a **bug**?

Bug?

#### Intended outcome:

I'm trying to set the default language of the embed stream to `nl`.

#### Actual outcome:

Language in the embed stream as well as the admin app is always `en`.

#### How to reproduce the issue:

```Dockerfile
# Dockerfile
ARG TALK_DEFAULT_LANG=nl
ARG TALK_WHITELISTED_LANGUAGES=nl
FROM coralproject/talk:4.6-onbuild
```

```json
/* plugins.json */
{
  "server": [
    "talk-plugin-auth",
    "talk-plugin-local-auth",
    "talk-plugin-love",
    "talk-plugin-notifications",
    "talk-plugin-notifications-category-reply",
    "talk-plugin-slack-notifications",
    "talk-plugin-sort-most-loved"
  ],
  "client": [
    "talk-plugin-auth",
    "talk-plugin-comment-content",
    "talk-plugin-facebook-auth",
    "talk-plugin-flag-details",
    "talk-plugin-local-auth",
    "talk-plugin-love",
    "talk-plugin-notifications",
    "talk-plugin-notifications-category-reply",
    "talk-plugin-permalink",
    "talk-plugin-sort-most-loved",
    "talk-plugin-sort-newest",
    "talk-plugin-sort-oldest",
    "talk-plugin-viewing-options"
  ]
}
```

For completeness, we're hosting on Heroku with the following:

```yaml
# heroku.yml
build:
  docker:
    web: Dockerfile
  config:
    TALK_DEFAULT_LANG: nl
    TALK_WHITELISTED_LANGUAGES: nl
run:
  web: npm start
```

This sets the variables with `--onbuild-arg` (confirmed by Heroku Support) as described in the [Talk onbuild docs](https://docs.coralproject.net/talk/installation-from-docker#onbuild). This is also shown in the build output log:

```
=== Fetching app code
=== Building web (Dockerfile)
Sending build context to Docker daemon  4.608kBStep 1/3 : ARG TALK_DEFAULT_LANG=nl
Step 2/3 : ARG TALK_WHITELISTED_LANGUAGES=nl
Step 3/3 : FROM coralproject/talk:4.6-onbuild
4.6-onbuild: Pulling from coralproject/talk
4fe2ade4980c: Pulling fs layer
eeb7d76f44e7: Pulling fs layer
...
```

#### Version and environment

Talk v4.6.6
Latest Safari, Chrome, Firefox.

I tried setting the browser preferred language to only `nl` as well as `localStorage.setItem('locale', 'nl')` but both without any effect. I'd be happy to provide any other information if needed.

**Comment by wyattjoh** [comment]
Should hopefully be a simple fix!

Instead of setting the language key to`nl`, set it to `nl_NL`.

Essentially, you should set the language key to the one defined in the following folder: https://github.com/coralproject/talk/tree/master/locales

**Comment by richardvenneman** [comment]
Thanks @wyattjoh! It's working now. The [docs even mention this too](https://docs.coralproject.net/talk/integrating/translations-i18n#languages), don't know how I missed that.

By the way, would you be interested in a pull request documenting how to get up and running on Heroku with the onbuild Docker image? If yes, where should this go?

**Comment by wyattjoh** [comment]
We're always open to contributions!

You can create a markdown file here: https://github.com/coralproject/talk/blob/master/docs/source

Use the following as a template: https://github.com/coralproject/talk/blob/master/docs/source/01-02-installation-from-docker.md

And add the item to the sidebar here: https://github.com/coralproject/talk/blob/master/docs/_config.yml#L83-L94
