### ISSUE TITLE
When I connect my talk server to mongo atlas url the plugin stops working

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/talk#2102]
Hi support,

we have a talk running perfectly fine with the following docker set up:

`

version: '2'
services:
  talk:
    image: xxxx.dkr.ecr.us-east-1.amazonaws.com/container-example-test:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=development # remove this line in production
      - TALK_MONGO_URL=mongodb://mongo/talk
      - TALK_REDIS_URL=redis://redis
      - TALK_ROOT_URL=https://comment-test.stg2.xx.com/
      - TALK_PORT=3000
      - TALK_JWT_SECRET=password
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis:/data
volumes:
  mongo:
    external: false
  redis:
    external: false

`

The above code works fine. However as soon as I change the TALK_MONGO_URL to mongo atlas  Url I got from a free account I created as follows:

`

version: '2'
services:
  talk:
    image: xxxxx.dkr.ecr.us-east-1.amazonaws.com/container-example-test:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development # remove this line in production
      - TALK_MONGO_URL=mongodb+srv://stg4-talk:TXrwT4mloomOQ3VE@stg4-talk-qptsl.mongodb.net/talk
      - TALK_REDIS_URL=redis://redis
      - TALK_ROOT_URL=https://xx-test.stg2.xx.com/
      - TALK_PORT=3000
      - TALK_JWT_SECRET=password

`

I get the following error and talk stops working:

![image](https://user-images.githubusercontent.com/24658315/49245737-9b1b7e80-f3e9-11e8-8010-3f65a8c41d63.png)

So the question is can we use MongoAtlas at all for talk?

If yes is there any trick or anything we need to follow to have it work?

**Comment by kgardnr** [comment]
You'll need to use the 3.4 or earlier driver syntax: https://www.mongodb.com/blog/post/mongodb-3-6-here-to-SRV-you-with-easier-replica-set-connections

**Comment by kgardnr** [comment]
More info here: https://docs.mongodb.com/manual/reference/connection-string/?_ga=2.86078608.9438358.1543519897-31358338.1540387923

**Comment by hminaeeBrunswicknews** [comment]
Thanks  ,


when I switch to the <3.6 version admin page also stops working which was working with >3.6.


![image](https://user-images.githubusercontent.com/24658315/49251707-6bc03e00-f3f8-11e8-823f-33a0914668dc.png)


Also the comment now throw me a new error as follows:


![image](https://user-images.githubusercontent.com/24658315/49251690-63680300-f3f8-11e8-8f9e-6b01e663cbe2.png)


Also here is the new url I use for Mongo variable:

mongodb://hamed1:xxxx@fargate4-shard-00-00-d8wly.mongodb.net:27017,fargate4-shard-00-01-d8wly.mongodb.net:27017,fargate4-shard-00-02-d8wly.mongodb.net:27017/test?ssl=true&replicaSet=fargate4-shard-0&authSource=admin

Also here is my mongoAtlas set up:

![image](https://user-images.githubusercontent.com/24658315/49293011-2eee5880-f485-11e8-9510-9dff6de9106b.png)



![image](https://user-images.githubusercontent.com/24658315/49293049-4d545400-f485-11e8-96ff-8a85a54f9dc5.png)


![image](https://user-images.githubusercontent.com/24658315/49293087-60672400-f485-11e8-85db-a27c6e55a30f.png)



Any idea? @kgardnr  @wyattjoh @losowsky

**Comment by wyattjoh** [comment]
The "Internal Error" is printed in production, with it logging the bug on the backend, what is the error you're seeing?

**Comment by hminaeeBrunswicknews** [comment]
Thanks @wyattjoh 
All I see is the below:

`{"name":"talk","version":"4.5.1","revision":"76bb6df084f9ff910d394ecbb237faf83b331e26","hostname":"7be468006eb6","pid":26,"level":50,"err":{"message":"not found","stack":"Error: not found\n    at new ExtendableError (/usr/src/app/errors.js:8:18)\n    at new TalkError (/usr/src/app/errors.js:23:5)\n    at new ErrNotFound (/usr/src/app/errors.js:236:5)\n    at router.use (/usr/src/app/routes/index.js:149:8)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at Immediate.next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at Immediate.<anonymous> (/usr/src/app/node_modules/express/lib/router/index.js:635:15)\n    at runCallback (timers.js:812:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)"},"msg":"http error","time":"2018-11-30T17:08:23.887Z","src":{"file":"/usr/src/app/middleware/logging.js","line":36,"func":"error"},"v":0}
`
and also:

` stack: 'Error: Talk is currently not setup. Please proceed to our web installer at $ROOT_URL/admin/install or run ./bin/cli-setup. Visit https://docs.coralproject.net/talk/ for more information on installation and configuration instructions\n    at new ExtendableError (/usr/src/app/errors.js:8:18)\n    at new TalkError (/usr/src/app/errors.js:23:5)\n    at new ErrSettingsNotInit (/usr/src/app/errors.js:267:5)\n    at loadFn (/usr/src/app/services/settings.js:16:11)\n    at <anonymous>',
talk_1   |   status: 500,
talk_1   |   translation_key: null,
talk_1   |   metadata: {} }
talk_1   | {"name":"talk","version":"4.5.1","revision":"76bb6df084f9ff910d394ecbb237faf83b331e26","hostname":"7be468006eb6","pid":26,"level":50,"err":{"message":"not found","stack":"Error: not found\n    at new ExtendableError (/usr/src/app/errors.js:8:18)\n    at new TalkError (/usr/src/app/errors.js:23:5)\n    at new ErrNotFound (/usr/src/app/errors.js:236:5)\n    at router.use (/usr/src/app/routes/index.js:149:8)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at Immediate.next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at Immediate.<anonymous> (/usr/src/app/node_modules/express/lib/router/index.js:635:15)\n    at runCallback (timers.js:812:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)"},"msg":"http error","time":"2018-11-30T17:11:03.889Z","src":{"file":"/usr/src/app/middleware/logging.js","line":36,"func":"error"},"v":0}
`

**Comment by wyattjoh** [comment]
As you likely pointed your application to a fresh Atlas install, you need to run the setup in order to see your comments.

It looks like you did try that, so if you can also provide the console logs from the install page, we can see why the install is failing.

**Comment by hminaeeBrunswicknews** [comment]
@wyattjoh 


When I run it I get this:


` stack: 'Error: Talk is currently not setup. Please proceed to our web installer at $ROOT_URL/admin/install or run ./bin/cli-setup. Visit https://docs.coralproject.net/talk/ for more information on installation and configuration instructions\n    at new ExtendableError (/usr/src/app/errors.js:8:18)\n    at new TalkError (/usr/src/app/errors.js:23:5)\n    at new ErrSettingsNotInit (/usr/src/app/errors.js:267:5)\n    at loadFn (/usr/src/app/services/settings.js:16:11)\n    at <anonymous>',
talk_1   |   status: 500,
talk_1   |   translation_key: null,
talk_1   |   metadata: {} }
talk_1   | {"name":"talk","version":"4.5.1","revision":"76bb6df084f9ff910d394ecbb237faf83b331e26","hostname":"7be468006eb6","pid":26,"level":50,"err":{"message":"not found","stack":"Error: not found\n    at new ExtendableError (/usr/src/app/errors.js:8:18)\n    at new TalkError (/usr/src/app/errors.js:23:5)\n    at new ErrNotFound (/usr/src/app/errors.js:236:5)\n    at router.use (/usr/src/app/routes/index.js:149:8)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)\n    at /usr/src/app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)\n    at Immediate.next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)\n    at Immediate.<anonymous> (/usr/src/app/node_modules/express/lib/router/index.js:635:15)\n    at runCallback (timers.js:812:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)"},"msg":"http error","time":"2018-11-30T17:22:05.019Z","src":{"file":"/usr/src/app/middleware/logging.js","line":36,"func":"error"},"v":0}
talk_1   | {"name":"talk","version":"4.5.1","revision":"76bb6df084f9ff910d394ecbb237faf83b331e26","hostname":"7be468006eb6","pid":26,"level":30,"traceID":"75192670-f4c4-11e8-91ed-8f2a64423c1e","url":"/api/v1/live","method":"GET","statusCode":404,"userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36","responseTime":5,"msg":"http request","time":"2018-11-30T17:22:05.019Z","src":{"file":"/usr/src/app/middleware/logging.js","line":19,"func":"res.end"},"v":0}
`

**Comment by wyattjoh** [comment]
When you try to install Talk, what is the logs you see in the web browser when you see that "undefined" popup?

**Comment by hminaeeBrunswicknews** [comment]
@wyattjoh 

Here is what I see :

![image](https://user-images.githubusercontent.com/24658315/49304667-708dfc00-f4a3-11e8-9f14-7fb4bb8d5148.png)



![image](https://user-images.githubusercontent.com/24658315/49304727-97e4c900-f4a3-11e8-9eeb-eaf017e1b60f.png)




![image](https://user-images.githubusercontent.com/24658315/49304760-ad59f300-f4a3-11e8-80c4-ea94583e575f.png)


Here is mongo url I am using and it is widely open in case if you need it:

mongodb://hamed1:11111@fargate4-shard-00-00-d8wly.mongodb.net:27017,fargate4-shard-00-01-d8wly.mongodb.net:27017,fargate4-shard-00-02-d8wly.mongodb.net:27017/test?ssl=true&replicaSet=fargate4-shard-0&authSource=admin

**Comment by immber** [comment]
@hminaeeBrunswicknews I was just able to go to your talk instance at `https://commenthamed5.stg1.dev-telegraphjournal.com/admin/moderate`, and complete the setup with the same credentials you provided in your screenshot above. 

I also tested connecting to the MongoDB instance that you reference `mongodb://hamed1:11111@fargate4-shard-00-00-d8wly.mongodb.net`, but that does not seem to be the mongo instance that the Talk instance I just logged into is connected to. In the mongo instance, I see a `test` db with one user, but not the `talk` db or the user I just created. 

It looks like either you've resolved the issue with connecting to the DB or Talk is connecting to a different instance than expected. Can you confirm if you've resolved the connection issue or if you're able to login and access the moderation interface?

**Comment by hminaeeBrunswicknews** [comment]
@immber 

Thanks a lot for your help.
It worked!!!!!!!!!!
I just updated the mongo url to point at the cluster you changed.
Can you please explain what changes you made?

**Comment by hminaeeBrunswicknews** [comment]
@immber 

Thanks a lot for your help.
It worked!!!!!!!!!!
I just updated the mongo url to point at the cluster you changed.
Can you please explain what changes you made?
Did you change anything in mongo cluster?

**Comment by immber** [comment]
@hminaeeBrunswicknews I only connected to the mongo instance and queried it, I made no configuration changes. 

On the talk instance, I also made no config changes, but I connected to the url you provided, and walked thru the setup steps using the same credentials that you had provided in your screenshot. *Make sure you change your login pwd* :) 

I think you fixed it by updating the mongo url, and pointing at a different mongo instance. As I said, I don't see the user I created in the `@fargate4-shard-00-00-d8wly.mongodb.net` instance, so I think Talk is connecting to a different mongo instance. As long as you know what instance that is, you should be good to go!

**Comment by hminaeeBrunswicknews** [comment]
@immber 

Actually right now it is connected to @fargate4-shard-00-00-d8wly.mongodb.net
How can I query the db to see if my user exist over there?

**Comment by immber** [comment]
@hminaeeBrunswicknews  I like MongoDB Compass, available here: https://www.mongodb.com/products/compass

You just connect with your connection string, and you will be able to explore and interact with the data in your mongo instance.

**Comment by hminaeeBrunswicknews** [comment]
@immber 

Thanks a lot @immber 

Just to double check I am going to create a new mongo cluster in atlas and test it that way.
I will get back and let you know about the result.

**Comment by hminaeeBrunswicknews** [comment]
@immber 

Here is my admin page:

https://commenthamed5.stg1.dev-telegraphjournal.com/admin

and here is my new test cluster:

mongodb://hamed:11111@hamedfargat1-shard-00-00-0n1yr.mongodb.net:27017,hamedfargat1-shard-00-01-0n1yr.mongodb.net:27017,hamedfargat1-shard-00-02-0n1yr.mongodb.net:27017/test?ssl=true&replicaSet=hamedfargat1-shard-0&authSource=admin

When I run it I get the exact same error as above.
By following the steps do you mean this:

![image](https://user-images.githubusercontent.com/24658315/49322063-3263fd00-f4e2-11e8-9e46-81307650c808.png)


Can you see the error over there? is there any step I am missing on setting up talk?

**Comment by hminaeeBrunswicknews** [comment]
Thanks,

It worked.
It turned out to be a caching issue.
When I try it in incognito window it works.

Thanks for your help
