### ISSUE TITLE
Feature idea: Remove size limit from adminCommentContent slot

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2104]
## Description

I'll use the plugin I'm working on as an example:

I've added an additional text field to the embed stream for the user to input a name to display with the comment instead of their username. The data is saved on the comment object, not the user, since it is a field required for every comment. Since it is relevant text for the comment, not just data about the comment (like the toxicity level), the value itself should also be evaluated by the moderators. The logical place (to me) to display this is with the comment's body content, meaning that the moderators wouldn't have to go hunting for the information.

This would speed up the moderation process for additional fields like the one I've created.

Here is the slot in question:
https://github.com/coralproject/talk/blob/5d32c4ec034c44f4167a7cf25fe2e80c3f5fb01f/client/coral-admin/src/routes/Moderation/components/Comment.js#L164-L170

I've tested this locally, removing the size restriction (`size={1}`) allows both the comment and the second field to display in the same area:

<img width="661" alt="screen shot 2018-11-30 at 9 43 02 am" src="https://user-images.githubusercontent.com/7051012/49299061-74f6ec80-f484-11e8-926a-31e04e6e3e6f.png">

CSS changes would also be required to make the fields display sequentially (like the screenshot) instead of inline with each other.

**Comment by kgardnr** [comment]
Hey @lriggle-strib we won't be adding this for v4, but could consider this for v5. Thank you!
