### ISSUE TITLE
Talk on Aws ECS Fargate not working properly  

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/talk#2106]
Hi support,

I set up talk on aws Ec2 and everything worked fine from admin console to SSO from web browser.
Here is the docker file I am using:

`

version: '2'
services:
  talk:
    ### image: coralproject/talk:4.5.0
    image: xxxxx.dkr.ecr.us-east-1.amazonaws.com/container-example-test:l                                                                                                                                                             atest
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development # remove this line in production
      - TALK_MONGO_URL=mongodb://hamed:11111@fargate2-shard-00-00-0n1yr.mongodb.                                                                                                                                                             net:27017,fargate2-shard-00-01-0n1yr.mongodb.net:27017,fargate2-shard-00-02-0n1y                                                                                                                                                             r.mongodb.net:27017/test?ssl=true&replicaSet=fargate2-shard-0&authSource=admin
      - TALK_REDIS_URL=tj-stg3ue1-talk.w9aiiq.ng.0001.use1.cache.amazonaws.com
      - TALK_ROOT_URL=https://commenthamed5.stg1.dev-telegraphjournal.com/
      - TALK_PORT=3000
      - TALK_JWT_SECRET=password
`

However when I try the same configuration on aws ECS as follows:

![image](https://user-images.githubusercontent.com/24658315/49377509-bbe11e00-f6e0-11e8-8198-8adcc9305a3d.png)

I get this error:

![image](https://user-images.githubusercontent.com/24658315/49377550-da471980-f6e0-11e8-975a-5b67a5eabd1d.png)

I encounter this error on EC2 only when mongourl was in the format of +3.6.
But here I am using the +3.4 url as follows:

mongodb://hamed:11111@fargate2-shard-00-00-0n1yr.mongodb.                                                                                                                                                             net:27017,fargate2-shard-00-01-0n1yr.mongodb.net:27017,fargate2-shard-00-02-0n1y                                                                                                                                                             r.mongodb.net:27017/test?ssl=true&replicaSet=fargate2-shard-0&authSource=admin

So I am not sure why I get this error.
Anyone faced this issue before? Any idea?

Update:

I was on call with aws support and we confirmed that all the configuration for both working version and not working one is the same but we could not find any logs related to this issue to be able to nail it down and proceed.
Seems to be a weird issue. 

All we see is the following:

{"name":"talk","version":"4.5.1","revision":"76bb6df084f9ff910d394ecbb237faf83b331e26","hostname":"ip-172-20-0-230.ec2.internal","pid":27,"level":30,"traceID":"a5e26920-f716-11e8-bec6-5579331e03c1","url":"/admin","method":"GET","statusCode":200,"userAgent":"ELB-HealthChecker/2.0","responseTime":4,"msg":"http request","time":"2018-12-03T16:15:27.926Z","src":{"file":"/usr/src/app/middleware/logging.js","line":19,"func":"res.end"},"v":0}

![image](https://user-images.githubusercontent.com/24658315/49386605-5435cd80-f6f6-11e8-85e3-eaa6e3b651bd.png)

No error related to :

GraphQl error: Could not query field "ScheduledDeletionDate" on type "User"

That would be awesome if you can shed light on it?

@immber  @kgardnr  @wyattjoh

**Comment by wyattjoh** [comment]
That looks like you have a plugin enabled on the client, but not on the server. Check to see that `talk-plugin-profile-data` is enabled on both the client and the server, then it should clear that error.

**Comment by hminaeeBrunswicknews** [comment]
Yaaaaay worked 
Thanks :)
