### ISSUE TITLE
Question: Can plugins also listen for events?

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2107]
Is the embed stream the only thing that can actively listen for events, or can plugins do so as well? I know plugins can emit custom events, but can they also listen?

**Comment by wyattjoh** [comment]
Depends! We do have an event bus that will service some requests sent, take a look at how we internally handle notification emails: https://github.com/coralproject/talk/blob/master/plugins/talk-plugin-notifications/server/connect.js#L33 and https://github.com/coralproject/talk/blob/master/plugins/talk-plugin-notifications-category-reply/index.js#L180-L187

If you wanted to listen for other events, like a button clicked, then we don't have some of those events tied to server requests.

**Comment by lriggle-strib** [comment]
@wyattjoh We are looking at listening for things like "comment posted" (which looks feasible based off that second link), the goal of which being monitoring. Ex: If we listen for comments posted, and send a metric to datadog every time one is posted, then we can monitor the number of comments posted over time and if that dips below a threshold then there might be a problem that we can get on top of before something utterly fails.

**Comment by wyattjoh** [comment]
I'd actually recommend taking a look at the plugin we wrote for Prometheus: https://github.com/coralproject/talk-plugin-prom

In this plugin, we pull out the "operation name" from each GraphQL query, and add it to the metrics, so you can listen for the "PostComment" query name in this case.

**Comment by lriggle-strib** [comment]
Awesome, thanks!
