### ISSUE TITLE
Creating users with moderator role

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/talk#2108]
Hi support,

We have the Talk with custom SSO plugin running.
Everything is good.
We have an admin user set up via /admin/install and couple of users created through SSO.
Here is what we have:

![image](https://user-images.githubusercontent.com/24658315/49539690-9dc41b00-f8a4-11e8-808b-e9ea11e6e061.png)

The problem now is what we should do if we need to have other accounts set as moderator.
We do not want to give the root admin password to every moderator.
In talk console I could not find any tab for creating different users with different roles.

Any suggestion is appreciated

**Comment by kgardnr** [comment]
Hey @hminaeeBrunswicknews, you'll need to ask your moderators to sign up via the comment stream (so browse to any article, sign up), and then you can change their role.

You can also create them manually via the CLI: https://docs.coralproject.net/talk/configuration-cli-tools/#working-with-your-application%E2%80%99s-authentication

**Comment by hminaeeBrunswicknews** [comment]
@kgardnr 

Thanks for the answer.
So if we have the SSO on, they cannot create a user with email/pass since SSO will do the job.
So does this mean that the only way left is cli?

**Comment by kgardnr** [comment]
Oh ok - so then you search for them in the Community > People tab, and change their permissions there.

**Comment by hminaeeBrunswicknews** [comment]
@kgardnr 

Yeah I can find them there but in the admin page but  if they need to login they should use email/password but for SSO we do not have that since it is token based.


they look like this:

![image](https://user-images.githubusercontent.com/24658315/49540569-c9e09b80-f8a6-11e8-90c3-c2565c30050b.png)

**Comment by hminaeeBrunswicknews** [comment]
@wyattjoh  @kgardnr @immber 

So the problem is when the moderators try to access the admin moderator console. The console is asking for username and password when their login method is through SSO. 
How do we allow them to login to the console as moderator?

**Comment by kgardnr** [comment]
There are 2 options, you can extend your auth plugin to have a "Login with _____" button. You can check our Facebook and Google Auth plugins to see how to do that. (See screenshot attached)

Or you can have them login via the frontend and browse to the Admin, where they will be automatically logged in.

This is assuming you've given them a "Moderator" or "Admin" role in Community > People.

<img width="514" alt="admin_login" src="https://user-images.githubusercontent.com/1077300/49591446-661da780-f966-11e8-8a2a-56a34e70faec.png">

**Comment by hminaeeBrunswicknews** [comment]
@kgardnr 

If I add google plugin authentication,
 is it possible to just add it in the admin console and not the client where we insert the <script> code?
Or if we add it it is gonna be shown in both places?

**Comment by lriggle-strib** [comment]
@hminaeeBrunswicknews We also have SSO set up on our application for front-end users. What we ended up doing when adding new moderators was:
1. Log into the main website and browse to a page with the commenting interface on it
   - This creates them in the Talk application
2. An admin finds them in the Talk admin interface and promotes them to moderator.
3. New moderator goes to the Talk admin interface. They will see the login screen there.
   a. If Talk think's they're already logged in, have them log out of talk (the gear).
4. New moderator clicks on the Forgot Password link. This will allow them to set a password.
5. New moderator logs in.

**Comment by immber** [comment]
@hminaeeBrunswicknews If you add the google auth plugin, the default behavior is that it would be shown in both places. However if you're already creating users with SSO and just need a way for them to log in, I don't think adding the google plugin will be helpful for you. 

@kgardnr  was suggesting that you could implement a custom SSO integration that would give you a "log in with ___" that would be connected to your SSO authentication system. That's an option, but it's also not totally necessary. 

Instead, you can implement a workflow like the suggestion above. 

1.  Change the role on the users created by your SSO to Moderator
2. Once they have logged into with your site with SSO, they should be able to just nav to `<TALK_ROOT_URL>/admin/moderate` and they will be logged in as moderators. 

If they get to that page and are not signed in, then they should login to your site using your SSO, and refresh once they have a valid session in their browser. 

You don't actually need them to set a separate pwd for Talk as described by @lriggle-strib unless you've also implemented the local Talk authentication plugin.

**Comment by lriggle-strib** [comment]
We did remove the talk auth plugins, so that makes sense. All user creation on our end is silent as long as the user is logged into our main website.

**Comment by losowsky** [comment]
@hminaeeBrunswicknews Hey Hamed - do you have all you need? Are you looking to go live at any point soon?
