### ISSUE TITLE
new client plugin injection

### ISSUE THREAD

**Issue by AbodyAmer** [coralproject/talk#2111]
hello talk people, 

i am creating a new plugin to allow commenters to remove their comments. but i don't know where to inject my plugin 

```
import RemoveCommentButton from './components/RemoveButton';

export default {
  slots: {
    commentActions: [RemoveCommentButton],
  },
};
```
this is my component and this is the result 

![asktalk](https://user-images.githubusercontent.com/29151700/49627753-7e033300-fa1b-11e8-8bf2-91242b284ff8.png)

delete button is below share button. I want to make on the left of share button. which slot should i use??? 

Thank you

**Comment by kgardnr** [comment]
Hi @AbodyAmer! You'll need to override the existing CSS to make this work. You can read more here: https://docs.coralproject.net/talk/integrating/styling-css/
