### ISSUE TITLE
Info-Tooltip always visible on recommended posts

### ISSUE THREAD

**Issue by BokiDzoki** [coralproject/talk#2112]
cc @hjanuschka 

Greetings!

As it seems there is a bug, blocking part of the visible area of recommended posts on mobile devices by casting the help-tooltip without a click on the information-button.

#### Do you want to request a **feature** or report a **bug**?
Bug

#### Intended outcome:
Filter by recomended posts by selecting the corresponding tab on a mobile device.

#### Actual outcome:
The tooltip with additional information is popping up directly when the "recommended"-Tab is selected without being called by a touch on the information button (![image](https://user-images.githubusercontent.com/3089217/49641338-23b0a500-fa10-11e8-9c5e-4b0042815a19.png))

![image](https://user-images.githubusercontent.com/3089217/49641012-4c846a80-fa0f-11e8-895a-bb98b9e4c327.png)

#### How to reproduce the issue:
Got to https://www.krone.at/1819943 with a mobile device (Chrome Debugger too)
Scroll to the bottom where you can see the implementation of the Ttalk instance.
Klick on "Empfohlen" and the mentioned behavior should be visibible.

#### Version and environment
v.4.6.6

Thank you!

**Comment by jqueryisamonad** [comment]
This issue is related to `onMouseEnter` event (triggered by hover on a tab) which works on mobile like a toggle. One possible solution is to show tooltip only on `info-icon` hover but hover area will be very small for the mobile users' convenience

**Comment by kgardnr** [comment]
This should be fixed now!
