### ISSUE TITLE
Question: Logout url?

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2113]
Is there an explicit URL (or query parameter) that will log the current user out of the admin whenever it is navigated to? I know there is a logout link in the gear dropdown, but it doesn't seem to be tied to a unique URL. I'm trying to implement an auth plugin for admin users w/ `passport-saml`, since that's what we use for SSO here, and it wants logout information.

Example: Talkurl.com/admin/logout Talkurl.com/admin/?logout=true

Does something like that exist? I can't tell if I'm just missing it or if logout is handled in a way that I'm not understanding.

**Comment by immber** [comment]
@lriggle-strib The sign out button triggers logout through the api by making a `DELETE` request to `/api/v1/auth` there is no logout url. The delete request contains the user's cookie to identify the session being terminated, and the response sends an expired `authorization=` cookie back to the user.

**Comment by lriggle-strib** [comment]
Thanks @immber!
