### ISSUE TITLE
Accept/Reject Buttons vanish with longer strings/urls

### ISSUE THREAD

**Issue by BokiDzoki** [coralproject/talk#2129]
Greetings!

#### Do you want to request a **feature** or report a **bug**?
bug

#### Actual outcome:
when posts are premoderated the accept/reject buttons can move out of the visible area, if words with a high character count are used (usually urls). It seems the behavior is related to the fact, that longer concatenated strings are not broken into the next line.
![image](https://user-images.githubusercontent.com/3089217/50081135-0210a400-01ee-11e9-9e39-ef5542f7b058.png)

#### How to reproduce the issue:
->premoderate posts.
->including some longer urls in the text should result in the described behavior.

#### Version and environment
v4.6.9
Windows 10
Chrome  71.0.3578.98

Cheers!
Bogdan

**Comment by BokiDzoki** [comment]
cc
@hjanuschka

**Comment by oafx** [comment]
I opened a PR to fix that one recently; #2128

**Comment by immber** [comment]
Fix was released in v 4.6.11, closing this issue.
