### ISSUE TITLE
Implications of running in NODE_ENV=development

### ISSUE THREAD

**Issue by campaignupgrade** [coralproject/talk#2137]
I can't find NODE_ENV defined in any one place in the docs, but references to it are scattered in several locations — what are the implications of running in NODE_ENV=development? 

I did read that it allows for http access. We're considering running in HTTP and using CloudFlare as the HTTPS proxy, but to do that we expect we'll need Talk to run locally in HTTP. 

Otherwise we can spin up an nginx instance to use it as the proxy but it seemed simpler to use CloudFlare

**Comment by kgardnr** [comment]
Hey @slamorte, this isn't a Talk specific variable, but a Node one, you can read about it here: https://stackoverflow.com/questions/16978256/what-is-node-env-in-express

**Comment by kgardnr** [comment]
Also, Talk does require https in production, so you'll need to use something Cloudflare. Locally when you run in development, it doesn't require https.

**Comment by wyattjoh** [comment]
We strongly recommend running Talk in production mode always. Talk does not serve SSL certificates, but it does send HSTS headers as well as expect that the request is over TLS. So it does trust the forwarded protocol headers to infer that, which Cloudflare does send. Running Talk in development mode will turn off many performance improvements.

**Comment by campaignupgrade** [comment]
Thanks for the info. We ended up running in production mode and handling HTTPS on the production server as per your recommendations.
