### ISSUE TITLE
unique identifier get the comment list

### ISSUE THREAD

**Issue by StevenYuysy** [coralproject/talk#2140]
#### Do you want to request a **feature** or report a **bug**?

bug, maybe not.

#### Intended outcome:

I want to pull a list of comments with a unique identifier instead of assets url, because my url will change as the title of the article changes. I am not sure if there are other ways to help me achieve my goal.

#### Actual outcome:

every time url changes and comment list was "lost" on the front page.

#### How to reproduce the issue:

change the url of the page.

#### Version and environment

master branch, development.

**Comment by oafx** [comment]
Hi @StevenYuysy 

there is a plugin for that purpose: https://github.com/coralproject/talk-plugin-custom-asset-id

and i think these docs might be helpful:

https://docs.coralproject.net/talk/integrating/cms-integration/

if you enable the plugin mentioned above it should be sufficient to modify your embed code like described on the bottom of the page:

```html
<div id="coral_talk_stream"></div>
<script src="${TALK_ROOT_URL}static/embed.js" async onload="
  Coral.Talk.render(document.getElementById('coral_talk_stream'), {
    talk: '${TALK_ROOT_URL}',
    asset_id: '${ASSET_ID}'
  });
"></script>
```

hope this helps!
Chris

**Comment by StevenYuysy** [comment]
Thx, it works perfectly!

**Comment by mkonikov** [comment]
This is awesome! Gotta check it out
