### ISSUE TITLE
Typos in spanish translations

### ISSUE THREAD

**Issue by gerardogalvez** [coralproject/talk#2141]
#### Do you want to request a **feature** or report a **bug**?
Bug.

#### Intended outcome:

- Correct translations in for filter_users.
- Suspended and Banned have the same translations ("Suspendido") and they seem to be two different things.
- moderator isn't translated.

#### Actual outcome:

![image](https://user-images.githubusercontent.com/8509232/50467148-2e9f8b00-0967-11e9-8a88-7a33a11701ba.png)

#### How to reproduce the issue:

Go to admin/community/people in spanish.
#### Version and environment

Talk v4.7.0
Google Chrome Version 71.0.3578.98

I haven't taken a look at all the translations in spanish, these are just the ones I found but I'll take a look later and update this issue if anything else comes up.

**Comment by kgardnr** [comment]
Hi @gerardogalvez! Would you like to contribute the corrections for these in a PR? We'd love it if you would!
