### ISSUE TITLE
"Load More" in People tab does not apply filter to returned results

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2143]
#### Do you want to request a **feature** or report a **bug**?
Bug

#### Intended outcome:
After filtering users by role, clicking "Load More" should display more users of that role

#### Actual outcome:
After filtering users by role, clicking "Load More" does not display more users of that role, it displays users of any role.

#### How to reproduce the issue:
1. Filtered all people so only Administrators would show.
   - There are currently 14 administrators in the database.
   - Initial pageload displays 10 users
2. Click "Load More"
3. The additional 4 administrators should display. Instead 5 additional users of any role display.

<img width="1792" alt="screen shot 2019-01-04 at 12 03 31 pm" src="https://user-images.githubusercontent.com/7051012/50703357-6a96b800-1019-11e9-9e64-5b16256a21b2.png">

#### Version and environment
We're currently on 4.6.5. We had some issues upgrading to newer versions prior to our launches last month and haven't circled back around to figure out what went wrong.

**Comment by immber** [comment]
This looks related to a similar bug ticket we have open for an issue with the Assets (Stories) page pagination. I've added a note to that bug ticket to investigate this at the same time. https://www.pivotaltracker.com/story/show/162740247

**Comment by immber** [comment]
May be related to #2158, which is also reported as being and issue with Assets, but could be hitting the same issue of query missing limit.

**Comment by kgardnr** [comment]
Fixed in https://github.com/coralproject/talk/pull/2174 @lriggle-strib!

**Comment by lriggle-strib** [comment]
Thanks @kgardnr!

**Comment by mkonikov** [comment]
Hey @immber -

I'm still finding this to be an issue in v4.8.0

**Comment by immber** [comment]
@kgardnr You closed this as fixed in #2174, however that PR only addressed the issue on the Stories view, I believe this is still an issue on the People tab, so I'm re-opening. We might need to apply the same or similar fixes to Users as were done to Assets.

**Comment by kgardnr** [comment]
Thanks @immber!

@mkonikov and/or @lriggle-strib would you mind submitting a fix for this potentially? Our team is heads down on v5 the next few weeks so it would really help us out if you could!
