### ISSUE TITLE
Question: What does "Internal Error" mean?

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2146]
## Description
Bugsnag is receiving a bunch of exceptions from the GraphQL API that just read "Internal Error". In this particular situation I think it is related to whether or not an asset exists, but since the message is extremely generic it is hard to be certain.

<img width="1380" alt="screen shot 2019-01-07 at 9 37 15 am" src="https://user-images.githubusercontent.com/7051012/50777206-96f04580-1260-11e9-8071-6931d7f9e10f.png">

<img width="1147" alt="screen shot 2019-01-07 at 9 45 29 am" src="https://user-images.githubusercontent.com/7051012/50777404-19790500-1261-11e9-83e1-e2c80de557ee.png">

Is there a way to get more meaningful error information out of the GraphQL API?

**Comment by wyattjoh** [comment]
When you see an internal error like that, it's because an error occurred that was designated "sensitive". You can take the uuid that's presented there (the `33f...17`) and search your logs for it, as a stack trace will be associated with that particular error.

**Comment by lriggle-strib** [comment]
@wyattjoh I'm confused as to why "I can't find an asset to get a comment count for" would be considered sensitive, considering the query itself doesn't require a login and therefore the data is open to the public.

Where is "sensitivity" determined? Is there a way to adjust it?

**Comment by lriggle-strib** [comment]
@wyattjoh Additionally, what's really unusual is that the bugsnag reporting within Talk (via plugin) is not catching any of these "internal error" messages and passing them along. Shouldn't that end at least catch it?

How we're reporting to bugsnag: https://github.com/coralproject/talk/issues/2000#issuecomment-430386406

**Comment by wyattjoh** [comment]
I don't think that retrieving the comment count via this method would be "protected", but it depends on what error is actually occurring. Did you see what error was referenced on the server?

Sensitivity can not be adjusted, as it's a feature baked into the core product.

Related to some messages not being reported properly through bugsnag, it's tricky. Depending on the type of error, Talk v4 has some edge cases where it does not report the error through the logger, thereby meaning that it can't report the error via bugsnag. We've been working really hard for v5 to ensure that these cases are caught, but if you can identify where we are not using the logger to report errors, we'd welcome a PR addressing the issues!

**Comment by lriggle-strib** [comment]
@wyattjoh When I run the query through postman on my local environment (i.e. not a production environment), here is the error that is generated:

```json
{
    "data": {
        "asset": null
    },
    "errors": [
        {
            "message": "class ErrInvalidAssetURL extends TalkError {\n  constructor() {\n    super('asset_url is invalid', {\n      translation_key: 'INVALID_ASSET_URL',\n      status: 400,\n    });\n  }\n}",
            "locations": [
                {
                    "line": 1,
                    "column": 25
                }
            ],
            "path": [
                "asset"
            ]
        }
    ]
}
```

I will keep an eye out for places where logger can be integrated, though I'm not sure about the best way to go about integrating it. It looks like all GraphQL errors are handled via this file: https://github.com/coralproject/talk/blob/master/graph/errorHandler.js but my local attempts to integrate the logger object into it did not result in any data showing up in Bugsnag.

In fact the only errors we seem to get with any reliability are Mongo and Redis errors.

**Comment by lriggle-strib** [comment]
@wyattjoh As an alternative, is there a baked in way to query the existence of an asset before trying to query data about it? Something that won't return an error if the asset doesn't exist, basically. If not I can try and get a research ticket added to our local roadmap over here.

**Comment by lriggle-strib** [comment]
@wyattjoh

**Comment by wyattjoh** [comment]
You can query based on the ID of the Asset, but the default behavior of the Asset resolver in v4 is to create/retrieve it. You can override the `Query.asset` resolver if you want to change this behavior!
