### ISSUE TITLE
Bug: NODE_ENV value in .env file ignored

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2147]
#### Do you want to request a **feature** or report a **bug**?
bug

#### Intended outcome:
NODE_ENV to have the value specified in my .env file (or docker-compose or wherever a user is specifying their environment variables)

#### Actual outcome:
NODE_ENV has a value specified in:
* the yarn command used to run the application
* the Dockerfile pulled in from Github

#### How to reproduce the issue:
Open up whatever file you use to specify your environment variables. Add/update NODE_ENV to that file and give it a value, something other than `development` or `production`. When you start/restart your application the NODE_ENV will not have the specified value, and instead will have the value defined in the command used to run the application.

Our staging environment, where we specify `stage` for this var, still outputs this when I restart docker:

```
✗ docker-compose up
Creating network "20190103203913_default" with the default driver
Creating 20190103203913_talk_1
Attaching to 20190103203913_talk_1
talk_1  | yarn run v1.9.4
talk_1  | $ NODE_ENV=production ./bin/cli-serve -j -w
talk_1  | (node:25) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
talk_1  | subscriptionManager is deprecated, use `execute` or `subscribe` directly from `graphql-js`!
```

My local environment, which I have set to `local` to differentiate from the deployed dev environment, still outputs this when I start the yarn command:

```
✗ yarn watch:server
yarn run v1.10.1
$ nodemon --config .nodemon.json
[nodemon] 1.17.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.* bin/cli bin/cli-serve
[nodemon] starting `npm-run-all --parallel generate-introspection start:development`
$ NODE_ENV=development ./bin/cli-serve -j -w
$ WEBPACK=TRUE NODE_ENV=test ./scripts/generateIntrospectionResult.js
Outputted result of introspectionQuery to /Users/riggllm/GitHub/news-comments-platform/client/coral-framework/graphql/introspection.json
Outputted result of introspectionQuery to /Users/riggllm/GitHub/news-comments-platform/docs/source/_data/introspection.json
(node:56155) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
subscriptionManager is deprecated, use `execute` or `subscribe` directly from `graphql-js`!
```

This makes it difficult to filter metrics by environment if the environments don't respect the value specified. For example, I don't want my staging environment affecting prod metrics because of release testing.

#### Version and environment
Talk version 4.6.5

**Comment by wyattjoh** [comment]
This is by design. We wanted to make it "difficult" to deploy the application in development mode in environments like Docker.

You can see in our `package.json` file:

https://github.com/coralproject/talk/blob/dd0601a80132d2849c53ef7eaf12ff382f3920b9/package.json#L13-L14

That you can change the start behavior using `yarn start` or `yarn start:development`. If you want to change how this works by:

- Override the `CMD` argument in your `Dockerfile` to `CMD ["yarn", "start:development"]`
- Override the `command` argument in your `docker-compose.yml` as seen in https://docs.docker.com/compose/compose-file/#command

```yml
# ...
services:
  talk:
    command: ["yarn", "start:development"]
# ...
```

While we agree this is slightly confusing from a development workflow, we also want to ensure that the easiest path is the safest path. Let me know if this explanation helps!

**Comment by oafx** [comment]
Hi, maybe it's worth mentioning that changing the docker command to something that depends on the devDependencies of the package.json will result in a failing container as the images are built without devDependencies. Stumbled over this a bit ago, if i recall correctly.

**Comment by wyattjoh** [comment]
Great point @oafx. If that's the case, you'll also have to ensure that you install the full set of dependencies as a separate step. You can always create your own `Dockerfile` based off of the `coralproject/talk:4` image which would allow you to install the dependencies for development:

```Dockerfile
FROM coralproject/talk:4

ENV NODE_ENV development

# Setup the build arguments
ENV TALK_ADDTL_COMMENTS_ON_LOAD_MORE 10
# ...
# Other build args as seen in: https://github.com/coralproject/talk/blob/dd0601a80132d2849c53ef7eaf12ff382f3920b9/Dockerfile.onbuild#L4-L14
# ...

# Bundle app source
COPY . /usr/src/app
RUN cli plugins reconcile && \
    yarn && \
    yarn build && \
    yarn cache clean

CMD ["yarn", "start:development"]
```
