### ISSUE TITLE
Supporting multiple site languages

### ISSUE THREAD

**Issue by immber** [coralproject/talk#2156]
#### Coral Community Question
This question was originally submitted to our Coral Community forum, but could better be answered here:

> We have two type versions of stories one is English and one is Chinese. We want the Talk comment to be in English in the English story and Chinese in Chinese story. How to change the language of the system??

**Comment by immber** [comment]
Talk supports selecting a single "default" language and has been translated into many languages. 

Here's some documentation on that:

#### how to set the default language 
https://docs.coralproject.net/talk/integrating/translations-i18n/

#### locales/languages supported by Talk
https://github.com/coralproject/talk/tree/master/locales

Talk does not currently support using different languages on different articles or story sections.

**Comment by skolhustick** [comment]
We had this issue, and decided to host Talk on two separate instances. Both instances were parked under different subdomains. For e.g, talk.xxxxx.com, and talkzh.xxxxx.com (this would be for the ZH_CN ) version of Talk. For the ZH instance, we have a different .env, which only allows ZH_CN. This way, we have multiple languages on the same site.  

In our article site, we make sure the ZH articles calls the embed from the talkzh.xxxxx.com instance, and the EN articles call the usual talk.xxxxx.com. Problem solved! :)
