### ISSUE TITLE
Admin Stories /api/v1/assets request returns 500 error for large JSON response sizes

### ISSUE THREAD

**Issue by clintabrown** [coralproject/talk#2158]
#### Do you want to request a **feature** or report a **bug**?

Bug

#### Intended outcome:

In Talk admin load all assets in the Stories tab

#### Actual outcome:

In our Talk environment (75,000+ assets) upon load of the Stories tab in Talk admin the following GraphQL request returns a `500` error response -

/api/v1/assets?value=&asc=false&filter=all&limit=undefined

After testing this request with a limit imposed up to around 40,000 assets it returns a `200` status response -

/api/v1/assets?value=&asc=false&filter=all&limit=40000

Any limit much higher than that returns the `500` error response again.

All search requests in the Stories tab return a `200` response.

Is there any response size limit being imposed by the GraphQL server / other middleware? (couldn't see one). We use both Akamai and Varnish in front of our Talk installation but our ops team aren't aware of any limits being imposed at these layers too.

Ideally, it'd be preferred if a limit could be applied to this query as feels somewhat wasteful (for installs with many assets) to download numerous MB's of data for this request.

#### How to reproduce the issue:

Talk installation with 50,000+ assets
Visit the Stories tab and inspect the GraphQL assets requests

#### Version and environment

v4.6.11

**Comment by wyattjoh** [comment]
It is a known issue that the Stories tab is... unwieldy with large lists. We are planning on directly addressing this in Talk v5, but are currently unsure as to the status of resolving this for v4. We'll get back on the status of this soon.

If you are pointing out the specific endpoint as you'd like to use it in API requests, there is a `Query.assets` GraphQL edge you can query against that should be better suited for it.

**Comment by clintabrown** [comment]
Thanks for the update @wyattjoh - (as search is working) this isn't really impacting our moderators at all.

**Comment by mkonikov** [comment]
This does seem to be a regression - as it was working fine as recently as in version 4.4.3.

**Comment by wyattjoh** [comment]
When you experience the `500` error @clintabrown, what error was logged by the server?

**Comment by clintabrown** [comment]
@wyattjoh Very sorry for the delay getting back, I believe this is the error logged -

`{"name":"talk","version":"4.6.11","revision":"08f579225b13e4d0c41367ca262ff097d416a76a","hostname":"wtilt-talk-69b59878bc-hcp98","pid":27,"level":50,"err":{"message":"Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.","name":"MongoError","stack":"MongoError: Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.\n    at queryCallback (/usr/src/app/node_modules/mongodb-core/lib/cursor.js:247:25)\n    at /usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:531:18\n    at _combinedTickCallback (internal/process/next_tick.js:132:7)\n    at process._tickCallback (internal/process/next_tick.js:181:9)","code":96},"msg":"http error","time":"2019-02-01T05:51:57.769Z","src":{"file":"/usr/src/app/middleware/logging.js","line":40,"func":"error"},"v":0}
`

**Comment by wyattjoh** [comment]
We might be able to "improve" this operation by adding some indexes... I've created #2174 to address this, let me know if you're able to test that out @clintabrown!

**Comment by clintabrown** [comment]
Thanks @wyattjoh! Just tried applying the indexes and can confirm these requests now return `200` status -

<img width="1680" alt="production - stories asset graphql queries" src="https://user-images.githubusercontent.com/1551632/52184161-dd3ac380-2863-11e9-868a-0561fe40f799.png">

**Comment by wyattjoh** [comment]
Wonderful! As soon as we get that merged, it'll auto-close this issue.
