### ISSUE TITLE
No way to enable facebook plugin

### ISSUE THREAD

**Issue by tomascrespo** [coralproject/talk#2160]
### Expected behavior

We should be able to login via Facebook 

### Actual behavior
![imagen](https://user-images.githubusercontent.com/3028295/51535237-2a706b80-1e48-11e9-82ce-8a8286f65b8f.png)
url of this window is  `https://www.facebook.com/dialog/oauth?display=popup&auth_type=rerequest&response_type=code&redirect_uri=https%3A%2F%2Ftalk.tomascrespo.com%2Fapi%2Fv1%2Fauth%2Ffacebook%2Fcallback&scope=public_profile&client_id=604728343310879`

My config in facebook developers app is:
![imagen](https://user-images.githubusercontent.com/3028295/51535828-df575800-1e49-11e9-88e0-df4972ca30e5.png)

The domain talk.tomascrespo.com (where I'm running talk) is whitelisted

This are my Client OAuth settings
![imagen](https://user-images.githubusercontent.com/3028295/51535745-a1f2ca80-1e49-11e9-82e5-759498270ab2.png)

As you can see I have no set any redirect URI.

I have enabled Google Auth plugin in talk with no problems.

### Steps to reproduce behavior
You can visit any post of this blog https://verdepistacho.tomascrespo.com and try to login with Facebook (at the bottom of the page).
![imagen](https://user-images.githubusercontent.com/3028295/51535965-4ffe7480-1e4a-11e9-9ec9-b7c40dcb979d.png)

**Comment by kgardnr** [comment]
Hey @tomascrespo, you'll need to set the Redirect URI to be: 
`https://talk.tomascrespo.com/api/v1/auth/facebook/callback`

**Comment by tomascrespo** [comment]
Perfect! I worked!
I should know that, sorry
In your docs, in google auth plugin is specified the Redirect UI. In facebook auth plugin documentation doesn't say anything about Redirect URI.

Thanks Kim
