### ISSUE TITLE
Enable support for injecting js, e.g., Mathjax or Katex

### ISSUE THREAD

**Issue by ghost** [coralproject/talk#2164]
Hi,

First off, thanks for this project.

#### Do you want to request a **feature** or report a **bug**?
Feature.

#### Intended outcome:
I am trying to use Coral Talk on my website, and am anticipating people using latex in their comments. I would like to be able to include mathjax or katex script in the Talk subdomain iframe, so that math in the comments is properly rendered. Including the script in the original webpage, doesn't include it in the iframe (security limitation of js).

#### Version and environment
Dockerized Coral Talk on Debian 9

**Comment by kgardnr** [comment]
Thank you @fosshelper for your kind words! This sounds like a unique use case, and would probably be best suited to be a plugin (probably an adaptation of our `talk-plugin-rich-text`). If you'd like to take this on, you can host this on your own repo and let us know and we can help you with code reviews/questions.

Thank you again!

**Comment by ghost** [comment]
Thanks for considering. I might take this on, but probably after a while (website is still in infancy and busy with other work at the moment). In particular, if you already have a plugin for similar functionality, it shouldn't be too difficult.
