### ISSUE TITLE
Text Direction for RTL languages (CSS)

### ISSUE THREAD

**Issue by mkonikov** [coralproject/talk#2166]
Currently for RTL languages (believe Arabic is currently the only one), text is not specifically set to RTL in the styling. This causes issues when a line includes a mix of both the for language and english/Latin ABC, such as this:
```
    organization_info_copy: 'نستخدم هذه المعلومات في إشعارات البريد الإلكتروني التي يتم إنشاؤها بواسطة Talk. يعمل هذا على توصيل الرسائل إلى مؤسستك ، ويوفر طريقة للمستخدمين للاتصال بك إذا كانت لديهم مشكلة في حسابهم.'
```

Ideally, there should be some way to apply `direction: rtl;` for defined languages that are RTL. 

May take a stab at implementing if you have ideas on best way to do so.

**Comment by kgardnr** [comment]
I'm going to tag @cvle here, as he was going to look into some possible solutions for this.

**Comment by kgardnr** [comment]
Hey @mkonikov - great news! Another organization is going to be contributing this to v5 in the coming months. So I'm going to close this ticket, and we'll let you know when we release it! 🎉

**Comment by kgardnr** [comment]
This has been delayed, but should be here before EOY.
