### ISSUE TITLE
Requesting comments by `author_id` returns too much

### ISSUE THREAD

**Issue by freder** [coralproject/talk#2169]
#### Do you want to request a **feature** or report a **bug**?

bug

#### Intended outcome:
I want to get all comments by a specific user, using the graphql API.

#### Actual outcome:
query seems to ignore `author_id` and return _all_ comments.

#### How to reproduce the issue:
```graphql
{
  comments(query: {
    author_id: "does-not-matter", 
    sortBy: CREATED_AT, 
    sortOrder: DESC, 
    limit: 9999
  }) {
    nodes {
      id
      body
      richTextBody
      created_at
      asset {
        id
        title
      }
      user {
        id
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/724844/51976051-0a622d00-2484-11e9-9148-e8617488587e.png)

#### Version and environment
version `4.6.4`

**Comment by freder** [comment]
**update:** the above request was made as a _~commenter~ admin_. using this user's id as `author_id`, works as expected. however, when using any other value, _all_ comments are returned.

---

I'm not super familiar with the codebase. what happens, when https://github.com/coralproject/talk/blob/master/graph/loaders/comments.js#L394 is not the case?

**Comment by wyattjoh** [comment]
Great question!

It's by design that only administrative users can retrieve comments written by a specific users. If you want to perform those queries, it must be done with an admin token, otherwise the `author_id` filter won't be applied.

**Comment by freder** [comment]
I see. thanks @wyattjoh
