### ISSUE TITLE
Replies and reply button should be disabled when a comment stream is closed.

### ISSUE THREAD

**Issue by theysamtheirs** [coralproject/talk#217]
When comment streams are closed ability to reply should be disabled - button is disabled, and nothing appears if clicked.

Flagging and liking still remains available.

![replies issue](https://cloud.githubusercontent.com/assets/12632662/21727479/a8af0f0e-d40f-11e6-9562-d95189642c70.gif)

**Comment by jde** [comment]
Fixed
