### ISSUE TITLE
Snackbar too short for longer messages

### ISSUE THREAD

**Issue by mkonikov** [coralproject/talk#2171]
We're finding for some of the Snackbar messaging, we'd like to extend the length of time the Snackbar appears on screen. 

Wondering the teams thoughts on adding a small close (X) button and extending it a bit longer.

**Comment by kgardnr** [comment]
Hey @mkonikov! I don't think we'd have any problem if you wanted to do this in core - I think it's a good idea to extend the display time and adding an X.

**Comment by mkonikov** [comment]
With https://github.com/coralproject/talk/pull/2182 merged in, will close now.
