### ISSUE TITLE
Change Default Stream Sort

### ISSUE THREAD

**Issue by eshwarenm** [coralproject/talk#2172]
Hi Team!

How do I change the default sorting order for the stream? 
For some reason, we need to have 'Oldest First' as the default. 
If no, is there a way to persist user's sorting preferences?

Thanks!

**Comment by kgardnr** [comment]
Hey @eshwarenm, you can't change the default sorting order, but you can enable `talk-plugin-remember-sort` and it will persist the user's sorting choice.

Where are you going to be using Talk? We'd love to see it!

**Comment by eshwarenm** [comment]
@kgardnr Oh! How did I miss that! Very convenient. Thanks for the swift reply. 

We have recently launched Talk on our site, www.malaysiakini.com. Malaysiakini is an independent online news portal in Malaysia. You can see Talk in action on our English and Chinese articles. But only paid subscribers would be able to comment. 

Our subscribers are loving the their new comment system, which is a great improvement over the previous one. 

:smile:

**Comment by kgardnr** [comment]
Wow, awesome @eshwarenm! So happy to have you on board using Talk!
