### ISSUE TITLE
Clicking on Settings tab and then clicking back to Comments tab, sets Stream closed and the setting is `null`

### ISSUE THREAD

**Issue by kgardnr** [coralproject/talk#220]
### Expected behavior
Clicking different tabs if the stream is set to Open - you should be able to comment, take actions, see your history, and see settings (if you have appropriate permissions)

### Actual behavior
Clicking on Settings and then back to Comments, seems to clear the Settings which results in the stream being Closed.

### Steps to reproduce behavior
1. Go to comment stream, click on Settings, click back to Comments
2. Can't comment or reply (get 500)
3. Go to Settings, re-open stream, all works as expected

**Comment by wyattjoh** [comment]
I don't think that this is a backend issue @kgardnr. Might be related to the stream expiry setting, but I think these are separate tickets.
