### ISSUE TITLE
list of events embed can listen to?

### ISSUE THREAD

**Issue by tomaszrondio** [coralproject/talk#2200]
is there a list of events coral embed can listen to?
 eg:
`coralEmbed.on('query.CoralEmbedStream_Embed.ready', ...)`

To be more specific. I need to listen to user login/logout events. But in general it would be nice to see all possibilities.

**Comment by immber** [comment]
@tomaszrondio You can get a list by following the instructions here: https://docs.coralproject.net/talk/integrating/event-tracking-metrics/

**Comment by kgardnr** [comment]
Hey @tomaszrondio! I've added some more details at the bottom of our event tracking docs page.

Fixed in https://github.com/coralproject/talk/pull/2262
