### ISSUE TITLE
Email notify on reply enabled by default

### ISSUE THREAD

**Issue by tomascrespo** [coralproject/talk#2209]
Is there any way to enable notification emails by default? 

A configuration option in .env for that will be a good idea, or a option in admin panel to enable notifications manually for each registered user

**Comment by wyattjoh** [comment]
Unfortunately, without forking the plugin related to that particular notification type, no.

We've taken quite a principled stance on opt-in for these types of notifications as they could unintentionally be used as tools for harassment.

Another possible solution could be using our GraphQL API to toggle the setting based on some user feedback if you're integrating Talk into an existing user management system that would allow you to toggle that.
