### ISSUE TITLE
Feature Idea: Add list for most commented assets, sorted by publication_date in API

### ISSUE THREAD

**Issue by juhaniahola** [coralproject/talk#2214]
Would it be a viable feature to implement possibility to request such list from the api?

This wouldn't probably be necessary to be implemented anywhere in Talks front-end but for the purpose of the using site, so we could show the list of most commented assets within a time period by using Talks own api instead of making our own.

Sorting the assets by created_at key won't work in this case, as assets may appear in the older articles much later which makes created_at timestamp to be recent.

**Comment by wyattjoh** [comment]
Unfortunately, this feature is not very easy to accomplish in version 4 of Talk, as we don't store the number of comments on each of the Assets, it would involve some pretty expensive aggregation operations.

We do however have this possible in version 5, and will keep it in mind during the development.

**Comment by mkonikov** [comment]
Cool. What is the rough timeline for v5?

**Comment by wyattjoh** [comment]
We're aiming to have a beta available by the end of March @mkonikov.
