### ISSUE TITLE
Google+ API Shutdown

### ISSUE THREAD

**Issue by wyattjoh** [coralproject/talk#2215]
This issue is being created to track the issue in an upstream repository we're using related to the [Google+ API Shutdown](https://developers.google.com/+/api-shutdown): https://github.com/mstade/passport-google-oauth2/pull/15

Once this PR is merged and a new version of published, we will release a new bug release of Talk that will upgrade this particular package.

We don't expect it to affect existing users of Talk as Google has indicated that they have added mitigations to the existing behaviors implementation that should allow for a seamless transition.

**Comment by mstade** [comment]
FWIW – the PR was merged and v0.2.0 of the library published to npm.
