### ISSUE TITLE
"Failed login" settings

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2230]
## Description
I'm trying to find settings around handling failed login attempts to the moderator tool. Specifically I'd like to know how to set the number of attempts, how long the user has to wait, and where an admin can go to end the wait prematurely.

I'm not able to find any information about that in the docs or the interface. We're currently on 4.6.5.

![image](https://user-images.githubusercontent.com/7051012/54561463-bd360e00-4992-11e9-802b-9a239edc435a.png)

**Comment by wyattjoh** [comment]
A bit confusing, but it's related to the following configuration:

- [TALK_RECAPTCHA_WINDOW](https://docs.coralproject.net/talk/advanced-configuration/#talk-recaptcha-window)
- [TALK_RECAPTCHA_INCORRECT_TRIGGER](https://docs.coralproject.net/talk/advanced-configuration/#talk-recaptcha-incorrect-trigger)

Please reopen if this didn't answer the question!
