### ISSUE TITLE
[IE11 only] Talk defaults to Spanish in IE11

### ISSUE THREAD

**Issue by hminaeeBrunswicknews** [coralproject/talk#2235]
Hello support,

We are using talk coral in our project and recently we noticed that only in Internet explorer the talk language is set as spanish:

![image](https://user-images.githubusercontent.com/24658315/54706545-f353c900-4b1d-11e9-9ab5-da4edd6eadaa.png)

When we check the same page in other browsers they are all in English. 
Also it is noteworthy that our default language is set to English so we expect talk to appear in English in all browsers.

Any idea?

**Comment by kgardnr** [comment]
Hey @hminaeeBrunswicknews, could you test with 2 different computers, so we can see if it might be the IE browser settings on your machine, or if this is widespread?

If you can't test on another machine, could you check your IE language settings and also clear your cookies and cache, and try again?

**Comment by hminaeeBrunswicknews** [comment]
@kgardnr 

Thanks for the answer.
we already tested it in different machines and after clearing the cache the same issue happens.
So I think it is widespread.
Also I checked my setting and here is my default language setting:

![image](https://user-images.githubusercontent.com/24658315/54707150-2fd3f480-4b1f-11e9-85b0-65032eb23f13.png)

**Comment by kgardnr** [comment]
Ok great @hminaeeBrunswicknews, could you also check your install of Talk and see if any language settings are configured? It would be these: https://docs.coralproject.net/talk/advanced-configuration/#talk-default-lang

**Comment by hminaeeBrunswicknews** [comment]
@kgardnr Yes the configured language at the build time was set to English and all the browsers except IE respect that.

**Comment by kgardnr** [comment]
@hminaeeBrunswicknews ok cool, could you send me the url of the site so I can test on our side and try and diagnose?

**Comment by kgardnr** [comment]
If you need to send us credentials/etc, you can email support at coralproject.net and we can go from there.

**Comment by hminaeeBrunswicknews** [comment]
@kgardnr 
Email sent :)
Thanks

**Comment by kgardnr** [comment]
Bug is related to newsroom-specific setup. Closing as it's not a widespread issue.
