### ISSUE TITLE
Remove the use of Source sans pro font

### ISSUE THREAD

**Issue by GlynnPhillips** [coralproject/talk#2237]
## Potential improvement

I have noticed that the Source sans pro web font is downloaded for all views rendered by Talk because it is included in the [base template](https://github.com/coralproject/talk/blob/master/views/templates/base.njk#L21). This results in it get loaded during the render of the embed component. 

As far as I can tell this font is then only ever referenced in an [admin stylesheet](https://github.com/coralproject/talk/blob/master/public/css/admin.css#L28) which is only used on a couple of pages and never in the embeds.

### Suggestion 1
My first suggestion is to remove this from the base template so its not downloaded by the end user viewing the embeded component.

### Suggestion 2
However I have a further suggestion which would remove it entirely and rely on system fonts instead. I have produced this as an example [commit](https://github.com/GlynnPhillips/talk/commit/e6b638bb4aa8dbf2aa00f516fe3cc960e78a0bbe) for your consideration.

My reasoning for this suggestion is that custom css relies on overrides so if a developer using Talk wishes to use their own fonts they would be forcing an unnecessary download on the user.

### Suggestion 3
There could also be a potential middle ground if Coral wished to keep a default theming/brand which included web fonts but this I imagine would require it to become a configuration option.

**Comment by janslu** [comment]
Are there any plans to change the forced font inclusion? Source Pro in Talk is coming from typeface-source-sans-pro package which doesn't include characters outside of the latin subset. So to use talk in polish I HAVE to either change the font to something different or include additional font import in css for latin-ext subset... 

Would it be possible to make font inclusion a customisable option or if you really, really like Source Sans Pro - move to https://github.com/bedlaj/openfonts and for languages other than English include also latin-ext subset?

**Comment by wyattjoh** [comment]
We're currently looking into this issue related to fonts, and will update this issue when we've made some movement on the issue.
