### ISSUE TITLE
Chrome Edit Comments Bug

### ISSUE THREAD

**Issue by immber** [coralproject/talk#2256]
#### Do you want to request a **feature** or report a **bug**?
Bug

#### Intended outcome:
When editing a comment in Chrome browser, backspace should delete text in the Edit Comment field. 

#### Actual outcome:
*Only happens in Chrome browser, no issue in FF or Safari*
After clicking edit, and clicking into the text area of the comment box, backspace will delete chars until the last one. When pressing backspace to delete the last text character, all characters return. 

#### How to reproduce the issue:

1. be logged into Talk in Chrome
2. post a comment
3. Click edit and into the edit text area
4. backspace to remove all text
![editcommentsbug](https://user-images.githubusercontent.com/7496030/55579003-1b216000-56cc-11e9-82dd-0ca7f1f4844f.gif)

#### Version and environment
Talk v 4.8.3
Chrome Version 72.0.3626.121

**Comment by gerardogalvez** [comment]
So I started to look into this and I think figured out what's causing this behavior.

In Safari and Firefox, ContentEditable inserts a `<br>` element when the text area is empty, Chrome doesn't do this. I tested this using the [demo](https://codesandbox.io/s/4rlw34mnk7) directly from the `react-contenteditable` [repo](https://github.com/lovasoa/react-contenteditable)

### Safari (note how a `<br>` element is added):
![2019-05-05 00 32 09](https://user-images.githubusercontent.com/8509232/57189367-a1031780-6ed3-11e9-861c-644479b562de.gif)


### Chrome (no `<br>` element):
![2019-05-05 00 29 22](https://user-images.githubusercontent.com/8509232/57189366-a1031780-6ed3-11e9-95ae-4c10e49b96c2.gif)

So when the following function gets called to show the value in the Editor `props.input.richTextBody` is `""` in Chrome and `"<br>"` in Safari/Firefox.
https://github.com/coralproject/talk/blob/1c2ff7d2aececc2323ed2e3f2209f18d47802b04/plugins/talk-plugin-rich-text/client/components/Editor.js#L24-L31

If `props.input.richTextBody` is `"<br>"` (Safari/Firefox), it returns the same `"<br>"` which still shows the text area as empty.

But if `props.input.richTextBody` is `""` (Chrome), it returns the richTextBody from the original comment, thus showing the original comment again in the textArea.
https://github.com/coralproject/talk/blob/1c2ff7d2aececc2323ed2e3f2209f18d47802b04/plugins/talk-plugin-rich-text/client/components/Editor.js#L29

which simply returns the richTextBody from the original comment, thus making the original comment appear again in the text area.

Maybe just adding a check for an empty string?

**Comment by kgardnr** [comment]
Thank you so much for this detailed report @gerardogalvez! We will take a look and get back about your proposed fix. Thank you again!

**Comment by alinhle** [comment]
Hi @gerardogalvez, thanks for your analysis! It turns out to be a bad falsey comparison, see: https://github.com/coralproject/talk/pull/2308/files. The PR should fix it :-)
