### ISSUE TITLE
Load Balancing Best Practices

### ISSUE THREAD

**Issue by jhardingmmfa** [coralproject/talk#2258]
#### Question about running multiple Talk servers for load balancing?

Hey I'm new to Talk and Docker. I have a single instance of Talk running on a cloud server. I want to add multiple servers for load balancing. The customer expects 1000+ comments per day once in production. Talk, Redis, Mongo are docker containers. If I wanted three Talk servers running, what would be the best approach? Docker swarm mode or something else?

**Comment by kgardnr** [comment]
Hey @jhardingmmfa! There's a couple different approaches we can take here. You can check out our docs for some high level guidance (see: https://docs.coralproject.net/talk/planning-architecture/) - or you can email our support and we can try and give you some more in depth help: just email support at coralproject dot net. Let us know what works best!
