### ISSUE TITLE
Is it possible to disable scraping?

### ISSUE THREAD

**Issue by freder** [coralproject/talk#2263]
hi,

I was wondering if there is a way to disable scraping.

scraping from within a docker container fails, and I am using a custom mutation to add metadata to an asset anyway, so I would simply like to disable it entirely, if possible.

**Comment by wyattjoh** [comment]
You can!

Check out https://docs.coralproject.net/talk/integrating/cms-integration/#customizing-the-integration-with-a-plugin for documentation on how to do that.
