### ISSUE TITLE
Scrolling is janky in Admin panel

### ISSUE THREAD

**Issue by mkonikov** [coralproject/talk#2268]
I'm finding the scrolling through comments in the admin panel to be quite janky. You can be scrolling and a comment can suddenly move up or down significantly making it hard to keep place.
I'd imagine it's related to how the comments are added and removed via JS to the viewport.

**Comment by kgardnr** [comment]
Thanks @mkonikov!

**Comment by kgardnr** [comment]
Hey @mkonikov we have a fix for this in v5! We'll be in touch about upgrading when we're ready.
