### ISSUE TITLE
Filter comments in Mod queue by section

### ISSUE THREAD

**Issue by mkonikov** [coralproject/talk#2269]
Our moderators have shown an interest in being able to moderate comments and filter specifically by section.

The benefit would seem to be that it's easier to say factor in context when you're moderating say `Sports` articles vs. `US Politics`.

As the assets don't have any section data in the first place - and only basic metadata from the scraper - wondering thoughts on if possible and/or if others see value in that idea.

**Comment by kgardnr** [comment]
Hey @mkonikov - this is a great request and we've definitely heard it before. We have some plans to review for v5, because we think the work required to add it to v4 might be too complex. I can keep you posted on this!
