### ISSUE TITLE
SSO with external authentication provider

### ISSUE THREAD

**Issue by maveonair** [coralproject/talk#2273]
I have the following situation that I want to use Talk with an external SSO provider which is able to issue JWT tokens with the RSA256 algorithm. But I have the following limitations:

1. I have only access to the public key to validate the JWT tokens of the provider, but there is no way to self-sign JWT tokens with the private key of the provider. The provider is the only one who has the private key.
2. The `aud` field is not set in the JWT token from the provider.

According to this [documentation](https://docs.coralproject.net/talk/integrating/authentication/), I need to configure `TALK_JWT_ISSUER`, `TALK_JWT_AUDIENCE` and `TALK_JWT_SECRET`. 

- `TALK_JWT_ISSUER`: This information is available and included in the JWT token from the provider.

- `TALK_JWT_AUDIENCE`: As mentioned before, this information is not available at all.

- `TALK_JWT_SECRET`: According to this [documentation](https://docs.coralproject.net/talk/advanced-configuration/#talk-jwt-secret), I can set `TALK_JWT_ALGO` to `RSA256` and then set the public and private key in `TALK_JWT_SECRET`. Unfortunately, I only have access to the public key. The private key is kept secure by the provider.

When I understood it correctly then Talk uses the same JWT algorithm and secrets for their own authentication. Thus, when I don't have the right private key to the public key then Talk is not able to work correctly? In addition to that, when some fields are missing in the JWT token (such as `aud`) then Talk doesn't call the `tokenUserNotFound` method of custom plugin that implements this function?

Thus, is my assumption correct that Talk cannot be configured out of the box to just validate the JWT tokens from the external SSO provider to authenticate the clients (users) for writing comments while using another internal approach (local-auth) for managing Talk (admins, moderators, etc). Or is there a simple way to achieve this SSO integration with the known limitations.

**Comment by wyattjoh** [comment]
When your provider generates a JWT, you can check it's contents by pasting it into https://jwt.io/ which would tell you what the `TALK_JWT_ISSUER` (the `iss` claim), `TALK_JWT_AUDIENCE` (the `aud` claim) should be set to.

If the token does not have those claims, you can disable them via the [TALK_JWT_ISSUER](https://docs.coralproject.net/talk/advanced-configuration/#talk-jwt-disable-issuer) and [TALK_JWT_AUDIENCE](https://docs.coralproject.net/talk/advanced-configuration/#talk-jwt-disable-audience) variables.

As for the secret, you can use the [TALK_JWT_SECRETS](https://docs.coralproject.net/talk/advanced-configuration/#talk-jwt-secrets) config variable in lieu of the  `TALK_JWT_SECRET` variable to provide the public key from the auth provider as the *second secret*, that way the first secret you can generate with [coralcert](https://github.com/coralproject/coralcert), and the second secret can be the public key provided from your auth provider.

Let me know if this helps!

**Comment by maveonair** [comment]
@wyattjoh Thank you very much! Now it works as expected! 

But is it ok to only provide the public key in `TALK_JWT_SECRETS` without any private key specified? Will Coral then use the other key generated with `coralcert` to create JWT tokens for the internal use?

**Comment by wyattjoh** [comment]
That's correct! The second key can be a public key, which will allow verification. Ensure however that JWT's signed by your external auth provider include a `kid` header, and that the header value is also mirrored in the `TALK_JWT_SECRETS` config.

**Comment by maveonair** [comment]
You made my day!

**Comment by wyattjoh** [comment]
Out of curiosity, does your external auth provider also implement OIDC?

**Comment by brvaland** [comment]
@maveonair - are you able share some code snippet for custom-auth plugin and *.env variable.? I am having same issue and tokenUserNotFound does not call.

I have raised a seperate issue if kindly help share some light. https://github.com/coralproject/talk/issues/2285

**Comment by maveonair** [comment]
> Out of curiosity, does your external auth provider also implement OIDC?

Unfortunately not, its kind of a custom login logic where we get an JWT Token in the end.

**Comment by maveonair** [comment]
> @maveonair - are you able share some code snippet for custom-auth plugin and *.env variable.? I am having same issue and tokenUserNotFound does not call.
> 
> I have raised a seperate issue if kindly help share some light. #2285

Let's continue the discussion in #2285
