### ISSUE TITLE
Comments are editable for an additional 30 seconds when using IE 11

### ISSUE THREAD

**Issue by willogura** [coralproject/talk#2274]
#### Do you want to request a **feature** or report a **bug**?
Bug

#### Intended outcome:
Setting the Edit Comment Timeframe to zero in order to have comments un-editable.
#### Actual outcome:
When using Windows IE 11 the comment is editable for 30 seconds.

#### How to reproduce the issue:
- Set the 'Edit Comment Timeframe' to zero seconds in the admin.
- Post a comment while using IE 11 and attempt to edit the comment.

#### Version and environment
Talk: 4.8.0
Browser: IE 11

**Comment by kgardnr** [comment]
Thank you @willogura! We will test this and get back to you. Thank you for reporting it!

**Comment by kgardnr** [comment]
Hey @willogura we're going to be moving to v5 soon and we will no longer support IE11. So I'm goig to mark this as a wont-fix for now.
