### ISSUE TITLE
Question: Is there a better way to get Premod status comments into the moderator stream using a plugin

### ISSUE THREAD

**Issue by willogura** [coralproject/talk#2275]
Hello,

I am hoping someone might be able to give me a little help with getting premod comments to the embed stream so that when premod is enabled globally, moderators are still able to see premod comments in the embed stream. Ideally, both on page load and in realtime as new comments are added. And it is necessary to do this from entirely within the plugin.

I am currently able to achieve the desired results through modifying the `typeDefs` in a plugin:

 ```
type Subscription {
  commentAdded(asset_id: ID, statuses: [COMMENT_STATUS!] = [NONE, ACCEPTED, PREMOD]): Comment
}
```
By adding the `PREMOD` status here, moderators are able to receive new premod comments in the embed stream. And fortunately, this automatically makes them appear only for moderators.

However, getting `PREMOD` comments to appear when initially loading the comment page is proving to be more difficult. The only way I can seem to get this to work is by having the plugin index.js export a loaders file which is a copy of the `graph/loader.comments.js` file. Then modifying `getCommentsByQuery(`:

```
  if (
    statuses &&
    !statuses.some(status => ['PREMOD'].includes(status)) &&
    statuses.some(status => ['NONE'].includes(status)) &&
    statuses.some(status => ['ACCEPTED'].includes(status)) &&
    ctx.user &&
    ctx.user.can(SEARCH_NON_NULL_OR_ACCEPTED_COMMENTS)
  ) {
    statuses = statuses.concat(['PREMOD']);
  }

  if (statuses) {
    query.merge({ status: { $in: statuses } });
  }
```

Before the query merge, I check for both `NONE` and `ACCEPTED` as the admin uses the same query to populate its results, and this way `PREMOD` won't work its way into its results, and then merge the status. 

The problem with this solution is that it involves copying the content of `graph/loader.comments.js` in order to override `getCommentsByQuery`. And it seems like I can probably achieve the same result through a different and simpler method.

Anyways, if anyone has managed to get this functionality working through a plugin, please let me know how you did it.

**Comment by kgardnr** [comment]
Hey @willogura! I saw you just closed this ticket before we could respond. Did you figure out what you needed?

**Comment by willogura** [comment]
@kgardnr I did work this out. Thanks for checking up.
