### ISSUE TITLE
Make available/public development roadmap

### ISSUE THREAD

**Issue by HectorNM** [coralproject/talk#2276]
Thank you all for the great development on this project!

It looks like there's a `next` branch under development and that it will change completely the folder structure of Talk project. Since it looks like breaking changes will occur, we were wondering if there's a development roadmap or something like that so we can foresee what kind of changes to expect and even try to develop a few features before the next version is released.

I noticed there's a link for the development roadmap in the [Contributing Guidelines page](https://github.com/coralproject/talk/blob/master/CONTRIBUTING.md), but it redirects me to a PivotalTracker page with the message "Sorry, we couldn't find that project", so I guess it's a private project or something like that. 

Is there any docs or information that can be made available for users of this project? It would be very helpful!

Thank you in advance!

**Comment by kgardnr** [comment]
Hey @HectorNM! Thanks for writing in. We've actually been in touch with Carlos from your team to help on some of these pieces, and I've shared our roadmap with him.

Currently, we don't have a public roadmap, but are looking at a way to make this happen easily in the future. I'll update that broken link, thank you!

For our `next` branch is not yet released, we do have some preliminary docs in the README (I also sent this to Carlos too).

**Comment by HectorNM** [comment]
Hi @kgardnr ! Thank you for your reply.

I see, I understand it must be difficult to have a public roadmap while the project is still being planned, so I'll check with @caeugusmao those new information you've been exchanging with him. 

Thank you for your help!
