### ISSUE TITLE
Loading Coral admin in iframe results in blank page

### ISSUE THREAD

**Issue by jakubito** [coralproject/talk#2284]
#### Do you want to request a **feature** or report a **bug**?
Bug

#### Intended outcome:

I am trying to load Coral Talk admin moderation page (`/admin/moderate`) in `iframe`. 

#### Actual outcome:

Iframe loads the page but it doesn't render anything; `<div id="root"></div>` stays empty. It works fine in separate window/tab, the problem only occurs when trying to load the admin page in iframe. I'm not sure if this is intentional or I'm missing something? There is no error in javascript console either.

#### How to reproduce the issue:

Create iframe and populate `src` attribute with Coral Talk URL

#### Version and environment

Talk v4.8.3
Chrome v73.0.3683.86

**Comment by wyattjoh** [comment]
We don't currently support loading the admin panel through an iFrame. You're likely running into a storage exception, which is a browser security feature designed to prevent storage access from iFrames. We've added specific mitigation to support our comment stream, but haven't added support for the Admin panel yet.
