### ISSUE TITLE
Talk integration to multiple application with SSO OKTA

### ISSUE THREAD

**Issue by brvaland** [coralproject/talk#2287]
Hi,

I would like to integration talk with number of internal applications (web based) and we would like to use talk project for commenting for applications. 

We are using Okta for SSO and i have tried to integration with single application and it works fine (https://github.com/coralproject/talk/issues/2285) but unable to integration with second application as we have different `TALK_JWT_ISSUER` and `TALK_JWT_AUDIENCE` as each application have authorisation server where we configure claims specific to the application.

I can add public keys for each application to `TALK_JWT_SECRETS` but token verification fails as i have incorrect `TALK_JWT_ISSUER` and `TALK_JWT_AUDIENCE` 

We have our own authorisation service that can validate token so is it possible to overwrite token verification via custom-auth plugin and hook back to `tokenUserNotFound` for user creation.

Any suggestion or help will be appreciated.

Thanks
Bhavesh

**Comment by wyattjoh** [comment]
You can disable the issuer and audience check within Talk via the `TALK_JWT_DISABLE_AUDIENCE` and `TALK_JWT_DISABLE_ISSUER` vars: https://docs.coralproject.net/talk/advanced-configuration/.

**Comment by brvaland** [comment]
@wyattjoh - is it possible to integrate with custom authorisation service to validate the token and hook to `tokenUserNotFound` for user account creation with jwt token.? I would like to avoid storing public key as we already have a service that handles it.

**Comment by wyattjoh** [comment]
Unfortunatly in the current version of Talk (v4) it will not allow that.

In our next version, we directly support OIDC, which should be a better match for a service like Okta.
