### ISSUE TITLE
Enable authorization for all graphql apis

### ISSUE THREAD

**Issue by brvaland** [coralproject/talk#2290]
Hi

I have been trying graphql apis and discovered that some of the queries returns 200 OK with response without bearer token required. 

The query worked without auth are `asset, comments`. The create comment mutation returns "NOT_AUTHORIZED".

Is it possible to protect all api's except selected ones like acccount creation with authorisation ?

Let me know ?

Thanks
Bhavesh

**Comment by wyattjoh** [comment]
Talk uses the GraphQL api's to serve all the comments across the platform.

If we required authorization for all routes, not logged in users would not be able to view comments.

**Comment by brvaland** [comment]
Yes we require all routes to have authorization and only logged in users would be able to see comments as assest will only be visible to logged in user. Is it possible to add a plugin to achieve it ?
