### ISSUE TITLE
Users can load any user's comments

### ISSUE THREAD

**Issue by jde** [coralproject/talk#232]
### Expected behavior

The endpoint that loads all the comments for a user should only allow users to see their own comments.

### Actual behavior

Users can load any user's comments.

https://github.com/coralproject/talk/blob/31b7dac48adc57a6fae916cc663e9d8387fc3ae5/routes/api/comments/index.js#L51

By convention, all endpoints that allow a logged in user to access their own data should be under the /profile/ route. This can do things call the model with the logged in user's id explicitly so that users can never pull each other comments.

### Steps to reproduce behavior

Call the endpoint linked above with various user id's.

**Comment by wyattjoh** [comment]
Actually, it's blocked by a previous check for this specific situation here: https://github.com/coralproject/talk/blob/31b7dac48adc57a6fae916cc663e9d8387fc3ae5/routes/api/comments/index.js#L28-L32

**Comment by jde** [comment]
@wyattjoh That is correct, I missed that.  Closing.
