### ISSUE TITLE
HTML links sanitize

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#2329]
Hello, I wold like know what you think about HTML links sanitization in the comments body. I believe that in some scenarios it isn't interesting to show HTML links in the comments. And there are other scenarios that the use of links causes the comment to be treated as suspicious.

Maybe we could make this behavior optional or follow some other approach. I could help with a PR.

Thanks

**Comment by wyattjoh** [comment]
When you have the [talk-plugin-rich-text](https://docs.coralproject.net/talk/plugin/talk-plugin-rich-text) plugin enabled, it automatically handles links for you. It was a conscious security decision to only allow links that show their entire address. Like this:

```
<a href="https://google.com/">https://google.com/</a>   <-- Like this
<a href="https://google.com/">Click Here</a>            <-- Not like this
```

This is a feature we are unlikely to change.

You can however also turn on link premod to automatically place any comment with a link into premod.

**Comment by Chavao** [comment]
@wyattjoh, Cristian forgot to mention we are working on branch `next`, and it seems like this branch doesn't have an option to premod comments with links.

The suggestion would be allow sanitisation/strip tags throught configuration and not hard-coded, like nowadays.

**Comment by kgardnr** [comment]
Thanks @Chavao! We have premod comments with links at the article-level and will be adding it soon for the site-wide level. 

However, we don't foresee a feature allowing sanitization as a configuration option. v5's goal is to simplify a lot of the configuration, and unless we hear this request from several others, I don't think we would add it. 

Does that make sense?

**Comment by cristiandean** [comment]
Thanks @kgardnr! If the comments with link will be premod ,that already would be enough for our case =)

**Comment by kgardnr** [comment]
Awesome @cristiandean! 🎉
