### ISSUE TITLE
Feature Idea: Add hash option to permalink plugin's "Share" link

### ISSUE THREAD

**Issue by AndrewGibson27** [coralproject/talk#2330]
The permalink plugin is quite handy. Our only issue is the link created when you click "Share" doesn't contain a hash allowing you to jump users down to where the Talk embed actually is. Having the option to include one would be fantastic ... and could (maybe) be accomplished using some text in a `translations.yml` file?

![Screen Shot 2019-05-28 at 4 44 59 PM](https://user-images.githubusercontent.com/2243202/58514848-a5d08980-8168-11e9-87af-7dcb25c1ae33.png)

We've thought about adding some code in our website to detect whether a URL contains `?commentId` and then appending the proper hash from there. But that feels a bit hacky and we'd prefer to have the "Share" URL be the source of truth.

Thanks!

**Comment by mkonikov** [comment]
FWIW On our site we do load the comments section when `commentId` query is present.

**Comment by kgardnr** [comment]
Whoops lol
