### ISSUE TITLE
Plug-in: distinction between root comments and replies

### ISSUE THREAD

**Issue by vadim-berman** [coralproject/talk#2331]
Hello Coral Talk team,

We're building a plug-in, and at some point, we need to differentiate between a comment which is at the root level vs a reply to another comment. 

We can't find it in the API reference. 

In hooks.js, we link it to editComment / createComment, and the parameters are _context and _info. Is the root / not root distinction available there?

**Comment by kgardnr** [comment]
Hey @vadim-berman were you able to get it working?

**Comment by vadim-berman** [comment]
Hi @kgardnr,

No we weren't, sorry. We decided to put the entire thing on hold because nobody was answering, and we were having concerns over how much effort we should put into the integration. 

On the technical side: maybe it's not the right way to approach it. This is what we're trying to do:

We have a way to determine the relevance of the comment to the article and assign an on-topic score. But how do we integrate it in Talk? Is there a custom sort for the comments, or custom labels? I recall there was something you deprecated, and it was not in the documentation. 

For context, this is our plugin: https://github.com/tisanelabs/talk-plugin-tisane. Similar to Perspective API, but with more languages and transparency. There were more functions we wanted to add, so if you believe it's something your users could use and give us a couple of quick pointers, we will.
