### ISSUE TITLE
CoralTalk MongoDB occasionally loses all data and returns to "initialize" state

### ISSUE THREAD

**Issue by kaichristiansen** [coralproject/talk#2343]
I am running the latest Coraltalk on Digital Ocean closely following your docs and examples with a very vanilla docker-compose setup. Everything works great in general except for a show-stopping mystery. Coral support directed me to create an issue here. 

Sporadically (like once every few weeks), all the comment data disappears. When I login to the admin interface, Coral Talk presents the install interface. What I determined is that the MongoDB volume data is actually being “destroyed” or “reinitialized” (or something). I made a snapshot of the volume data while it was functional with comments, and then made another snapshot after this mysterious “reset”, and most of the Mongo index files have disappeared. I created my own “marker file” with a custom name and a date stamp, and it persists. So, it is not a general docker/volume problem in that it is all or nothing. 

I did install Mongo Express to look at the data in a raw form. I don't THINK Mongo Express is causing this issue, but any insights appreciated!

Has anyone ever seen this before? I have no clue what is happening. Here is my docker compose file. 
(Sensitive data "XX"'ed out. This is a working configuration)

-------
   restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - TALK_MONGO_URL=mongodb://mongo/talk
      - TALK_REDIS_URL=redis://redis
      - TALK_ROOT_URL=XXXXXXX
      - TALK_PORT=3000

      - TALK_JWT_ISSUER=XXXXXX
      - TALK_JWT_AUDIENCE=XXXXXX
      - TALK_JWT_SECRET=XXXXXXXX
      - TALK_JWT_USER_ID_CLAIM=user.id

      - TALK_SMTP_FROM_ADDRESS=XXXXXX
      - TALK_SMTP_USERNAME=XXXXXX
      - TALK_SMTP_PASSWORD=XXXXXXXXX
      - TALK_SMTP_HOST=smtp.mailgun.org
      - TALK_SMTP_PORT=587

      - TALK_DISABLE_REQUIRE_EMAIL_VERIFICATIONS_NOTIFICATIONS=TRUE
      - TALK_CLIENT_FORCE_NOTIFICATION_SETTINGS=TRUE
      - TALK-EMAIL-SUBJECT-PREFIX="XXXXXX"

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=XXXXXX
      - ME_CONFIG_BASICAUTH_PASSWORD=XXXXXX

**Comment by kgardnr** [comment]
Hey @kaichristiansen are you still experiencing this issue?

**Comment by kaichristiansen** [comment]
Hi Kim, 

Thanks for writing. After some trial and error, it seems that the inclusion of MongoExpress (a web-based client for viewing mongodb) was the culprit. I don’t understand why, but I removed MongoExpress from my docker container and the CoralTalk data now persists! Puzzled, but resolved. 

Thank you for following up. So far, CoralTalk is working wonderfully. I appreciate all the work from the team. 

sincerely

Kai

**Comment by kgardnr** [comment]
That's great @kaichristiansen, we're so glad you got it working!
