### ISSUE TITLE
Extending Coral 5.0 without plugin system?

### ISSUE THREAD

**Issue by schwabing** [coralproject/talk#2360]
#### **feature request** and **question**
I want to extend Coral 5.x, but the plugin system seems to have vanished

Plugins have been moved to core, Coral is now super fast and consumes less CPU, which is great. But I can't see how extensions of Coral will be done in the future, with plugin-api gone and all.

What are the plans for plugins/extensions?

#### Version and environment
Coral 5.0.2 Beta

**Comment by kgardnr** [comment]
Hey @schwabing! Welcome to Coral :) What site(s) are you aiming to use it for?

**Comment by schwabing** [comment]
Hi @kgardnr, thanks :)
German editorial sites, one about gadgets, one about cooking, one local news site. 
I'd like to add features such as 

- reactions (similar to fb reactions) 
- a user login widget for the page header, including a notification center (new comments/replies)
- E-mail notifications etc.

**Comment by schwabing** [comment]
Any news on plugins and custom extensions of coral next/5.x? *bump*

**Comment by wyattjoh** [comment]
At present, we are planning on re-introducing plugin-like features down the line, but it will not be included in v5.0.x, though this is likely to take the form of webhooks and API integrations rather than the plugin system you saw in v4.

**Comment by mrhein** [comment]
subscripe the redis>pub/sub over graphql => wss://YOURDOMAIN/api/graphql/live
how it works can be adapted from the admin console => /admin/moderate/reported
initial values need to be extracted over graphql

in this way it is very easy to extend talk with your own microservices
