### ISSUE TITLE
Notifications Settings in My Profile not displaying

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2362]
## Description
I feel like I'm missing a setting or something when trying to include `talk-plugin-notifications` and some of the plugins that are dependent on that.

Here's what I've done
- Activated `talk-plugins-notifications`
- Activated `talk-plugin-notifications-digest-daily`
- Activated `talk-plugin-notifications-digest-hourly`
- Added `TALK_CLIENT_FORCE_NOTIFICATION_SETTINGS=true` to .env
- Added `TALK_DISABLE_REQUIRE_EMAIL_VERIFICATIONS_NOTIFICATIONS=false` to .env

Despite all that, the My Profile settings display does not include any notifications settings.

<img width="538" alt="Screen Shot 2019-06-14 at 9 21 21 AM" src="https://user-images.githubusercontent.com/7051012/59515981-f7298a00-8e85-11e9-9800-a9aa3335a36b.png">

## Version and environment
Currently on version 4.8.0, using Docker.

**Comment by kgardnr** [comment]
Hey @lriggle-strib you'll need to enable the notification categories you want.

They are entitled `talk-plugin-notifications-category-*CATEGORY*`

Examples: 
https://docs.coralproject.net/talk/plugin/talk-plugin-notifications-category-reply
https://docs.coralproject.net/talk/plugin/talk-plugin-notifications-category-featured
https://docs.coralproject.net/talk/plugin/talk-plugin-notifications-category-staff

**Comment by kgardnr** [comment]
More info here too https://docs.coralproject.net/talk/plugin/talk-plugin-notifications

**Comment by lriggle-strib** [comment]
@kgardnr Thanks Kim! I'll pass it along.
