### ISSUE TITLE
Close comments after <period> does not appear to close comments.

### ISSUE THREAD

**Issue by evannagle** [coralproject/talk#2365]
#### Do you want to request a **feature** or report a **bug**?

bug 

#### Intended outcome:

Setting "Close Comment Timeframe" to 1 week.

#### Actual outcome:

Comments are still open on articles older than 1 week.

#### How to reproduce the issue:

Talk hosted via https://www.cmnt.xyz/admin/ and visible on civilbeat.org

Here's a post from May 29th with comments still open: https://www.civilbeat.org/2019/05/case-and-schatz-preach-caution/#comments
<img width="842" alt="Screen Shot 2019-06-16 at 1 02 27 PM" src="https://user-images.githubusercontent.com/556537/59570638-0d2a7c80-9037-11e9-8b35-15cdec79f6be.png">

And our comments are configured to close after 1 week:
<img width="767" alt="Screen Shot 2019-06-16 at 1 01 33 PM" src="https://user-images.githubusercontent.com/556537/59570623-e66c4600-9036-11e9-9009-f86e6254ac1e.png">

#### Version and environment

4.9.0

**Comment by mkonikov** [comment]
IIRC, the change only applies to assets created after the change was made.

**Comment by kgardnr** [comment]
Hey @evannagle! As per @mkonikov's comment, did you just recently turn this on?

**Comment by evannagle** [comment]
Thanks, guys! The setting has been on for awhile, but I just upgraded to 4.9.0. I do see that comment streams from June 16th have been closed, so I'm just checking with the editor to confirm that those were auto-closed and not updated manually.

**Comment by kgardnr** [comment]
Sounds great @evannagle!

**Comment by evannagle** [comment]
Alright, editors have confirmed that this is working. Thanks for the quick reply, guys!
