### ISSUE TITLE
Talk assets support for SPA

### ISSUE THREAD

**Issue by sangeraj** [coralproject/talk#2380]
Hi - looking for guidance on integrating Talk with our React SPA. Currently having issue with unique asset title being set on the Talk asset. Any workaround for this as it seems like a common pattern? Thanks

**Comment by kgardnr** [comment]
Hi @sangeraj! What site/sites are you running Talk on or looking to run it on?

**Comment by sangeraj** [comment]
Hi @kgardnr - unfortunately I’m unable to share the link to our app here as it is inside company firewall. It’s a single page react app that embeds a locally hosted instance of Talk. We use the “@coralproject/talk-plugin-custom-asset-id: 1.1.0” in the Talk instance as a plugin.

**Comment by kgardnr** [comment]
Hi @sangeraj, that's fine! In that case, just shed some more light on what your organization's name is and what you're using Talk for; that will help us give you appropriate advice here

**Comment by sangeraj** [comment]
We’re creating a intranet blogging platform and integrating Talk for the commenting feature.

**Comment by kgardnr** [comment]
And what's the name of your company/organization @sangeraj?

**Comment by kgardnr** [comment]
Closing as we never heard back
