### ISSUE TITLE
Talk API Get All Assets and their comments?

### ISSUE THREAD

**Issue by AuroraEscapes** [coralproject/talk#2381]
Hi, Looking for guidance on getting all assets and their comments from talk.
There is the v1/assets API but that doesn't return comments. Is there a way to pull this too?

**Comment by kgardnr** [comment]
Hi @AuroraEscapes, thank you for getting in touch! Where are you currently running Talk?

**Comment by kgardnr** [comment]
Closing issue as we never heard back
