### ISSUE TITLE
Pre-moderate comments containing links not working

### ISSUE THREAD

**Issue by gabelula** [coralproject/talk#239]
### Expected behavior

When 'Pre-Moderate Comments Containing Links' is ON then all the comments that contain links go to the moderation queue.

### Actual behavior

Comments are being displayed.

### Steps to reproduce behavior

- click on 'Pre-Moderate Comments Containing Links'
- add a comment with a link

**Comment by jde** [comment]
This story has been reprioritized. Hiding the UI component until we get around to adding the feature.

**Comment by jde** [comment]
https://github.com/coralproject/talk/pull/260
