### ISSUE TITLE
iOS Copy Permalink

### ISSUE THREAD

**Issue by mkonikov** [coralproject/talk#2397]
Generally the permalink overlay closes when clicking / tapping outside the overlay area but on iOS it does not.

Nothing pressing but an observation from our QA team that I thought to share.

![image](https://user-images.githubusercontent.com/7562285/60919437-b265f880-a263-11e9-9e8c-b11a7f451674.png)

**Comment by kgardnr** [comment]
Hey @mkonikov I'm going to mark this as a wont-fix; if you (or anyone else) would like to submit a PR for this, just let us know though!
