### ISSUE TITLE
Cannot turn off email verification in My Profile

### ISSUE THREAD

**Issue by lriggle-strib** [coralproject/talk#2403]
## Description
We are continuing to do testing with notifications plugins within the Talk application, but we are running into an issue around email verification within the My Profile tab. We are unable to turn it off.

#### Plugins Installed
- `talk-plugin-notifications`
- `talk-plugin-notifications-digest-daily`
- `talk-plugin-notifications-digest-hourly`
- `talk-plugin-notifications-category-reply`

#### Environment Variables Added
- `TALK_CLIENT_FORCE_NOTIFICATION_SETTINGS=true`
- `TALK_DISABLE_REQUIRE_EMAIL_VERIFICATIONS_NOTIFICATIONS=true`

Even with those two vars added, the interface still looks like this:

<img width="536" alt="Screen Shot 2019-07-12 at 12 56 52 PM" src="https://user-images.githubusercontent.com/7051012/61148510-93a27480-a4a4-11e9-8bae-230e4aba2eab.png">

## Related Issues
- https://github.com/coralproject/talk/issues/2362

**Comment by wyattjoh** [comment]
Hey @lriggle-strib 👋! It looks like the case of your booleans are lowercase, Talk requires that they are uppercase:

```
TALK_CLIENT_FORCE_NOTIFICATION_SETTINGS=TRUE
TALK_DISABLE_REQUIRE_EMAIL_VERIFICATIONS_NOTIFICATIONS=TRUE
```

Let me know if that resolves the issue!

**Comment by lriggle-strib** [comment]
@wyattjoh That fixes it, thanks!
