### ISSUE TITLE
review admin comments

### ISSUE THREAD

**Issue by mehdignu** [coralproject/talk#2417]
#### Do you want to request a **feature** or report a **bug**?
report a bug

#### Intended outcome:
review the admin comments

#### Actual outcome:
admin comments could not be reviewed on the backend

#### How to reproduce the issue:
upgrade coral to the latest version

#### Version and environment
v5.0.0-beta.4

**Comment by kgardnr** [comment]
Hey @mehdignu! This is by design actually, we assume that admin/moderator/staff comments do not need to be moderated.

Can you tell us where you're planning to use Coral?
