### ISSUE TITLE
Facebook ID not stored

### ISSUE THREAD

**Issue by ianwelsh** [coralproject/talk#2421]
#### Do you want to request a **feature** or report a **bug**?
Bug

#### Intended outcome:
We only allow users to login via the facebook auth plugin by hiding the other login form options. We would expect the Facebook user's Facebook ID to show beside the Facebook ID field in the UI.

#### Actual outcome:
The Facebook ID value in the UI is the same as the Talk ID value. It doesn't seem to be a valid Facebook ID. For instance, this user in the Talk UI has a FB ID of 2243476219247446, but the user's actual FB ID is 100007552696357(see https://www.facebook.com/profile.php?id=100007552696357). 

Screenshot:
<img width="551" alt="Screen Shot 2019-07-25 at 3 28 38 PM" src="https://user-images.githubusercontent.com/8646670/61902806-ef332000-aef0-11e9-9259-67524fd7ec8a.png">

Here is the record in mongo:
```
{
	"_id" : ObjectId("5cf69e9ebf70aa001fb49c62"),
	"status" : {
		"username" : {
			"status" : "SET",
			"history" : [
				{
					"assigned_by" : null,
					"_id" : ObjectId("5cf69e9ebf70aa001fb49c63"),
					"status" : "UNSET",
					"created_at" : ISODate("2019-06-04T16:38:54.959Z")
				},
				{
					"assigned_by" : "2243476219247446",
					"_id" : ObjectId("5cf69eadbf70aa001fb49c64"),
					"status" : "SET",
					"created_at" : ISODate("2019-06-04T16:39:09.228Z")
				}
			]
		},
		"banned" : {
			"status" : false,
			"history" : [ ]
		},
		"suspension" : {
			"until" : null,
			"history" : [ ]
		},
		"alwaysPremod" : {
			"status" : false,
			"history" : [ ]
		}
	},
	"role" : "ADMIN",
	"ignoresUsers" : [ ],
	"id" : "2243476219247446",
	"username" : "William_Ariel",
	"lowercaseUsername" : "william_ariel",
	"profiles" : [
		{
			"id" : "2243476219247446",
			"provider" : "facebook"
		}
	],
	"tokens" : [ ],
	"tags" : [ ],
	"created_at" : ISODate("2019-06-04T16:38:54.960Z"),
	"updated_at" : ISODate("2019-06-04T18:59:47.633Z"),
	"__v" : 0
}
```

#### How to reproduce the issue:
Log in via Facebook. Observe that the stored FB ID is not the real FB ID and is the same value as the Talk ID. 

#### Version and environment
Runs in Docker off the coralproject/talk:4-onbuild image. 
Plugins used:
```
{
  "server": [
    "talk-plugin-facebook-auth",
    "talk-plugin-respect",
    "talk-plugin-akismet",
    "talk-plugin-sort-newest",
    "talk-plugin-sort-oldest",
    "talk-plugin-sort-most-replied",
    "talk-plugin-deep-reply-count",
    "talk-plugin-toxic-comments",
    "talk-plugin-custom-asset-id",
    {"@coralproject/talk-plugin-comment-count": "^0.0.3-beta"}
  ],
  "client": [
    "talk-plugin-auth",
    "talk-plugin-author-menu",
    "talk-plugin-flag-details",
    "talk-plugin-moderation-actions",
    "talk-plugin-respect",
    "talk-plugin-viewing-options",
    "talk-plugin-sort-most-replied",
    "talk-plugin-sort-most-respected",
    "talk-plugin-sort-newest",
    "talk-plugin-sort-oldest",
    "talk-plugin-ignore-user",
    "talk-plugin-facebook-auth",
    "talk-plugin-akismet",
    "talk-plugin-comment-content",
    "talk-plugin-toxic-comments",
    "talk-plugin-permalink"
  ]
}
```

**Comment by wyattjoh** [comment]
The Facebook User ID being stored is the App Scoped User ID. Facebook's API's do not provide the actual Facebook User ID any more as per some privacy changes made in their new API. See [here](https://www.hellotecho.com/facebook-app-scoped-user-ids-in-api-v2) for a little explainer on it.

**Comment by kgardnr** [comment]
Hey @ianwelsh what newsroom or organization are you with? Just curious where you're using Coral :) Thanks!

**Comment by ianwelsh** [comment]
@kgardnr We're using Coral Talk for comments at [WRAL.com](https://www.wral.com/).

@wyattjoh Thanks for the response. It looks like Facebook used to allow accessing the user's profile via the `https://www.facebook.com/app_scoped_user_id/xxxxxxxxxxxxx` endpoint, but they have disabled it (source: https://developers.facebook.com/blog/post/2018/04/19/facebook-login-changes-address-abuse/). Is there currently a way that you know of to find the Facebook profile of the Talk user with what is being stored?

Is my only option here, if I want to be able to reach out to the Facebook user, to modify the talk-plugin-facebook-auth plugin to store the user's email or profile link? It looks like passport.js may be able to provide those to me. If so, do you foresee this being a difficult change?

**Comment by wyattjoh** [comment]
Unfortunately, as per the url you linked, it doesn't seem possible to resolve the app scoped user profile.

We had initially looked at having the facebook plugin pull the email address, but it was a design decision to instead have the email address populated by the user directly. You are free however to create your own facebook plugin for Talk that implements your desired behaviour, but it would be unlikely to be merged into our core codebase.
