### ISSUE TITLE
User comment history not showing in Settings tab

### ISSUE THREAD

**Issue by jde** [coralproject/talk#243]
### Expected behavior

All published comments should show under Settings in the user tab.

### Actual behavior

Comments are not showing.

Note in this image that they _are_ being returned from the api with the appropriate statuses.

![unspecified](https://cloud.githubusercontent.com/assets/259957/22030716/821eec92-dcac-11e6-8bdb-08a03f39400a.jpg)

### Steps to reproduce behavior

* Add comments and approve them
* Click settings
* Note they're not there

**Comment by kgardnr** [comment]
This is also fixed in @riley's PR. Closing.

**Comment by kgardnr** [comment]
Fixed in https://github.com/coralproject/talk/pull/250
