### ISSUE TITLE
[Next] Popup too small for some providers

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#2430]
I'm using OIDC for my talk instance but I've a problem with popup height. It looks this way:

![image](https://user-images.githubusercontent.com/25023177/62080445-0b9fc700-b227-11e9-8fc2-be0f769031be.png)

The same with google login:
![image](https://user-images.githubusercontent.com/25023177/62080521-368a1b00-b227-11e9-8e37-c3988a84af7e.png)

What do you think if we have the option to set popup size in talk admin?

**Comment by wyattjoh** [comment]
We are aware of resizing issues affecting that popup, a bug fix is in the queue!

**Comment by kgardnr** [comment]
@cristiandean this should be fixed now on `next` - can you confirm?

**Comment by cristiandean** [comment]
Yes, it is @kgardnr Thank you =)
