### ISSUE TITLE
[BUG] Code duplication.

### ISSUE THREAD

**Issue by musically-ut** [coralproject/talk#2441]
#### Do you want to request a **feature** or report a **bug**?

Likely a merge artifact.

It seems that the code for creation of an index is duplicated here:

https://github.com/coralproject/talk/blob/73040b1314e6dea5b53a8550f99291cdad798768/plugin-api/beta/server/getReactionConfig.js#L14-L34

However, since the method is idempotent, the second call is a NOP.

**Comment by PepeFranco** [comment]
I've dug around the code looking for this but couldn't find it in the current version. Seems it is on v4?
I created a PR for that branch as I couldn't find those files in any other branch.
https://github.com/coralproject/talk/pull/2618

**Comment by wyattjoh** [comment]
Thanks for the find!
