### ISSUE TITLE
[next] Admin login with OIDC

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#2443]
Hello, we found a bug in Talk admin login with Open ID Connect. 

To reproduce: 

1. Enable OIDC on admin
2. Try log in to admin dashboard

**Expected behavior:**
Redirect to admin dashboard

**Current behavior:**
Redirect to `/embed/auth/callback`
![image](https://user-images.githubusercontent.com/25023177/62392269-6b56e480-b53d-11e9-835c-8b1a98698356.png)

---

The user is authenticated, but the redirect doesn't work as expected.

**Comment by kgardnr** [comment]
Hey @cristiandean! Another person just logged this bug with us yesterday, funny enough! We've got it prioritized to fix! Thank you! 🐞

**Comment by kgardnr** [comment]
@cristiandean this is fixed here: https://github.com/coralproject/talk/pull/2493

Let us know if it works for you as well!
