### ISSUE TITLE
[NEXT] GraphQLError invalid operator  $objectToArray

### ISSUE THREAD

**Issue by bderen** [coralproject/talk#2454]
I'm receiving the graphql error on the "moderate" page

I have Coral Next and MongoDB 3.2.11

Nodejs error log:
`
"tenantID":"f5777e76-f8ef-4e79-8a0d-52f091029f45","context":"graph","contextID":"d2524ce0-ba80-11e9-8746-09aca8900a2e","level":50,"err":{"message":"invalid operator '$objectToArray'","name":"GraphQLError","originalError":{"message":"invalid operator '$objectToArray'","name":"MongoError"...
`

Browser console log:
`
"id": "QueueRouteReportedQuery",
    "payload": {
        "data": null,
        "errors": [{
            "message": "INTERNAL_ERROR",
            "locations": [{
                "line": 4,
                "column": 3
            }],
            "path": ["moderationQueues"],
            "extensions": {
                "code": "INTERNAL_ERROR",
                "id": "d2655fb0-ba80-11e9-8746-09aca8900a2e",
                "type": "INVALID_REQUEST_ERROR",
                "message": "INTERNAL_ERROR"
            }
        }]
    }
`

**Comment by wyattjoh** [comment]
Coral requires at least MongoDB 3.6, `$objectToArray` was introduced in 3.4.4. Upgrading your database version should resolve that issue.
