### ISSUE TITLE
Mixed Pre/Post moderation tenant support

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#2485]
Hello, I'd like to know what you think about a feature that would allow a mixed pre/post moderation scenario based on article category for example.  So we could customize which categories could be pre-moderated and which would be post-moderated maybe using `article:section` of Open Graph Protocol.

**Comment by wyattjoh** [comment]
We already have a feature in the works that would support exactly this use case! For now, we'd recommend using the `createStory` mutation with an Admin token to create stories with the desired moderation state instead of relying on the lazy asset creation until the feature lands.

**Comment by cristiandean** [comment]
Thanks @wyattjoh!

**Comment by deichholz** [comment]
This request is from 2019. Has this feature progressed to a point where this is an option? We would like to make all stories matching a specific pattern/category to be post moderation.
