### ISSUE TITLE
Feature idea: documentation for how to connect WordPress authentication to Talk v5

### ISSUE THREAD

**Issue by jonathanstegall** [coralproject/talk#2504]
I'm hoping that with the upcoming release of v5, there could be some documentation about how to connect WordPress authentication so users who are signed in to WordPress would also be signed in to Talk.

I was reading #1567 (which was just closed), and there's a comment (hoping this warrants making a separate issue):

> Hey @davisshaver I think you will find that auth/SSO is very improved and simpler to implement in v5, would love your feedback! v5 official release is coming first week of September 🎉

This is of course exciting, and maybe we could see how this would work, specifically in WordPress?

**Comment by kgardnr** [comment]
Hey @jonathanstegall (cc @davisshaver), you can do this with a JWT token. I believe there are WP plugins that can either help in this regard. Would love some feedback once you both try out v5!
