### ISSUE TITLE
[Next] Changing username of SSO user doesn't work.

### ISSUE THREAD

**Issue by bderen** [coralproject/talk#2507]
Hi there,

when the user is logged in using SSO he can change his username. But as soon as he logs in again with SSO the username is overwritten by the value from JWT.
Is this a bug or a feature?
How can I prevent the username to be overwritten?

**Comment by wyattjoh** [comment]
What version of Coral are you using @sgtram?

**Comment by bderen** [comment]
@wyattjoh I'm using Coral 5 beta 8

**Comment by kgardnr** [comment]
@sgtram we don't advise allowing SSO users to manage their account in Coral; this should all be done from your SSO system as the single source of truth.

**Comment by kgardnr** [comment]
Oh, so to answer your question - it's a feature 😄
