### ISSUE TITLE
[Next] level of responses / answers (Question)

### ISSUE THREAD

**Issue by bderen** [coralproject/talk#2508]
Is it possible or will be possible to limit the level of responses/answers to the comment?

**Comment by wyattjoh** [comment]
Not at this time no. We are planning on exploring the idea in the feature though, so any feedback or use cases would be welcome!

**Comment by kgardnr** [comment]
Also as a general direction here, we had configuration/limitations in v4 and got feedback to move in the direction of allowing nearly-infinite conversations, so I think this won't be on our roadmap for some time. I'll go ahead and close this.
