### ISSUE TITLE
How to make Talk Service url as Secured with Digital cert and other cert mechanisms

### ISSUE THREAD

**Issue by koushiktalk** [coralproject/talk#2510]
currently we have certificate installed for Talk url but its throwing below error.

 [AFT-DME2-0718]: Attempt to get response from endpoint failed within the request timeout period. Validate that service is running in a healthy state, no failover will be attempted as input is of type stream. [Context: service=http://DME2RESOLVE/service=com.att.kepler.pinnacle.pinnacle-talk/version=1.0.0/envContext=UAT/routeOffer=DEFAULT;endpointsAttempted=[EP=http://hlth578.hydc.sbc.com:30416/admin/moderate:closed];]]

**Comment by kgardnr** [comment]
Hey @koushiktalk! Welcome aboard! Where will you be using Coral?
