### ISSUE TITLE
Reporting / statistics dashboard

### ISSUE THREAD

**Issue by bderen** [coralproject/talk#2511]
Hi,
I have a couple questions.
Does coral have a report/statistics dashboard?
So I can see how many comments in total, how many rejected, accepted, which moderator did what?
Besides that: Is there a possibility to reject an already approved comment?

**Comment by kgardnr** [comment]
Hey @sgtram we do have reporting/analytics on our roadmap for the future, I'm unsure of any timelines for that at the moment.

Re: rejecting an already approved comment, can you explain more the use case for this?
