### ISSUE TITLE
[Next] wrong reactions number in the badge

### ISSUE THREAD

**Issue by bderen** [coralproject/talk#2512]
Hi there,

on the pages:
/admin/moderate/pending
/admin/moderate/unmoderated

we see a wrong number of reactions in the badge, for example, it says 262 but there is none on the page.

Coral Beta 7

**Comment by kgardnr** [comment]
@sgtram can you check the caching/CDN/server configuration on your end and report back?

**Comment by kgardnr** [comment]
Hey @sgtram we were able to confirm this is a bug, we have a fix for it here going out in the next release: https://github.com/coralproject/talk/pull/2516
