### ISSUE TITLE
[Next] some words  in the comment displayed as a link

### ISSUE THREAD

**Issue by bderen** [coralproject/talk#2513]
Hi there,

we see some strange behavior in the comments. Some words combinations, somehow are displayed as a link.

Here is an example:
this is original text from the user
`wie is nu de crimineel.in mijn ogen is`

this is how its displayed
`wie is nu de http://crimineel.in mijn ogen is`

How this is possible? And is there a way to restrict or sanitize the user input?

**Comment by kgardnr** [comment]
Hey @sgtram, if a commenter incorrectly uses punctuation, as in this case, it will read it as domain + tld. Unfortunately we can't correct for this.
