### ISSUE TITLE
Cli tool should initialize settings

### ISSUE THREAD

**Issue by jde** [coralproject/talk#252]
### Expected behavior

Settings should always be initialized no matter how we access the app. 

We should be able to use the cli tool before running the server.

### Actual behavior

Currently, settings init only happens when we run the server, so if we try to do something with the cli first, we get errors.

### Steps to reproduce behavior

drop your db
try to run `bin/cli users create`

**Comment by wyattjoh** [comment]
This is currently implemented with the `bin/cli settings init` action.

**Comment by jde** [comment]
Is there an argument for keeping this initialization step explicit? As far as I can see, there is not case in which the cli or the server should ever be run without an initialized settings object. 

My thought is to lazy initialize settings with the same mechanism that checks each time we start the app. This will prevent the need for an extra step that doesn't take any configuration and potential confusion for users trying to use the cli before starting the app.

**Comment by wyattjoh** [comment]
Really, this should be handled when we get to the "first time setup" story, to mirror tech like "wordpress" and what not. The cli could complain that you must run the "first time setup" instead of actually initializing it each time.
