### ISSUE TITLE
Enabling SSL in Talk

### ISSUE THREAD

**Issue by vtisnado** [coralproject/talk#2522]
I dont think this is a bug, maybe is a feature that already exists, but I cant find any guide in the documentation.

We have Talk installed in a virtual machine and everything works fine, but we can not find any image or setup to enable SSL. 

Im sorry if this is a dummy question, but I think having the steps in the documentation will also help others.

#### Intended outcome:
Serving comments over HTTPS.

#### Actual outcome:
The server needs to be configured with SSL.

#### How to reproduce the issue:
Just follow the steps in the Quickstart and Talk will be operating over HTTP, but not working with HTPPS.

#### Version and environment
Ubuntu 18.04.3 LTS
Talk v4.10.3

**Comment by wyattjoh** [comment]
The quickstart guide is not intended as a production deployment (with SSL). To do that you'll need to consult the documentation of a fronting webserver (as Talk will not manage or handle SSL).

**Comment by vtisnado** [comment]
> The quickstart guide is not intended as a production deployment (with SSL). To do that you'll need to consult the documentation of a fronting webserver (as Talk will not manage or handle SSL).

Ok, so as I understand with your answer, for production we need to setup a webserver (Nginx for example) to handle the HTTPS request and works like a proxy, is this right?

Nevertheless as an open source, I think the configuration steps for production should be in the documentation as well.

**Comment by wyattjoh** [comment]
You would need to use a webserver like caddy or nginx yes. We decided not to include those instructions as we felt that they were outside the bounds of our instructions, and our own tutorials would likely not do it justice to document.
