### ISSUE TITLE
[Next] Cannot return null for non-nullable field Settings.accountFeatures

### ISSUE THREAD

**Issue by bderen** [coralproject/talk#2526]
`
{"message":"Cannot return null for non-nullable field Settings.accountFeatures.","name":"GraphQLError","originalError":{"message":"Cannot return null for non-nullable field Settings.accountFeatures.","name":"Error","stack":"completeValue (node_modules/graphql/execution/execute.js:631:13)\ncompleteValueWithLocatedError (node_modules/graphql/execution/execute.js:580:21)\ncompleteValueCatchingError (node_modules/graphql/execution/execute.js:550:12)\nresolveField (node_modules/graphql/execution/execute.js:497:10)\nnode_modules/graphql/execution/execute.js:364:18\nArray.reduce (<anonymous>)\nexecuteFields (node_modules/graphql/execution/execute.js:361:42)\ncollectAndExecuteSubfields (node_modules/graphql/execution/execute.js:772:10)\ncompleteObjectValue (node_modules/graphql/execution/execute.js:762:10)\ncompleteValue (node_modules/graphql/execution/execute.js:660:12)\ncompleteValue (node_modules/graphql/execution/execute.js:629:21)\ncompleteValueWithLocatedError (node_modules/graphql/execution/execute.js:580:21)\ncompleteValueCatchingError (node_modules/graphql/execution/execute.js:550:12)\nresolveField (node_modules/graphql/execution/execute.js:497:10)\nnode_modules/graphql/execution/execute.js:364:18\nArray.reduce (<anonymous>)\n"}},"msg":"graphql query error","time":"2019-09-05T10:09:31.414Z","src":{"file":"src/core/server/graph/common/extensions/LoggerExtension.ts","line":13,"func":"error"},"v":0}
`
I'm getting this error on the admin/configure/auth page  after i've upgraded coral to beta-8
Could you please advise?

**Comment by bderen** [comment]
I've changed one line in shcema.graphql file
line 1218
`accountFeatures: CommenterAccountFeatures`

it was before `accountFeatures: CommenterAccountFeatures!`

now it works.

**Comment by wyattjoh** [comment]
It looks like you upgraded from v5.0.0-beta.7 to v5.0.0-beta.8 without running the mentioned required migrations, see https://github.com/coralproject/talk/pull/2497 for instructions.
