### ISSUE TITLE
[Next][Bug] authRedirectBackTo session storage key not set

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#2529]
After update the last release (v5.0.0-beta.8) we had a problem. 

After the user authenticate in the Talk, the authentication happen with success, but the user receives the following message in the pop up: "authRedirectBackTo session storage key not set"

This is when we have a single provider enabled (OIDC).

**Comment by wyattjoh** [comment]
To clarify @cristiandean, this is only in the Admin? I was unable to reproduce the issue on our side.

**Comment by cristiandean** [comment]
@wyattjoh this is in embed stream. For reproduce you have to:

Enable OpenID provider with a valid provider.
Disable all others providers for embed stream.


This is a fresh install after that steps:
![Screen Shot 2019-09-10 at 16 02 13](https://user-images.githubusercontent.com/25023177/64642292-6874cc80-d3e4-11e9-9aca-3399b5f36c36.png)

**Comment by cristiandean** [comment]
@wyattjoh  This happen when we use only one provider #2422 . For this reason, the user don't click in the "Sign in with ..." provider button and the function `handleOnClick` is not called.

![image](https://user-images.githubusercontent.com/25023177/64863744-f8488f80-d60b-11e9-83a9-5b2bb0824bbf.png)

The `handleOnClick` should call `redirectOAuth2` that set `authRedirectBackTo=/embed/auth` in the session storage. The error occurs because the handle click is never called.

**Comment by wyattjoh** [comment]
Great catch! We'll **address** this in the next release!
