### ISSUE TITLE
Admin Community: User roles should be additive, not toggling

### ISSUE THREAD

**Issue by jde** [coralproject/talk#253]
We have a mismatch between the element in the community page and the user role concept on the backend.  The backend is configured to allow users to have any number of roles.  The frontend has a dropdown toggle which only sends one role, adding it to the list.

My recommendation is to update our front end code to use a checkbox/tag widget to allows us to have more than one role.

Limiting users to single roles on the backend isn't a long term solution, as we already have stories that differentiate Moderators from Admins.

**Comment by kgardnr** [comment]
@jde Isn't this same thing solved if the roles themselves are additive/hierarchical? 

Eg. 
contributor - can do X
moderator - can do everything a contributor can, plus Y
admin - can do everything a moderator can, plus Z
