### ISSUE TITLE
[Next] Logout event - Question

### ISSUE THREAD

**Issue by bderen** [coralproject/talk#2535]
Hi there,
you have a custom event for login popup
`events.on("loginPrompt"...`

Do you have an event for logout click? 
Would be nice to have something similar

`events.on("logoutPrompt"...`

so we can redirect the user to the proper SSO logout endpoint

**Comment by wyattjoh** [comment]
We would suggest in this situation to instead issue JWT's for SSO without a JTI so you can display your own auth logout links outside Coral, as in that case, you are already managing the auth state.
