### ISSUE TITLE
Add custom button to SSO provider

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#2564]
What are you think about a custom button to the Single Sign On provider in administration? Something like that:

![image](https://user-images.githubusercontent.com/25023177/64815106-4792af80-d57b-11e9-9879-b8dcc834db48.png)

I wold also like to know if it's possible to have a route like `/api/auth/sso` where the administrators can use to login passing the SSO token as a parameter. Or do you recommend doing it another way?

I can help with the PRs if necessary.

Thank you

**Comment by kgardnr** [comment]
Hey @cristiandean sorry for the delay here. Did you still want to contribute this?

**Comment by cristiandean** [comment]
What do you think? Does that still make sense? As we don't have an established protocol to login the user with SSO maybe it could be done by another service. 
In addition we have the same problem here #2603
