### ISSUE TITLE
Cannot manually initiate installation wizard for new tenants

### ISSUE THREAD

**Issue by zikes** [coralproject/talk#2568]
**Expected behavior:**

When adding a new tenant/domain to Talk, there should be a way to trigger the installation wizard to configure the new tenant/domain and admin user.

**Actual behavior:**

At present, no known/documented method to do the above.

**Related Issues:** 

**Versions:**

- Talk: 5.0.0

**Comment by zikes** [comment]
I have managed to configure Talk 5.0.0 by manually copying and modifying the tenant and user objects in mongodb, but using the built-in Installation Wizard would make this process much easier.

**Comment by wyattjoh** [comment]
While Coral v5 does offer multi-tenant support, it is not currently planned to add support to manage multiple tenants yet. We'll keep this issue updated when our roadmap changes.
