### ISSUE TITLE
Error when using SSO

### ISSUE THREAD

**Issue by allanassis** [coralproject/talk#2579]
### Hi guys, first thanks for this awesome project!!

So , I had a issue when trying to use SSO, i just called the method to login and did not work.

![Screen Shot 2019-09-19 at 5 26 41 PM](https://user-images.githubusercontent.com/23871115/65278594-cef39c00-db02-11e9-97f7-e5064fe6cc61.png)

![image](https://user-images.githubusercontent.com/23871115/65278678-f8142c80-db02-11e9-923f-a7f34058e7f0.png)

![Screen Shot 2019-09-19 at 5 29 29 PM](https://user-images.githubusercontent.com/23871115/65278803-3f9ab880-db03-11e9-9670-ae9dcaf3d41d.png)

![image](https://user-images.githubusercontent.com/23871115/65278833-4f1a0180-db03-11e9-94ce-6b5b1b67e71a.png)

![Screen Shot 2019-09-19 at 5 20 39 PM](https://user-images.githubusercontent.com/23871115/65278239-10377c00-db02-11e9-92c3-11cbd8bc2c86.png)

![image](https://user-images.githubusercontent.com/23871115/65279121-e41cfa80-db03-11e9-9249-9e2a279d45c6.png)

**Expected behavior:*Create the user in mongo only once when `embed.login({JWT_TOKEN})` was called*

**Actual behavior:*When i call `embed.login({JWT_TOKEN})` there are two calls trying to create an user, the first call creates the user and the second one throw an error*

**Related Issues:** 

**Versions:**

- NodeJS: `10.15.1`
- NPM: `6.4.1`
- MongoDB: `4.0.4`
- Redis: `5.0.5`
- Browser: Chrome
- OS: Mac OS

**Comment by wyattjoh** [comment]
We've discovered the issue with the race, it should be corrected in v5.1.0.

**Comment by cristiandean** [comment]
Tyvm @wyattjoh
