### ISSUE TITLE
SSO login should create authorization cookie

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#2603]
**Expected behavior:**
The user should remain logged in when the page is refreshed after authenticating via SSO.

**Actual behavior:**
When SSO integration is enable and `talkEmbed.login(token)` is called with a valid token, the user is logged in. But when the page is refreshed, the user isn't logged anymore.

**Comment by wyattjoh** [comment]
Hi @cristiandean!

Unfortunately, with the advent of mobile advertisements injecting tracking cookies, we are unable to set a cookie without user interaction (like a click). If we were to do so, we would have 3rd party cookie status, and would likely get blocked anyways by Safari/Firefox users.

The feature as it is currently designed requires the authentication token to be generated for every page load of the embed unfortunately.
