### ISSUE TITLE
story ids with a slash break moderation views.

### ISSUE THREAD

**Issue by benjaminkreen** [coralproject/talk#2611]
I'm experimenting with using Talk for a science journal and I tried to key the story id to a DOI, our standard identifier. I think because DOIs contain slashes, it breaks the moderation view. I guess the slash should probably be escaped with `%2F`. I'm still getting to know the codebase (and typescript) otherwise I'd file a pull request. 

**Expected behavior:**
Moderation page displays correctly for a given story id.
**Actual behavior:**
<img width="944" alt="image" src="https://user-images.githubusercontent.com/5441006/65985776-53191e00-e437-11e9-9a24-d8595a4b0fcc.png">
the story id was set to `10.1371/journal.pntd.0007447`
**Related Issues:** 

**Versions:**
talk v5.1.0

I just used the heroku deploy button, but i'm assuming it doesn't have much bearing on this issue and they weren't readily aparent from the heroku dash. I can dig deeper if needed.
- NodeJS:
- NPM:
- MongoDB:
- Redis:
- Browser: Firefox 70.0b2 (64-bit)
- OS: MacOS 10.12.6

**Comment by wyattjoh** [comment]
Great find @benjaminkreen! We should have this addressed in the next release.
