### ISSUE TITLE
OpenID Connect user registration flow when email absent from identity provider fails

### ISSUE THREAD

**Issue by benjaminkreen** [coralproject/talk#2622]
One of the identity providers we work with is ORCiD who has implemented OpenID Connect, but it seems like the Joi model for the token expects an `email` key which isn't present in [their implementation](https://github.com/ORCID/ORCID-Source/blob/master/orcid-web/ORCID_AUTH_WITH_OPENID_CONNECT.md#what-is-an-id_token)
**Expected behavior:**

OpenID integration not require a value for `email` in the `id_token`, prompt user upon registration for an email address if its missing and accept valid user input.

**Actual behavior:**
With `email` enforcement:
![enforce_email](https://user-images.githubusercontent.com/5441006/66163749-de381680-e5e5-11e9-8d50-8642731ff9cd.gif)

I tinkered with the schema a bit:
```diff
--- a/src/core/server/app/middleware/passport/strategies/oidc/index.ts
+++ b/src/core/server/app/middleware/passport/strategies/oidc/index.ts
@@ -39,7 +39,7 @@ export interface OIDCIDToken {
   iss: string;
   sub: string;
   exp: number; // TODO: use this as the source for how long an OIDC user can be logged in for
-  email: string;
+  email?: string;
   email_verified?: boolean;
   picture?: string;
   name?: string;
@@ -52,7 +52,7 @@ export const OIDCIDTokenSchema = Joi.object()
     sub: Joi.string().required(),
     iss: Joi.string().required(),
     aud: Joi.string().required(),
-    email: Joi.string().required(),
+    email: Joi.string().default(undefined),
     email_verified: Joi.boolean().default(false),
     picture: Joi.string().default(undefined),
     name: Joi.string().default(undefined),
@@ -60,6 +60,7 @@ export const OIDCIDTokenSchema = Joi.object()
     preferred_username: Joi.string().default(undefined),
   })
   .optionalKeys([
+    "email",
     "picture",
     "email_verified",
     "name",
```
and it seems like you have a fallback in place for missing email, but I ran up against another error:

![relax_email](https://user-images.githubusercontent.com/5441006/66164123-cdd46b80-e5e6-11e9-934b-828e3d646bb3.gif)

and this server output:
```console
[2019-10-03T21:04:31.727Z] ERROR: coral/85291 on US-MC-00950.local(/Users/bmiller/PLOS/talk/src/core/server/graph/common/extensions/LoggerExtension.ts:14 in logError): graphql query error (clusterNode=master, tenantID=5aec2a48-fbfb-4015-bcf7-59e09adccb00, context=graph, contextID=6525dc00-e621-11e9-bcf3-798b289f8a07)
    err: {
      "message": "USER_NOT_ENTITLED",
      "name": "GraphQLError",
      "originalError": {
        "message": "USER_NOT_ENTITLED",
        "name": "UserForbiddenError",
        "stack": "auth (src/core/server/graph/common/directives/auth.ts:142:13)\nfield.resolve (node_modules/graphql-tools/src/generate/attachDirectiveResolvers.ts:31:18)\nfield.resolve (node_modules/apollo-server-core/node_modules/graphql-extensions/src/index.ts:274:18)\nresolveFieldValueOrError (node_modules/graphql/execution/execute.js:531:18)\nresolveField (node_modules/graphql/execution/execute.js:495:16)\nnode_modules/graphql/execution/execute.js:339:18\nnode_modules/graphql/jsutils/promiseReduce.js:25:10\nArray.reduce (<anonymous>)\npromiseReduce (node_modules/graphql/jsutils/promiseReduce.js:22:17)\nexecuteFieldsSerially (node_modules/graphql/execution/execute.js:336:38)\nexecuteOperation (node_modules/graphql/execution/execute.js:289:55)\nexecuteImpl (node_modules/graphql/execution/execute.js:154:14)\nObject.execute (node_modules/graphql/execution/execute.js:131:35)\nnode_modules/apollo-server-core/src/requestPipeline.ts:464:30\nGenerator.next (<anonymous>)\nnode_modules/apollo-server-core/dist/requestPipeline.js:7:71\n",
        "id": "652825f0-e621-11e9-bcf3-798b289f8a07",
        "context": {
          "pub": {},
          "pvt": {
            "reason": "authentication conditions not met",
            "userID": "712ea0c4-42ee-4d9c-8227-f9af7117076f",
            "resource": "setEmail",
            "operation": "mutation",
            "conditions": [
              "MISSING_EMAIL",
              "MISSING_NAME"
            ],
            "permit": [
              "MISSING_EMAIL",
              "SUSPENDED",
              "BANNED",
              "PENDING_DELETION"
            ]
          }
        }
      }
    }
```

I'll keep poking at it, but figured I'd raise the issue.

**Versions:**
- Talk version: 4a1492e88d66

- NodeJS: 12.5.0
- NPM: 6.9.2
- MongoDB: 3.6
- Redis: 3.2
- Browser: Firefox 70.0b2 (64-bit)
- OS: MacOS 10.12.6

**Comment by benjaminkreen** [comment]
Thanks so much @wyattjoh !! Deployed your branch to heroku, couldn't help myself. Its looking good, i was able to step through the registration, though I'm still running into an bump where it fails on first try but then works on the second:
![double_login](https://user-images.githubusercontent.com/5441006/66170193-1b0d0900-e5f8-11e9-86de-1c7bbb702880.gif) Let me know if I should file a separate ticket, seems related to https://github.com/coralproject/talk/issues/2529

**Comment by wyattjoh** [comment]
The issue you're experiencing regarding that one @benjaminkreen is unrelated to #2529, but is instead related to the fact that you need to set `TRUST_PROXY=1` as an environment variable. I've amended the `app.json` in that PR to address this for future Heroku installs.

I was able to determine that because I noticed your callback url was non SSL (note the padlock with the red cross through it after you redirect (the same page with the error)), which implies that Coral did not think you were on HTTPS. Setting `TRUST_PROXY=1` should resolve that issue  (though you may also need to add the https version of the callback URL to your OpenID Connect provider).

**Comment by wyattjoh** [comment]
Following up on that actually, we use `sessionStorage` to store the redirect URL. MDN states that:

> Data stored in sessionStorage is specific to the protocol of the page. In other words, http://example.com will have separate storage than https://example.com.

https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

Hence why HTTP/S matters in this case.

**Comment by benjaminkreen** [comment]
that totally makes sense, i'll update my callback url with orcid. I just used the copy button from the config page, and it defaulted to `http`:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/5441006/66171860-8c4fba80-e5fe-11e9-8afe-15a576ea3db7.png">
