### ISSUE TITLE
When SSO token expire stream stop to work

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#2624]
Hello, we found a bug when using SSO Token and it expires. When this happens all interactions stop working.
 
Expected behavior:
Open login window

From what I realized we need to set `authMiddleware.tokenRefreshPromise` ([createNetwork](https://github.com/coralproject/talk/blob/721b2e7d67272dea898be55d935f4c9dbf821f6d/src/core/client/framework/lib/network/createNetwork.ts#L61))  with an event to call login. What is the best way to do this?

**Comment by yannick-fernand** [comment]
Hello, do you plan to do something  about access token renewal ?

**Comment by alinhle** [comment]
We are looking into it!

**Comment by kgardnr** [comment]
Hey @cristiandean and @yannick-fernand if you want to take a look here: https://github.com/coralproject/talk/pull/3200

**Comment by cristiandean** [comment]
@kgardnr Looks good to me, thank you :)

**Comment by kgardnr** [comment]
Fixed in #3200
