### ISSUE TITLE
How to add a new language to Coral?

### ISSUE THREAD

**Issue by felixdro** [coralproject/talk#2628]
Hi!

We are looking forward to add coral to our article pages! But we need a different language and I have some troubles adding it and need some help.

When we feel the translations are ready we would like to contribute them here to, but first I would like to get them working and test them out.

I have tried adding the language to these files and folders
/src/core/common/helpers/i18n/locales.ts (in LanguageCode and LOCALES_MAP)
coral/src/core/client/admin/test/configure/__snapshots__/general.spec.tsx.snap
coral/src/locales (copied the "en-US" folder to a new "sv" folder")
coral/src/core/server/locales (copied the "en-US" folder to a new "sv" folder")

But when I run npm run build I get 
`ERROR: /src/core/common/helpers/i18n/locales.ts:5:27 - Replace `·"en-US"·|·"pt-BR"·|·"es"·|·"de"·|·"nl-NL"·|·"da"` with `⏎··|·"en-US"⏎··|·"pt-BR"⏎··|·"es"⏎··|·"de"⏎··|·"nl-NL"⏎··|·"da"⏎·``

Only if i remove the lint:client from the build script I can get it to build but not sure if that's a good idea? 

## Suggestion

Please add a guide in the documentation how to add your own language and run it from source

## Use Cases

When you need coral in a different language

**Comment by felixdro** [comment]
I noticed now that the lint problems where solved by running the "lint-fix" skript.

**Comment by kgardnr** [comment]
Oh hey @felixdro! Great news, just saw your last comment. Thank you for letting us know!
