### ISSUE TITLE
"Comment Count Integration" page has incorrect code

### ISSUE THREAD

**Issue by jonpincus** [coralproject/talk#2656]
**Expected behavior:**
Cutting and pasting the code on https://docs.coralproject.net/coral/v5/integrating/counts/ should update span.coral-count with the actual number of comments.

    <script href="//{{ CORAL_DOMAIN_NAME }}/assets/js/count.js" defer></script>
    ...
    <span class="coral-count" data-coral-url="http://example.com/blog-entry-1/"></span>

**Actual behavior:**

Nothing happens 

The script tag incorrectly uses the "href" attribute.  It should be "src":

    <script src="//{{ CORAL_DOMAIN_NAME }}/assets/js/count.js" defer></script>

**Related Issues:**

**Versions:**

(using the simple install on Heroku)

**Comment by wyattjoh** [comment]
Thanks for the report @jonpincus! We'll have that corrected shortly!

**Comment by kgardnr** [comment]
Fixed in #2648
