### ISSUE TITLE
TALK_ROOT_URL in v5?

### ISSUE THREAD

**Issue by tucson-tom** [coralproject/talk#2669]
Attempting to use Talk v5 behind a Nginx proxy (i.e. a standard deployment method).  The instructions for setting up v5 in a sane configuration are about as clear as mud.  `TALK_ROOT_URL` worked in v4 but that option doesn't appear to do anything in v5.  Also tried `ROOT_URL` like other config options.  No dice.  The Talk v5 server still spits out invalid URLs.

**Comment by wyattjoh** [comment]
v5 is actually designed as a multi-tenant system, and when you're pointing to a fresh database, you can hit Talk with any domain, and it will be saved as the application domain for Talk.

If you use the docker or source based install, you can clear out the database, start up the application, and Talk should show you the install page to get things installed.

**Comment by tucson-tom** [comment]
That, uh, makes no sense.  Nginx is proxying requests off a URL path (e.g. `https://somedomain.com/talk/` to the Talk backend server).

Running a command-line script clearly shows that Talk v5 as-is has no idea how to route paths:

`https://somedomain.com/talk/` redirects to `https://somedomain.com/install`, which doesn't exist.   The correct path should probably have been `https://somedomain.com/talk/install` but visiting that URL results in a blank page with the page title of "Coral" and delivers a bunch of JS and CSS requests that refer to non-existent URLs (i.e. 404 errors).  In v4, `TALK_ROOT_URL` was the mechanism that made Talk respond properly to requests from Nginx.  Forcing the `Host` header that is proxied to be the `somedomain.com` doesn't work either, but I didn't expect it to.

As to clearing the database, I guess I need instructions on how to do that.  From what I could tell, creating the `data` directory as per the v5 instructions should have effectively started fresh.  Since we hadn't really started using v4, we don't care about migrating and would prefer to start fresh.

**Comment by kgardnr** [comment]
Hey @tucson-tom can you share with us where you're using Coral currently?

**Comment by wyattjoh** [comment]
Noting as well that Talk v5 does not support path based routing. Talk will need to have it's own domain (or subdomain!) starting in v5.

**Comment by Shubhamsharma585** [comment]
Hi @tucson-tom I am facing the same issue, how you resolved it?
