### ISSUE TITLE
Talk not correctly identifying Author on Ghost 3

### ISSUE THREAD

**Issue by flosoft** [coralproject/talk#2670]
Talk is not correctly pulling the Author name when embedded on Ghost 3. Instead, every Author's name gets identified as `More posts`

<img width="962" alt="Screenshot 2019-10-24 at 00 50 58" src="https://user-images.githubusercontent.com/602633/67440084-6b282b80-f5f8-11e9-91e5-6e2a2d29c138.png">

This is happening when using Ghost's default theme, Casper.

The embed code I'm using is the following

```
<script src="https://talk.florianjensen.com/assets/js/embed.js" async onload="
var articles = document.getElementsByClassName('post-full post');
  if (articles.length === 1) {
    var coral = document.createElement('div');
    coral.setAttribute('id', 'coral_thread');
    articles[0].appendChild(coral);
    
    document.getElementById('coral_thread').appendChild(
        Coral.createStreamEmbed({
            id: 'coral_thread',
            autoRender: true,
            rootURL: 'https://talk.florianjensen.com',
            // Uncomment these lines and replace with the ID of the
            // story's ID and URL from your CMS to provide the
            // tightest integration. Refer to our documentation at
            // https://docs.coralproject.net for all the configuration
            // options.
            // storyID: '{{id}}',
            // storyURL: '{{url}}',
        }))
  }
  
  
"></script>
```

**Comment by wyattjoh** [comment]
Hi @flosoft!

It looks like even looking at the https://demo.ghost.io/style-test/ page (which uses the Casper theme) does not actually include a:

```html
<meta name="author" content="The Author's Name">
```

We use a metadata scraping library metascraper that implements the following rules for scraping author metadata:

https://github.com/microlinkhq/metascraper/blob/81f992112ee649529e304b27672953594e3475b8/packages/metascraper-author/index.js#L35-L51

And it seems that the structured data that Ghost exports does not include these standard article author tags unless facebook is enabled? https://github.com/TryGhost/Ghost/blob/master/core/frontend/meta/structured_data.js

You could try adding the following to the `<head>` of your posts:

```hbs
{{#author}}
<meta name="author" content="{{ name }}">
{{/author}}
```

Which should give Coral what it needs. Let me know if that works for you!

**Comment by flosoft** [comment]
Thanks for the info @wyattjoh.

Indeed, the meta object for author is missing, however it does provide this in a JSON-LD section at the top of a file or else in a `<h4 class="author-name">`.

As it's not possible it seems to simply use variables in the Code Injection for `{{ghost_head}}` in order to add the metadata you suggested and thus requires to update the raw theme files, is there any chance of adding scraping support for JSON-LD?

UPDATE: It seems that this has been added [here](https://github.com/microlinkhq/metascraper/commit/99897e8cf51416c51a2afc4c32ba0f492a893a42), but doesn't seem to be working for some reason?

An example:
```
<script type="application/ld+json">
{
    "@context": "https://schema.org",
    "@type": "Article",
    "publisher": {
        "@type": "Organization",
        "name": "Florian Jensen&#x27;s Blog",
        "logo": "https://florianjensen.com/content/images/2019/08/logo.png"
    },
    "author": {
        "@type": "Person",
        "name": "Florian Jensen",
        "image": {
            "@type": "ImageObject",
            "url": "https://florianjensen.com/content/images/2019/03/avatar-1.jpg",
            "width": 455,
            "height": 455
        },
        "url": "https://florianjensen.com/author/florian/",
        "sameAs": [
            "https://florianjensen.com",
            "https://www.facebook.com/florian.jensen"
        ]
    },
    "headline": "Configuring APC BX950U-GR UPS on Synology",
    "url": "https://florianjensen.com/2019/08/19/apc-bx950u-gr-ups-on-synology/",
    "datePublished": "2019-08-19T19:38:00.000Z",
    "dateModified": "2019-08-19T19:41:26.000Z",
    "image": {
        "@type": "ImageObject",
        "url": "https://florianjensen.com/content/images/2019/08/20190819_203922-01.jpeg",
        "width": 2000,
        "height": 1500
    },
    "keywords": "Synology, Tech",
    "description": "Setting up the APC BX950U-GR UPS on your Synology NAS after it failed to automatically recognise it, just saying &quot;No UPS is connected&quot;.",
    "mainEntityOfPage": {
        "@type": "WebPage",
        "@id": "https://florianjensen.com/"
    }
}
    </script>
```

**Comment by wyattjoh** [comment]
Hey @flosoft! I was able to confirm that upgrading the metascraper rules resolved the issue. I discovered a bug with the current version though that is holding up the release (https://github.com/microlinkhq/metascraper/pull/225). Once that's merged and a new release of these rules is done, we should be able to get this resolved in our next release.

**Comment by flosoft** [comment]
That's awesome. Thanks!
