### ISSUE TITLE
After 1 comment constantly receiving RATE_LIMIT_EXCEEDED

### ISSUE THREAD

**Issue by bderen** [coralproject/talk#2675]
Hi guys, 
After 1 comment constantly receiving RATE_LIMIT_EXCEEDED. 
When I look into redis DB with redis-cli I do see some entries there. When I remove them one by one - nothing helps, still see RATE_LIMIT_EXCEEDED. When I do FLUSHDB the error disappears and after 1 comment appears again. 
Any idea?

**Comment by wyattjoh** [comment]
Hi @sgtram! We implemented rate limiting for commenting to help curb bot style behaviour in v5.2.0. It's currently set to 3 seconds, (not configurable at the moment), so if you keep trying to send a comment every 2 seconds, you'll never be able to comment. The window will reset after the 3 second timeout. Is this not the behaviour you're experiencing?

**Comment by bderen** [comment]
I'm receiving RATE_LIMIT_EXCEEDED constantly, after 3 seconds or after 3 hours.

**Comment by bderen** [comment]
Hi guys, any updates on the issue/bag?

**Comment by kgardnr** [comment]
Hey @sgtram we're unable to reproduce the issue. Could you send us a link to your staging environment or post some additional information?

**Comment by bderen** [comment]
It is happening only in one of the staging environments. I also can't reproduce it on the other one. Maybe something with Redis?

**Comment by kgardnr** [comment]
Yeah I'm sorry @sgtram, I really can't say. Is there someone else on your team you could headcheck the SSO and setup with? Unfortunately that's the best advice we can give at this point.

**Comment by wyattjoh** [comment]
If you are able to reproduce the issue on an existing instance @sgtram, can you run the following via the `redis-cli`:

```
TTL {{ tenantID }}:lastCommentTimestamp:{{ userID }}
GET {{ tenantID }}:lastCommentTimestamp:{{ userID }}
```

Where you replace `{{ tenantID }}` and `{{ userID }}` with the Tenant and User ID for the affected Tenant/User. If it's an issue with Redis, we should see something interesting there.

**Comment by bderen** [comment]
Hi, @wyattjoh I don't have such entries in the Redis.
Here is what I have:

1) "{queue}:scraper:1167"
 2) "{queue}:scraper:1148"
 3) "ce3b8a94-3480-4683-ba4f-293223801739:commentCounts:moderationQueue:queues"
 4) "jtir:c4cf1b5d-f460-4325-98ca-87e674909141"
 5) "{queue}:scraper:1162"
 6) "{queue}:scraper:id"
 7) "{queue}:scraper:1166"
 8) "{queue}:scraper:1163"
 9) "{queue}:scraper:1165"
10) "{queue}:scraper:1147"
11) "{queue}:scraper:1164"
12) "{queue}:scraper:1161"
13) "{queue}:scraper:failed"
14) "{queue}:scraper:1150"
15) "ce3b8a94-3480-4683-ba4f-293223801739:commentCounts:status"
16) "ce3b8a94-3480-4683-ba4f-293223801739:commentCounts:moderationQueue:total"
17) "{queue}:scraper:1149"

**Comment by wyattjoh** [comment]
Currently the timeout is set at 3 seconds, which means that those keys should only live in Redis for a total of 3 seconds. Are you able to confirm that within that 3 second window, that the keys do not appear? We can't seem to replicate any issues without having some issue with keys in Redis.

**Comment by bderen** [comment]
I can confirm that within 3 seconds the keys are still there. Something with TTL?

**Comment by wyattjoh** [comment]
What version of Redis are you working with? I am unable to reproduce the mentioned error unfortunately.

**Comment by bderen** [comment]
We're running on Redis version 3.2.6

**Comment by wyattjoh** [comment]
I have a possible fix available in the following PR (https://github.com/coralproject/talk/pull/2709). If you wanted to give that a try and see if it improves things for you?

**Comment by bderen** [comment]
Thanks @wyattjoh , I've tried it and it doesn't help.
here are the entries in Redis:
9) "ce3b8a94-3480-4683-ba4f-293223801739:lastCommentID:1a9dc5b864334da700deff629c9b9a404b0f2d01"
10) "ce3b8a94-3480-4683-ba4f-293223801739:lastCommentID:a1fc93e19f21b0dcee7fb35fc09ca90465de9eb5"
and they never expire...

**Comment by wyattjoh** [comment]
`*:lastCommentID:*` keys are actually referring to our duplicate comment screening feature, not related to rate limiting. It shouldn't impact that feature.

Can you provide us with the server log containing the `RATE_LIMIT_EXCEEDED` message? Specifically we're interested in the `stack` part of the error message.

**Comment by bderen** [comment]
Nov 19 11:01:45 acceptance-talk-0 nodejs[10073]: {"name":"coral","clusterNode":"master","hostname":"acceptance-talk-0","pid":10130,"tenantID":"ce3b8a94-3480-4683-ba4f-293223801739","context":"graph","contextID":"984390d0-0ab3-11ea-a3c0-b1942082aca1","level":30,"responseTime":1,"authenticated":true,"persistedQueryID":"2b4eb18e6c2b6734e05f011583a5828e","persistedQueryBundle":"stream","persistedQueryVersion":"5.3.0","operation":"mutation","operationName":"CreateCommentMutation","msg":"graphql query","time":"2019-11-19T10:01:45.833Z","src":{"file":"/var/www/app/src/core/server/graph/common/extensions/LoggerExtension.ts","line":23,"func":"info"},"v":0}
Nov 19 11:01:45 acceptance-talk-0 nodejs[10073]: {"name":"coral","clusterNode":"master","hostname":"acceptance-talk-0","pid":10130,"tenantID":"ce3b8a94-3480-4683-ba4f-293223801739","context":"graph","contextID":"984390d0-0ab3-11ea-a3c0-b1942082aca1","level":50,"err":{"message":"RATE_LIMIT_EXCEEDED","name":"GraphQLError","originalError":{"message":"RATE_LIMIT_EXCEEDED","name":"RateLimitExceeded","stack":"rate (src/core/server/graph/tenant/directives/rate.ts:63:11)\nprocess._tickCallback (internal/process/next_tick.js:68:7)\n","id":"98456590-0ab3-11ea-a3c0-b1942082aca1","context":{"pub":{},"pvt":{"resource":"ce3b8a94-3480-4683-ba4f-293223801739:rl:1a9dc5b864334da700deff629c9b9a404b0f2d01:mutation.createComment","max":1,"tries":3,"resetsAt":"2019-11-19T10:01:48.821Z"}}}},"msg":"graphql query error","time":"2019-11-19T10:01:45.834Z","src":{"file":"/var/www/app/src/core/server/graph/common/extensions/LoggerExtension.ts","line":14,"func":"error"},"v":0}

**Comment by wyattjoh** [comment]
That error can only be returned when there is a Redis key indicating that there has been a recent attempt at creating a comment. I'd suggest that you try running `FLUSHDB` on that database to see if that resolves the issue, otherwise unfortunately, we'd likely have to go down custom support options as we are unable to reproduce or narrow the error down.
