### ISSUE TITLE
Migration Path from v4 to v5

### ISSUE THREAD

**Issue by cadecairos** [coralproject/talk#2676]
The Mozilla Foundation would love to upgrade our current Talk instance to v5, but this still appears to not be possible. Is there a timeline for support to migrate v4 data into a v5 instance? How long does the team plan to support the 4.11.x branch with bug fixes/security updates?

**Comment by kgardnr** [comment]
Hey @cadecairos! We'll definitely be supporting 4.x.x for a long time to come, at least through 2020. And we can help you upgrade when the time is right - we're still working on some toolkits to help make this easier for folks, and I can keep you posted on that.

Is this for the Internet Health Report or something else?

**Comment by cadecairos** [comment]
Hi @kgardnr, I'm looking into updating our Talk instance powering comments for our Privacy Not Included Buyer's Guide, but we'll also want to upgrade the Internet Health Report instance as well.

Glad to hear the 4.x branch will receive support for a while yet! 

Is a direct deployment to Heroku still supported in the latest 4.x and 5.x branches?

**Comment by kgardnr** [comment]
Hey @cadecairos yep we still support Deploy to Heroku for both 😄

**Comment by mkonikov** [comment]
Any update on when to expect an upgrade path from v4?

TIA :)
