### ISSUE TITLE
Talk 5.2.2 pulling incorrect publish date on Ghost 3

### ISSUE THREAD

**Issue by flosoft** [coralproject/talk#2690]
**Expected behavior:**
Talk should be pulling the date from the `datePublished` in the JSON-LD that Ghost 3 provides.

**Actual behavior:**
When using Talk 5.2.2 on Ghost 3, it seems to always be pulling the same publish date, 04/01/2018, 7:48 PM

<img width="939" alt="Screenshot 2019-11-03 at 00 26 00" src="https://user-images.githubusercontent.com/602633/68078142-8ea95e00-fdd0-11e9-92ba-9041d3f8e4e1.png">

The author now does get identified correctly though.

**Related Issues:** 
Could this be related to the fix in #2670?

**Versions:**

- Docker Container: coralproject/talk:5.2.2

**Comment by wyattjoh** [comment]
Hi @flosoft! Thanks for the report again on these issues. It seems that there was some priority issues with the existing ruleset we were using for date data. We've adjusted the order of the rules and it seems to have the desired behaviour now. Feel free to give #2702 a try to see if it works out better for you!

**Comment by flosoft** [comment]
Thanks once more for the quick fix here! Can confirm that this fixed it.
