### ISSUE TITLE
Talk wont render in a ghost blog

### ISSUE THREAD

**Issue by dennyabrain** [coralproject/talk#2703]
I am trying to integrate Coral into a ghost blog.
My server is running at http://13.233.152.184:3000.
I use the following script to inject the talk comment section
```
<script src="http://13.233.152.184:3000/assets/js/embed.js" async="" onload="
  var articles = document.getElementsByClassName('post-full');
  console.log(Coral.Talk)
  if (articles.length === 1) {
    var coral = document.createElement('div');
    coral.setAttribute('id', 'coral_talk_stream');
    articles[0].appendChild(coral);
    
    Coral.Talk.render(document.getElementById('coral_talk_stream'), {
      talk: 'http://13.233.152.184:3000'
    });
  }"></script>
```

**Expected behavior:**
Coral should render a comment section under my blog post

**Actual behavior:**
I see that a div named coral_talk_stream is created in my DOM but it is empty.

**Related Issues:** 
I notice that in my console i can find Coral object in the global namespace but Coral.Talk does not exist. Even when i try to console.log(Coral.Talk) within the onload block of the snippet above, i get an undefined.

**Versions:**
I installed Coral using the lates docker image on an AWS EC2 machine. I am running it on a Chrome machine.

**Comment by wyattjoh** [comment]
It looks like you may have tried to copy some JS from v4 of Coral, which used the `Coral.Talk.render` method. You need to use the method described in the `/admin/configure/advanced` page which uses:

```js
          Coral.createStreamEmbed({
              id: "coral_talk_stream",
              autoRender: true,
              rootURL: 'http://13.233.152.184:3000',
              // Uncomment these lines and replace with the ID of the
              // story's ID and URL from your CMS to provide the
              // tightest integration. Refer to our documentation at
              // https://docs.coralproject.net for all the configuration
              // options.
              // storyID: '${storyID}',
              // storyURL: '${storyURL}',
          });
```

**Comment by dennyabrain** [comment]
hey thank you. 

this makes sense and i see that createStreamEmbed does exist. so thats progress.

I do still get no content inside the coral_talk_stream div
but now i am guessing it has got to do with the parameters passed to createStreamEmbed.

Could you clarify if my understanding of this is correct?
storyId should be unique id  like the post Id
and story Url should be the complete URL of the blog post?

and also feel free to direct me to docs. i did look at https://docs.coralproject.net but could not find any explanation on storyID and storyURL

**Comment by wyattjoh** [comment]
Those configuration parameters are optional. When you modify the script, do you see anything in the console in terms of errors? I was able to render Coral on your linked site by calling the above mentioned `createStreamEmbed` function.

**Comment by dennyabrain** [comment]
you are right it works. it was a silly typo on my part. i had the parameter as autRender instead of autoRender. 

Thank you!
