### ISSUE TITLE
Would you like help in updating docz to v2 ?

### ISSUE THREAD

**Issue by rakannimer** [coralproject/talk#2754]
Hey ! 

Awesome work on the project, really high quality stuff 👍 

I'm the current maintainer of docz and I'm currently looking for projects to help migrate from older versions of docz to docz v2 (which is based on Gatsby and is really good ! (If I say so myself)).

Would you like some assistance in migrating to docz v2 ? 

Would be happy to setup a PR to help get started in the migration to v2. 

The biggest advantage you'll gain is that v2 generates a completely static website for your documentation which makes it much more easy to index by search engines and provides a huge performance boost for your users !

Let me know what you think !

**Comment by kgardnr** [comment]
Hi @rakannimer! That would be awesome! We are using docz only for our UI library right now, but we'd actually love to move all our docs over to docz potentially.

Thank you!

**Comment by rakannimer** [comment]
Awesome ! 

Thanks for the quick reply @kgardnr 😄 !

I'll setup a PR this week and we can move the discussion there 👍

**Comment by kgardnr** [comment]
Hey @rakannimer just wanted to follow up on this, if you're still interested? Thank you so much!

**Comment by rakannimer** [comment]
Hey @kgardnr, 

I started working on this but faced some issues that I didn't have the time yet to fix. 

I also wanted to ask you, is there a public-facing URL for the docz docs ?

**Comment by kgardnr** [comment]
Hey @rakannimer we don't have a public-facing url for the docz docs currently, it's used more for local development.
