### ISSUE TITLE
Romanian translation

### ISSUE THREAD

**Issue by vladimir04** [coralproject/talk#2762]
## Search Terms
translations, i18n, Romanian

## Suggestion
I would like to add Romanian translation to the project

## Use Cases
Using Talk for a blog and would like to use those translations.

I tried pushing a new branch to create a PR but couldn't. Could you please let me know what are the steps in order to achieve this?

Thank you!

**Comment by kgardnr** [comment]
Hey @vladimir04! You can follow these instructions to create a PR: https://opensource.com/article/19/7/create-pull-request-github

Let us know if you need more help! We'd love to add Romanian!

**Comment by wyattjoh** [comment]
Ensure you also take a look at our [CONTRIBUTING.md](https://github.com/coralproject/talk/blob/master/CONTRIBUTING.md#localization) guide!

**Comment by kgardnr** [comment]
Resolved in https://github.com/coralproject/talk/pull/2786
