### ISSUE TITLE
ERR wrong number of arguments for 'hmset' command

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#2763]
Hi, have the following error when the counts reset:

![Screen Shot 2019-12-20 at 11 27 45](https://user-images.githubusercontent.com/25023177/71262396-54fbca80-231e-11ea-9655-3226d4086b2f.png)

After the error, the application restart automatically.

Do you know what it can be?

**Comment by wyattjoh** [comment]
What version of Redis are you running @cristiandean? We're running 3.2 at the moment internally.

**Comment by cristiandean** [comment]
We're running 3.2.6 with redis sentinel.

**Comment by wyattjoh** [comment]
This should be addressed in the above linked PR @cristiandean!
