### ISSUE TITLE
Signin dialog appears on Settings page in stream when a user is signed in.

### ISSUE THREAD

**Issue by davidgljay** [coralproject/talk#278]
### Expected behavior

Once I'm logged in, the settings page should let me edit my settings.

### Actual behavior

![screen shot 2017-02-01 at 11 50 02 am](https://cloud.githubusercontent.com/assets/680687/22516734/c017f164-e874-11e6-9c80-4b3c43b0e51d.png)

### Steps to reproduce behavior

1. Log in on stream
2. Click "Settings" tab

**Comment by jde** [comment]
Fixed
