### ISSUE TITLE
Default account ban email customMessage does not currently support translations

### ISSUE THREAD

**Issue by ghost** [coralproject/talk#2841]
If Coral language is changed, the custom ban email message stays in the original language and there's no way to change the default message.

Note! I failed to trace where the default message is stored, so this may be user issue.

**Expected behavior:**

Full user ban email should be in the selected language.

**Actual behavior:**

If the email message is not updated during banning the message is mixed language

>(original language) Hello [user],
>
> Someone with access to your account has violated our community guidelines. As a result, your account has been banned. You will no longer be able to comment, react or report comments.
>
> (new language) Jos kielto on mielestäsi aiheeton, ota yhteyttä ylläpitoon [contact].

**Related Issues:** 

Account suspend email has the same issue.

**Versions:**

Used docker image coralproject/talk:5.5.1

**Comment by kgardnr** [comment]
Hey @jpkilpi you can find the translations for email messaging here: https://github.com/coralproject/talk/blob/dd45f46b194b75f0a3231d668a1e5bdabb5e5f9d/src/core/server/locales/en-US/email.ftl

Let us know if that helps!

**Comment by ghost** [comment]
Hi @kgardnr ,

my original report was incorrect in "custom ban email message stays in the original language"

Actually the first part of the email message is always English, no matter what the initial language was.

This is easy to test: Configure -> General -> Language, select anything else than English

Go to Community tab, select "Ban" for a user and click "Customize ban email message". The message is always in English. I tested this using all available languages and all had the same result.

**Comment by kgardnr** [comment]
Thanks @jpkilpi! I do believe this a bug. In the meantime, you can still go ahead and add the right files to the `email` folder as they've done in Portuguese, for example, and we'll address this when we get a moment.

**Comment by kgardnr** [comment]
Hey @HectorNM are you and your team able to confirm this is the case as well? If so, do you want to look into this bug by chance?

**Comment by alinhle** [comment]
I've opened a PR to fix this issue. Thanks for reporting!
