### ISSUE TITLE
Always receive reported comments to moderation queue

### ISSUE THREAD

**Issue by ghost** [coralproject/talk#2843]
## Suggestion

Receive reported comments to moderation queue even when pre-mod is on and comment is already approved.

## Use Cases

Our comment section has pre-moderation enabled, so all messages will be checked and approved before they are published.

We would still like to receive the reports from our users so that we can take action based on them.

Right now for the report to appear in the queue, the rule is that pre-mod must be off and comment has not yet been Approved or Rejected. This means that our users can report all they want, but we'll never see the reports.

https://docs.coralproject.net/coral/moderator-features/

We are using Coral 5

**Comment by kgardnr** [comment]
Hey @jpkilpi this is a product decision we made - because if a moderator has approved a comment, it should be deemed acceptable by the newsroom/org and the community, so reports would just add to their workload and might be a vector for abuse.

I'll close this issue for now but feel free to add additional comments for context.

**Comment by ghost** [comment]
Hi @kgardnr 

Not having a way to receive user reports is a bit problematic for us.

The majority of the Finnish media have signed the [Council for Mass Media](https://www.jsn.fi/en/) Basic Agreement.

CMM's [Guidelines for Journalists](https://www.jsn.fi/en/guidelines_for_journalists/) requires that

> 4. The public must be given the opportunity to inform editorial offices of inappropriate content in such a way that the informant receives due confirmation.

(Annex to Guidelines: Material generated by the public on a media website)

I understand the reasoning behind the product decision but it prevents us comply with local journalistic guidelines. Reporting functionality is already there, so it'd be great if we could enable it using a feature switch.

Separate issue with current situation is that we are deceiving our commenters by providing report functionality that does nothing.

**Comment by e-talent2018** [comment]
Hello @kgardnr,

I understand your decision, but I think you can instead add a new API that will allow us to retrieve the comments reported. 
for example in the GetComment request, we add a filter on the flag?
  
Best regards,

Lotfi.

**Comment by e-talent2018** [comment]
Hello @jpkilpi 

Did you find any solution for your need? Are you able to retrieve all reported comments already approved?

Best Regrades,
Lotfi.

**Comment by ghost** [comment]
Hi @e-talent2018 

I'm afraid we don't have proper solution for this. 

We have considered using [Slack notifications](https://docs.coralproject.net/coral/v5/integrating/slack/) to get a notification of a reported comment. It's not great, but at least reports would not go directly to /dev/null as it is now.

We haven't actually tried it, so I'm not sure if notification would be triggered in this kind of situation.
