### ISSUE TITLE
When a admin enabled "require email confirmation", they themselves are locked out.

### ISSUE THREAD

**Issue by wyattjoh** [coralproject/talk#285]
### Expected behaviour

**Need to check with product**

### Actual behaviour

- Email's now need to be verified, new logins are locked out

### Steps to reproduce behaviour

1. Install talk
2. Create user
3. Enable the requirement for email confirmations
4. Log out
5. Try to login

**Comment by wyattjoh** [comment]
@kgardnr could you weigh in on this?

**Comment by jde** [comment]
Two thoughts _if we apply email verification retroactively_:

As far as I understand, this shouldn't lock out the admin. The admin should try to log in, see they need to register, request a verification link, then be able to log in.

This move would force all users to do the same, and should be widely communicated to the user base well prior to the action.

Another option:

We could also only apply this to users registering while the setting is active.

**Comment by losowsky** [comment]
I like the first option. But for the beta would it save a lot of design/dev time to have this be something set up on install and not be changed?

**Comment by wyattjoh** [comment]
Another option, send the verification email always. That way when you turn it on, users always have the chance to verify it then.

**Comment by kgardnr** [comment]
I'm making the executive decision to go with @wyattjoh's suggestion above. We will break out any advanced functionality separately. Questions/concerns, please come directly to me.

**Comment by wyattjoh** [comment]
Resolved as of f488b0e02d8255b603f6e3ac6076b2a36b131500
