### ISSUE TITLE
Get total comment count for site

### ISSUE THREAD

**Issue by ghost** [coralproject/talk#2871]
## Suggestion

Our Coral Talk instance is being premoderated by a third party. Part of their moderation fee is the amount of work; number of comments approved / rejected by the moderators.

We would like to be able to get the total number of messages in a site. Preferably we could limit the count to a time period (e.g. new comments in February), but total counts would be sufficient.

**Comment by kgardnr** [comment]
Hey @jpkilpi, since you're hosting your own instance you can get this information directly from the database itself. We might bring on metrics in the future but we don't have firm plans at this time.
