### ISSUE TITLE
Bug: Static URI Path Support 

### ISSUE THREAD

**Issue by cristiandean** [coralproject/talk#2897]
Hello, this bug #2371 that was solved here: #2399 is happening again due to https://github.com/coralproject/talk/commit/707d65a11901d24b81c3207e125c7a28c2900056#diff-b1eac6ae145d4d181b45270d6f517a3dL504

We were about to update the Talk when we found this bug again. Could it be reversed? We can submit a PR.

P.S.: The latest release did not update the Talk version in [package.lock](https://github.com/coralproject/talk/blob/master/package-lock.json).

**Comment by wyattjoh** [comment]
Hi! Thanks for the report!

We had to remove the offending lines https://github.com/coralproject/talk/commit/707d65a11901d24b81c3207e125c7a28c2900056#diff-b1eac6ae145d4d181b45270d6f517a3dL504 because they affected loading fonts from deeper nested pages for when `STATIC_URI` is unset.

We currently don't have a solution to this problem, as the current implementation seems to be working for when we're using the internal `STATIC_URI`. We are open to suggestions that would fix things for both situations of course!

**Comment by wyattjoh** [comment]
As for the updates to `package-lock.json`, agreed, that was missed! We'll add a CI step to verify that in the future.

**Comment by cristiandean** [comment]
@wyattjoh  Do you have an example of deeper nested pages where it doesn't work when `STATIC_URI` is unset?

I did a test on the route `/admin/configure/organization/sites/new`with the `STATIC_URI` unset and it worked with these lines https://github.com/coralproject/talk/commit/707d65a11901d24b81c3207e125c7a28c2900056#diff-b1eac6ae145d4d181b45270d6f517a3dL504


![Screen Shot 2020-03-18 at 20 39 16](https://user-images.githubusercontent.com/25023177/77017349-0f6c8f00-6959-11ea-8f36-9991f3698c76.png)

It seems to make sense that the font paths are always two directories before the css paths (`../../`).

**Comment by cristiandean** [comment]
It would also be good to mention this in the release notes as a breaking change, as it ended up breaking us since we use s3 to store the static ones, keeping the URL like this:

```https://s3_host/v1/AUTH_hash/coral-talk/version/assets...```

**Comment by cristiandean** [comment]
Hello, do we have any updates on this?

As I said, we've been using this fix all this time and in both cases it seems to work well (with and without STATIC_URI):

<pre>
{
              // Exclude `js` files to keep "css" loader working as it injects
              // its runtime that would otherwise processed through "file" loader.
              // Also exclude `html` and `json` extensions so they get processed
              // by webpacks internal loaders.
              exclude: [/\.(js|ts|tsx)$/, /\.html$/, /\.json$/],
              loader: require.resolve("file-loader"),
              options: {
                <b>// Because the resources loaded via CSS can sometimes be loaded
                // directly from a CSS file, this will ensure that they are
                // relative to those referencing files.
                publicPath: (loaderPublicPath: string) =>
                  "../../" + loaderPublicPath,</b>
                name: isProduction
                  ? "assets/media/[name].[contenthash].[ext]"
                  : "assets/media/[name].[ext]",
              },
            },
</pre>

If there is a case that I cannot reproduce, could you tell me? so I can see if there is a way to solve it.

**Comment by wyattjoh** [comment]
Hey @cristiandean, I'm evaluating this proposed fix now. From what I remember before why we couldn't use this solution is that there was some issues with font loading... Will update here if I find any issues! Otherwise watch for a PR to address this!

**Comment by alinhle** [comment]
Hi @cristiandean! Thanks for bringing this up. I can definitely verify all your points and your fix is solving it for me as well. I opened a PR to address this https://github.com/coralproject/talk/pull/3275.

**Comment by alinhle** [comment]
Thanks for your patience and apologies for the delay in resolving this issue. We really appreciate your contribution @cristiandean.

**Comment by cristiandean** [comment]
@cvle @wyattjoh  Thanks for the support guys :)
