### ISSUE TITLE
How to import comments to Talk v5 from custom sources?

### ISSUE THREAD

**Issue by takeit** [coralproject/talk#2922]
Previously I used Coral Talk v4 and I used https://github.com/coralproject/talk-importer to import the data from my custom source which worked very well.

How do I import data from my custom source to Talk v5? Are there any tools out there? I couldn't find anything.

Thanks!

**Comment by kgardnr** [comment]
@takeit we don't have a migration path yet, and this will likely be delayed for the time being. Could you reach out to us on support@coralproject.net so we can discuss your options? Thank you!
