### ISSUE TITLE
Translation key displaying instead of actual text

### ISSUE THREAD

**Issue by mkonikov** [coralproject/talk#2925]
**Expected behavior:**
When a message is shown to a user that their username is rejected, the text labels should be the values from the translation yml file (aka translations in each language). 

**Actual behavior:**
The keys from the yml file seem to be displaying. See screenshot ->

![image](https://user-images.githubusercontent.com/7562285/78510535-c8a5d400-7763-11ea-9752-fe775af69f23.png)

**Versions:**

- Coral: 4.11.0

**Comment by kgardnr** [comment]
Hey @mkonikov, would it be possible for you to contribute this bug fix do you think?

Or @leeeandroo, would you?

**Comment by leeeandroo** [comment]
Hey @kgardnr ,

I could not reproduce this issue. Checked on `4.11.0` and `4.11.4`.

Could you give more information about how you got this @mkonikov ?

Thanks,

**Comment by mkonikov** [comment]
I believe I may have identified the issue in our local code. Sorry for the bother.
(Came across this issue when trying to fix https://github.com/coralproject/talk/issues/2941)
