### ISSUE TITLE
Users encountering GraphQL error related to ignoredUsers

### ISSUE THREAD

**Issue by mkonikov** [coralproject/talk#2929]
**Expected behavior:**
Comment viewing and posting should work fine.

**Actual behavior:**
User sees this error when viewing the stream
```
GraphQL error: Cannot return null for non-nullable field User.ignoredUsers.
```
I believe this is related to a user A ignoring user B and then user B deleting their account. 

**Versions:**

- Coral: 4.11.0

**Comment by kgardnr** [comment]
Hey @leeeandroo just raising this to your attention if you'd like to submit a fix for this!

**Comment by kgardnr** [comment]
Hey @mkonikov - we won't be addressing any additional v4 bugs

**Comment by mkonikov** [comment]
Does that mean that there’s an upgrade path from 4 to 5?

**Comment by kgardnr** [comment]
Yes, currently for hosted clients, hopefully Q1 for self-hosted. I owe you an email too!
