### ISSUE TITLE
Error when building on v4

### ISSUE THREAD

**Issue by mkonikov** [coralproject/talk#2941]
I'm getting an error when building with Docker locally

```
error semver@7.3.2: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.16.1"
error Found incompatible module
```

I'm guessing this is because the engine is pinned at 8

**Expected behavior:**
To be able to build

**Actual behavior:**
Can't build

**Versions:**
4.11.0

**Comment by wyattjoh** [comment]
If you're building with Docker, you should use Node at version ~8 instead of 10. Docker for v4.11.0 is pinned to the `node:8-alpine` image, so you should be fine.

What command do you invoke to start the build?

**Comment by mkonikov** [comment]
Our command is 
```
RUN cli plugins reconcile && \
    yarn --ignore-engines && \
    yarn build && \
    yarn add -W newrelic pm2 && \
    yarn cache clean &&\
    chmod +x startup.sh
```
with the startup file adding support for [pm2](https://www.npmjs.com/package/pm20).

**Comment by wyattjoh** [comment]
Are you basing your images from the `*-onbuild` tags? (ref: https://docs.coralproject.net/coral/installation-from-docker/#onbuild)

**Comment by mkonikov** [comment]
No.

Dockerfile is like this

```
FROM coralproject/talk:4.11.0
--
  |  
  | COPY . /usr/src/app
  | ENV TALK_DISABLE_EMBED_POLYFILL TRUE
  | ENV TALK_DEFAULT_STREAM_TAB talk-plugin-featured-comments
  |  
  | RUN cli plugins reconcile && \
  | yarn --ignore-engines && \
  | yarn build && \
  | yarn add -W newrelic pm2 && \
  | yarn cache clean &&\
  | chmod +x startup.sh
  |  
  | CMD ["./startup.sh"]
```

**Comment by wyattjoh** [comment]
The only thing I can assume is that one of the packages you're using is requesting a Node version `>=10`, hence the warning. I'd suggest trying to pin to a version that requires Node version `~8` in order to maintain compatibility with Coral v4 which currently requires version 8. Coral 5+ however now uses `^12`.

**Comment by mkonikov** [comment]
With Node 8 having reached EOL in 2019, any way to get v4 working with Node 10.

Alternatively, any word on an upgrade path to v5+?

Thanks!

**Comment by kgardnr** [comment]
Hey @mkonikov! I think definitely we'll want to move forward with getting you over to v5+. I think doing a node upgrade for v4 would be a risky venture.

Let me check with my team and I can get back to you about migration next steps!

**Comment by leonkunert** [comment]
We fixed this by fixing the node-gyp version to 6.1.0. They did an update that seems to require dependencies that need node 10.

**Comment by mkonikov** [comment]
@leonkunert Are you building with Docker?
Where is `node-gyp` used?

**Comment by leonkunert** [comment]
We are using a custom docker image but heavily inspired by booth the on-build and base.
[Here](https://github.com/coralproject/talk/blob/104b719dec0c0ddac37b515f584edfd6bcf93043/Dockerfile#L23) you can see node-gyp beeing installed without version constraint.
We replaced it with: ```RUN yarn global add node-gyp@6.1.0```

Edit: Forgot the link

**Comment by mkonikov** [comment]
Thanks for that @leonkunert!

@wyattjoh Would you consider pinning the `node-gyp` version in v4 to `6.1.0` to address this for those still on 4?

https://github.com/coralproject/talk/blob/release/4/Dockerfile#L23

**Comment by mkonikov** [comment]
I created a PR for that here -> https://github.com/coralproject/talk/pull/2992

If we could move forward with this it would seem to be the best solution for those still using v4 (apart from upgrading v4 to Node 10).

Thanks!

**Comment by mkonikov** [comment]
@leonkunert Did you find pinning `node-gyp` help you with the `semver` issue? I still seem to have the issue even after pinning `node-gyp`.

**Comment by leonkunert** [comment]
@mkonikov That was the only thing we changed in our Dockerfile and it seemed to fix the issue for us.
