### ISSUE TITLE
Edit comment with suspect word shows "Resource Already Exists" error to user

### ISSUE THREAD

**Issue by immber** [coralproject/talk#2943]
**Expected behavior:**
User is able to edit comment in the edit window.
**Actual behavior:**
User edits comment, clicks submit, and is shown a "Resource Already Exists" error. User's edit is not displayed on the stream, but the edit is successfully persisted. 

**Related Issues:** 

**Versions:**
Reproduced on Talk version 4.11.4
- Browser: Chrome
- OS: Mac Mojave

**Steps to reproduce**
1. As a commenter user, create comment with a suspect word
1. Edit the “beginning” of the comment body, error only occurs when the comment body changes are at the start of the comment text. 
1. Click Submit, and you will be shown the "Resource Already Exists" error

You will see this network response in browser tools:
```
data: {editComment: {errors: [{translation_key: "ALREADY_EXISTS", __typename: "GenericUserError"}],…}}
editComment: {errors: [{translation_key: "ALREADY_EXISTS", __typename: "GenericUserError"}],…}
errors: [{translation_key: "ALREADY_EXISTS", __typename: "GenericUserError"}]
0: {translation_key: "ALREADY_EXISTS", __typename: "GenericUserError"}
translation_key: "ALREADY_EXISTS"
__typename: "GenericUserError"
__typename: "EditCommentResponse"
comment: null
```

**Comment by kgardnr** [comment]
FYI @mkonikov and @leeeandroo if you want to take a look at this bug

**Comment by kgardnr** [comment]
We won't be addressing any additional v4 bugs
