### ISSUE TITLE
Internal Error thrown when registering an admin account and Organization URL is missing http:// header 

### ISSUE THREAD

**Issue by munguia-strib** [coralproject/talk#2945]
Steps:
 Follow https://docs.coralproject.net/coral/   for Docker
When registering an account for the first time, add a website to the Organization URL field like so:
www.example.com  (without http://)
Validation checks out.
Add Whitelisted domains and Finish Install

**Expected behavior:**
I'm able to finish install successfully *or* validation fails when trying to input an incomplete Organization URL
**Actual behavior:**
Internal Error is thrown when clicking on Finish Install
This is outputted in the terminal whenever I click on Finish Install:
talk_1   | {"name":"coral","clusterNode":"worker.3","hostname":"cb70c1934a6a","pid":44,"context":"http","contextID":"35dfff50-88b2-11ea-ae08-4bf66e33df50","level":50,"url":"/api/install","method":"POST","statusCode":200,"host":"localhost","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0","ip":"::ffff:172.22.0.1","err":{"message":"child \"tenant\" fails because [child \"organization\" fails because [child \"url\" fails because [\"url\" must be a valid uri]]]","name":"ValidationError","stack":"Object.exports.process (node_modules/joi/lib/errors.js:196:19)\ninternals.Object._validateWithOptions (node_modules/joi/lib/types/any/index.js:675:31)\nmodule.exports.internals.Any.root.validate (node_modules/joi/lib/index.js:138:23)\nObject.validate (src/core/server/app/request/body.ts:12:37)\nvalidate (src/core/server/app/handlers/api/install.ts:203:13)\nprocessTicksAndRejections (internal/process/task_queues.js:97:5)\n"},"msg":"http error","time":"2020-04-27T18:09:17.806Z","src":{"file":"/usr/src/app/src/core/server/app/middleware/logging.ts","line":41,"func":"error"},"v":0}

**Versions:**

- NodeJS: v12.16.2
- NPM: v6.14.4
- MongoDB:
- Redis:
- Browser: any
- OS: MacOS 10.14.6 Mojave

**Comment by wyattjoh** [comment]
I'm expecting that this is related to adding the scheme to the URL. Ensure you add `http://` or `https://` to the front of the URL. Let us know if that fixes things!
