### ISSUE TITLE
Where can I find a graphql viewer?

### ISSUE THREAD

**Issue by xixuefeng11** [coralproject/talk#2950]
I've installed Coral on the DigitalOcean docker droplet.

Does this platform support Graphql viewer?
I've tried it on https://localhost:8080/api/graphql, and https://localhost:3000/graphiql.
but it shows an error page.
Where can I find the Graphql viewer?

**Comment by allanassis** [comment]
There is a section in the docs that explains about it.
https://docs.coralproject.net/talk/v5/api/overview/

Basically you have to enable the Graphql viewer by setting the ```ENABLE_GRAPHIQL=true```.
After that you can access the viewer in this endpoint ```http://localhost:3000/graphiql```

<img width="1308" alt="Captura de Tela 2020-05-04 às 17 36 21" src="https://user-images.githubusercontent.com/23871115/81011118-c780c900-8e2d-11ea-86dd-95b5d5b944aa.png">

**Comment by xixuefeng11** [comment]
I've inserted ENABLE_GRAPHIQL=true in the environment area of docker-compose.yml.
After restarting the docker, it works.
Thanks, allanassis.
