### ISSUE TITLE
Deleted comments in moderation queues

### ISSUE THREAD

**Issue by allanassis** [coralproject/talk#2951]
Hi guys, i know it is an expected behavior, but why is it necessary to keep deleted comments in moderation queues?

I can not see any reasons for that, there are no information about these comments, it is just the relation about a blank box with the story title.

What do you guys think about removing these comments from these queues?

<img width="699" alt="Captura de Tela 2020-05-04 às 18 38 12" src="https://user-images.githubusercontent.com/23871115/81016584-1b43e000-8e37-11ea-9945-5391fa53e2af.png">

**Comment by HectorNM** [comment]
Another idea instead of not showing at comments at all, maybe it could exist an extra queue called "Deleted" just to keep deleted comments. What do you think?

**Comment by tessalt** [comment]
should be resolved by https://github.com/coralproject/talk/pull/3638
