### ISSUE TITLE
No easy way to query nested comments

### ISSUE THREAD

**Issue by cloudlena** [coralproject/talk#2954]
We are using Talk as a commenting solution for news articles. There, users can also comment on other people's comments. For that, we want to query all the comments of a news article and display them as a tree of nested comments. Our use case is to display the first n comments and all of their "children" (meaning comments that were written as a response to the top level comment).

```txt
Article
├── Comment 1
│
├── Comment 2
│   ├── Reply 1 to Comment 2
│   └── Reply 2 to Comment 2
│
└── Comment 3
    └── Reply 1 to Comment 3
```

After reading the GraphQL documentation, it seems like that is not easily doable. There are mainly two difficulties:

- The `limit` limits all returned comments. We want to only limit the number of top level comments returned. There is no way of e.g. filtering by ones with `hasParent: false`.
- One cannot request comments and their children. It is only possible to request a comment and its parent, which is not very helpful for us.

For now, our best solution is to always request all comments for an article and then assemble the tree of nested comments as we need them in our own business logic outside of Talk. Is there any better way of doing this through the GraphQL API of Talk?

We're using version `v4.11.4` of Talk.

Sorry for creating this as a bug. I wanted to create it as a question but there was no template for that. If someone can, please change the label.

**Comment by wyattjoh** [comment]
You could construct a query like this:

```graphql
query GetNestedComments($asset_id: ID!) {
  asset(id: $asset_id) {
    comments(query: { limit: 10, parent_id: null }) {
      nodes {
        id
        body
        user { username }
        created_at
        replies(query: { limit: 20 }) {
          nodes {
            id
            body
            user { username }
            created_at
          }
        }
      }
    }
  }
}
```

This would return comments (with no parent, or top level comments) as `asset.comments.nodes` (limiting them to 10). Replies to those top level comments would be found on each comment's `replies.nodes` (limiting them to 20).

This is how we do it inside the frontend of Coral today across versions.

**Comment by cloudlena** [comment]
Thanks so much, @wyattjoh! That's exactly what we needed.
