### ISSUE TITLE
User reports "internal error"

### ISSUE THREAD

**Issue by nate-john** [coralproject/talk#2958]
hey Coral Talk folks, 

I have a user who's written in saying whenever she attempts to log in to the commenting system on our site she gets an "internal error." 

I created a new user and commented on our site effectively just now. So, I wasn't able to replicate the issue. 

Is there something to this - or other users you've seen report the same issue? 

Thanks, 
Nate John

**Comment by kgardnr** [comment]
Hey Nate John! I'm going to remove this comment and create a support ticket for you!
