### ISSUE TITLE
Logging configuration 4.11

### ISSUE THREAD

**Issue by kbwffx** [coralproject/talk#2962]
How can I configure the logging in Talk to interface with our back-end log collection? Can I do it through a plugin?

## Search Terms

logging configuration

**Comment by wyattjoh** [comment]
In Talk v4, we only outputs logs to standard out. We also don't provide a mechanism to interface through the plugin system. You could perhaps explore using the onbuild image and overriding the https://github.com/coralproject/talk/blob/v4.11.4/services/logging.js file, which might let you route the logs elsewhere.
