### ISSUE TITLE
Coral talk section doesn't render on latest Chrome if third-party cookies are blocked

### ISSUE THREAD

**Issue by Jonahss** [coralproject/talk#2993]
Hello,

My mother called me because the comment section on a Vox article disappeared for her. She used to be able to use it and now it's gone.

She's using Chrome v83.0.4103.112

She had the setting for "block cookies from third party sites" enabled.
I walked her through adding "https://[*.]coralproject.net:443" to the whitelisted domains for cookies and the comment block re-appeared.

I would assume that this is fixed by https://github.com/coralproject/talk/pull/2944. Maybe the version of Talk used by Vox.com is a few versions behind? (I don't know how to check). On the other hand, if this change was deployed, it's possible it introduced this bug.

My mother reports that she saw the comment block two weeks ago.

**Expected behavior:**
See the comment section on a site that coral talk is embedded on
**Actual behavior:**
Embedded talk widget is missing from rendered page

**Related Issues:** 
Maybe https://github.com/coralproject/talk/pull/2944
**Versions:**
Whatever Vox.com uses. 
Chrome v83.0.4103.112
Chrome OS v83.0.4103.112

**Comment by kgardnr** [comment]
Thank you @Jonahss, for bringing this to your attention, and helping find the workaround! We will review this and get back to you!

**Comment by kgardnr** [comment]
We've address this here @Jonahss - thanks again for bringing it to our attention! https://github.com/coralproject/talk/pull/2994

**Comment by Jonahss** [comment]
Wow! Super quick response! Thanks

**Comment by kgardnr** [comment]
You're welcome! :)

**Comment by kgardnr** [comment]
Fixed in https://github.com/coralproject/talk/pull/2994
