### ISSUE TITLE
I can't access Coral Project Talk from outside with public ip

### ISSUE THREAD

**Issue by yos77** [coralproject/talk#3001]
Good Morning:

I installed Coral Talk in ubuntu server and I want to access it from outside with public ip, but for some reason I can't. I can access it with local ip 127.0.0.1:3000 using command lynx and I know with this method is working. All containers in Docker are running. To install Coral I used the docker-compose.yml file (Version 5+), that is in this link https://docs.coralproject.net/coral/.
The server has not firewall. 

**Expected behavior:**
Access Coral Talk from outside with public ip

**Actual behavior:**
I can access with local ip only (127.0.0.1:3000), and all docker containers are in up state.

**Versions:**
I used the following version:

- NodeJS: 12.18.1
- NPM: 6.14.5
- MongoDB: 4.2
- Redis: 3.2
- Browser: Chrome 83.0.4103
- OS: Ubuntu 18.04.4
- Docker Engine - Community: 19.03.11

Please help me, thanks

**Comment by wyattjoh** [comment]
In order to access an application inside a docker container, the port must be exposed. I'd recommend using a web server like [Caddy](https://caddyserver.com/) and proxy to the Docker container at `127.0.0.1:3000`. It may be the case that you'll have to open a firewall port for `80` and `443`.
