### ISSUE TITLE
Spanish translation typo

### ISSUE THREAD

**Issue by anibalpacheco** [coralproject/talk#3004]
https://github.com/coralproject/talk/blob/86c81c7b9fa543249fe7ab3bc6659332709d68cf/src/locales/es/stream.ftl#L75

It shlould be "Enviar" (screenshot attached for more context)

![es_typo](https://user-images.githubusercontent.com/89636/85896130-4a8b2380-b7ce-11ea-9134-7f53837b88c7.png)

**Comment by natastro** [comment]
Hi coralproject team! I fixed the typo - could I submit a PR for this? Thank you! :) Have a nice weekend.

**Comment by wyattjoh** [comment]
Yes please @stroudn1!!

**Comment by kgardnr** [comment]
Fixed in https://github.com/coralproject/talk/pull/3008

Thank you again @anibalpacheco and @stroudn1!
