### ISSUE TITLE
How to configure https on my Coral Project server?

### ISSUE THREAD

**Issue by yos77** [coralproject/talk#3009]
Good Morning:

I installed Coral Talk in ubuntu server and I want to configure https. Where should I to configure this, on the server or on the Docker? Do you have documentation about this? Thanks.

**Expected behavior:** https://www.test.com

**Actual behavior:** http://www.test.com

**Versions:**

NodeJS: 12.18.1
NPM: 6.14.5
MongoDB: 4.2
Redis: 3.2
Browser: Chrome 83.0.4103
OS: Ubuntu 18.04.4
Docker Engine - Community: 19.03.11

**Comment by wyattjoh** [comment]
Great question! I'd suggest taking a look at [Caddy](https://caddyserver.com/) to help with that. Coral doesn't handle or manage HTTPS certificates, but Caddy does!
