### ISSUE TITLE
Support for multiple languages on one page

### ISSUE THREAD

**Issue by karlsgreenict** [coralproject/talk#3029]
We have a page where you can choose different languages. http://my.site/en and http://my.site/fr. 

Is it possible to change the language of the coral talk integration dynamically? I tried to set the locale value in the LocalStorage as described in the documentation.

localStorage.setItem('locale', 'fr')

Unfortunately, this seems not to work anymore in the current version.

**Comment by kgardnr** [comment]
Hi @karlsgreenict, can you share the site you're using Coral on? Thanks!

**Comment by karlsgreenict** [comment]
Hello @kgardnr,
thanks for the feedback. We are currently checking the suitability of Coral Talk for a site that is not yet realized. So unfortunately, I can't share it.

**Comment by wyattjoh** [comment]
At the moment, Coral only supports a single language per site, where a site has a unique origin `https://domain.com`, and are unable to support multilingual deployments at the moment.
