### ISSUE TITLE
Edge case Like bug

### ISSUE THREAD

**Issue by jde** [coralproject/talk#303]
### Expected behavior

Clicking like always toggles as expected.

### Steps to reproduce behavior

1. Log in as a user
2. like a comment
3. log out (don't refresh)
4. log in as another user
5. like the comment (you will actually unlike it, then liking again shows +2)

This is a major edge case, but will likely lead to more bugs in the future.

The local state implementation of optimistic updating doesn't seem to take into account which user liked it. I recommend find a way to take advantage of redux actions that update the apollo state so that the component doesn't have to worry about these things.

**Comment by wyattjoh** [comment]
Same behaviour with flagging.

**Comment by jde** [comment]
This behavior is fixed
