### ISSUE TITLE
6.2.3/6.3 won't start

### ISSUE THREAD

**Issue by mkochco** [coralproject/talk#3052]
We've been running for several days in ECS without issue.  However a rolling restart has resulted in the following;
```
/usr/src/app # cat /root/.npm/_logs/2020-07-29T03_45_15_813Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @coralproject/talk@6.2.3~prestart: @coralproject/talk@6.2.3
6 info lifecycle @coralproject/talk@6.2.3~start: @coralproject/talk@6.2.3
7 verbose lifecycle @coralproject/talk@6.2.3~start: unsafe-perm in lifecycle true
8 verbose lifecycle @coralproject/talk@6.2.3~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle @coralproject/talk@6.2.3~start: CWD: /usr/src/app
10 silly lifecycle @coralproject/talk@6.2.3~start: Args: [ '-c', 'NODE_ENV=production node dist/index.js' ]
11 silly lifecycle @coralproject/talk@6.2.3~start: Returned: code: 1  signal: null
12 info lifecycle @coralproject/talk@6.2.3~start: Failed to exec start script
13 verbose stack Error: @coralproject/talk@6.2.3 start: `NODE_ENV=production node dist/index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @coralproject/talk@6.2.3
15 verbose cwd /usr/src/app
16 verbose Linux 4.14.123-111.109.amzn2.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v12.18.1
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error @coralproject/talk@6.2.3 start: `NODE_ENV=production node dist/index.js`
22 error Exit status 1
23 error Failed at the @coralproject/talk@6.2.3 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Console logs show the following additional entries

```
{"log":"(node:24) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit","service":"coral-dev","source":"stderr","timestamp":1595990023000}
{"log":"(node:24) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.","service":"coral-dev","source":"stderr","timestamp":1595990023000}
```

**Comment by wyattjoh** [comment]
If you've upgraded from a previous release, you might need to re-run:

```
npm install
npm run build
```

We're running 6.2.3 and 6.3.0 currently on GKE without issue. The provided logs related to max listeners and deprecation warning shouldn't affect the runtime.

**Comment by mkochco** [comment]
We're running the image published by Coral in AWS ECS Fargate.  We're not building locally.   Are you saying that switching the docker image version from 6.2.3 to 6.3.0 will break existing deployments?  Is there a manual migration required?

**Comment by kgardnr** [comment]
Hey @mkochco can you tell us which site(s) you're running Coral on?

**Comment by mkochco** [comment]
It's running in our development/staging environment on AWS and not currently available to the public.   Is there a way to configure the Container to provide more logging info so that we can see the root cause of the failure to start?

**Comment by kgardnr** [comment]
Can you tell us the site it will eventually be used on? If you're not comfortable sharing publicly, you can email us support@coralproject.net

**Comment by kgardnr** [comment]
Thank you @mkochco!

**Comment by wyattjoh** [comment]
No migrations are required for this transition. We run these images in production ourselves without issue. It may be the case that other logs were outputted that were not related to the npm logs you printed there. Make sure the deployments have enough memory available to start as well as anything that isn't application bound related to things are typically resource related.

You can also set `LOGGING_LEVEL=trace` to get more verbose logging.

**Comment by mkochco** [comment]
Thanks @wyattjoh - further digging reveals; 
```
InProgressMigrationDetectedError: migration "1579189174930" was in progress
```
This is the second time this has occurred on the deployment of a new coralproject/talk container to ECS.  The last occurrence was resolved by a rebuild of the MongoDB/Redis clusters.  What is the appropriate recovery path from this situation?

**Comment by wyattjoh** [comment]
It looks like a migration was in progress from a previous release. You will have to delete the document in the `migrations` collection with id `1579189174930` and then start up a single instance of Coral to perform that migration till it's ready to go.

We're still improving the migration system, but we haven't added any new migrations since January (hence the timestamp/id of `1579189174930`).

**Comment by mkochco** [comment]
So it looks like the issue has to do with `text` indices not being supported by DocumentDB.  Strangely the initial install and run of Coral in ECS succeeded and we were able to run/test in our dev and prod environments in AWS.  Since about a week or so ago we've been unable to rolling restart the nodes.  The first error is `InProgressMigrationDetectedError`.   A manual removal of the migration record, and a single node restart results in `Index type not supported : text`.  I see from a similar issue that version 5.x did not support a Mongo-compliant DocumentDB.  Are there plans to support it?  Is there a workaround for running on DocumentDB?

**Comment by wyattjoh** [comment]
Ah, yes. That would definitely be the issue then.

Unfortunately, we have no plans as of yet to support DocumentDB. We only officially support MongoDB using their official client.

I'd suggest either self-hosting MongoDB yourself or using a hosted instance from MongoDB Atlas. If that's not possible, you might need to fork Coral and remove the offending indexes from the migration.
