### ISSUE TITLE
Feature Idea: Metrics for Perspective API/Akimest 

### ISSUE THREAD

**Issue by desk467** [coralproject/talk#3072]
## Search Terms

prometheus, metrics, external services

## Suggestion

Currently, Talk provides some metrics via Prometheus, but it does not bring any metrics about any of external services it uses (such like Perspective API or Akimest). It would be interesting that this metric could also be collected, so we could have one more piece of data that could help in decision making when triggering these external services.

## Use Cases

With this data being collected, we could have a clearer idea of how the time spent on these external services may be impacting the user experience (in particular the Perspective API)

**Comment by kgardnr** [comment]
@desk467 we don't have plans to do this in the near future, but thank you for the suggestion!
