### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by bowser2010** [coralproject/talk#3091]
Hello, I changed a text in the file /usr/src/app/src/locales/es/stream.ftl, when I did a **git push -u origin coral623_v1** says this:

**remote: Permission to Coralproject/talk.git denied to bowser2010.
fatal: unable to access 'https://github.com/coralproject/talk.git/': The requested URL returned error: 403**

I guess that you have to give me account permissions. Please help.

Regards,

**Expected behavior:**

Git push successful

**Actual behavior:**

remote: Permission to Coralproject/talk.git denied to bowser2010.

**Related Issues:** 

**Versions:**

- NodeJS: 12.16.1
- NPM: 6.13.4
- MongoDB: 4.2
- Redis: 3.2
- Browser: Chrome
- OS: Linux Ubuntu

**Comment by kgardnr** [comment]
Hey @bowser2010 you'll need to create a pull request, we don't allow anyone to push directly to the repo - you can follow these instructions step by step here: https://opensource.com/article/19/7/create-pull-request-github

**Comment by bowser2010** [comment]
Hi Kim, WOW I did it at last.  Below is the information after I did git push:

Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 6 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 552 bytes | 552.00 KiB/s, done.
Total 6 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), completed with 5 local objects.
remote:
remote: Create a pull request for 'translate_1' on GitHub by visiting:
remote:      https://github.com/bowser2010/talk/pull/new/translate_1
remote:
To https://github.com/bowser2010/talk.git
 * [new branch]          translate_1 -> translate_1
Branch 'translate_1' set up to track remote branch 'translate_1' from 'origin'.

I already pushed button Create a pull request so you please let me know when this is ready. Thank you.

**Comment by kgardnr** [comment]
Awesome @bowser2010 and thank you so much for submitting those pull requests!! They are now included in our latest release, 6.3.3! 🎉
