### ISSUE TITLE
SSO Auth Configuration showing Blank Page

### ISSUE THREAD

**Issue by sailendra2017** [coralproject/talk#3123]
Hi Coral,

I am getting Blank Page while go for SSO Auth Configuration.

![image](https://user-images.githubusercontent.com/25950585/90795910-468e0480-e32c-11ea-8216-63295c0bb56d.png)

**Comment by kgardnr** [comment]
Hey @sailendra2017 can you let us know where you're planning to use Coral? Is this for a client site?

**Comment by sailendra2017** [comment]
Hi kgardnr,

I try Coral in my local environment, after checking all functionality, we will use it for our client.

**Comment by kgardnr** [comment]
I think this is probably related to the other issues you've logged that are related to developing on a Windows machine.

**Comment by wyattjoh** [comment]
For this issue, you need to run `npm run build` before you run `npm run start:development` to build the client bundles.
