### ISSUE TITLE
Error: Cannot find module './build/Release/re2'

### ISSUE THREAD

**Issue by sailendra2017** [coralproject/talk#3129]
Hi Coral Team,
I found "Error: Cannot find module './build/Release/re2'" while run application using "npm run start:development" in Window 10 OS

![image](https://user-images.githubusercontent.com/25950585/90950043-ac34da80-e46b-11ea-9547-1dbe72723849.png)

**Comment by kgardnr** [comment]
Hey @sailendra2017 we don't formally support development on Windows 10. You can use a Linux dev environment instead, by using something like Virtual Box.

You're also welcome to add Windows dev env support if you like, but we don't have any plans to address this.

**Comment by kgardnr** [comment]
Try the `build` step Wyatt mentioned in his reply.
