### ISSUE TITLE
Comment count is incorrect when comment with replied is deleted

### ISSUE THREAD

**Issue by tranvansang** [coralproject/talk#3130]
When a comment with replies is deleted

**Expected behavior:**

Decrease the comment count including the replies

**Actual behavior:**

Only decrease the comment count by one

**Related Issues:** 

**Versions:**

- Docker: coralproject/talk:6.3.2
- NodeJS:
- NPM:
- MongoDB:
- Redis:
- Browser: chrome/firefox
- OS: `Linux vultr.guest 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by kgardnr** [comment]
Hey @tranvansang! The comment count only counts the top-level comments, not the replies.

What sites do you plan on using Coral on?

**Comment by tranvansang** [comment]
@kgardnr hi.

I am hosting the server myself by the open-sourced version. Thank you for the awesome product.

> The comment count only counts the top-level comments, not the replies.

If this is the case. I think that replies are now mistakenly counted as comment count.

Btw, this does not affect too much to my website.

**Comment by kgardnr** [comment]
Ok thanks!
