### ISSUE TITLE
Unrecognize Request Url

### ISSUE THREAD

**Issue by sailendra2017** [coralproject/talk#3136]
I am getting Unrecognize Request URL error while run the application after npm run start:development

![image](https://user-images.githubusercontent.com/25950585/91188639-2638be00-e70f-11ea-8000-5ebe24577390.png)

**Comment by kgardnr** [comment]
Probably the same issue with running `build` step first. Can you try and let us know?

**Comment by sailendra2017** [comment]
I am getting  following error while build application using "npm run build" command

![image](https://user-images.githubusercontent.com/25950585/91385422-75d1d380-e84e-11ea-9852-4cf6ee6cc9fe.png)

After that while run "npm run start:development", i got following info, then try to access it on localhost and get "Unrecognize Request Url"
![image](https://user-images.githubusercontent.com/25950585/91385593-e8db4a00-e84e-11ea-92b5-373c82b74ca8.png)
