### ISSUE TITLE
Can't login to Admin Page (no user/pass dialog)

### ISSUE THREAD

**Issue by mkochco** [coralproject/talk#3142]
**Expected behavior:**
/admin/login - presents user with a username/password dialog

**Actual behavior:**
![image](https://user-images.githubusercontent.com/1760848/91340284-fd5b0c00-e794-11ea-87f1-630652463fcf.png)

**Related Issues:** 
None

**Versions: **
6.3

- NodeJS: v12.8.3
- NPM: 6.14.6
- MongoDB: MongoDB Atlas
- Redis: ElastiCache Redis
- Browser: Chrome/Safari
- OS: docker image coralproject/talk:6 on ECS Fargate

**Comment by kgardnr** [comment]
Hey @mkochco you've disabled sign in on the Admin. You'll need to correct this by changing the settings in Admin > Configure > Authentication. If you've locked yourself out, you'll need to update this in the database directly.

What sites are you planning to use Coral on?

**Comment by mkochco** [comment]
havenly.com

We're locked out.  Which collection contains the config for enabling/disabling Admin signons?

**Comment by mkochco** [comment]
Found it `tenants` collection - 
```
"auth": {
        "sessionDuration": 7776000,
        "integrations": {
            "local": {
                "enabled": true,
                ....
```

**Comment by mkochco** [comment]
Sorry.  Issue on our side.
