### ISSUE TITLE
Migration and Backup

### ISSUE THREAD

**Issue by andrewfam** [coralproject/talk#3144]
**Expected behavior:**
Our Coral project crashed and we had to reset it up with a backup of the last coral backup from the mongodb using mongodump.

**Actual behavior:**
After loading the database using mongo restore, we are stuck at the installation screen and after filling in the data, we do not see any of the data that was loaded in. Inspecting using compass shows that the data is all in there. Is there any configuration or things we need to trigger the site to load the past tenant?

**Versions:**
We are using the latest coral 6

**Comment by andrewfam** [comment]
Any update on this?

**Comment by wyattjoh** [comment]
Ensure you're pointing to the same database that your application is pointing to would be my first guess. We do dump/restore all the time and have not encountered issues.

**Comment by andrewfam** [comment]
I've had to clone the site to another site.

The following are the 2 commands I used and I see the data from the old site but I'm still seeing the installation page
docker-compose exec -T mongo mongodump --archive --gzip --db coral > dump.gz
docker-compose exec -T mongo  mongorestore --archive --gzip < dump.gz
