### ISSUE TITLE
Update from version 5.3.2 to v6

### ISSUE THREAD

**Issue by snkekorfus** [coralproject/talk#3145]
Hi dear coral team,

I would like to know how I can migrate talk from v5.3.2 to v6. I know that I first have to update to version 5.5.1 but I don't even know how to do that. Are there any scripts that can be executed to apply the migration to the database?

I'm really thankful for any help!

**Comment by kgardnr** [comment]
Hey @snkekorfus here are our migration docs: https://docs.coralproject.net/coral/migration/6.0/
