### ISSUE TITLE
Char count feedback

### ISSUE THREAD

**Issue by allanassis** [coralproject/talk#3197]
**Expected behavior:**
When commenting i expect to see a feedback if i click on send comments button with less characters then allowed

<img width="640" alt="Captura de Tela 2020-09-23 às 16 23 45" src="https://user-images.githubusercontent.com/23871115/94059685-2af99c00-fdb9-11ea-8936-d4354386c11a.png">

This picture is from 6.2.3 version

**Actual behavior:**
Nothing is happening when i click on send comment button if there are less characters then allowed

<img width="1678" alt="Captura de Tela 2020-09-23 às 10 25 08" src="https://user-images.githubusercontent.com/23871115/94059317-9f800b00-fdb8-11ea-8366-84796488008a.png">
<img width="1680" alt="Captura de Tela 2020-09-23 às 10 24 59" src="https://user-images.githubusercontent.com/23871115/94059324-a149ce80-fdb8-11ea-921b-9baf67cd717e.png">

Those pictures is from 6.3.4 version

**Versions:**

- NodeJS: 12.14.1
- Browser: Chrome 85

**Comment by kgardnr** [comment]
Hey @allanassis! We found this issue last week as well, we're working on a fix! Thank you!

**Comment by allanassis** [comment]
Thanks @kgardnr !!

**Comment by kgardnr** [comment]
Fixed in #3188 🎉
