### ISSUE TITLE
unable to Login with OpenID Connect  if i had already signup with SSO with the same email and sub

### ISSUE THREAD

**Issue by yannick-fernand** [coralproject/talk#3198]
We have configure  and enable 2 auth. SSO and OpenId Connect in admin console to allow admin to go directly on admin console without going through our site. 
But when someone signup with SSO and after want to signin to admin console using OpenID Connect we got an DuplicateEmailError. 
 
**Expected behavior:**
If an existing user auth successfully using another auth method we expected an auth succeeded and a merge of the auth informations and not an DuplicateEmailError 

**Actual behavior:**
The user is blocked with DuplicateEmailError

**Talk version :** 6.3.6

<img width="1676" alt="Capture d’écran, le 2020-09-24 à 12 41 07" src="https://user-images.githubusercontent.com/6329739/94175269-74eb8c00-fe64-11ea-9b2c-3c7050e4dc8a.png">

database tenant auth configuration:

<img width="827" alt="Capture d’écran, le 2020-09-24 à 12 52 57" src="https://user-images.githubusercontent.com/6329739/94176133-a6188c00-fe65-11ea-80cf-44da93e78456.png">

**Comment by yannick-fernand** [comment]
update: 

I disable all others auth configurations and enable only SSO and OpenID Connect. When i have try login with OpenID Connect i got the following page 

<img width="1674" alt="Capture d’écran, le 2020-09-24 à 11 24 43" src="https://user-images.githubusercontent.com/6329739/94170526-2fc45b80-fe5e-11ea-85a4-be5ce1eadb52.png">


And when i enter a password and click on `Link account`  i got an 500 error 

<img width="1679" alt="Capture d’écran, le 2020-09-24 à 11 42 19" src="https://user-images.githubusercontent.com/6329739/94170638-4ff41a80-fe5e-11ea-9c80-ea24b3fcebf1.png">

**Comment by genetus** [comment]
Same if you is admin and try to sign in through SSO. Mutiple auth methods on one email not work?

**Comment by kgardnr** [comment]
Hey @yannick-fernand and @genetus, Coral has the requirement of a unique email address. We don't prevent you from using different login providers, but you should limit to max 2, one for Admins/Mods and one for Commenters. If you're using SSO, you shouldn't be also using OIDC.

Does that make sense?

**Comment by yannick-fernand** [comment]
Thank you for your answers. 

I understand  your requirement of unique  email address if OIDC login and SSO login return the same `email` but different `sub/id`. But what  i don’t understand is why i am blocked if the OIDC login and SSO login return the same `email` and `sub/id` ? 

What are the others auth that are compatible with SSO for admins ?

**Comment by yannick-fernand** [comment]
hi any update?

**Comment by wyattjoh** [comment]
We currently have no process to merge or manage users that use different login methods SSO/OIDC. This is a planned problem for us to tackle, and we will update this ticket when we get to this issue.
