### ISSUE TITLE
Mobile implementation

### ISSUE THREAD

**Issue by djock** [coralproject/talk#3210]
We're trying to implement the coral v5 system in our mobile app (built with flutter). Has anyone implemented on mobile, suggestions on how to communicate with the coral graphql?

**Comment by wyattjoh** [comment]
We've seen people use Coral embedded inside an iframe/webview in mobile apps before!

**Comment by kgardnr** [comment]
@djock we've added this to our docs now! https://docs.coralproject.net/coral/v5/integrating/mobile/
