### ISSUE TITLE
Support "quarantine"/inactive user status for a custom duration before completely delete user

### ISSUE THREAD

**Issue by HectorNM** [coralproject/talk#3221]
## Search Terms
delete, deletion, deleted, inactive, temporarily, quarantine

## Suggestion
Today, when the user chooses to delete their account, Talk will schedule deletion for a specific time. In this meantime, user is still active, with all their comments available in database and avaialble to final users to see. And after that time, the user and all of their comments are completely deleted from database. We have a new case inside Globo and we would like to suggest, which is a "temporarily deletion", "account deactivation" or something like a "quarantine" for a specific duration (eg. 180 days). During this time, user is marked as inactive, and all of his comments won't appear for the general public (or they'll appear as deleted). However, if during this period (eg. of 180 days) the user logins again, their accounts will be reactivated and all of their comments will be shown again, in a scheduled time as well. 
_Maybe_ that could be modeled as a new user status (eg: `inactive`), that would have some behaviours similar to deleted (eg. showing a message as "deleted", etc).

## Use Cases
Deactivation will allow user to have some time to think if they really want to delete their data from the system. From a business perspective, this could improve retention of users in databases. From user perspective, this is less harsh than deleting their account. Globo is an example case that would benefit from this feature.
Today, to develop this by ourselves, we would move user comments from another database, and if the user logins again, we would insert their comments again in Talk database, so that feature would be perfect for our needs.

**Comment by losowsky** [comment]
Hi Hector! Just so that I understand, this means that if, say, a user dies, then all of their contributions to your community will be removed/hidden?

**Comment by HectorNM** [comment]
Hi @losowsky , thank you for your time ! Not really, what we were thinking is a intermediate step before the complete deletion of the user comments..

Something like this:
- How Coral Talk works today:
-> User asks to delete account -> user is marked as deleted (`deletedAt`) and all of their comments are deleted from database;

- What we are proposing:
-> User asks to delete account -> user is marked as "deactivated" for X days. During this time, all of their comments appear as removed (so, they are shown as "This user deleted this comment" or some deletion message). But Coral Talk still have their comments stored in database. And we have the possibility to ask Coral Talk to reactivate user, if we need so (for example, if user logins again and/or asks to reactivate account again), and so all os their comments will reappear. After X days, all of their comments are deleted from database, and ultimately deleted, and then the user will be marked as deleted (in `deletedAt` field).

Just to give an example, this is the behaviour when deleting a Facebook profile: it keeps your data for 90(I think) days before deleting your account. If you login again before 90 days, then your profile is activated again. Although Facebook is not a comment platform, it's just to be clear..  :) 

What do you think?
If you like the idea, we could contribute with a PR!

**Comment by tessalt** [comment]
Closing as the proposed solution would not comply with GDPR right to erasure
