### ISSUE TITLE
Perspective API plugin disappeared

### ISSUE THREAD

**Issue by mattlinares** [coralproject/talk#3233]
I am looking for this plugin: https://docs.coralproject.net/talk/plugin/talk-plugin-toxic-comments/

Which is listed in the directory: https://docs.coralproject.net/talk/plugins-directory/

But appears to have disappeared from GitHub:
https://github.com/coralproject/talk/tree/master/plugins/talk-plugin-toxic-comments

Any ideas?

Thanks!

**Comment by wyattjoh** [comment]
Looks like the docs need some updating, thank you!

The plugin is on the `release/4` branch:

https://github.com/coralproject/talk/tree/release/4/plugins/talk-plugin-toxic-comments

**Comment by mattlinares** [comment]
fyi This also breaks the link from: https://perspectiveapi.com/#/start

**Comment by wyattjoh** [comment]
We'll be contacting the perspective team about that one, thank you!
