### ISSUE TITLE
DUPLICATE_USER error in this case: user creation via SSO, and then deletion, and then creation again via SSO

### ISSUE THREAD

**Issue by HectorNM** [coralproject/talk#3243]
Hi everyone!
We are trying to use Coral Talk for a new case use, which could be described as this: user creation via SSO -> user deletion -> same user creation via SSO again. When trying to create user again via SSO, we receive a `DUPLICATE_USER`  from Talk.

After trying to understand why this happened, we found out how user creation using SSO and user deletion work. It seems there is a case when Coral Talk creates in mongo user collection a document with `id` having the same value as `profiles[].id`.  This happens in `findOrCreateSSOUser`  in `src/core/server/app/middleware/passport/strategies/verifiers/sso.ts` file. In this function, we check if the user has a SSO profile (or any other profile) with the given `id` (from `sub` claim in JWT token). This happens on `retrieveUserWithProfile` call, line 129. If the user doesn’t have a profile created using SSO, then we reach the `if (!user)`  on line 140, and inside this `if`, on line 155, we try to create a new user passing the same `id`  mentioned before to be his root id and also to be his `profile[].id` in `user` collection. So, in the first time that we execute this piece of code, we will have created user with his root `id` and `profile[].id`  to be the same as subclaim in JWT token.

And then let’s suppose we try to delete this user. User deletion deletes all of his profiles (line 158 of file `src/core/server/services/users/delete.ts`). However, users are kept with theirs root ids in mongo document in user collection, so user will have `id` in his document collection, but won’t have `profiles` anymore. So, if we try to recreate user in these conditions,  this is what will happen: code on `sso.ts`  file mentioned before will try to check if there are SSO profiles associated with that user, and it isn’t the case. So it will try to create the user with the provided `id` , but since we already have a user with that `id` in mongo document, we will receive a `DUPLICATED_USER` error.

Could this be considered a bug of Talk? I labelled this as a bug, because if we delete all of user SSO profiles but still have his `sub` claim in `id` in mongo document, then there are still mentions to his SSO id, which prevents user from being created again. And it looks like Talk’ intentions when deleting a user is to remove all data that could make user recognizable, but it looks like it isn’t the case, since we have his SSO id stored in mongo document. So although it’s not the focus of this issue, if my understanding is correct, this could be a privacy concern, since we are storing an old SSO user id. It could be a problem if the SSO provider decides to use any personal information about user to identify user (example: his email).  But we are more worried with the possibility of creating a user again via SSO, which is not possible in these conditions.

Maybe, could this be done differently? For example, when deleting user, if we want to keep his mongo document without any mentions to him, maybe we could set his root `id` to be a random new uuid.  Or maybe this could be done during user creation as well. This could make user anonymous, without any old SSO id reference in his mongo document. Or maybe the user creation on `findOrCreateSSOUser` (and other user creation functions) could be done differently. We could check if user has a `deletedAt` field, and if that’s the case, then we know we have to update an existing user document, instead of updating it.

**Expected behavior:** Old user SSO ids are not kepts in mongo, so we can recreate user with SSO id used before.

**Actual behavior:** Old user SSO id is being store in id in user document in mongo, preventing users created via SSO before to be created again.

**Related Issues:** 
Issue https://github.com/coralproject/talk/issues/3198 is similar because returns DuplicateEmailError, but this issue is somewhat different.

**Comment by wyattjoh** [comment]
We currently don't have a workaround to this particular behaviour, but it is planned to address with more hard delete options.

**Comment by HectorNM** [comment]
Hi @wyattjoh ! Regarding this issue, I thought that when deleting the user, instead of leaving its id from its SSO provider there, we could change the user id to something like:

before: `userID`
after: `userID-deleted-timestamp` 
This way, the user could be recreated multiple times if necessary, and we could know that this user existed in database in the past (instead of using a random uuid, as I suggested originally in the issue). Do you think this could be a valid contribution for a PR?

**Comment by wyattjoh** [comment]
The issue we're concerned with at the moment is orphaning documented created by the user. By default, when a user is deleted, we don't delete their comments, only the comment text itself is deleted!

The means that if we wanted to change the ID of the user, we would have to also update all their comment author id's and similar, which could be pretty expensive.

I think we would be interested in a hard delete option that would resolve these situations!
