### ISSUE TITLE
Perspective API not working or reporting error

### ISSUE THREAD

**Issue by mattlinares** [coralproject/talk#3284]
**Expected behavior:**

When activated by adding API key (here: https://talkserver.com/admin/configure/moderation) Perspective API should flag/moderate/block obviously offense messages e.g. those with straight profanity.

**Actual behavior:**

Offensive messages are published, no intervention from Perspective.

Ideally there would be some validation on the config screen to show that the API key and service are functional, but there isn't.

**Versions:**

- NodeJS: v12.19.0
- NPM: 6.14.8
- MongoDB: 4.2.10
- Redis: 3.2.12
- Browser: Firefox 82.0.2
- OS: MacOS

**Comment by kgardnr** [comment]
Hey Matt! Can you write into our support so we can get some more details and help you troubleshoot this? It has to be an issue with your specific setup.

coralsupport@voxmedia.com

**Comment by kgardnr** [comment]
Also let us know what version of Coral you're using.

**Comment by cristiandean** [comment]
Hey @mattlinares, I went through a similar problem and solved it by increasing the timeout for the perspective API by changing the value of the environment variable PERSPECTIVE_TIMEOUT to 1500.

Sadly the response time exceeds 1 second for me most of the time.
