### ISSUE TITLE
Plugins in v5+

### ISSUE THREAD

**Issue by aliblackwell** [coralproject/talk#3291]
Hello Coral Talk team! I am working with @mattlinares for openDemocracy on web monetization for comments, funded by Grant for the Web. Details here (search page for "openDemocracy"): https://www.grantfortheweb.org/grantees 

We are currently in a very early research phase and are working out potential architecture. We had thought to build it as a plugin, but I have just discovered that [plugins are no longer supported](https://docs.coralproject.net/coral/migration/5.0/). Perhaps we could use this thread to discuss "some of the new ways to solve custom use cases in v5 and beyond"?

We are planning to open an issue to discuss the web monetization idea, but wanted to get our heads around Coral Talk first. Any pointers you could offer at this stage would be greatly appreciated :) Thank you.

**Comment by kgardnr** [comment]
Hey Ali, I'd recommend getting in touch with us here so we can talk more about this: coralsupport@voxmedia.com
