### ISSUE TITLE
Feature Request: Require Email Confirmation

### ISSUE THREAD

**Issue by diegoos** [coralproject/talk#3297]
I've installed and try to find the option to make the verification email required before comment.
After a search on docs, I find the option `requireEmailConfirmation` on version 4, but nothing on version 5+.

My question is: Is there any way to make the confirmation required prior to comment?

### **Expected behavior:**
Users can only comment when they confirm their email.

### **Actual behavior:**
I cannot find any configuration to enable this, so users can comment without confirming their email.
This behavior can increase the number of fake accounts since a user can register with any fake email.
For example, I able to create an account with the email `fake@fake.com`, comment and the comment was visible to everyone.

**Comment by wyattjoh** [comment]
We do not have this feature currently in version 5+ yet! It's planned to be supported in the future!

**Comment by diegoos** [comment]
Hi @wyattjoh.
Thanks for your reply.
Sad to known that is not possible now. :(

**Comment by kgardnr** [comment]
@diegoos we had a lot of issues with this in v4 actually; what we recommend for the time being is integrating with your own SSO and requiring email verification on your account side.

**Comment by diegoos** [comment]
Thanks for the feedback @kgardnr. 
We don't have any kind of login system on our side. :(
