### ISSUE TITLE
Provide a way to set amount of comments and replies to load in V5+

### ISSUE THREAD

**Issue by diegoos** [coralproject/talk#3304]
## Search Terms

load, comments, limit, amount of comments

## Suggestion

Provide a way to choose how many comments and replies will be initially loaded and by clicking on the load more button.
I think that if it were possible to set this quantity by an environment variable it would be enough.

## Use Cases

On our page, we have a lot of content, and we usually keep a maximum of 10 comments on the first load.
This decreases the number of scrolls that a user needs to make to reach the content below the comments block.

**Comment by kgardnr** [comment]
Hey @diegoos we discussed this and won't be adding this feature in the near future

**Comment by diegoos** [comment]
Sad to know that.  😢

**Comment by ideallical** [comment]
This is the same issue I'm experiencing.
I'm in the progress of migrating coral v4 to v5/v6 and noticed that these handy envs are now gone:
```
TALK_ADDTL_COMMENTS_ON_LOAD_MORE
TALK_ASSET_COMMENTS_LOAD_DEPTH
TALK_REPLY_COMMENTS_LOAD_DEPTH
```

We used these configuration abilities to be able to create a feature that allows users to read the first 5 comments, and if they click on "load more comments" a popup is shown that they have to authenticate to read more comments.

I noticed it is now hardcoded to 20: https://github.com/coralproject/talk/blob/v6.16.1/src/core/server/graph/schema/schema.graphql#L3920

And that you can best change it here at the `AllCommentsTabQuery`, by inserting `e.g count: 5` here https://github.com/coralproject/talk/blob/v6.16.1/src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabQuery.tsx#L104-L108

Would you reconsider making this a configurable? It seems like a small change that could be really useful.
