### ISSUE TITLE
Add Jaeger for tracing

### ISSUE THREAD

**Issue by allanassis** [coralproject/talk#3314]
Hello Talk team, what do you guys think about instrumenting the code to use Jaeger?

Would be great for improve traceability.

## Search Terms

- Tracing
- Jaeger

## Suggestion

Instrumenting the code to use [Jaeger](https://www.jaegertracing.io/), a very popular tracing tool.

## Use Cases

Improving all traceability in Talk

**Comment by wyattjoh** [comment]
Definitely interested! We're working internally to improve the server architecture, and will definitely be looking into this!

**Comment by rafaeleyng** [comment]
Hi! I suggest you looking into https://opentracing.io/ instead of focusing on integrating with Jaeger. Is just an abstraction layer to make it work better with several tracing tools.

**Comment by wyattjoh** [comment]
I actually looked into OpenTracing, looks like a great project! That definitely would be the direction we'd take it.
