### ISSUE TITLE
Translations missing in Spanish

### ISSUE THREAD

**Issue by mato777** [coralproject/talk#3336]
There are some translations missing in Spanish:
1. In the report form: Additional information Optional, 
2. Share link => "Copy link"
3. Comment on:
4. Replying to: 
I can make the changes to fix this, but I have the installation in docker, I've tried to re build the app but it fails and also can not rerun the node index.js.

Is there a way to this changes directly and rebuild inside a docker image?

**Comment by wyattjoh** [comment]
I would suggest using the application in development mode ([see instructions on how to here](https://docs.coralproject.net/coral/v5/developing/)), and follow the linked instructions on how to submit changes for a localization there! Most of our localizations are contributed, so we always welcome fixes!

**Comment by kgardnr** [comment]
@bowser2010 since you've been submitting new Spanish translations (thank you for that 😍 ), wanted to bring this to your attention as well!

@mato777 are there other translations missing?
