### ISSUE TITLE
Documentation request: dealing with 100+ relocated pages

### ISSUE THREAD

**Issue by Pomax** [coralproject/talk#3337]
It looks like there's no documentation request template, so that might be worth adding - having said that, I'm trying to find docs that explain how (if at all) to tell Coral that some 300 pages are now on different URLs. They used to have URLs similar to http://example.com/discuss/product/product-name, but are now on http://example.com/discuss/product-name without the `products/` infix, but because the URL is different, none of the old comments show up.

Is there an argument that can be passed to `Coral.Talk.render` to indicate _both_ "the current url" and "the old URL" so that coral can rebind the comment asset (so that it loads the old comments on the new canonical/asset url), or, is it possible to (bulk?) update the URL(s) associated with comment thread(s) manually, or is there maybe something else that lets one deal with permanently moved pages that you want to preserve the conversation on?

**Comment by wyattjoh** [comment]
You'll likely have to change those url's in the database directly (as it appears that you're using Talk v4). Documents are stored in the `assets` collection in MongoDB, so you should just need to issue some commands that look like this:

```js
db.assets.updateOne({ "url": "<old url>" }, { "$set": { "url": "<new url>" } });
```

Let me know if you have any other questions, or close the issue if this resolves things for you!

**Comment by Pomax** [comment]
Thanks!

Though, even if it works for me, that sounds like something that's worth putting in the docs as advanced topic, since site IA refreshes are not uncommon on the web =)

**Comment by wyattjoh** [comment]
In Talk v6 (and beyond) we actually provide this via our standard GraphQL API as the `updateStory` mutation!

```graphql
mutation UpdateArticleMetadata($id: ID!, $story: UpdateStory!) {
  updateStory(input: {clientMutationId: "", id: $id, story: $story}) {
    story {
      id
    }
  }
}
```

We're planning a documentation pass soon, so I'll make sure to call this out! Thank you!

**Comment by Pomax** [comment]
cheers!
