### ISSUE TITLE
Features for non authenticated users (guests)?

### ISSUE THREAD

**Issue by index23** [coralproject/talk#3356]
Is there option or configuration that allows non authenticated users (guests) to post reaction on existing comments? 

Currently users have to be authenticated to be able to post reaction on comment. So we should force users to some sort of authentication which can impact badly our UX. We want more interaction on our articles and comments and this could discourage users to post reaction on comments.

**Comment by wyattjoh** [comment]
Coral doesn't store PII outside of email addresses for users, so we don't store ip addresses or other identifiable pieces of information. Reactions are recorded against content using the user's ID. To encourage a safe and maintainable environment for all users, we've advocated against adding any anonymous user features to the platform, as it would be difficult to police without having to collect more intrusive personal information (like ip address) from every visitor.

Unfortunately we are unable to support this feature request. If you want to ease signing up, Coral does provide single sign on via Facebook or Google to speed up the login process for users.
