### ISSUE TITLE
Issues with Context Paths

### ISSUE THREAD

**Issue by bmfrench89** [coralproject/talk#3376]
Good Afternoon,

We are having issues setting up Coral as a context path.  Is it possible to setup Coral behind a context path? In older documentation I see that it exists, however we are on 6.3.11 and it seems that this was removed?

TALK_ROOT_URL and TALK_ROOT_URL_MOUNT_PATH

If so, any documentation provided would be great. 

Thank you!

**Comment by losowsky** [comment]
Hi bmfrench89,

Thanks for asking. Coral 6+ can not be mounted on a path, and must be mounted on its own domain.

Best wishes

Andrew
