### ISSUE TITLE
Inject html to the embed code

### ISSUE THREAD

**Issue by bowser2010** [coralproject/talk#3377]
Hi, is there a way to inject html to the embed code that goes in the article? Any hook, API or function?

Best Regards,

**Comment by wyattjoh** [comment]
You can see examples of the embed code on our documentation [here](https://docs.coralproject.net/coral/v5/integrating/cms/) also in your admin area of a running Coral instance in *Configure* > *Organization* > *Site Details*.

Hope that helps!
