### ISSUE TITLE
group text + button for login with stable class name

### ISSUE THREAD

**Issue by frisi** [coralproject/talk#3385]
## Suggestion

in order to hide the "join the conversation" text + buttons 
![grafik](https://user-images.githubusercontent.com/1120517/105739098-09abe680-5f38-11eb-9749-c9500e9c89f0.png)

one currently needs to hide
`UserBoxUnauthenticated-actions-*` and `UserBoxUnauthenticated-joinText-*`

```
.coral-comments div[class^='UserBoxUnauthenticated-actions'],
.coral-comments span[class^='UserBoxUnauthenticated-joinText'] {
  display: none;
}
```

margin and padding of the surrounding container are stil applied

if the surrounding div would have a stable class this would be easier and more robust to implement

**Comment by tessalt** [comment]
updated stable classnames will be shipped in the next release https://github.com/coralproject/talk/pull/4131
