### ISSUE TITLE
Setup does not prompt for whitelisted domain

### ISSUE THREAD

**Issue by wyattjoh** [coralproject/talk#342]
### Expected behaviour

- During the setup wizard, it should prompt to whitelist the current domain as safe, or recommend you enter the whitelisted domain

### Actual behaviour

- It does not

**Comment by jde** [comment]
This is a good point. I think we need to rethink the entire concept of how we fake out assets as it is confusing. I'm not sure if we want to support fake threads, or if we do we need to be very specific about what's going on.

**Comment by wyattjoh** [comment]
Resolved with https://github.com/coralproject/talk/pull/348
