### ISSUE TITLE
How I can to use Avatars? 

### ISSUE THREAD

**Issue by DenisDoroshchuk** [coralproject/talk#3436]
Hello,

I can't find instructions on how to enable avatar support for users. 
I installed the Coral through a docker, version the Coral - 6.7.2.

Thanks,
Denis

**Comment by wyattjoh** [comment]
We currently have not released avatar support as a stable feature yet! We'll be sure to update this ticket when we've been able to do so.

**Comment by DenisDoroshchuk** [comment]
Hello @wyattjoh 
Thanks for your answer.
May be your know how I can to add only 2 images (for site member and simple user).

**Comment by wyattjoh** [comment]
Unfortunately we don't support that at the moment. You could experiment with using a custom CSS file, but we're unable to provide support for that.

**Comment by DenisDoroshchuk** [comment]
@wyattjoh thanks, I will wait avatar support realisation.
