### ISSUE TITLE
Apollo Client not using addTypename

### ISSUE THREAD

**Issue by wyattjoh** [coralproject/talk#344]
### Expected behaviour

No error after production deploy.

### Actual behaviour

Got the following while viewing a comment in the console:

> You're using fragments in your queries, but don't have the addTypename:
true option set in Apollo Client. Please turn on that option so that we can accurately
match fragments.

### Steps to reproduce behaviour

1. Build for production
2. Create account
3. Post comment
4. Observe warning in console.

**Comment by davidgljay** [comment]
Adding this directly doesn't effect the error, and there is no Apollo
documentation that I can find that mentions addTypeName in this way.
