### ISSUE TITLE
How to retrieve reported comments already moderated?

### ISSUE THREAD

**Issue by e-talent2018** [coralproject/talk#3442]
Hello,

The situation is the following: a user reports an approved comment, In Coraltalk this comment doesn't change status so it is not in the reported queue!!.
Is there an API that allows retrieving reported comments?

Best Regards,

Lotfi.

**Comment by kgardnr** [comment]
Hey Lofti, thanks for getting in touch! Where are you using Coral?

The question you raise is by design - if a comment is approved, we're assuming the decision made was the right one, and therefore, we won't pull comments back into the reported queue ad infinitum, worsening the moderator burden.

**Comment by e-talent2018** [comment]
Hey @kgardnr, 

Thanks for your answer.

We are a company specialized in moderation, our customer is a large group of TV channels using your hosted coraltalk solution.
I understood your decision, but I think you could have left the choice to the administrator or to the limit add an api that allows us to retrieve the comments reported for example in Getcomment add a filter on flag.

Is there an api to retrieve all reported comments regardless of their status, approved or not?    

Best,
Lotfi.

**Comment by tessalt** [comment]
This information could be retrieved through the graphql API by querying comment flags to find IDs of reported comments. https://docs.coralproject.net/api/queries/flags
