### ISSUE TITLE
Problem with comment count

### ISSUE THREAD

**Issue by DenisDoroshchuk** [coralproject/talk#3445]
Hello,

I think comment count working not correctly for me.
site: https://cyclingtips.com/

For example: this article have > 0 comments https://cyclingtips.com/2021/02/from-addiction-to-abstinence-what-i-learned-from-12-months-without-coffee/#coral_thread
Please check my screenshot http://joxi.ru/nAylvp8TwlMGQ2

But on homepage comment count equal 0.
Please check my screenshot http://joxi.ru/Grq8jlgCGEdyQA

Please help me!
Thanks

**Comment by wyattjoh** [comment]
Hi @DenisDoroshchuk! Coral uses cache headers for the comment count responses, so updates to comment counts could take up to 2 minutes to update!

**Comment by DenisDoroshchuk** [comment]
Hi @wyattjoh you can to check my site https://cyclingtips.com/
It's been more than 10 hours, but a comments count didn't updated.

**Comment by wyattjoh** [comment]
I took a look, and the comment count looks like it's 10 (instead of the current 13). It looks like you have Cloudflare in front of this that's caching the entries longer than expected:

```
HTTP/2 200 OK
date: Wed, 10 Feb 2021 17:14:16 GMT
content-type: text/javascript; charset=utf-8
x-content-type-options: nosniff
referrer-policy: strict-origin-when-cross-origin
x-xss-protection: 1; mode=block
x-trace-id: b3cf4d40-6b82-11eb-9a0f-07f5641b5122
content-language: en-US
etag: W/"af-09qXmsE8MBZJjGnmqwZOPBVkXt4"
x-cache-level: Z
x-cache-why: user-disabled-cache
vary: Accept-Encoding
x-cache: MISS:(lb2-c27-2)
cache-control: public, max-age=31556952
pressidium-rid: 37d8492087a0651c
cf-cache-status: HIT
age: 26530
cf-request-id: 082e88cfe1000002c050070000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=9smzPqWiaKwaSeOmJI%2F%2Fo9EOZqSazEPsMwEuS7g7ltkSafn0%2FAzV13myCjVjvd4Kii54WJqfxaXMrySMxXJAIVJgAg%2FBlqgKmVxUVF4CJ7Xge77xW3I%3D"}],"max_age":604800,"group":"cf-nel"}
nel: {"max_age":604800,"report_to":"cf-nel"}
server: cloudflare
cf-ray: 61f7772c986202c0-SEA
content-encoding: br
X-Firefox-Spdy: h2
```

Note the:

```
cf-cache-status: HIT
age: 26530
```

I would review your configuration there to ensure it's not being overridden.

**Comment by DenisDoroshchuk** [comment]
Hey @wyattjoh What is configuration you want review?
Cloudflare or Coral?

**Comment by wyattjoh** [comment]
I'm suggesting you check your Cloudflare configuration to see if you have forced any specific cache control policies on the Coral instance, as it appears you have forced a max age of 1 year (31556952 seconds from the above `cache-control` header).

**Comment by DenisDoroshchuk** [comment]
Hey @wyattjoh thanks for your info.
I disabled proxied on cloudflare, leave DNS only, and it work for me.
http://joxi.ru/Dr8zRaETM6XNO2
