### ISSUE TITLE
CoralTalk 4: actio_type filter does not work !

### ISSUE THREAD

**Issue by e-talent2018** [coralproject/talk#3455]
Hello,

I'm using the Coraltalk version 4, I wanted to retrieve comments reported with the CommentsQuery API, whatever the action_type value, the api returns all comments :(!!

Best Regards,

Lotfi.

**Comment by wyattjoh** [comment]
If that edge is returning all comments, are you sure that the user you're hitting the API with is a moderator or an admin? That edge requires one of those roles to use the `action_type` filter.

**Comment by e-talent2018** [comment]
Hello,
indeed, you were right, I used postman to do the test and forgot to change the token. thank you for your help.

Can you help me to retrieve the reported comments with the API 5+, unfortunately, I don't find this edge in the v 5+, knowing that I work in a company specialized in moderation and that our client is a large group of French TV channels that use the hosted version of Coraltalk, he insists on retrieving the comments posted even those that are moderated. 

Thank you in advance

**Comment by e-talent2018** [comment]
@wyattjoh, if you want, you can answer me on this ticket:
https://github.com/coralproject/talk/issues/3442
