### ISSUE TITLE
Shadow banning

### ISSUE THREAD

**Issue by DenisDoroshchuk** [coralproject/talk#3459]
Hello,

Are you planning to add "shadow banning"? 
Or do you already have it, but I can't found it.
https://en.wikipedia.org/wiki/Shadow_banning

Thanks
Denis Doroshchuk

**Comment by wyattjoh** [comment]
Hi @DenisDoroshchuk!

At this time, we do not support shadow banning, nor are we planning on implementing it.

It's often easy to detect by bad actors, and is a misleading tactic that continues to foster bad behaviour in a community. We instead advocate for methods of moderation like account suspension and account bans.

**Comment by DenisDoroshchuk** [comment]
Hey @wyattjoh thanks for your answer!
