### ISSUE TITLE
Question: SSO with Piano ID login

### ISSUE THREAD

**Issue by ghost** [coralproject/talk#3479]
Hi,

We have the Piano system for user login and identity management, and we're currently struggling with two issue:

- The structure of the JWT from Piano
- The Secret used to sign the JWT by Piano

...Nether of which we have any control over.

Piano generates a JWT signed with a Base64 secret, with the following structure:
```
{
  "iss": "https://id.piano.io",
  "sub": "58bcdeb8-a0c4-4434-ae4c-f93e61eabeee",
  "aud": "765tg976",
  "login_timestamp": "1615566229416",
  "given_name": "Bob",
  "family_name": "Dopaleena",
  "email": "Bob@dopaleena.com",
  "email_confirmation_required": false,
  "exp": 1618190629,
  "iat": 1615566229,
  "jti": "TI876g98769g87"
}
```

We're using the Piano secret across multiple other apps, and have no control over the values used, so we can't change it to fit assigned it to `SIGNING_SECRET` as per the docs here https://docs.coralproject.net/coral/v5/configuration/#signing-secret however I noted that the docs here: https://docs.coralproject.net/coral/advanced-configuration/ contain a lot more configuration options, for example setting the `TALK_JWT_SECRETS` values, the `TALK_USER_ID_CLAIM` value etc...

Are the docs for v4 still relevant for Version 5? And does anyone have any advice re: an approach for getting Piano and Coral working together?

**Comment by wyattjoh** [comment]
You must generate a token for Coral that conforms to the structure it expects. You can stand up a separate service to exchange the piano token for a Coral token to facilitate that structural change.
