### ISSUE TITLE
API 6.8.1 comments field query argument

### ISSUE THREAD

**Issue by vitalibertas** [coralproject/talk#3486]
Could you give an example of what the query argument is used for?  I’m wondering how to filter comments by a date range and wondering if that could be used for it.  If not, how can I query comments by createdAt range?

**Comment by wyattjoh** [comment]
The following GraphQL query should get you what you want!

```graphql
query FindComments($after: Cursor) {
  comments(after: $after) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      cursor
      node {
        id
        body
        author { username }
      }
  }
}
```

Refer to https://docs.coralproject.net/coral/v5/api/overview/ for instructions on how to use the GraphQL API.
