### ISSUE TITLE
Custom Stylesheet In Configure Breaks The Tool

### ISSUE THREAD

**Issue by esherred** [coralproject/talk#3488]
Using the Docker version of 6.x we have experienced a weird issue where adding a custom stylesheet to the dashboard is now breaking the comments tool. It actually seemed to happen randomly and we're not sure what's up.

Talk is sitting on its own server with it's own subdomain and coming into our WordPress site.

This is an example URL: https://morningchalkup.com/2021/03/31/the-morning-chalk-up-printed-a-newspaper/

I've obviously got the custom sheet removed so comments work. But our Talk scripts seem to be canceled and I'm getting a cross-script issue in the header. The domain is approved (obviously) and I've updated Talk to the latest version as well.

Not sure if anyone else has seen this and/or might have a solution, but we'd really like to get this knocked out.

Also here is our stylesheet, just in case it's something in there: https://morningchalkup.com/wp-content/themes/morningchalkup/resources/css/coral.css

Much appreciated.

**Comment by tessalt** [comment]
Hi there, couple things could help us debug this: 
- can you share a screenshot of the cross-script error?
- can you try embedding a stylesheet _without_ the font links? the issue may be that the fonts are hosted on a different domain.

**Comment by losowsky** [comment]
Closing due to lack of response and inability to replicate
