### ISSUE TITLE
Changing coral's domain 

### ISSUE THREAD

**Issue by Emptyfruit** [coralproject/talk#3494]
Not so much of a bug, i guess, but this feature drives me crazy sometimes.

I deploy coral to some domain. i.e. `coral.domain-A.com`, go through installation wizard. Use it for some time.
After some time i need to move my infrastructure to another domain. So coral (docker) is moving to `coral.domain-B.com`. All the files (volumes, db) stay the same, just proxy settings and dns setting change for the server.

It stops working. It goes into some state, where it does not respond to api and admin panel redirects to `/install` with a message: `TENNANT ALREADY INSTALLED`.

So i'd be happy to understand:
1) Is it intentional?
2) How coral determines its state and is there a trick to make this transition easy? I.e. some magical field in the database.
3) what is the "official" resolution to this situation?

I tried to change `domain` in tennant object in database, tried deleting it, tried messing with admin user, but no luck (

**Comment by wyattjoh** [comment]
As this type of transition is quite rare, we typically recommend modifying the single document you should find in the `tenants` collection in MongoDB and updating the `domain` field to the new domain. Note that you'll need to restart the server (or have it turned off) while you are updating the domain record.

Reopen this ticket if you are still encountering issues!
