### ISSUE TITLE
Improve installation documentation v5+ by adding NGINX setup instructions

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [coralproject/talk#3502]
Here's a short list of what went wrong when installing coral/talk behind NGINX:
  - tenant domain was set to `127.0.0.1` (fixed locally with `docker exec -it coral_mongo_1 mongo mongodb://127.0.0.1/coral` then `db.tenants.updateOne({}, {$set: {domain: 'coral.example.com'}});`
  - The error above was probably caused by a bad NGINX header configuration, I fixed it by copying [the configuration in this comment](https://github.com/coralproject/talk/issues/2972#issue-626532219)
  - Setting up `auth_basic` in NGINX causes API 401 errors due to unexpected `Authorization` header token, had to remove it. Having it allowed me to setup the server securely without proxying through the host.

The 5+ docs are lacking an explanation on how to properly setup NGINX reverse-proxying.

**Comment by wyattjoh** [comment]
We've been very careful about not including production deployment details in the documentation related to other products as there are many conflicting mechanisms related to how they work that we didn't want to maintain.

As for Nginx, I'd suggest using the `proxy_set_header Host "coral.example.com";` directive to set the upstream host. Coral expects that there is a `Host` header that includes the name of the instance.

Coral is also not supported behind basic auth, so unfortunately you won't be able to use the `auth_basic` directive.
