### ISSUE TITLE
Localhost:3000 doesn't load after following instructions for Docker installation

### ISSUE THREAD

**Issue by luananama** [coralproject/talk#3508]
I'm trying to install Coral 5 on Windows. The issue seems to be related to mongodb. 
![image](https://user-images.githubusercontent.com/20238185/114994452-12f48180-9e9d-11eb-8ecf-dc0d8611a500.png)

**Comment by wyattjoh** [comment]
We don't directly support Windows as a development target for Coral unfortunately. The only part of our instructions configuring MongoDB are as follows:

```yml
mongo:
    image: mongo:4.2
    volumes:
      - ./data/mongo:/data/db
```

I'd suggest ensuring that the folder located in `./data/mongo` exists and is empty, and checking the logs with the MongoDB container (by running `docker-compose logs mongo` and investigating the MongoDB documentation on how to resolve!
