### ISSUE TITLE
Enabling SSO invites sign in from all users

### ISSUE THREAD

**Issue by kenara** [coralproject/talk#3538]
**Expected behavior:**

Not all users can log in or comment. Qualified users log in through main site and their SSO token allows them to comment. Ordinary users without a token are not logged in to Talk and should not see the comment form or login button. 

**Actual behavior:**

With SSO enabled, `post-comment-form` is shown. The "Sign in and Join the Conversation" button does nothing when clicked if `loginPrompt` is undefined.

**Comment by kenara** [comment]
My use case involves expert users reviewing items. New experts are welcome to apply but comments from the general public would not be appropriate and could discourage experts.

I was able to provisionally work around this with custom CSS. Users without the necessary Firebase custom claim are shown an embed with `bodyClassName: "pink"` and `.pink .coral-createComment {display: none;}.pink [class*='CallOut-inner']{visibility: hidden;}.pink [class*='CallOut-inner']: after {content: 'There are no comments yet.';visibility: visible;display: block;}.pink .coral-comment-actionBar {display: none;}`

If a user were to display the post-comment-form using developer tools, they could enter text but the login prompt does nothing.

**Comment by wyattjoh** [comment]
If you're using SSO to sign in users to the comments, and want to restrict it to a subset of your users, the solution is even easier! _Don't generate a SSO token for the users you don't want to sign in_! This is the same process that we recommend to newsrooms that restrict comments to subscribers. Does that satisfy your usecase?

**Comment by kenara** [comment]
The problem is not that unwanted commenters can comment - they can't (and mostly wouldn't want to). Only qualified users are given a token. 

The issue is that there is a text area and a big button inviting them to "Sign in and Join the Conversation" and when you click it, nothing happens. I've managed to hide these with CSS but that's not a brilliant solution.

It seems that, when SSO is enabled (and no other log in method is enabled), `loginPrompt` should be defined. 

My use case does not call for users to log in through the comments application.

The problem stems from the "Login with Single Sign On" checkbox being enabled. In fact users with a token are logged in automatically when they enter the app.

**Comment by kenara** [comment]
This is probably just a weird edge case not affecting many users. Closing due to lack of interest.
