### ISSUE TITLE
Need assistance in eliminating cors issues

### ISSUE THREAD

**Issue by Adrian-Samuel** [coralproject/talk#3543]
Hey!

I'm using the coral verison 4 docker-compose example found in the coral talks with no amendments:
https://docs.coralproject.net/talk/installation-from-docker/

I'm consistently getting cors issues and I'm wondering how to resolve this.

<img width="2032" alt="Screen Shot 2021-05-07 at 1 26 06 PM" src="https://user-images.githubusercontent.com/31516988/117486675-ee3d7800-af37-11eb-9f31-3cba4ff73b70.png">

This final image shows the step I cannot move forward from due to the cors issues.

<img width="2032" alt="Screen Shot 2021-05-07 at 1 25 37 PM" src="https://user-images.githubusercontent.com/31516988/117486654-e54ca680-af37-11eb-871d-08b45fc4be41.png">

I hope you can help!

**Comment by Adrian-Samuel** [comment]
There are no such issues with the version 5 release, but I'm interested to see if there was something I didn't do correctly

**Comment by kenara** [comment]
Hey @Adrian-Samuel, just a wild guess but have you tried 127.0.0.1:3000 instead of localhost? The error hints at that...

Apart from that, a really clean install - with all old containers removed - can help!

**Comment by wyattjoh** [comment]
You might need to update your `TALK_ROOT_URL=http://localhost:3000` instead of `TALK_ROOT_URL=http://127.0.0.1:3000` as the comment from @kenara makes sense.
