### ISSUE TITLE
Revert version pinning on node 7.6.0

### ISSUE THREAD

**Issue by wyattjoh** [coralproject/talk#357]
Currently experiencing an upstream issue with node ~7.7 https://github.com/nodejs/node/issues/11628

We should remove the version pin when the issue is resolved.

**Comment by gobengo** [comment]
Looks like 7.7.1 is now released with a fix? https://github.com/nodejs/node/issues/11628#issuecomment-283587919

7.7.2 is out too, as are corresponding Docker Hub tags.

**Comment by wyattjoh** [comment]
Awesome @gobengo, I've pushed this for review.
