### ISSUE TITLE
Question: Using Coral's GraphQL server only?

### ISSUE THREAD

**Issue by senseiurata** [coralproject/talk#3590]
Hi!

With `NODE_ENV` set to `production`, the GraphQL server only appears to only accept specific persisted queries. Is there a way around this restriction?

Also - is the restriction mainly for performative reasons, or are there security implications as well?

**Comment by wyattjoh** [comment]
This choice was made for security reasons to prevent random GraphQL queries without them being audited by the application team. If you need to interact with Coral for admin actions, you can use a access token with admin access and it'll bypass this restriction. If you are trying to build an external UI against Coral's API, we don't formally support that unfortunately.
