### ISSUE TITLE
Question: Turning REDUCED_SECURITY_MODE on

### ISSUE THREAD

**Issue by senseiurata** [coralproject/talk#3598]
A bit of a follow-up to [this question](https://github.com/coralproject/talk/issues/3590)

Looking through the source, we found the [REDUCED_SECURITY_MODE](https://github.com/coralproject/talk/pull/3027) flag as a supported feature.

> It is not recommended to use this feature without deep knowledge of the drawbacks.

The role-based authorization we see in the schema / source code looks awesome, and we confirmed that they work well in practice. With REDUCED_SECURITY_MODE on, we'd be relying more heavily on that security layer - and are there additional security concerns worth of note?

**Comment by wyattjoh** [comment]
What's really important to note is that by turning on `REDUCED_SECURITY_MODE`, you are no longer protected from someone executing arbitrary GraphQL queries to your server. This may include DoS attacks based on extremely deep or convoluted queries, potentially harmful or unexpected query paths causing side affects, and other related vectors. The feature was not documented as we feel it is not safe to use in a production environment.
