### ISSUE TITLE
Edited comments aren't updated live (also breaks replies)

### ISSUE THREAD

**Issue by Sentynel** [coralproject/talk#3662]
**Expected behavior:**

If a comment is edited while you have a comment stream open, the updated version should be provided via the same mechanism which shows new comments.

You should be able to post replies to a comment which has been edited while you have the stream open.

**Actual behavior:**

Edits do not arrive live; comments retain their original, unedited form.

If you attempt to reply to a comment which has been edited, the submit button does nothing and the request generates the following error:

```
[2021-08-08T14:09:44.067Z] ERROR: coral/1769996 on coral(/opt/talk/talk/src/core/server/graph/plugins/logger.ts:25 in logAndReportError): graphql query error (context=graph, contextID=47c01730-f852-11eb-a0c7-951994914319, tenantID=84301b9e-c07a-4cad-b454-b165cb19f4fd, report=null)
    err: {
      "message": "COMMENT_NOT_FOUND",
      "name": "CommentRevisionNotFoundError",
      "stack": "Object.retrieveParent (src/core/server/stacks/helpers/retrieveParent.ts:32:11)\nObject.create (src/core/server/stacks/createComment.ts:230:18)\nObject.mapFieldsetToErrorCodes (src/core/server/graph/errors.ts:17:12)\ncreateCommentReply (src/core/server/graph/resolvers/Mutation.ts:22:13)\n",
      "id": "47c8a2b0-f852-11eb-a0c7-951994914319",
      "context": {
        "pub": {
          "commentID": "b62a69e9-08fc-4f4d-a753-548f687cb076",
          "commentRevisionID": "ac85768e-bb6d-43c3-a2cd-87821bf28d0e"
        },
        "pvt": {}
      }
    }
```

(A version of this error is delivered to the client, but nothing is shown to the user.)

Steps to reproduce:

1. Open the same comment stream in two browsers or browser tabs
2. Post a comment in one browser; observe that the comment is delivered live to the other browser (you get the "show new comment" notification)
3. Edit the comment in the first browser; observe that nothing changes in the other browser
4. Attempt to reply to the edited comment from the second browser; observe that nothing happens when you click "submit"

**Related Issues:**

#3355 

**Versions:**

- Coral: 7118e2b776baa7a2649549530ddd8eda9fa6efe4
- NodeJS: 14.17.4
- NPM: 6.14.14
- MongoDB: 3.6.8
- Redis: 5.0.7
- Browser: Chrome 92
- OS: Ubuntu 20.04

**Comment by immber** [comment]
Opened CORL-2252 for internal investigation

**Comment by losowsky** [comment]
This is fixed in an upcoming release in the new year. Thanks!
