### ISSUE TITLE
Sign-in popup: Email address validator error pushes SSO buttons down, causes misclicks

### ISSUE THREAD

**Issue by Sentynel** [coralproject/talk#3663]
**Expected behavior:**

Opening the "sign in" popup and clicking an SSO sign-in button (e.g. Facebook, Google) immediately should always work.

**Actual behavior:**

https://imgur.com/a/fxSbARD (Video shows me attempting to sign in with Facebook twice; the first time works successfully, while the second nothing happens.)

With apologies for an annoying inconsistent bug: Sometimes clicking the SSO button too quickly means nothing happens (other than that the form validator goes off, which makes it look like you're supposed to enter an email address before using the SSO button, which you're not). Sometimes it works fine. I've seen the "nothing happens" state last up to a few seconds. Dev Tools confirms that no requests are being made and nothing is being logged in the "nothing happens" state. (Hint: You can turn "Auto-open DevTools for popups" on in Chrome's settings - I've not been able to manually open it fast enough to catch the issue!) I have verified this issue occurs in both Chrome and Firefox, and it's happening on both dev and prod builds of Coral.

**Related Issues:**

n/a

**Versions:**

- Coral: 7118e2b
- NodeJS: 14.17.4
- NPM: 6.14.14
- MongoDB: 3.6.8
- Redis: 5.0.7
- Browser: Chrome 92 / Firefox 90
- OS: Ubuntu 20.04

**Comment by Sentynel** [comment]
I have just twigged what the actual issue is here, and if you watch the video closely you can see it: when you mouse button _down_, it causes the email address validator to fire, which displays the "required field" error, which pushes the rest of the window down, which slides the SSO login buttons down. The SSO login buttons don't trigger until you mouse button _up_ on them, and if they've been slid down too far by this process, your click misses. Result: Clicking the bottom half or so of the button works fine; clicking the top half does not work.

Solutions here could include forcing the container size for the login form to grow a bit so the validator appearing doesn't shove the SSO buttons down.

**Comment by immber** [comment]
Opened CORL-2251 for internal investigation

**Comment by Sentynel** [comment]
Fixed by #3721.
