### ISSUE TITLE
Problem with keyboard shortcuts

### ISSUE THREAD

**Issue by DenisDoroshchuk** [coralproject/talk#3674]
Hello,

I have a problem with the screen jumps on my site. If user click a "C" key, the screen move to comments area.
How I can disable it?

Please open this article https://cyclingtips.com/2021/08/preview-your-guide-to-the-cycling-events-at-the-tokyo-paralympics/ and click a "C" button on keyboard.

The problem is that users start typing their email in the input box and if they press the C key, get an unexpected scrolling of the page to comments.

**Expected behavior:** no the screen jumps if user click a "C" button

**Actual behavior:** the screen jumps if user click a "C" button

Thanks
Denis D.

**Comment by Sentynel** [comment]
This isn't a Coral thing. The `c` keyboard shortcut on your site is coming from your Pico WordPress plugin. You'd have to talk to them about how to turn it off.

**Comment by DenisDoroshchuk** [comment]
@Sentynel I think 100% problem with Coral, because I see it on code.
https://github.com/coralproject/talk/blob/develop/src/core/client/stream/common/KeyboardShortcuts/KeyboardShortcuts.tsx#L133

**Comment by Sentynel** [comment]
Event listeners inside Coral's iframe will only hook events that happen with focus inside the iframe. You can check with a debugger where the event hook is actually coming from, which as I say is your Pico WordPress plugin:
![image](https://user-images.githubusercontent.com/2052340/130619210-3f6b8098-6849-494b-a32d-c0678920a175.png)

**Comment by DenisDoroshchuk** [comment]
Thanks for answer @Sentynel 
I disabled Pico widget on site, but problem is not resolve, please check
https://cyclingtips.com/2021/08/new-orbea-orca-aero-road-racing-bike-teased-at-the-vuelta/?debug=1

**Comment by DenisDoroshchuk** [comment]
If I click "C" button I see this:
![Screenshot 2021-08-24 at 21 24 10](https://user-images.githubusercontent.com/42928564/130653758-abc01ba1-b96d-4e7f-81da-a56b70a49e4f.png)

**Comment by Sentynel** [comment]
Ah, yes, I see. My bad! It doesn't trigger on my Coral instance, which I think is because I'm not including pym.js at the outer embed level (rather than inside the iframe). It looks like it's supposed not to trigger the keyboard shortcut if the source is a `<textarea>` or `<input>` element - https://github.com/coralproject/talk/blob/develop/src/core/client/stream/common/KeyboardShortcuts/KeyboardShortcuts.tsx#L112 - so it shouldn't be triggering for your email input, but I can't actually see which input element it's triggering in for you so I can't see what's not working there. Anyway, I should duck out and stop being unhelpful at this point!

**Comment by DenisDoroshchuk** [comment]
Please open this article https://cyclingtips.com/2021/08/new-orbea-orca-aero-road-racing-bike-teased-at-the-vuelta/?debug=1
And try input "C" symbol on subscribe form.
I recorded video:
https://user-images.githubusercontent.com/42928564/130729749-ffe5171e-2075-4145-aa63-2b937a3909f1.mov

**Comment by Sentynel** [comment]
Ah, yes, I see the problem actually - the event is caught here and then sent as a message: https://github.com/coralproject/talk/blob/develop/src/core/client/embed/decorators/withKeypressEvent.ts#L7
When a real `KeyboardEvent` is received, it looks for a `target` and removes events with `tagName` set to `<input>` or `<textarea>`, or with a `contenteditable` property set to `true`: https://github.com/coralproject/talk/blob/develop/src/core/client/stream/common/KeyboardShortcuts/KeyboardShortcuts.tsx#L112
But this check never happens in the case that it's an event broadcast from the parent page: the message generation in `withKeypressEvent.ts` doesn't check and doesn't include the `target.tagName` and `.contenteditable` in the message, and the branch in `KeyboardShortcuts.tsx` which deserialises doesn't do those checks either.

The solution would be to either duplicate the filtering logic from `KeyboardShortcuts.tsx` into `withKeypressEvent.ts` before the message is sent, or include the relevant properties from the event in the message payload in `withKeypressEvent.ts` and restructure the receiver in `KeyboardShortcuts.tsx` so the checks happen on deserialised events too.

**Comment by DenisDoroshchuk** [comment]
Thanks for you answer @Sentynel 
Do you know how I can fix it from my side? I mean from a parent page.

**Comment by Sentynel** [comment]
This is a terrible hack, but this JavaScript one-liner appended to your page will stop events from the email input being propagated to Coral's handler:
`document.getElementsByTagName("input")["EMAIL"].onkeypress = function (event) {event.stopPropagation();}`

**Comment by DenisDoroshchuk** [comment]
Thanks @Sentynel 
It's working, but it's hack, and I will use this as a temporary solution.

**Comment by alinhle** [comment]
@DenisDoroshchuk Thanks for reporting this. This is totally Coral's fault. I'll take a look on how we want to fix that.

**Comment by alinhle** [comment]
For the first iteration we'll likely make sure to exclude propagating any events from input fields to Coral.

**Comment by DenisDoroshchuk** [comment]
Thanks @cvle 
Please write me, when you will fix it

**Comment by alinhle** [comment]
@DenisDoroshchuk It's fixed in 6.15.0 with this commit: https://github.com/coralproject/talk/commit/9aefbfb4f81c878a9d99b046ab295d37dc7576cd
