### ISSUE TITLE
Heroku app crashes when attempting to upgrade to newer v6

### ISSUE THREAD

**Issue by amyevans** [coralproject/talk#3680]
I am currently running the [6.3.3 Docker image](https://hub.docker.com/layers/coralproject/talk/6.3.3/images/sha256-fae16064d649762684b0008a993614e60a8b27999d66b6d1298bda22af188bab?context=explore) on Heroku. When updating to a newer version, the app crashes with the following error:
```json
{
    "name": "coral",
    "hostname": "90da815c-79b7-42d5-9f31-a4a5dc6a81e0",
    "pid": 3,
    "level": 50,
    "err": {
        "message": "invalid language code: .wh..wh..opq",
        "name": "Error",
        "stack": "I18n.load (src/core/server/services/i18n/index.ts:47:17)\nServer.connect (src/core/server/index.ts:221:5)\nbootstrap (src/index.ts:51:5)\n"
    },
    "msg": "can not bootstrap server",
    "time": "2021-08-24T20:06:38.634Z",
    "src": {
        "file": "/usr/src/app/src/index.ts",
        "line": 59,
        "func": "bootstrap"
    },
    "v": 0
}
```
In an attempt to narrow things down, I have tried `6.13.2`, `6.10.0`, and `6.9.1`, which crash; and `6.8.1`, `6.7.2`, and `6.3.12`, which do not crash. I am deploying according to [Heroku's instructions](https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-an-existing-image), e.g.:
```
heroku container:login
docker pull coralproject/talk:6.13.2
docker tag coralproject/talk:6.13.2 registry.heroku.com/<app>/web
docker push registry.heroku.com/<app>/web
heroku container:release web --app=<app>
```
The error seems to point to an issue with Heroku's filesystem not liking the ../../.. parent directory iteration of locales, but beyond that conclusion I'm a bit lost for how it could be resolved. Any insights?

**Expected behavior:**
Upgrading to a newer version of Coral on Heroku is successful.

**Actual behavior:**
Heroku app crashes.

**Related Issues:**
None

**Versions:**

- NodeJS: 12
- NPM:
- MongoDB: 4.4.8
- Redis: 6.0.9
- Browser:
- OS:

**Comment by losowsky** [comment]
Hi there

I'm afraid we no longer support Heroku out of the box with a one-click image. All our latest docs are at docs.coralproject.net 

Best wishes

Andrew
