### ISSUE TITLE
HTML display as text in alerts.

### ISSUE THREAD

**Issue by jose-zapata** [coralproject/talk#3744]
See the attached file for an example. This happens everywhere, even in the administration console
![screenshot-coral](https://user-images.githubusercontent.com/6288402/135732227-082a0eb0-4fa0-468e-a23b-0dcdf5840998.jpg)
.

**Comment by wyattjoh** [comment]
Coral does not serve HTML that looks like that. It seems that there's a problem occuring with your web server.
