### ISSUE TITLE
MongoDB v5 support and upgrade

### ISSUE THREAD

**Issue by yogeshbeniwal** [coralproject/talk#3762]
**Expected behavior:**
Upgrade from v4 to v5 for MongoDB should happen smoothly. 

**Actual behavior:**
Upgrading from v4 to v5 for MongoDB in docker-compose.yml result in 5XX error. Fresh installation with v5 works fine.

Understand that as per official document https://docs.coralproject.net/#docker only v4 is supported.

**Comment by losowsky** [comment]
Hi Yogeshbeniwal

We expect to support Mongo 5 in 2022. 

Best wishes

Andrew
