### ISSUE TITLE
Recommended approach to implement anonymous posting

### ISSUE THREAD

**Issue by deichholz** [coralproject/talk#3783]
As we upgrade our v4 platform to v6, we are trying to figure out how to reproduce our anonymous posting feature. We used a plugin and a custom field to permit users to simply provide a display name for their post, and each comment was associated with a custom user. 

I understand that anonymous users are not directly supported, but for this specific application, we need to maintain this ability. Our other publications all use SSO with JWT tokens. I am leaning towards using a custom JWT token to create a one-time user, but I am hoping for suggestions on where I could hook in to modify the behavior of the guest submit feature to register a new SSO user. 

Are there any others that have implemented anonymous users on v5/6 and could suggest alternative approaches?

**Comment by tessalt** [comment]
Hi there, this would all have to be handled outside of Coral in your auth/SSO flow. In theory there's no reason you can't create and pass in a short-lived jwt that coral will treat as any other jwt, but the token will still need to encode a username and an email address. You would then have to listen for the `createComment` event to manually log the user out https://github.com/coralproject/talk/blob/main/CLIENT_EVENTS.md
