### ISSUE TITLE
splitting talk into webserver and jobserver part

### ISSUE THREAD

**Issue by bhagtrajaram** [coralproject/talk#3790]
Hi,

I'm running coraltalk 4.8.3 in a docker-compose setting.

Due performance reasons i would like to split the talkserver in a webserver and jobserver.

I have tried various commands in the docker-compose.yml with no success.

Is this splitting possible?

Regards,

**Comment by losowsky** [comment]
Hi Bhatrajaram

I'm afraid we no longer support 4.8.3 and can't give you any support regarding development based on that version. 

Best wishes

Andrew
