### ISSUE TITLE
Delete user account that accesses by SSO

### ISSUE THREAD

**Issue by bowser2010** [coralproject/talk#3791]
Hello, what is the best way to delete a user account, since the user id when accessing by SSO changed. Now that user cannot comment as it shows him an error in the comment box: "Network error. Please refresh your page and try again". Please Help me and best regards.

**Expected behavior:**
I want to delete user account

**Actual behavior:**
It is not posible to do in the administration panel.

**Comment by losowsky** [comment]
HI Bowser2010

you should use the 'deleteUserAccount' mutation in the API: https://docs.coralproject.net/api/mutations/delete-user-account 

Best wishes

Andrew
