### ISSUE TITLE
Serve static assets with an efficient cache policy

### ISSUE THREAD

**Issue by yogeshbeniwal** [coralproject/talk#3808]
**Expected behavior:**
assets/js/embed.js should be served with 1 year cache TTL, as [recommended here](https://web.dev/uses-long-cache-ttl/).

**Actual behavior:**
assets/js/embed.js is served with 30 mins cache TTL.

**Comment by wyattjoh** [comment]
Because the `embed.js` file is not fingerprinted, it _needs_ to have a short cache lifetime to ensure that changes due to upgrades/changes are respected. Otherwise there's a risk users will continue to use the cached version that is outdated for up to a year, hindering the ability for us to release updates.

**Comment by yogeshbeniwal** [comment]
@wyattjoh Thank you. How often embed.js is updated.

**Comment by wyattjoh** [comment]
We've updated it a few times this year to account for non-backwards compatible changes to the interaction between the iframe JS and the host page.

**Comment by yogeshbeniwal** [comment]
Can we use cache busting technique to overcome this. Or there a challenge in that.

**Comment by wyattjoh** [comment]
You can adjust this though:

https://github.com/coralproject/talk/blob/b8a24713cd03603ec97814e7f3c080af72d262ca/src/core/server/config.ts#L475

Set the env var for `NON_FINGERPRINTED_CACHE_MAX_AGE`, but you do so at your own risk that version updates could introduce non backwards compatible changes that are very complex to resolve.

**Comment by yogeshbeniwal** [comment]
Thank you for that. If this can be incorporated in development. File name versioning (e.g. embed.v2.js).

**Comment by wyattjoh** [comment]
Unfortunatly not, as it's been generally hard for newsrooms to update their templates that render Coral, and as such, we need a constant URL for the integration, and not a versioned one. Changes made to the embed file aren't always backwards compatible, so there's no guarentee one version of embed.js will work with a future version of Coral.
