### ISSUE TITLE
Lack of documentation for migrating versions

### ISSUE THREAD

**Issue by amsnickw** [coralproject/talk#3810]
We are currently running 5.4.0, hoping to eventually migrate to the latest 6.x.  It is my understanding that we need to first be on 5.5.1 before moving to 6.  Unfortunately there seems to be no documentation about how to move from 5.4.0 -> 5.5.1.  And, once we are on 5.5.1 (if we ever get there), it's also unclear to me how to move on to 6.x.

I hope there is some real documentation available because we have spent far too much time on this.  We have Talk installed on a large, high traffic website and will soon be forced to look at alternatives to your product.

**Comment by losowsky** [comment]
Hi Asmnickw, 

You should update to Coral 5.5.1 the same way you'd update Coral using any kind of source code. Here's the 5.5.1 link https://github.com/coralproject/talk/releases/tag/v5.5.1 

Then you can update to the latest version from there (currently 6.16.1)

Best

Andrew
