### ISSUE TITLE
upgrade client MongoDB to v4

### ISSUE THREAD

**Issue by yannick-fernand** [coralproject/talk#3814]
Is it possible to upgrade your client mongo to v4 ? we need this client version to make it work with our database version

Actual version:
"mongodb": "^3.5.9",

expected version:
"mongodb": ">=4.1.1",

**Comment by losowsky** [comment]
hi Yannick, the latest version of Coral is compatible to Mongo 4.2 https://docs.coralproject.net/

**Comment by bastiankistner** [comment]
according to https://www.mongodb.com/docs/drivers/node/v4.8/compatibility/ the used driver version should also be compatible to Mongo 6 at least
