### ISSUE TITLE
get the ip address of the User that has made a comment And Give the possible to make ip block

### ISSUE THREAD

**Issue by yannick-fernand** [coralproject/talk#3815]
I dont know if it is RGPD friendly. But i would like to know if it is possible to :

- Get the ip of the user that has made the comment into comment properties like with facebook comment and show it on the admin console.  

- Give us a way to block the user by their ip ?

**Comment by losowsky** [comment]
Hi Yannick! Coral doesn't do any logging or display of IP addresses as part of our commitment to privacy by design; any collection/blocking will have to take place at an auth level
