### ISSUE TITLE
Clickable links in comments broken by #3780

### ISSUE THREAD

**Issue by Sentynel** [coralproject/talk#3827]
**Expected behavior:**
If you post a bare link in a comment (e.g. https://www.google.com/), it should appear as a clickable link when the comment is posted. This was the behaviour prior to #3780 (commit 243890a951c8c6076999992f23d207661eebcfbd) getting merged.

**Actual behavior:**
Links are not clickable and just appear as plain text. Reverting the above commit is sufficient to restore the old behaviour. I believe that commit is supposed to alter the behaviour of rich text pastes with embedded links, which is reasonable, but the effect seems to have broken _all_ links.

**Related Issues:**
none

**Versions:**

- Coral: v6.16.1
- NodeJS: 14.18.2
- NPM: 6.14.15
- MongoDB: v3.6.8
- Redis: 5.0.7
- Browser: Chrome 96
- OS: Ubuntu 20.04

**Comment by tessalt** [comment]
this is intended behaviour, pasted links being active was a bug, corrected in #3780

**Comment by Sentynel** [comment]
Hi Tessa - I don't mean that it's stripping pasted links, I mean that it's rendering all links unclickable. I'm pretty sure this isn't intended behaviour, as the moderation tools include special handling for comments that contain links. Screenshots below.

Behaviour after that change:
![image](https://user-images.githubusercontent.com/2052340/147781418-52633b1b-086f-47d3-bb42-630a7daf5567.png)

Behaviour before that change:
![image](https://user-images.githubusercontent.com/2052340/147781429-362181d7-59c5-4d3a-8f26-0c33e628d5ec.png)

**Comment by Sentynel** [comment]
Fixed in #3828. Thanks @tessalt @kabeaty!
