### ISSUE TITLE
Possibility to update User.badges using GraphQL mutation

### ISSUE THREAD

**Issue by ideallical** [coralproject/talk#3838]
## Search Terms

badges, tags, badge, mutation, graphql

## Suggestion

Currently a User in coral talk v6 holds a `User.badges` array, which can contain 0 or multiple strings.
I can add them manually by editing directly in the MongoDB client and see that they show up in the dashboard:
https://github.com/coralproject/talk/blob/v6.16.1/src/core/client/admin/components/UserHistoryDrawer/UserBadgesContainer.tsx#L14-L31

and in the comment stream:
https://github.com/coralproject/talk/blob/v6.16.1/src/core/client/stream/tabs/Comments/Comment/AuthorBadges.tsx#L10-L18

However, I'd prefer maintaining these badges using a graphQL mutation instead of adding them via SSO as described in the readme:
https://github.com/coralproject/talk/blob/v6.16.1/docs/docs/sso.md?plain=1#L38-L40

## Use Cases
I want to use this to be able to show user badges in the comment stream (like expert labels) e.g. journalist, mathematician, virologist.

In coral talk v4, I was able to add a tag to a user like so:
```
        mutation {{
            addTag(
                tag: {{
                    name: "{name}"
                    id: "{coral_user_id}",
                    item_type: USERS
                }}
            )
        {{
            errors {{
                __typename
                translation_key
            }}
        }}
    }}
```

I'd like a similar mutation for User badges in v6 as I'd prefer not to make changes directly in the mongoDB.

**Comment by losowsky** [comment]
If you're using SSO, you can include a claim that defines the badges: https://docs.coralproject.net/sso 

Does that solve your issue?

**Comment by ideallical** [comment]
It doesn't, as then you have to wait for users to re-login before the badges are shown from other users.
Hence we just use a raw mongodb query now.

**Comment by ideallical** [comment]
Hi, I noticed it's indeed possible to set the badges of a user in a SSO JWT. However, what I didn't expect is that the current badges known in a user's `badges` property in the MongoDB are overwritten with null if you do not define this in the SSO JWT.

Expected:
I login with a SSO jwt without badges information, so keep the known badges from the MongoDB.

Actual:
I login with a SSO jwt without badges information, the badges information in the MongoDB user is overwritten with `null`

**Comment by losowsky** [comment]
Hi, 

The badges that are attached to roles (ADMIN, MODERATOR, STAFF, MEMBER) remain, but we don't allow for manually adding more in the DB. The SSO must remain the source of truth outside of roles, so either you can give a role to those users (MEMBER for eg doesn't currently do anything except add that badge, and is customizable) or use the SSO to pass that information.

Hope that helps!
