### ISSUE TITLE
Reduce docker image size (and ARM64 support)

### ISSUE THREAD

**Issue by patrickdung** [coralproject/talk#3841]
## Suggestion
There are methods to reduce docker image size.
Below are my method for using it with ARM64 platform.
Feel free to backport/adopt it in the Talk repo.

1) Multi stage build
One stage for building the NPM modules.
Another stage for copying files from stage one to the final shipping container.

[Reference Dockerfile](https://github.com/patrickdung/coral-project-talk-container/blob/main/Dockerfile)
Note I am using Node container based on Debian instead of Alpine, concept is the same.

2) Squash the layer
Need to enable Experimental mode when building
[Reference CI](https://github.com/patrickdung/coral-project-talk-container/blob/main/.circleci/config.yml)

## Result
The image is about 160MB compressed and 600 MB uncompressed.
The official image is about 1GB uncompressed.

## Use Cases
I am using it for the ARM64 container build.

**Comment by tessalt** [comment]
Hi there, we're working to iteratively optimize our docker images for size and memory consumption but I don't currently have a timeline for when those optimizations will be complete. Thank you!
