### ISSUE TITLE
Use Coral as OpenID Connect Provider for login in other apps

### ISSUE THREAD

**Issue by yogeshbeniwal** [coralproject/talk#3844]
## Suggestion
Coral has a better inbuilt profile management and Login with Google and Facebook features. Why not to use it as authentication provider for related communities using other platforms.

## Use Cases
It will be great to use it as source of authentication for users in other communities such as Forum. This can be made possible by using Coral as OpenID Connect provider.

**Comment by losowsky** [comment]
Thanks for the compliment! However, we don't want to get into becoming an auth provider ourselves, so this isn't a path we're looking to explore.
