### ISSUE TITLE
Support for OAuth with Custom Application

### ISSUE THREAD

**Issue by yogeshbeniwal** [coralproject/talk#3847]
## Suggestion
Currently Talk support Oauth login using Google and Facebook only. It should also support oAuth login with other provider.

## Use Cases
Lots of in house custom developed app or Saas provide oAuth authentication too. Add a feature to add oAuth login with generic application (Without being specific to Google and Facebook).

**Comment by tessalt** [comment]
Hi there, we're not currently planning to support custom oAuth providers, but you can integrate with any auth provider that can provide an appropriately formatted token using our SSO integration https://docs.coralproject.net/sso
