### ISSUE TITLE
Automatically redirect to Signup with only OpenID Connect enabled

### ISSUE THREAD

**Issue by yogeshbeniwal** [coralproject/talk#3853]
## Suggestion
When only OpenID Connect is enabled for authentication, Register button should direct, directly to Sign up page on OpenID Connect provider rather than first to Coral Sign up page, showing only one sign up option.

## Use Cases
Save an extra step for Registration, as currently done for Sign-in.

**Comment by tessalt** [comment]
Hi there, improving the OIDC flow in several ways is in our current backlog, but we don't have a timeline for implementing these improvements yet.

**Comment by yogeshbeniwal** [comment]
@tessalt Thank you, it would have been better to keep it open for tracking purpose.
