### ISSUE TITLE
Possibility to use email instead of id in OIDCProfile

### ISSUE THREAD

**Issue by mvdwaeter** [coralproject/talk#3859]
## Search Terms

OIDCProfile, oidc, email, OpenID, profiles

## Suggestion

Make it possible to use a custom `OIDCProfile` and custom `findOrCreateOIDCUser` function.
Now the OIDCProfile hardcodes that it needs an ID (sub), where in my use-case I prefer to use an email:
https://github.com/coralproject/talk/blob/v6.16.2/src/core/server/models/user/user.ts#L77-L82
https://github.com/coralproject/talk/blob/v6.16.2/src/core/server/services/oidc/oidc.ts#L152-L214

## Use Case
When migrating our oidc users from coral v4 to coral v6 I noticed that coral v4 stores the e-mailaddress and coral v6 stores the ID in the OIDCProfile.
So in order to migrate these users I'd need to find the corresponding ID for each of the emailaddress.
However, if I would be able to easily change these 2 lines of code, I'm able to login via OIDC.

**Comment by tessalt** [comment]
Hi there, improving the OIDC flow in several ways is in our current backlog, but we don't have a timeline for implementing these improvements yet.
