### ISSUE TITLE
add rootClassName as an option to the createStreamEmbed function

### ISSUE THREAD

**Issue by macgyver** [coralproject/talk#3863]
## Suggestion

Currently we have the `bodyClassName` option but I'd like the ability to add a class name to the `<html>` tag / `:root` css element to have more control over the theming of the page, as well as the ability to *update* this class name during the lifetime of the page.

## Use Cases

- conditionally change root font size to impact the `rem` unit on the page
- updating color scheme on the page - if the user selects dark or light mode on the page after loading the Coral iframe, it's not possible to *update* the styles, the user would need to refresh before seeing the theme change reflected in Coral

It's more typical to set or update css custom properties on the `:root` tag and it would give clients a bit more control over the styles, e.g. adding margins, padding, font-size, etc.. to the html tag.

**Comment by tessalt** [comment]
Hi there, thanks for the suggestion but we're not planning to make changes to these options at this time. We anticipate releasing new features which will enable some enhanced theming but do not have a timeline for when it will be available. Thank you!

**Comment by macgyver** [comment]
Hi @tessalt thanks for responding - can you comment on whether the use cases I've outlined above will be handled by the future enhancements?

**Comment by tessalt** [comment]
it should be possible to do what you've mentioned with the existing embed code but it depends on how your CSS works and how your embed works. For example you could apply all the styles you would apply to the html tag to the body, and override any conflicting styles from the html tag as needed, or you could re-render the embed when you make updates.

**Comment by macgyver** [comment]
That's correct, the issues can be worked around in a way that is not ideal but mostly invisible to users. A little bit of state is lost when the embed is re-rendered - comment and reply text is preserved, but open reply forms are collapsed and scroll position is lost when the frame refreshes - I think all things considered it would be a better user experience to leave the theme unchanged in the embed until the user chooses to refresh it.
