### ISSUE TITLE
Coral use mongodb login and password

### ISSUE THREAD

**Issue by frostdeacon** [coralproject/talk#3907]
Dear Coral team.

Coud you help as with setup login\password on MongoDb Client?
We use docker-compose settup coral, try to setup with ENV variable Login\Password but Coral talk not create own database.
Maybe Coral Talk not support Login\Password with MongoDb Client?

Regards,
Dmitry

**Comment by tessalt** [comment]
Coral supports configuring mongo via connection string only https://www.mongodb.com/docs/manual/reference/connection-string/
