### ISSUE TITLE
Put comments of users with unconfirmed email always in moderation

### ISSUE THREAD

**Issue by jacotec** [coralproject/talk#3924]
## Search Terms

email confirmed moderation

## Suggestion

I'm evaluating Coral as a comment system for my sites and it looks very promising. Unfortunately anyone can comment even with a fake email address which is pretty much a show stopper.

I found the old request #3297 which targeted V5 ... we're now at V7 and it seems still not be implemented.

May I just resuggest this?

It could be done in a way that any comment from an user with an unconfirmed email is always put into moderation. What do you think?

## Use Cases

In my opinion this will massively reduce fake or troll comments by users using fake credentials and email addresses.

**Comment by losowsky** [comment]
Thanks Jacotec. The truth is that 90%+ of our user base use an existing SSO provider so we don't plan to spend many resources developing and improving our custom auth, which is very bare bones. You could always limit to Google/Facebook login, which will require real accounts. 

Best wishes and thanks for considering Coral

**Comment by jacotec** [comment]
@losowsky I would if Facebook and Google auth would actually work ;-)
See #3927

**Comment by losowsky** [comment]
Yep, we're looking into that. Thanks for reporting!
