### ISSUE TITLE
V7 fonts unreadable tiny

### ISSUE THREAD

**Issue by jacotec** [coralproject/talk#3925]
**Expected behavior:**

Update from V6 to V7 should not break design or make text unreadable

**Actual behavior:**

After update from V6 to V7 the fonts got incredible tiny ... ways to small to read comfortable

<img width="863" alt="2022-04-24_23-08-03" src="https://user-images.githubusercontent.com/3321655/164996718-4a116aff-f048-451f-9048-76146a75020d.png">
**Related Issues:** 

**Versions:**

- NodeJS: 14.18.0
- NPM: 8.0.0
- MongoDB: 4.4
- Redis:
- Browser: Edge / Chrome / Firefox / Safari
- OS:

**Comment by tessalt** [comment]
Hi there, please read the documentation updating from v6 to v7 https://docs.coralproject.net/migrating-6-to-7, you may need to update your CSS files.

**Comment by jacotec** [comment]
@tessalt Yap, I introduced my own CSS file (BTW: it would be **much** more convenient to have an editor window to directly enter the override-CSS. An external file only forced be to put an NGINX on the talk VM between my main HAPROXY and the talk app itself ... only to serve the CSS file).

I just raised this issue as there is a significant difference between V6 and V7 by default.

Closing it now.
