### ISSUE TITLE
Extreme bundle size

### ISSUE THREAD

**Issue by kwiat1990** [coralproject/talk#3930]
Hi, first of all I want to thank you guys for your work and cool comments system! However after I integrated Coral Talk on my site I've noticed that all requested dependencies are huge. See screenshot:

<img width="724" alt="image" src="https://user-images.githubusercontent.com/19494075/165924522-c8338d5a-a2d1-4fc5-932f-fdd38862f36e.png">

Is it normal?

**Comment by tessalt** [comment]
hi there, we've tried to balance functionality and bundle size, and we've prioritized keeping the stream-side bundle (embed.js) relatively small. The bundle for the admin panel is larger, and this looks normal to me.
