### ISSUE TITLE
Building & Running Coral with Node 16 LTS does not work

### ISSUE THREAD

**Issue by ihardyslide** [coralproject/talk#3932]
Hi,

I am experiencing issues with Coral while setting everything up locally on my machine as advised by [the docs](https://docs.coralproject.net/development).

Everything seems to work, until I am running _npm run watch_.
The command itself will not fail, but it will output an error inbetween:
`@coralproject/talk@7.0.1 generate:relay:account`
`ts-node --transpile-only ./scripts/compileRelay --bundle account`
`Ignore watch: [ './docs/' ]`
`Using ts-node version 9.1.1, typescript version 3.9.5`
`TypeError: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
    at new NodeError (node:internal/errors:372:5)
    at Object.watch (node:fs:2262:11)
    at add (/home/ihardyslide/git/talk/node_modules/filewatcher/index.js:74:34)
    at /home/ihardyslide/git/talk/node_modules/filewatcher/index.js:93:5
    at FSReqCallback.oncomplete (node:fs:199:5)`
`Debugger listening on ws://127.0.0.1:9229/540ab85a-227b-44d8-a8d4-7428f46b9bf1`
`For help, see: https://nodejs.org/en/docs/inspector`
`Command exited with 1`

In the end, everything will seem to run through and listen, but actually Coral was never started in the first place.
This behaviour can be examined, while trying to go to the /admin or /install page.
You will get an endless reload loop, because all connections to Coral on the exported $PORT will fail with a Connection Refused error, e.g.:
`[HPM] Error occurred while trying to proxy request /embed/bootstrap from localhost:8080 to http://localhost:6789 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

`[HPM] Error occurred while trying to proxy request /api/story/count.js?callback=CoralCount.setCount&notext=false&ref=ZmFsc2U7aHR0cDovL2xvY2FsaG9zdDo4MDgwL3N0b3J5Lmh0bWw%3D&url=http%3A%2F%2Flocalhost%3A8080%2Fstory.html from localhost:8080 to http://localhost:6789 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

`[HPM] Error occurred while trying to proxy request /embed/bootstrap from localhost:8080 to http://localhost:6789 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

`[HPM] Error occurred while trying to proxy request /admin from localhost:8080 to http://localhost:6789 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

`[HPM] Error occurred while trying to proxy request /install from localhost:8080 to http://localhost:6789 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

It is more obvious, when you start the _npm run start:development_ script, because this one will fail and won't stay executing.

After digging into, I came to [this issue](https://github.com/wclr/ts-node-dev/issues/143).
[This comment](https://github.com/wclr/ts-node-dev/issues/143#issuecomment-626248500) was my rescue.

I rolled back to Node 13.13.0 (via NVM), did a _npm ci_ again, did _npm run watch_ again, suddenly the error message is gone and Coral boots up as expected and I can enter the /install and /admin screen as expected.
Also the script _npm run start:development_ runs through smoothly then.

**Expected behavior:**
Coral starts as it should, when running _npm run watch_ on Node 16 LTS

**Actual behavior:**
Coral does not start at all, when running _npm run watch_ on Node 16 LTS

**Related Issues:**
https://github.com/wclr/ts-node-dev/issues/143

**Versions:**

- Ubuntu 20.04.4 LTS
- Node 16.15.0 LTS
- NPM 8.5.5
- Redis docker image redis:3.2
- Mongo docker image mongo:4.2
- Firefox 99

**Comment by tessalt** [comment]
Hi there, Coral is not currently tested against node 16, though we plan to look into this in the near future.
