### ISSUE TITLE
Duplicate usernames permitted by E-Mail Authentication

### ISSUE THREAD

**Issue by ihardyslide** [coralproject/talk#3941]
Hi,

my fresh coral setup has an issue with usernames, since it's permitting duplicate ones, even though the [documentation](https://docs.coralproject.net/auth#login-with-email-authentication) clearly states that usernames must be unique:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/1192287/167584853-d368110c-1f7d-4a2e-b6cb-530354893b19.png">

Userflow:
* Register a new user (e.g. in the comment section via the register button)
* Choose username "test"
* Log out after completing registration
* Register another new user, with the same username "test"
* Coral will successfully let you do this

**Expected behavior:**
Usernames must be unique on registration

**Actual behavior:**
Usernames can be duplicate
<img width="482" alt="image" src="https://user-images.githubusercontent.com/1192287/167591586-bf55200a-337a-4080-aa8a-40afa11bf3f3.png">

**Versions:**
- MongoDB: docker image _mongo:4.2_
- Redis: docker image _redis:3.2_
- Coral: docker image of coral release 7.0.2
- Browser: Chrome & Firefox
- OS: containers running on Debian GNU/Linux 9 (stretch)

**Comment by tessalt** [comment]
thanks for reporting, we'll investigate this issue.

**Comment by losowsky** [comment]
We're working on a fix in this sprint

**Comment by ihardyslide** [comment]
Hi, I wanted to ask if there is any update on this one.
Also I wanted to mention that this does not only affect e-mail auth, but also OIDC auth.

**Comment by ihardyslide** [comment]
Also I can confirm, this is still an issue with 7.3.0
![image](https://user-images.githubusercontent.com/1192287/187714941-9dd8c44f-2c20-4bb0-88a0-9c5945411a71.png)
![image](https://user-images.githubusercontent.com/1192287/187714960-748ba8d3-fc2a-40f5-8b8e-75a323dd2328.png)

**Comment by losowsky** [comment]
Closing this as our recommended and preferred setup for Coral is always using SSO, where username/email is the responsibility of the registration system
