### ISSUE TITLE
User can upload images and gifs into the comment field in V7

### ISSUE THREAD

**Issue by tgravemaker** [coralproject/talk#3942]
Hi all, 

when entering a comment in Coral Talk (in Firefox), I am able to drag and drop an image and even a gif into the comment field. I am not able to upload the comment with a gif, but I am able to upload my comment with the image. The text in the image is uploaded and shown in the commentstream, but the image isn't. At the moment there isn;t any error-handling for the user to tell images/gifs cannot be used.

**Expected behavior:**
User is not able to upload images and/or gifs into the comment field in Firefox.

**Actual behavior:**
User is able to upload images and/or gifs into the comment field in Firefox.

**Related Issues:** 

**Versions:**

- NodeJS: 14.8.1
- NPM: 16.14.15
- MongoDB: 5.0.x
- Redis: 3.2
- Browser: Firefox 99.0.1 
- OS: MacOS Big Sur 11.6.1

**Comment by tessalt** [comment]
I have been unable to replicate this behavior, do you have a screenshot or screen recording?

**Comment by losowsky** [comment]
Hi there, Coral doesn't not allow for drag and drop images, and never has – if I'm reading this correctly, you're trying to do behavior that we do not support.
