### ISSUE TITLE
Can not sort comments by section

### ISSUE THREAD

**Issue by Jeff-Albertson** [coralproject/talk#3950]
We're only allowed to sort reported comments by "All Sections." I used to be able to sort by individual section, ie: Local News or Local Politics. 

Please address.

**Comment by tessalt** [comment]
thanks for reporting, we'll look into this

**Comment by Jeff-Albertson** [comment]
Any update on this? We're still unable to sort comments by section, which is a huge help for us.

**Comment by Jeff-Albertson** [comment]
Any update?

**Comment by losowsky** [comment]
Discussed offline
