### ISSUE TITLE
Search by site under stories is not working

### ISSUE THREAD

**Issue by yogeshbeniwal** [coralproject/talk#3952]
**Expected behavior:**
Search by site under stories section should filter stories.

**Actual behavior:**
Search by site name is resulting in an internal error.

![Screenshot](https://user-images.githubusercontent.com/7325107/168440510-c9d770aa-5533-485d-a2ec-66a3918b656c.png)

**Comment by losowsky** [comment]
Hi Yogesh

Can you give more information? Where is that error appearing exactly?

**Comment by tessalt** [comment]
Hi there, you likely need to create the index for the text search, see https://github.com/coralproject/talk/blob/develop/INDEXES.md#2021-12-17
