### ISSUE TITLE
Troubleshooting help: SSO login for admin pages

### ISSUE THREAD

**Issue by ihardyslide** [coralproject/talk#3954]
Hi,

we are currently trying to achieve the following setup:
* Normal users (**commenters**) should log-in and register through **comment stream**, via **OIDC**.
(This does already work)
* Admin/Moderator/... users (**employees**) should login through the **/admin login screen**, but should in the background use our **SSO** with their usual accounts

So now I already understand how SSO is intended to be implemented, when the user should visit the comment stream first.
You simply should pass the signed JWT to the `Coral.createStreamEmbed()` function.

But I do not really understand, how it is intended to work for the admin login page, since this function won't be on this page clearly (no comment stream present).

I am currently trying to customize the admin login page by my own, but I still wanted to raise the question if there is no cleaner solution to this out of the box.

Thanks & Br,
Marco

**Comment by tessalt** [comment]
Hi there, Coral wasn't built to support this use case, but you may be able to create a workaround: you can specify an access token as a URL segment following the hash symbol, for example, `https://<yourcoraldomain>/admin/moderate#accessToken=<jwt>`. This should log the user in to the admin.

**Comment by ihardyslide** [comment]
Hi,
I was able to implement the flow as needed with your suggestion.
Thanks very much.
