### ISSUE TITLE
Webhooks / moderation phase / premod all

### ISSUE THREAD

**Issue by remko79** [coralproject/talk#3960]
Our goals are: send comments to an external moderation tool and then set it to 'premod', 'rejected' or 'accepted' based on those results. To do this correct we need information like the comment ID and timestamp. Currently this information isn't available if we configure a moderation phase.

The second option we we're thinking about were the webhooks (event COMMENT_CREATED) where we just listen to comments created and then handle the data + update on the comment from there. Now if you set the moderation configuration value to "Pre-moderate all comments sitewide", the webhook won't be triggered. So I thought of setting a moderation phase which just sets everything to 'premod', but then also, the webhook won't be triggered.

Why isn't this happening? Is there another valid way to do this easily? For me it seems weird that the webhook isn't triggered UNLESS the comment is live and thus approved.

FYI: We're currently running v6.15.4, but according to release notes nothing changed regarding this

**Comment by tessalt** [comment]
Hi there, the comment ID and time stamp are not available in the external moderation phase as the comment has not yet been saved. What is your use case for requiring this information to make a moderation decision? The webhooks were not designed to be used to make moderation decisions and there would likely be issues implementing this solution.

**Comment by remko79** [comment]
We want to use an external AI moderation tool which will determine if the comment should be allowed/rejected or set to pre-mod. Everything that's set to pre-mod still has to be manually approved/rejected and those comments we want to resend to the external tool to keep training it. So in that case we do need to re-send something external using the same comment ID so the tool knows which was originally declared as pre-mod.

**Comment by losowsky** [comment]
You can set it as PREMOD or COMMENT_DETECTED_TOXIC (which sends a comment to PENDING for moderator review) through the External Mod Phases, which is designed exactly for what you describe: https://docs.coralproject.net/external-moderation-phases

**Comment by kenara** [comment]
> We want to use an external AI moderation tool which will determine if the comment should be allowed/rejected or set to pre-mod. Everything that's set to pre-mod still has to be manually approved/rejected and those comments we want to resend to the external tool to keep training it. So in that case we do need to re-send something external using the same comment ID so the tool knows which was originally declared as pre-mod.

Hey @remko79 , what about capturing the createComment.success event or some other relevant event (see [https://github.com/coralproject/talk/blob/e001d58e452ce43402eec4d0ee5e404c69bcf1a7/docs/docs/events.md](url)), since you need to send the data to an external tool ?
