### ISSUE TITLE
Comment section does not load in some browsers - "invalid access token passed"

### ISSUE THREAD

**Issue by jacotec** [coralproject/talk#3965]
**Expected behavior:**

The comment section should load on every browser and computer

**Actual behavior:**

I have two computers where the plugin does not load in Edge browser. On the same machine but in different browsers it works. On other machines it works in the same version of Edge.

It's a fully mystery why it does this. I'm afraid users might experience the same issue.

The page shows a "network error". The browser dev tools are showing a couple of "graphql" accesses failing, but in the same request before there are graphql accesses working fine.

Error message is "invalid access token passed". I've cleaned the browser cache and deleted the cookies for my talk domain which did not help.

<img width="1433" alt="2022-05-25_12-36-51" src="https://user-images.githubusercontent.com/3321655/170244378-1149a650-6624-4ad7-a792-e09e19fc38b8.png">

Who is passing this wrong access token and where does it come from / is it stored?

**Related Issues:** 

**Versions:**

- NodeJS: 14.18.0
- NPM: 8.0.0
- MongoDB: 4.4
- Redis:
- Browser: Edge
- OS: Windows 10, MacOS

**Comment by kenara** [comment]
Hey Marko,

I've seen this error but I doubt it has to do with the browser.

Are you logged in each time as the same user, to the same page on the same exact domain?

Otherwise, the token will not be valid.

Ken

May 25, 2022, 11:45 by ***@***.***:

**Comment by losowsky** [comment]
This also happens if you create two accounts using the same email address, because email is a Unique ID - so if you make an account with email/password, then another account using SSO with the same email, the second one will be rejected with this error

**Comment by jacotec** [comment]
Hi,
thanks ... I could solve it by:
- Deleting the cookies for the talk domain **and** the website domain which loads the comments
- Deleting the browser cache
