### ISSUE TITLE
Delete User via Admin UI and example for deleting a user via API

### ISSUE THREAD

**Issue by jacotec** [coralproject/talk#3975]
## Search Terms

Delete User, API

## Suggestion

I got stuck since hours, because I have a "dead" SSO user which needs to be deleted. I've found issues #3791 and #2711 regarding this - but none of these are describing really how this should be done.

For someone who is not involved in the project the API description is more than cryptic. After trying more than 2 hours I need to give up here as there is no example of the syntax how a user should be deleted.

As I think there are several use cases where admins want to delete users from Coral, this should be available in the user actions in the admin UI.

As long as this is not implemented, an example should be provided how a user can be deleted via API call.

## Use Cases

- Deletion of Spam users (i.e. to free their usernames)
- Deletion of SSO users which are not available anymore

**Comment by losowsky** [comment]
Hi Jacotec

Here's the mutation: https://docs.coralproject.net/api/mutations/delete-user-account 

Hope that helps,

Andrew
