### ISSUE TITLE
Roles/Permissions explanation

### ISSUE THREAD

**Issue by ihardyslide** [coralproject/talk#3988]
Hi,

is there somewhere a info about what each role is allowed to do?
I am speaking about Admin, Moderator, Staff and Member roles.
As far as I can see, there is nothing about this in the docs.

Thanks in advance

**Comment by losowsky** [comment]
Hi ihardyslide

Sure thing: 

Commenter: can comment unless suspended/banned
Member: gets a badge next to their name in the comments whose text can be customized in the admin configuration
Staff: all of the above plus their comments are automatically approved, so won't appear in the queues if reported and they can use banned words
Moderator: all of the above plus they can moderate comments on the page or in the moderation interface
Admin: all of the above plus they have a CONFIGURE tab in the moderation interface that lets them change global site/network settings.

Hope that helps!
