### ISSUE TITLE
Silent Login for OIDC integration

### ISSUE THREAD

**Issue by ihardyslide** [coralproject/talk#3995]
Hi,

is there some recommended way of how to use [silent login](https://auth0.com/docs/authenticate/login/configure-silent-authentication#initiate-silent-authentication-requests) with Coral using an OIDC integration?
So basically I want to login the user, without manually needing the user to press the login button in the comment stream, if he has already/still some session open with the OIDC provider.
I have not found something related to this in the docs, so I wanted to ask before customizing it by myself.

Thanks & Br

**Comment by nick-funk** [comment]
In the script for embedding on the site, we call `Coral.createStreamEmbed(...)`. This will return an embed.

You should then be able to use the returned embed to login a user with an OIDC or SSO token via `embed.login("{{ SSO TOKEN }}");`

Check our docs here: https://docs.coralproject.net/sso
