### ISSUE TITLE
Inject external script inside the iframe as we do with custom css

### ISSUE THREAD

**Issue by diegoos** [coralproject/talk#4001]
Hello,

Is there any way to inject an external script tag inside the comments iframe?
We need to add `<script src="example.js" />` on iframe, as we do with custom css.

Thanks.

**Comment by losowsky** [comment]
Hello! The latest version of Coral is no longer inside the iframe so this shouldn't be an issue in the same way any more: https://docs.coralproject.net/migrating-6-to-7
