### ISSUE TITLE
App extention - formatting and active links

### ISSUE THREAD

**Issue by KaylaWaruschka** [coralproject/talk#4002]
Hi there, how can one format text that it displays in app as it does on the web comment section? Hyperlinks are also active on site but not app? How can we fix this? Images are app vs web display. 

<img width="476" alt="Screen Shot 2022-07-05 at 15 44 02" src="https://user-images.githubusercontent.com/108741716/177343396-7d9a0142-ac89-43aa-bd8f-2cc0343cd1fc.png">
<img width="332" alt="Screen Shot 2022-07-05 at 15 45 22" src="https://user-images.githubusercontent.com/108741716/177343466-2f795878-ffb4-43ff-8260-227892e7ee2d.png">

**Comment by losowsky** [comment]
Hi Kayla

Adele also emailed me about this. Can you confirm if you're using webview in the app or doing something else?

**Comment by losowsky** [comment]
Hi Kayla, I'm going to close this ticket as we haven't heard from you in a few months. Feel free to re-open at any point.
