### ISSUE TITLE
Moderation panel

### ISSUE THREAD

**Issue by kamhealey** [coralproject/talk#4006]
Is there any way to:
- build a member filter by team site? It's difficult to pick up troll/duplicate accounts quickly when the community tab lists everyone that joined SB Nation. The old mod panel showed community members only. (see photos 1 and 2)
- show accounts that register or log in from the same IP address on a user profile? The old panel did this (see photo 3)

Thanks! 
LaRomaBella from Amazin' Avenue

<img width="963" alt="Coral Community Panel IMG #1" src="https://user-images.githubusercontent.com/102908737/178499912-1a48a934-441d-4356-b209-3f572fd09dc7.png">

<img width="963" alt="Old Mod Panel IMG #2" src="https://user-images.githubusercontent.com/102908737/178499917-c691a96d-ab71-43f0-9ef2-7811f2edc3d1.png">

<img width="397" alt="Old User Panel IMG #3" src="https://user-images.githubusercontent.com/102908737/178499920-f1b8aa1f-13c1-45b9-95b6-e654b1de2869.png">

**Comment by losowsky** [comment]
Hi Kam, 

There isn't a concept of "Member of a single site" inside SB Nation within Coral. If you need to know more, please contact your League Manger to get the email address of the Coral team, so we can discuss further.
