### ISSUE TITLE
Network error. Please refresh your page and try again

### ISSUE THREAD

**Issue by KazunoriSawayama** [coralproject/talk#4017]
I installed talk and tried to display comments, but "Network error. Please refresh your page and try again.” Appeard.

When the URL containing the comment is accessed, the comment tag is first displayed.
However, after a while, the screen changes to a network error.

Actually, when talk was first launched from docker-compose, it was able to access the comment successfully.
However, after deleting /var/lib/docker(CentOS7) and data/mongo,redis of the talk system to clean up the docker container, 
I started it with docker-compose, and the above phenomenon occurred.

Docker-compose log shows below.
 
{"name":"coral","hostname":"e37aad8f1c4b","pid":1,"context":"http","contextID":"39e46a40-13c1-11ed-aee8-2f3c646cf9bd","tenantID":"f879eee9-bf4f-4dc4-b656-b27b94d6e1d5","level":50,"u
rl":"/api/graphql","method":"POST","statusCode":401,"host":"160.74.72.77","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[103.0.0.0](https://jpn01.safelinks.protection.outlook.com/?url=http%3A%2F%2F103.0.0.0%2F&data=05%7C01%7Ck2sawayama%40jst.go.jp%7Cdac480e11ca143753e0308da76078f8c%7C7a15dcb470154556a78f4d8c28e4ef01%7C0%7C0%7C637952072099544512%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BetX8xa5r3Nwezxso8qSs0UGvNhNMUskDqDIvFTVRvA%3D&reserved=0) Safari/537.36","ip":"::ffff:160.74.1.163","err":{"me
ssage":"TOKEN_INVALID","name":"TokenInvalidError","stack":"verifyAndRetrieveUser (src/core/server/app/middleware/passport/strategies/jwt.ts:110:9)\nJWTStrategy.authenticate (src/core/server/app/middleware/passport/strategies/jwt.ts:142:2
6)\nattempt (node_modules/passport/lib/middleware/authenticate.js:366:16)\nauthenticate (node_modules/passport/lib/middleware/authenticate.js:367:7)\nsrc/core/server/app/middleware/passport/index.ts:164:3\nLayer.handle [as handle_request
] (node_modules/express/lib/router/layer.js:95:5)\ntrim_prefix (node_modules/express/lib/router/index.js:317:13)\nnode_modules/express/lib/router/index.js:284:7\nFunction.process_params (node_modules/express/lib/router/index.js:335:12)\n
next (node_modules/express/lib/router/index.js:275:10)\ninitialize (node_modules/passport/lib/middleware/initialize.js:53:5)\nLayer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)\ntrim_prefix (node_modules/exp
ress/lib/router/index.js:317:13)\nnode_modules/express/lib/router/index.js:284:7\nFunction.process_params (node_modules/express/lib/router/index.js:335:12)\nnext (node_modules/express/lib/router/index.js:275:10)\n","id":"39e554a0-13c1-11
ed-aee8-2f3c646cf9bd","context":{"pub":{},"pvt":{"token":"[Sensitive]","reason":"no suitable jwt verifier could be found"}}},"msg":"http error","time":"2022-08-04T06:46:53.939Z","src":{"file":"/usr/src/app/src/core/server/app/middleware/
error.ts","line":80,"func":"wrapAndReport"},"v":0}

**Comment by yogeshbeniwal** [comment]
@KazunoriSawayama data/mongo and data/redis are required for proper functioning. Better you reinstall Coral Talk from scratch to get it working.

**Comment by KazunoriSawayama** [comment]
Thanks for your advice.

I have reinstalled coralproject/talk using the following procedure, but the error remains the same. 
Are there any problems with the following reinstallation procedure?

docker-compose down
rm -rf /var/lib/docker
rm -rf data/mongo
rm -rf data/redis
docker-compose up -d

**Comment by yogeshbeniwal** [comment]
@KazunoriSawayama You seems to have deleted important docker files. Please reinstall docker also. Do you need help with Coral setup and configuration?
