### ISSUE TITLE
No username shown when replying to a comment with german localization

### ISSUE THREAD

**Issue by ihardyslide** [coralproject/talk#4035]
Hi,

my Coral installation is running in german and I have discovered a small bug.

When replying to a comment, there should be a text above the comment box saying "Antwort auf `<Username>`", but since the .ftl file is having a wrong variable name in it, it can't map it in the .jsx file correctly.

Every other language has the correct variable name, but DE not, as you can see here: https://github.com/coralproject/talk/blob/0c23b5075bfe01652acb4f8937a87904a8d1fb78/src/locales/de/stream.ftl#L213
https://github.com/coralproject/talk/blob/0c23b5075bfe01652acb4f8937a87904a8d1fb78/src/locales/de/stream.ftl#L214

I changed this to `<Username></Username>` and then everything worked fine again.

![image](https://user-images.githubusercontent.com/1192287/186452740-e5022b1d-604f-4782-bbb7-d0e70c033f0b.png)

Br

**Comment by losowsky** [comment]
Thanks for finding this! We'll fix in an upcoming release

**Comment by ihardyslide** [comment]
I have found yet another issue with the german stream.ftl file:
https://github.com/coralproject/talk/blob/0c23b5075bfe01652acb4f8937a87904a8d1fb78/src/locales/de/stream.ftl#L218-L219
Here the ``Melden`` should be removed in Line 218, because line 219 which should be actually used is ignored.

**Comment by ihardyslide** [comment]
First: Thanks for fixing this in the newest release 😄 

Unfortunately, I found another issue in the german stream.ftl file, so I didn't want to create a new ticket for this small issue.

In this line

https://github.com/coralproject/talk/blob/develop/src/locales/de/stream.ftl#L583

You will see a wrongly named var:
`profile-account-notifications-buttonon-update = Aktualisieren`
It actually should be like this:
`profile-account-notifications-button-update = Aktualisieren`

**Comment by kabeaty** [comment]
Closing this issue, as all translation issues have been addressed. The `profile-account-notifications-button-update` typo was fixed in https://github.com/coralproject/talk/releases/tag/v8.1.0
