### ISSUE TITLE
INTERNAL_ERROR: TOKEN_INVALID: jwt not active

### ISSUE THREAD

**Issue by yogeshbeniwal** [coralproject/talk#4041]
**Expected behavior:**
Login with OpenID Connect should work with Azure AD B2C

**Actual behavior:**
Login with OpenID Connect is throwing `INTERNAL_ERROR: TOKEN_INVALID: jwt not active` error. However testing with https://jwt.ms/ shows jwt is returned in response by Azure AD B2C and same configuration is working for other OpenID client applications.

![Screen Shot](https://user-images.githubusercontent.com/7325107/187503806-af931056-c5f7-4645-aebf-1e32b2cccf02.png)

This may be because of time clock difference, hence related to #4040

**Comment by losowsky** [comment]
This is related to your time zone issue, which we closed before.
