### ISSUE TITLE
Unable to only use storyID or storyURL when creating the comment stream embed

### ISSUE THREAD

**Issue by oliver-dvorski** [coralproject/talk#4043]
**Expected behavior:**

According to [the docs](https://docs.coralproject.net/cms), you can specify the following parameters when creating the comment stream embed
> - storyID - [string] (optional): ID for the story. May alternately specify via storyURL or allow Coral to scrape and determine automatically
> - storyURL - [string] (optional): URL for the story. May alternately specify via storyID or allow Coral to scrape and determine automatically.

My understanding of this is that you can specify **either** parameter to tell Coral to look for an existing story

**Actual behavior:**

When creating a stream with only the storyID parameter defined but without a storyURL, Coral will not find the existing story.
![image](https://user-images.githubusercontent.com/9038049/187907079-dec82357-eedd-4ec6-a4dd-e182d1c3e53f.png)

It says that there are no comments but there is one on this story.

![image](https://user-images.githubusercontent.com/9038049/187907499-cdff3e54-b7ef-4047-98f4-e8ff6e7c3f80.png)

When I then specify both the storyID and storyURL, it will find the story and the comment for it
![image](https://user-images.githubusercontent.com/9038049/187907692-41b04273-41ff-47e7-ad7b-8f30f764a048.png)

**Versions:**

- NodeJS: 16.16.0
- NPM: 8.11.0
- MongoDB: 4.2
- Redis: 5.2
- Browser: FF 103.0
- OS: Arch, btw

Here's the code for the Stream integration

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
  </head>
  <body>
    <div id="coral_thread"></div>
    <script type="text/javascript">
    (function() {
      var d = document, s = d.createElement('script');
      s.src = 'http://my-local-domain.loc/assets/js/embed.js';
      s.async = false;
      s.defer = true;
      s.onload = function() {
        Coral.createStreamEmbed({
          id: "coral_thread",
          autoRender: true,
          rootURL: 'http://my-local-domain.loc',
          storyID: 'tralalalala',
          // storyURL: 'actual-url',
        });
      };
      (d.head || d.body).appendChild(s);
    })();
  </script>
  </body>
</html>
```

**Comment by wyattjoh** [comment]
You can specify either, _but you must be consistent_. If the `storyID` is specified, Coral won't even bother looking up the story by URL even if both are provided. If you had at first provided only the `storyURL`, then Coral will generate an ID for the story, thereby creating a disconnect.

Additionally, if you only specify the `storyID`, the stream will use the canonical URL of the embedded page as the `storyURL`. Check in your database if the `storyURL` matches the one seen on the page where you're observing the story.

**Comment by oliver-dvorski** [comment]
Thanks! That's exactly how the system behaves. I didn't know that the stream will use its own canonical URL as a search parameter if the URL hasn't been provided.

**Comment by kamalravi** [comment]
@wyattjoh On a related issue, I am trying to collect the comments.

When queried using storyID, I get the comments in json format.
```
https://motherjones.coral.coralproject.net/api/graphql?query=&id=6b8b6732bad09d3084f195dd40eafb4b&variables={"storyID":"944154","commentsOrderBy":"CREATED_AT_ASC","tag":null,"storyMode":null,"flattenReplies":false,"ratingFilter":null}
```
However, when storyURL is used, it doesn't return the same results.
```
https://motherjones.coral.coralproject.net/api/graphql?query=&id=6b8b6732bad09d3084f195dd40eafb4b&variables={"storyURL":"https://www.motherjones.com/politics/2022/01/trump-january-6-insurrection-pardons/","commentsOrderBy":"CREATED_AT_ASC","tag":null,"storyMode":null,"flattenReplies":false,"ratingFilter":null}
```

Can we query the comments using the storyURL? Could you direct me where I can get the storyID using the storyURL?

**Comment by wyattjoh** [comment]
When a `storyURL` is used, it tries first to lookup the story by URL, if it doesn't, it'll create it. If the story was created with a slightly different canonical URL, it will just create another story. Validate that the URL you're using is the same URL used in the comment embed for those stories.

Also, rather than using those URL's, you should be using the Coral API directly, refer to [the documentation](https://docs.coralproject.net/api/schema) on how to connect to it, and query using the following:

```graphql
{
  story(url: "https://...") {
    id
    comments {
      edges {
        cursor
        node {
          body
        }
      }
    }
  }
}
```

cc @tessalt  + @nick-funk

**Comment by kamalravi** [comment]
Thanks!
I checked the comment-embed-URL 

```
https://motherjones.coral.coralproject.net/embed/stream?storyID=944154&storyURL=https%3A%2F%2Fwww.motherjones.com%2F%3Fp%3D944154%23comment-container&v=6.18.2&ts=1673283600000&initialWidth=845&childId=coral_thread&parentTitle=Trump%20Declares%20Support%20for%20January%206%20Insurrectionists%20%E2%80%93%20Mother%20Jones&parentUrl=https://www.motherjones.com/politics/2022/01/trump-january-6-insurrection-pardons/
```
It breaks into.
```
https://motherjones.coral.coralproject.net/embed/stream?storyID=944154
&storyURL=https://www.motherjones.com/?p=944154#comment-container
&v=6.18.2
&ts=1673283600000
&initialWidth=845
&childId=coral_thread
&parentTitle=Trump Declares Support for January 6 Insurrectionists – Mother Jones
&parentUrl=https://www.motherjones.com/politics/2022/01/trump-january-6-insurrection-pardons/
```

It appears we still need storyID. Is that the correct embed URL? 

Also, I looked into Coral API, we need an access token to query which requires an account with Coral. Is it a paid service?

Appreciate your help!

**Comment by wyattjoh** [comment]
The Coral CLI can [generate a token](https://docs.coralproject.net/api/schema#get-an-access-token) if you are an authenticated administrator. There is no way for users that are not administrators to interact with this API directly.
