### ISSUE TITLE
Send email and show email in detail view based on third party

### ISSUE THREAD

**Issue by mvdwaeter** [coralproject/talk#4047]
## Search Terms

email, e-mail, send, mail, override, third party, smtp, sso

## Suggestion

Make it possible to send email and show email that is retrieved on the fly from a third party service.

## Use Cases
Our company doesn't allow to store email addresses in the coral talk database for security reasons.
When our users sign in via SSO in coral talk (on the client side), a coral talk user is created with an email that is generated based on their user-id of the external service. E.g **gigya_{external-user-id}@our.website.com**
We do this, because the email field is required.

Now when our moderators ban a user, an email is attempted to send to this fake emailaddress.
If we can make showing the emailaddress and sending email to a user extendable, our problem would be solved.

E.g. an advanced configuration to fill in an API endpoint that returns an emailaddress based on the userID.
Is this on your roadmap?

If not, what would be the best place in the code to inject this?

Thank you!

**Comment by tessalt** [comment]
Hi there, this is not currently on our roadmap. You could potentially set up some type of SMTP relay service that receives emails from coral and then maps fake emails to real emails, other open source users have set up relay services to customize email delivery.
