### ISSUE TITLE
CPU spikes when having a story with > 2000 comments

### ISSUE THREAD

**Issue by ihardyslide** [coralproject/talk#4078]
Hi,

I have experienced some kind of performance issues when Coral tries to render a comment stream for a story with over 2000 comments.
It seems that MongoDB uses a lot of CPU when multiple people try to access that story at the same time.
With enough added CPU power (too much for my feeling), Coral is able to handle those requests.

Nevertheless, I analysed the respective code parts and found out, that Coral immediatly fetches all remaining comments on first render, not only the 20 visible ones.
I think, that this should only happen after the user clicks on the "Load all comments"-button.
Because as it is now, with this many comments, each user who accesses the story needs to load an additional ~2MB of data, even though the user will maybe never click on the "Load all comments"-button.

In order to make the first render on page load way more faster in this scenario, I have removed this code:
https://github.com/coralproject/talk/blob/1d705537351d62976f895b74246ba4331fd26c2b/src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabContainer.tsx#L174-L176
and copied it before this line:
https://github.com/coralproject/talk/blob/1d705537351d62976f895b74246ba4331fd26c2b/src/core/client/stream/tabs/Comments/Stream/AllCommentsTab/AllCommentsTabVirtualizedComments.tsx#L113

Now the initial render of the comment stream does not need to load ~2MB of data.
It will be only fetched and rendered as soon as the user clicks on the button, which makes it much more useable in my observation.

Setup:
Coral: v7.3.0 (container)
MongoDB: 4.2 (container)
Redis: 3.2 (container)

I don't know if there was an intention behind the way it was built now, but maybe it was just overseen because nobody ever tested with such an amount of comments.
If this is intentionally like this, I would be happy to hear why.

BR

**Comment by tessalt** [comment]
Hi there, This is related to an undocumented feature that is used by our parent company, unfortunately we haven't had the resources to separate code paths for different use cases. We will likely do this in the future but don't currently have a timeline. You might be best of creating a fork with this change for now, it should be fairly straightforward to maintain.

**Comment by ideallical** [comment]
Interesting, I'll try out this fix, as we run into some similar issue; https://github.com/coralproject/talk/issues/4125
