### ISSUE TITLE
Login leads to empty Talk embed screen

### ISSUE THREAD

**Issue by mattlinares** [coralproject/talk#4100]
Our Coral instance was working fine until recently - now attempts to login lead to an empty comments embed div and the following error:

```
Uncaught TypeError: Cannot read properties of null (reading 'location')
    at c.value (Popup.ts:226:17)
    at wi (react-dom.production.min.js:135:172)
    at Ua (react-dom.production.min.js:179:157)
    at bu (react-dom.production.min.js:263:490)
    at fc (react-dom.production.min.js:246:265)
    at sc (react-dom.production.min.js:246:194)
    at tc (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at $o (react-dom.production.min.js:122:325)
```

<img width="1014" alt="Screenshot 2022-11-23 at 17 20 58" src="https://user-images.githubusercontent.com/71731/203610966-2a3fdc58-7c3b-40ac-bda8-ecc21cd52425.png">

Anyone know why this might be happening? Thanks!

**Expected behavior:**

When logging in, the comment box continues to show and user can comment.

**Actual behavior:**

When logging in, the comment box becomes empty.

**Related Issues:**

I can't see any other bugs that look similar.

**Versions:**

Coral Talk v6.11.1
- NodeJS:  12
- NPM:
- MongoDB: 4.2
- Redis: 3.2
- Browser:  Chrome and Firefox 107.0
- OS: Mac OS

**Comment by tessalt** [comment]
Hi there, I'm not totally certain what's happening here but it looks like the popup has lost its reference to `window`. I would suggest updating to the latest stable version of coral v6.x which is https://github.com/coralproject/talk/releases/tag/v6.18.1 and see if the issue persists
