### ISSUE TITLE
Error - Duplicate Story ID

### ISSUE THREAD

**Issue by manojkvenkat** [coralproject/talk#4116]
Hi,

Opening the comment(configured with Coral) of an article for which the URL is changed is throwing the below error. Can anyone help how to fix this?

```
An error has occurred
Trace ID
8f61ab30-7d03-11ed-842b-c1ea865a9b7b
Message
DUPLICATE_STORY_ID
```

**Comment by losowsky** [comment]
hi Manoj

This indicates that you've set up your CMS integration incorrectly. See here:

[storyID#](https://docs.coralproject.net/cms#storyid)
To more tightly couple Coral with your CMS you can provide your CMS's unique identifier to Coral by including a storyID parameter in the render function. Doing so will allow you to target the Story for later updates via Coral's Graphql API, such as updating the URL if it changes.

Best wishes

Andrew

**Comment by manojkvenkat** [comment]
Hi Andrew,

Indeed, we're passing the Story ID in a render function. Please find the below screenshot. Are we missing anything here?
![image](https://user-images.githubusercontent.com/2069696/210949237-ffb8f171-918f-46cb-87e2-931f1ac5f20d.png)

**Comment by tessalt** [comment]
When you change a URL on a story that has been previously published and scraped by Coral, you will need to use the API to update the story with the new URL. Instructions for integrating the API are at https://docs.coralproject.net/api/schema and the mutation you'll want to call is https://docs.coralproject.net/api/mutations/update-story

**Comment by Vignesh291292** [comment]
@tessalt 

We tried below query to update story url but it throws error
![Screenshot from 2023-02-23 18-53-53](https://user-images.githubusercontent.com/44498588/220919354-3f50d0e8-7ab2-4cda-9057-327f99ee4617.png)

{"query": "{mutation updateStory(input: UpdateStoryInput!)}",
"operationName": "updateStory",
"variables":{"UpdateStoryInput":{"id": 60896316,"story": {"url":"xxxxxxx"},"clientMutationId": "60896316"}}
}

Anything wrong in this format
