### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ideallical** [coralproject/talk#4117]
I'd love to see a changelog in the talk project.
E.g. a CHANGELOG.md in the root folder.

## Search Terms

changelog

## Suggestion

Add a CHANGELOG.md file in the root folder.

## Use Cases

To quickly see what new features, bugfixes and deprecations are introduced by upgrading to a newer version of talk.

**Comment by tessalt** [comment]
changelog is available for each version via releases https://github.com/coralproject/talk/releases
