### ISSUE TITLE
readinessProbe for k8s

### ISSUE THREAD

**Issue by ideallical** [coralproject/talk#4121]
## Search Terms

readinessProbe, k8s, kubernetes

## Suggestion

An endpoint to probe whether a coral talk instance is ready to be used.

## Use Cases

When scaling up, k8s is currently doing a request on `/ `, but I believe this endpoint can be live before the rest of the website is live. It would be nice to have an official readinessProbe endpoint to prevent bringing the pod live too early.

**Comment by tessalt** [comment]
does /api/health work for you?

**Comment by mvdwaeter** [comment]
Hi, not sure how we missed that endpoint. Thanks, we'll use that endpoint from now on!

**Comment by Shubhamsharma585** [comment]
Hi @mvdwaeter   I am a coral user. Have you deployed coral on the sub-directory? Can you please suggest a way to use coral on the sub-dire as 

'http://127.0.0.1:5000/${path}' ==> 'http://127.0.0.1:5000/discussions/${path}'

**Comment by ideallical** [comment]
Hi, I have not deployed coral talk on a sub directory.
I'd suggest to deploy it on a sub domain instead. E.g. https://talk.example.org if your website is on https://example.org

good luck 👍
