### ISSUE TITLE
Akismet blocking edited posts - not submitting recheck_reason?

### ISSUE THREAD

**Issue by Sentynel** [coralproject/talk#4122]
It's end-of-year best-of list season over at my site, and many of our commenters are joining in with the writers and submitting their lists in the comments. You can see a number of examples [on this post](https://www.angrymetalguy.com/new-blood-same-bad-taste-the-amg-staff-pick-their-top-tenish-records-o-2022/) among others. This is the first year we've had Akismet turned on (as this is the first year we've started getting much spam posting to our Coral instance). While moderating, I've noticed the following problem:

If somebody submits a list post and then edits it, _most of the time_ Akismet will mark the edited post as spam, even though the original version was not.

Notably, the list posts are significantly wordier than the typical comments we get. My theory is that we're not currently correctly informing Akismet that this is an edit, and therefore it thinks it's a new post with identical content. When combined with being wordy and oddly formatted compared to normal comments, this seems to be enough to trip the spam filter reasonably reliably.

Looking at the Akismet API docs, I think the solution is fairly simple: if this is an edited comment, we should be sending `recheck_reason=edit`: https://akismet.com/development/api/#comment-check As you can see in the code, that's not currently happening: https://github.com/coralproject/talk/blob/36c7b84a48738ac14f0f3ea66cf8f8f20c6a0932/src/core/server/services/comments/pipeline/phases/spam.ts#L97

**Expected behavior:**

Non-spammy posts are not suddenly marked spam when they're edited.

**Actual behavior:**

Long but non-spammy posts are regularly marked spam when edited.

**Related Issues:**

None

**Versions:**

- NodeJS:
- NPM:
- MongoDB:
- Redis:
- Browser:
- OS:

**Comment by losowsky** [comment]
Thanks for the heads up - it's in our queue to fix via the PR you submitted
