### ISSUE TITLE
Slow after upgrading from 7.1.3 to 7.4.4

### ISSUE THREAD

**Issue by ideallical** [coralproject/talk#4125]
Hi, I recently attempted to upgrade our coral talk from 7.1.3 to 7.4.4 but had to reverse it, as the read and writes on the MongoDB increased 10x.
The network activity increased (without the throughput increasing), and the CPU increased a lot.
I recon there is some change in how the data is fetched which is a lot less efficient than before. I suspect the 7.2.0 version as it mentions something about optimisation in the release log: https://github.com/coralproject/talk/releases/tag/v7.2.0, but will verify this.

Could it be that I'm missing an index?
I have all the indexes on creation, the ones mentioned in INDEXES.md, and some that the profiler was suggesting.

**Expected behavior:**
Upgrading to a new version should not make the system slower.

**Actual behavior:**
Upgrading to new version made system slower.

**Versions:**
- coral talk 7.4.4

**Comment by tessalt** [comment]
Hi there, thanks for reaching out. Recent versions of coral (> 7.2.0 https://github.com/coralproject/talk/releases/tag/v7.2.0) were optimized to support a use case used by Vox Media's properties, but it may cause issues for other use cases. We're working on a resolution that should optimize loading for all use cases, but until we have that resolved, it may be best to use coral v7.1.3.

**Comment by mvdwaeter** [comment]
Hi @tessalt, what's the status on the proposed resolution to optimise loading for all use cases?

**Comment by tessalt** [comment]
we're hoping to release the update in about 2 weeks.

**Comment by ideallical** [comment]
It seems like 8.0.0 is that release, is that correct?

**Comment by tessalt** [comment]
@ideallical correct!
