### ISSUE TITLE
Add ActivityPub endpoint

### ISSUE THREAD

**Issue by saerdnaer** [coralproject/talk#4130]
## Suggestion

Are there any discussions regarding providing ActivityPub endpoints in Coral Talk?

## Use Cases

Users could post comments to with their existing accounts (e.g. from Mastodon), while publishers still can moderate the comments on their site.

**Comment by losowsky** [comment]
Hi saerdnaer, 

No, there aren't - comments are very often restricted by publishers to registered users or subscribers, this would negate a lot of the benefit that they get from having comments in the first place. Thanks for the suggestion!

**Comment by rasos** [comment]
Well, ActivityPub can also _create_ traffic to original articles. As not only Mastodon gained maturity, but also THreads is supporting ActivityPub, this option should probably be reconsidered. 

See also https://github.com/coralproject/talk/issues/2078
