### ISSUE TITLE
Show Mod Tools in View Conversation Window

### ISSUE THREAD

**Issue by SomethingThatIsGeneric** [coralproject/talk#4148]
Give moderation tools on the popup "View Conversation" window so we can delete comments within that pop up to save time having to open a new window or tab.

What do you want to use this for? This will help save time moderating a conversation that has devolved into name-calling and requires more than just the flagged comment to be removed
What shortcomings exist with current approaches? Currently you'd have to go to the front end and delete all other comments around it before removing the directly linked comment or else all comments disappear and you get the message: "This comment has been removed or does not exist." so you'll have to go back to the tool or load all comments and scroll to where you just were.

**Comment by losowsky** [comment]
This is a good idea! I'll add it to our backlog. This isn't something high on our priority list, so if it's something you'd like to contribute to our open source code, do please go right ahead!
