### ISSUE TITLE
commentModerationActions table infos

### ISSUE THREAD

**Issue by ihardyslide** [coralproject/talk#4149]
Hi,

is there any Frontend or any possibility to use the info available for the "Audit log" (as it is called in the source code) which is stored inside _commentModerationActions_ table?
https://github.com/coralproject/talk/blob/cfe3f908b9568a10fa42e23acab66273cb9742a6/src/core/server/services/comments/moderation/moderate.ts#L93-L103
I could not find anything related to this table in the docs.

Thanks

**Comment by tessalt** [comment]
there is no front-end that exposes this info, but you can query the moderation actions for a specific comment using the API, via the `statusHistory` field
