### ISSUE TITLE
proxy request /api/graphql (ECONNREFUSED) on watch

### ISSUE THREAD

**Issue by akuales** [coralproject/talk#4151]
For legacy reasons I need to run v6.18.1 of talk. 
After `npm i ` running `npm run build ` and `npm run start` work fine and the frontend on Port `3000` connects to  the DB (Docker Containers for mongo on `27017` and redis `6379`) leading me through the installation process - no problems whatsoever.

Running `npm run watch` running on Port `8080` spins up fine, but opening `http://localhost:8080/` I am getting an error in the console:
`[HPM] Error occurred while trying to proxy request /api/graphql from localhost:8080 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)` 
for every api request from the frontend.

If I start a second terminal running `npm run start` it works, but as I couldn't find anything about running two processes simultaneously in the docs I was assuming this is not intended.
May I ask for any suggestion if I missed something in the docs that would let me run `npm run watch` solely or if it's expected to run 2 processes for development? Thanks a lot in advance.

**Expected behavior:**
Running `npm run watch` connecting to /api/graphql`

**Actual behavior:**
Need to start `npm run watch` and `npm run start` simultaneously during development to make requests to /api/graphql

**Related Issues:** 
-

**Versions:**
6.18.1

- NodeJS: 14.18.3
- NPM: 8.1.4
- MongoDB: 4.3
- Redis: 3.2
- Browser: Chrome, FF, Edge, Safari
- OS: Windows 10 (running wsl)

**Comment by thisissmohan** [comment]
in the package.json, devDependencies change ts-node-dev to below
"ts-node-dev": "github:mmvsk/ts-node-dev#d7e9cfbad414bcc5fc9ddb5cf75a74496a9e4549",

**Comment by thisissmohan** [comment]
![Screenshot from 2023-02-19 00-00-54](https://user-images.githubusercontent.com/40170313/219882446-07f1c1ca-02d9-4fa2-bbe0-0549b98aed40.png)
