### ISSUE TITLE
Comment Count issue

### ISSUE THREAD

**Issue by rsankaronline** [coralproject/talk#4166]
To show all comments, we don't want the Newest, Oldest, Most replies, and most respected. 

Even if we count all the comments in the 4 drop - down options, the count will be less because they are sorted. (33 comments will only load, but there are 38 comments)

Simply give an option for the readers to see all the comments. Is that any option for showing all comments when default?

**Comment by tessalt** [comment]
I'm not sure what the question is here, but the only display options for the comments are the ones in the dropdown.

**Comment by losowsky** [comment]
This could also be happening because you've rejected a parent comment and its replies are hidden except for direct links. Hope that helps!
