### ISSUE TITLE
Recommended OpenID Connect provider?

### ISSUE THREAD

**Issue by yogeshbeniwal** [coralproject/talk#4168]
May I know what is recommended OpenID Connect provider for self hosted instances? 

Coral doesn't support Azure B2C spec implementation. Google Identity platform doesn't seems to support custom domain with /.well-known/openid-configuration Issuer URL and other URLs to use in Coral settings.

**Comment by tessalt** [comment]
we don't have a recommended provider as this time, we haven't worked with OIDC in a while and I'm not up to date on what is available, sorry!
