### ISSUE TITLE
API query for users

### ISSUE THREAD

**Issue by mattlinares** [coralproject/talk#4199]
**Expected behavior:**

I expect the API docs to explain `users` `query` field behaviour. https://docs.coralproject.net/api/queries/users#query-string.  (Don't mean this to sound snide, just trying to make this fit the ticket format!)

**Actual behavior:**

I am confused about how to [query `users`](https://docs.coralproject.net/api/queries/users), which shows:

```
users(
  first: Int = 10
  after: Cursor
  role: USER_ROLE
  query: String
  status: USER_STATUS_FILTER
): UsersConnection!
``` 

I'm not sure how to supply `query` as a meaningful string:

In testing the `users`I am trying things like:

```
{ 
  users ( query: "createdAt: 2023-03-28T09:51:50.132Z" ) { 
    nodes { email createdAt } 
  } 
}
```

and:

```
{ 
  users ( query: "query user (createdAt: 2023-03-28T09:51:50.132Z)" ) { 
    nodes { email } 
  } 
}
```

which return no objects although that creation date is one attached to an existing user in another query.

I am specifically wanting to query all users `createdAt` the last 24 hours, so will eventually query a range. Tips on that most welcome. 

I also find this part of the docs strange, makes me think I may have totally misunderstood the `Users` query type:

```
Type[#](https://docs.coralproject.net/api/queries/users#type)
[UsersConnection](https://docs.coralproject.net/api/objects/users-connection)[#](https://docs.coralproject.net/api/queries/users#usersconnection)
UsersConnection represents a subset of a **stories** list.
```

I'd ideally not log this as a bug but there isn't another good space for discussing Coral Talk matters and previous API query enquiries have gotten a good response here, so here goes...

Thanks.

**Comment by mattlinares** [comment]
As it happens, I will be able to fulfil our needs by using `first` (limited to 50) to get the most recent users, but this is fallible because it's harder to guarantee that it's returning all new users.

I'm also fascinated by what `query` is intended for.

**Comment by tessalt** [comment]
hi there, the `query` filter is a text search field. The API does not support the kind of advanced querying you're looking for, you'll want to run those queries directly in the database.
