### ISSUE TITLE
Unit tests seem to expect current language to be en-US

### ISSUE THREAD

**Issue by ideallical** [coralproject/talk#4216]
**Expected behavior:**
When I set the env `LOCALE` to e.g. `de` or `it-IT` the unit tests should not fail.

**Actual behavior:**
The unit tests fail, as the unit tests contain assertions with hardcoded English strings. 

E.g this unit tests fails when setting the language to `de`:
/src/core/client/stream/test/comments/stream/liveCommentReplies-rtl.spec.tsx 

I'm not sure which translations are the ones that break the test, but for now I disabled this test to keep on developing. 

**Related Issues:*
-

**Versions:**
- Coral Talk:
v8.0.1

- NodeJS:
v14.20.0

- NPM:
v8.19.4

- OS:
OSX

**Comment by ideallical** [comment]
On second thought, this seems to work if all issues with the command  ./scripts/i18n/validate.ts de 

or  ./scripts/i18n/validate.ts nl-NL are removed

**Comment by tessalt** [comment]
hi there, the test suites include generated and hardcoded strings meant to ensure consistent rendering for functional validation, and currently only support the en-US locale.

**Comment by ideallical** [comment]
Thank you for letting me know about the test suites and their limitations. I will keep in mind that they include generated and hardcoded strings that ensure consistent rendering for functional validation, and that they currently only support the en-US locale. Is there any plan to expand the support for other locales in the future?
