### ISSUE TITLE
Badge Refresh SSO / image badges?

### ISSUE THREAD

**Issue by jbotte** [coralproject/talk#4250]
Noticed an issue with custom user badges and SSO. 

It looks like I cannot change the badges after the SSO account is created, even if I log the user out and then generate a new SSO token it still maintains the old badge and the database does not updated (used graphql query to verify this). I also verified that the data structure in my token was correct using the JWT debugger linked in the coralproject/talk docs. 

I have attached a payload example

<img width="562" alt="Screenshot 2023-05-23 at 11 34 19 AM" src="https://github.com/coralproject/talk/assets/2279461/a76f4cea-2486-489d-ad9b-b2ad584412c3">

Additionally, is there an option for image badges / flair in the works, have any forks successfully implemented this?

**Comment by tessalt** [comment]
what was the payload the first time you sent it, and then what was the updated payload? If you just remove the badges field I don't think it will update it, you will need to send through an empty array.

**Comment by jbotte** [comment]
Here was my original 

  {
    "user": {
      "id": "25",
      "email": "fakeemailzzz+1@gmail.com",
      "username": "anotheruser",
      "badges": [
        "BadgeName"
      ],
      "url": "https://mysite.com/profile"
    }
  }

Here is a screenshot of the badge working 

<img width="418" alt="Screenshot 2023-05-23 at 6 24 02 PM" src="https://github.com/coralproject/talk/assets/2279461/175a0afc-c78e-475d-8253-6e1d51eceb80">

It seems to me that the badge is updated and saved only on first sso token auth and after that the system ignores it, I will try and test a bit more and confirm. 

I may try rotating the secret and invalidating all old tokens and then try again.

I do appreciate your time, thanks for getting back to me.

**Comment by jbotte** [comment]
Can confirm even after invalidating old SSO secret and generating new tokens again the badges do not update, 

Here is what I have tested

payload with empty array for the users.badges field 
payload with 1 string array with the badge string of "badge1"
payload with 2 string array of ["badge1","badge2"] 

created a new user with the new payload and it shows the newest badge input.

**Comment by tessalt** [comment]
are you including an `iat` field in your payload?

**Comment by jbotte** [comment]
It seems when I enable iat, exp, jti things work as expected. 

I'll test and see which one did it or if I need all 3 turned on. 

May be worth updating the documentation to say that badges require them?

**Comment by jbotte** [comment]
thanks for your help @tessalt !
