### ISSUE TITLE
Image Badges (flair)

### ISSUE THREAD

**Issue by jbotte** [coralproject/talk#4254]
## Search Terms

image badge, image badges, flair, image user badge, user badges

## Suggestion

Allow image url strings for badges so sites can create something similar to "flair" for their comment sections

Here is an example of what I implemented on a test server

<img width="914" alt="Screenshot 2023-05-25 at 6 41 40 PM" src="https://github.com/coralproject/talk/assets/2279461/42687390-1888-4ba1-9e3c-0e90f2f6aef0">

Here is a code excerpt of me implementing this on my test server.

https://pastebin.com/g4EtiJEM

I also plan on adjusting the regex to make sure it handles urls query params.

The function excerpt is from my modified AuthorBadges.tsx

## Use Cases

We want to encourage user interaction and reward them for different things with flair icons.

**Comment by jbotte** [comment]
formatting for the code didn't work so here is a pastebin

https://pastebin.com/g4EtiJEM

**Comment by jbotte** [comment]
Here is my updated code with support for query parameters (i may serve images through a cdn that needs query params to retrieve proper sizes) 


```
import React, { FunctionComponent } from "react";

import { Tag } from "coral-ui/components/v2";

interface Props {
  badges: ReadonlyArray<string>;
  className?: string;
}

const AuthorBadges: FunctionComponent<Props> = ({ badges, className }) => (
  <>
    {badges.map((badge) => {
      if (/^https?:\/\/.*\.(?:png|jpg|jpeg|gif)(\?.*)?$/i.test(badge)) {
        className = className + " flairBadge"
        return (
          <Tag key={badge} color="dark" className={className}>
            <img src={badge} />
          </Tag>
        )
      }
      else {
        return (
          <Tag key={badge} color="dark" className={className}>
            {badge}
          </Tag>);
      }
    })}
  </>
);

export default AuthorBadges;

```

**Comment by tessalt** [comment]
Hi there, thanks for the suggestion, we'll add to our backlog.
