### ISSUE TITLE
Token invalid: There are token validation errors.

### ISSUE THREAD

**Issue by tanabem** [coralproject/talk#4270]
After setting "Login with Single Sign On" of CoralProjectTalk to ON (true) and connecting to the CoralProjectTalk server from an embedded script of embed.js from a certain access source (A), set "Login with Single Sign On" is set to OFF (false), docker-compose.yaml volume setting (permanence setting) is performed, and docker compose down & docker-compose up -d is executed, from the connection source (A) There was a problem that the access was regarded as an SSO connection and resulted in a JWT token validation error.

An example error log is below: 
{"name":"coral","hostname":"44e92ed58322","pid":1,"context":"http","contextID":"92060190-0f0e-11ee-9a64-f1de8424d714","tenantID":"89f01bb7-7747-4cd7-b74d-ac90cdd41367","level":50,"url":"/api/graphql","method":"POST","statusCode":401,"host":"jobs","userAgent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0","ip":"::ffff:192.168.48.6","err":{"message":"TOKEN_INVALID","name":"TokenInvalidError","stack":"verifyAndRetrieveUser (src/core/server/app/middleware/passport/strategies/jwt.ts:131:9)\nJWTStrategy.authenticate (src/core/server/app/middleware/passport/strategies/jwt.ts:164:26)\nattempt (node_modules/passport/lib/middleware/authenticate.js:369:16)\nauthenticate (node_modules/passport/lib/middleware/authenticate.js:370:7)\nsrc/core/server/app/middleware/passport/index.ts:181:6\nLayer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)\ntrim_prefix (node_modules/express/lib/router/index.js:317:13)\nnode_modules/express/lib/router/index.js:284:7\nFunction.process_params (node_modules/express/lib/router/index.js:335:12)\nnext (node_modules/express/lib/router/index.js:275:10)\ncors (node_modules/cors/lib/index.js:188:7)\nnode_modules/cors/lib/index.js:224:17\noriginCallback (node_modules/cors/lib/index.js:214:15)\ncallback (node_modules/cors/lib/index.js:219:13)\nsrc/core/server/app/middleware/corsWhitelisted.ts:33:5\nrunMicrotasks (<anonymous>)\n","id":"920676c0-0f0e-11ee-9a64-f1de8424d714","context":{"pub":{},"pvt":{"token":"[Sensitive]","reason":"Token invalid. Either a verifier (JWT, SSO, OIDC) is not enabled or there are token validation errors.","validationErrors":""}}},"msg":"http error","time":"2023-06-20T02:02:54.892Z","src":{"file":"/usr/src/app/src/core/server/app/middleware/error.ts","line":80,"func":"wrapAndReport"},"v":0}

Inside the log message is the "TOKEN_INVALID" part, which indicates that the provided token is invalid. There is also a message saying "Either a verifier (JWT, SSO, OIDC) is not enabled or there are token validation errors." This suggests either JWT, SSO (single sign-on) or OIDC (OpenID Connect) is not enabled or there was an error validating the token.

**Expected behavior:**
A comment input form will be displayed, and we can send comments by signing in.

**Actual behavior:**
The message "Network error. Please reload the page and try again. (401 error)" is displayed and the comment input field is not displayed.

**Related Issues:** 
I searched but could not find it. I think the error message is the same as "#4041 INTERNAL_ERROR: TOKEN_INVALID: jwt not active".

**Versions:**

-   coralproject/talk:7
-   Nginx: 1.25.1
-   NodeJS: 14.21.3
-   NPM: 8.0.0
-   MongoDB: 4.2.24
-   Redis: 3.2.12
-   Browser: Chrome, FF, Edge, Safari
-   OS: Ubuntu20.04LTS

**Comment by tanabem** [comment]
Additional information is provided below.
Access from the embedded script of embed.js on the server of another domain that is permitted to access the site displays the comment input form without any problems, and comments can be posted.
I get a Token invalid error for access from a specific domain. Is there a cache left on the CoralProjectTalk server side? I have deleted the Mongo and Redis volumes that were previously created with persistence settings, and cleared the browser cache.

**Comment by tessalt** [comment]
it's difficult to pinpoint the exact issue from your description, but you might try:

- verifying that your token decodes correctly using a tool like https://jwt.io/
- verifying that you have enabled the correct authentication strategies in the auth configuration panel (/admin/configure/auth)
- verifying that you have no typos in your site domain whitelist, and have included all subdomains (including www) and the correct protocols

**Comment by tanabem** [comment]
Thank you for your reply.
Of the 3 points you pointed out, the 2nd and 3rd were no problem. The first is that the connection source server does not generate the JWT, so it cannot be confirmed.

Currently, only "Login with email authentication" is checked in "auth configuration panel (/admin/configure/auth)".
The CoralProjectTalk server (site) I built allows access from two domains. Let's say one is www.example1.com and the other is www.example2.com.
When accessing from www.example1.com, the comment form page is displayed without any problems, and comments can be posted after email authentication.
However, www.example2.com seems to be accessed with "Login with Single Sign On (JWT)". www.example2.com seems to get a "TOKEN_INVALID" error because it doesn't specifically generate a JWT.

I'm thinking of resetting the entire CoralProjectTalk environment and rebuilding it from scratch, as it's not clear at all.

**Comment by jbotte** [comment]
Try with this matching settings? I got some weird quicks if I didn't have allow registration checked.

<img width="561" alt="Screenshot 2023-06-24 at 2 33 25 PM" src="https://github.com/coralproject/talk/assets/2279461/d7e12119-8619-459a-8274-db2ff56ec56c">

**Comment by tanabem** [comment]
@jbotte Thank you for your advice.
After checking and saving "enabled" for "Login with Single Sign On" on the CoralProjectTalk server, a network error occurs when accessing from a web page (script including embed.js) of a permitted domain. So, I tried unchecking "enabled", but the network error still persists. Deleting the cache of the browser (Firefox) does not change the situation. At this time, if you access from another browser (Edge or Chrome), the comment registration form will be displayed without any problems, and you can sign in with email (Login with email authentication) and post a comment. As a test, when I restarted the PC, no network error occurred even in Firefox, and I was able to post a comment without any problems. 
There may be a JWT token left somewhere on your PC or browser, but I haven't been able to identify it.

**Comment by tanabem** [comment]
Hi, all.
After further investigation, I finally found the cause!!
The key & value "coral:v2:accessToken" are stored in the browser's local storage, which seems to have had an adverse effect. I removed this key & value and the network error was resolved.
However, if this problem occurs, it is difficult to force the user to do this operation, so I think it is necessary to fix it on the CoralProjectTalk side.

**Comment by losowsky** [comment]
Hi there,

Coral is specifically set up only to allow one user with UIDs email and username to exist on any given instance, otherwise an error is caused. We describe this here: https://docs.coralproject.net/sso#troubleshooting-jwt-validation-errors 

If you are generating repeated different accounts with the same UIDs, this error will keep occuring.

Best wishes

Andrew
