### ISSUE TITLE
Android Integration 

### ISSUE THREAD

**Issue by apptestacc02** [coralproject/talk#4286]
Hi Team ,
I want to integrate coral in Android but I am unable to find any reference project for that , the documentation is not complete it does not provide the integration process, Can We have a reference Github project or document that describes in detailed process of integration or an article link

**Comment by losowsky** [comment]
Hi there, 

We detail integration of Coral in native mobile apps here: https://docs.coralproject.net/mobile 

Best wishes

Andrew
