### ISSUE TITLE
Missing JWT destination endpoint for "Login with Single Sign On" implementations.

### ISSUE THREAD

**Issue by tanabem** [coralproject/talk#4288]
Dear all,

I am currently working on integrating Single Sign-On (SSO) between my existing website and the Coral Project Talk comment system.

Despite following the available documentation and various online resources, I am encountering some issues. Specifically, I am struggling with the redirection step. After successfully generating the JWT on my server side, I am unable to redirect the user to the correct Coral Project Talk endpoint using the following URL: https://my-coral-talk-instance/api/v1/auth/sso/login?token={MY_JWT}

Upon trying to use this URL, I receive a "NOT_FOUND" error message, suggesting that the /api/v1/auth/sso/login endpoint may not exist or isn't properly configured.

My understanding is that the user should be automatically redirected to this URL upon clicking the Sign In button in Coral, and then returned to the comments page after a successful login. However, this flow does not seem to be working.

Could you please provide some assistance or direction? Is there a different endpoint I should be using, or perhaps some additional configuration required on my end? Also, is there an existing plugin that I should be using to facilitate this process?

I greatly appreciate any help or guidance you can provide.

**Expected behavior:**
The authentication by Single Sign-On (SSO)  is successful.

**Actual behavior:**
The endpoint is not found.

**Related Issues:** 
I didn't find any related issues.

**Versions:**
- coralproject/talk:7
- Nginx: 1.25.1
- NodeJS: 14.21.3
- NPM: 8.0.0
- MongoDB: 4.2.24
- Redis: 3.2.12
- Browser: Chrome, FF, Edge, Safari
- OS: Ubuntu20.04LTS

**Comment by tessalt** [comment]
Hi there, I'm not sure what documentation you're referring to, but that API URL does not look correct. Documentation should be at https://docs.coralproject.net/sso

**Comment by tanabem** [comment]
Dear @tessalt, 
It took me a long time to understand and verify the SSO specification document you gave me, but I finally succeeded in SSO authentication and posting a comment with a few users.
Thank you very much.
