### ISSUE TITLE
Android Login Pop up Not visible

### ISSUE THREAD

**Issue by apptestacc02** [coralproject/talk#4294]
Hi Team,
We have integrated the Coral setup in Android webview ,We are able to see the coral comments view but as We click on Login or register button it is not showing login or signup popup .it is working in web but not in android webview 

`.     

       mWebView.setThirdPartyCookiesEnabled(true);
        mWebView.setDesktopMode(true);
        mWebView.settings.setDomStorageEnabled(true);
        mWebView.settings.javaScriptEnabled = true
        mWebView.getSettings().setSupportMultipleWindows(true);
        mWebView.setCookiesEnabled(true);
        mWebView.setMixedContentAllowed(false);
        val webSettings: WebSettings = webView.getSettings()
        webView.getSettings().setSupportMultipleWindows(true);
       webSettings.setJavaScriptCanOpenWindowsAutomatically(true);
        webView.webViewClient = object : WebViewClient() {
            override fun shouldOverrideUrlLoading(
                view: WebView,
                request: WebResourceRequest
            ): Boolean {
            
                val url = request.url

                 return if (url != null && url.host != null) {
                    // Load the URL in the current WebView
                    view.loadUrl(url.toString())
                    true
                } else {
                    // Open the URL in a new tab or external browser
                    val intent = Intent(Intent.ACTION_VIEW, url)
                    startActivity(intent)
                    true
                }
                //return false>
            }

            override fun onPageFinished(view: WebView, url: String) {
              
            }
        }

      `

**Comment by apptestacc02** [comment]
Hi Team,Any Update on this ?

**Comment by losowsky** [comment]
Hi there, I'm afraid we don't have the knowledge or resources to debug issues with your app. 

Others have integrated Coral on webview without any issues, so we have to assume it's something in your code, but we're not able to provide free support to help you debug. Good luck!
