### ISSUE TITLE
Featuring and embedding comments from other social media platforms

### ISSUE THREAD

**Issue by vigorousnorth** [coralproject/talk#4298]
## Search Terms
"social media" Reddit Twitter Facebook 

## Suggestion

Sometimes our stories get really great comments and conversations on other social media platforms, like Reddit. I'd love for there to be a way to draw those conversations into the discussions we host on our own site with Coral. 

I'm envisioning a system by which a Moderator can create a new Coral comment that embeds and links to a comment from another social media site, then pings the original comment on that site to let them know that we've featured it on Coral and are inviting them to join the discussion with Coral users on our own site.

More generally, I think it would be useful for the Coral Project to bear in mind that a lot of our reader comments aren't being posted in our own comment sections, but in other social media platforms, where we have a lot less control over the conversations. As a nonprofit newsroom, I'd much rather host constructive comments and discussions on our own site  (Twitter and Facebook can keep the bad comments) instead of giving away more attention to platforms that frequently undermine us.

**Comment by losowsky** [comment]
Thanks for the idea! Other social media platforms tend to punish/report as spam any automated bot messages that try to push the conversation off their platform (for understandable reasons), so we don't have any plans to set up a "Hey! someone mentioned you over here! Come sign up!" bot system. Fun to think about, just not on our roadmap for that reason. Thanks!

**Comment by vigorousnorth** [comment]
Ah, OK, that makes sense. Thanks for the response!
