### ISSUE TITLE
SIGN IN AND JOIN THE CONVERSATION is not clickable for authentication free comment stream

### ISSUE THREAD

**Issue by Shubhamsharma585** [coralproject/talk#4305]
I have removed authentication for the comment stream but still, the sign-in button is coming and that too not working and not doing anything. In that case, the user is not able to post anything. I am sharing the screenshots from both sides "Admin" as well as "client" side.
Note:: I am on Windows 11 and using docker for evaluating coral/talk.
![ui-bug1](https://github.com/coralproject/talk/assets/77038696/05308b2e-f2ac-44cd-9f00-2417e4c11d9b)
![server-bug-2](https://github.com/coralproject/talk/assets/77038696/5275bb2a-6ab8-4850-8a2a-483039295009)

**Comment by Shubhamsharma585** [comment]
@cvle

**Comment by tessalt** [comment]
you will need to enable email authentication for the Comment Stream for this to work.
