### ISSUE TITLE
If Parent Comment is edited, Unable to edit Child Comment

### ISSUE THREAD

**Issue by Shubhamsharma585** [coralproject/talk#4320]
1. I have created a parent comment
2. Posted a reply
3. Edited Parent comment
4. Tried to edit child comment/reply but unable to do that
5. getting error of comment id.

![Screenshot 2023-08-21 at 1 53 50 PM](https://github.com/coralproject/talk/assets/77038696/8a3adbb0-c493-42e3-98b4-5361bbc790ba)

**Comment by Shubhamsharma585** [comment]
It's a serious bug. Can you please help me to fix it quickly?

**Comment by Shubhamsharma585** [comment]
Can you please look into this @cvle

**Comment by Shubhamsharma585** [comment]
Can you please look into this @wyattjoh @nick-funk @tessalt @marcushaddon

**Comment by tessalt** [comment]
Hi there, thanks for reporting this bug, we will investigate

**Comment by Shubhamsharma585** [comment]
Hi @tessalt Have you  investigated this issue. I think when comment is updated or edited then its 'comment id' is also updated but reply or its child reply's parent id is not updating. Can you please fix it as it is very serious issue in the product.

**Comment by losowsky** [comment]
hi @Shubhamsharma585 We have been able to replicate this issue, and we will fix it in an upcoming release. As it is an edge case that isn't blocking the basic functions of the product, we aren't going to release an emergency fix, but will get to it soon. Thanks.

**Comment by Shubhamsharma585** [comment]
Hi @losowsky Is there any update on this bug?

**Comment by losowsky** [comment]
hi Shubham, we have a PR here with the fix: https://github.com/coralproject/talk/pull/4334. It's awaiting final approval, we don't have a date yet for when it'll be merged. We have another code change that has priority, this should go in with some other fixes and improvements after that. Thanks again for reporting!

**Comment by kabeaty** [comment]
Closing this issue, as it has been resolved with this release: https://github.com/coralproject/talk/releases/tag/v8.5.2
