### ISSUE TITLE
"Unknown variable: $numberClass" error when using a german version and https://docs.coralproject.net/counts

### ISSUE THREAD

**Issue by wredzio** [coralproject/talk#4337]
I discovered that the German version of the common bundle had a mistake. 

```
https://github.com/coralproject/talk/blob/a50fff78c350bad5e80849915dad66fcabd539a2/src/core/server/locales/de/common.ftl
comment-count =
  <span class=**"{ $numberClass }"**>{ $number }</span>
  <span class="{ $textClass }">{ $number  ->
    [one] Kommentar
    *[other] Kommentare
  }</span>
```

should be 
```
https://github.com/coralproject/talk/blob/a50fff78c350bad5e80849915dad66fcabd539a2/src/core/server/locales/en-US/common.ftl
comment-count =
  <span class="**{ $textClass }**">{ $number  ->
    [one] Comment
    *[other] Comments
  }</span>

```

**Expected behavior:**

I would receive comments count in German. 

**Actual behavior:**

{"message":"Unknown variable: $numberClass","name":"ReferenceError","stack":"resolveVariableReference (node_modules/@fluent/bundle/compat.js:352:25)\nresolveExpression (node_modules/@fluent/bundle/compat.js:316:16)\nresolveComplexPattern (node_modules/@fluent/bundle/compat.js:561:21)\nFluentBundle.formatPattern (node_modules/@fluent/bundle/compat.js:922:21)\nObject.translate (src/core/server/services/i18n/index.ts:131:24)\ngetTextHTML (src/core/server/app/handlers/api/story/count.ts:64:12)\nsrc/core/server/app/handlers/api/story/count.ts:102:24\nrunMicrotasks (<anonymous>)\n"},"msg":"http error","time":"2023-09-01T11:26:40.269Z","src":{"file":"/usr/src/app/src/core/server/app/middleware/error.ts","line":80,"func":"wrapAndReport"}

**Comment by kabeaty** [comment]
thank you for reporting, this PR has been opened to address this issue: https://github.com/coralproject/talk/pull/4347

**Comment by kabeaty** [comment]
Closing this issue, as it has been resolved with this release: https://github.com/coralproject/talk/releases/tag/v8.5.2
