### ISSUE TITLE
RequestUserCommentsDownload doesn't work on users with a lot of data

### ISSUE THREAD

**Issue by ideallical** [coralproject/talk#4346]
Given a user with ~60k comments, of which 28% rejected.
You can get the archiveUrl of a user with this graphql:
https://docs.coralproject.net/api/mutations/request-user-comments-download

**Expected behavior:**
When I download the archiveUrl

Then, I can unzip the file, and I can view the contents of the user data.

**Actual behavior:**
When I download the archiveUrl

Then I cannot unzip it, and hence I cannot see the contents of the user data.

It does work for users with way less comments.
E.g a user with 471 comments of which 12%rejected, unzipped fine.

A user with 7,182 comments, and 17% rejected also seems to fail..

**Comment by losowsky** [comment]
Thanks - we'll look into this.

**Comment by ideallical** [comment]
So the download succeeds, but the zip cannot be openend. See screenshot.

![Screenshot 2023-09-11 at 12 15 58](https://github.com/coralproject/talk/assets/5603406/4a1359fd-1e88-4e71-b309-7b97a8238aa3)

I have tried with multiple users that have different amounts of comments. The ones with few comments can be downloaded/unzipped without issues, the one with a lot cannot be unzipped. It seems the download size is also not correct for these cases. And some on the border can be unzipped after you have downloaded it for a second time.

- 3k, 5k, 8K, 13k comments are no problem
- 15K comments doesn't unzip (only 539kb downloaded)
- 17K first time problem, then after trying a second time re-downloading it with a new **archiveURL**, it suddenly works to unzip it (the zip file was 205Kb when it fails, and 3.8Mb~4Mb when it succeeded)
60K it doesn't unzip (and also the download size is very small, ~1Mb)

My setup:
- Coral talk 7.3.1, which uses  `"archiver": "^3.1.1",` (just as the latest coral talk)

Pods with these limits:
```
 Limits:
      cpu:     900m
      memory:  1500Mi
    Requests:
      cpu:      700m
      memory:   900Mi
```

And these NODE_OPTIONS:
```
NODE_OPTIONS: "--max-old-space-size=8192"
```

This is where the download is created:
https://github.com/coralproject/talk/blob/v7.1.3/src/core/server/services/users/download/download.ts#L83-L169

**Comment by ideallical** [comment]
Good to know; when I do the same request locally, it does work. Locally I'm not bound by the pod limits of 900m/1400Mi, so perhaps it has something to do with loading the entire contents into memory which fails.. but somehow still produces a download.

**Comment by ideallical** [comment]
I tried:
- increasing pod cpu and memory (however, when monitoring I did not see any spikes in memory or cpu anyway), didn't solve it
- upgrading to `archiver@4.0.2`, didn't solve it
- upgrading to `csv-stringify@6.4.2`, didn't solve it
- lowering the zip compression level from 9 to 0

I wonder: 
- It does work locally
- No exceptions are logged in sentry in production
- If I force an exception locally, then I see that the download fails, so there is no exception raised I assume

The download on production succeeds, only the zip file is corrupt.
Also the zip file is significantly smaller when downloaded via production then locally.

**Comment by ideallical** [comment]
I think I pinpointed it to the load balancer that cuts off idle connections after 60 seconds.
I think the current script sets up a download stream but on large data sets, it takes more than 60 seconds to create the zip, hence the connection is closed before all data is received, resulting in a corrupt zip file. Increasing this value has quite some impact on our cluster, so I think it's better the zip wouldn't be created on request but in one of the task pods. And then as soon as the download is complete the user will receive an email with the download link. Makes sense?

**Comment by tessalt** [comment]
Hi there, we've looked into this issue and are unable to replicate it with our hosting environment, but it seems plausible that you've correctly pinpointed the issue with the load balancer. Unfortunately, we don't have the resources to look into a long-term fix for this issue at this time, though we may look into it in the future.
