### ISSUE TITLE
Support Microsoft Teams for moderation pings

### ISSUE THREAD

**Issue by rmens** [coralproject/talk#4353]
## Search Terms
Webhook, Teams, Moderation

## Suggestion
Microsoft Teams is used more and more in companies as replacement for Slack. It's included in Microsoft 365 that lot's of companies already pay for. It would be useful to have built-in Teams integration to help you forward comments from moderation queues into appropriate Teams Teams.

## Use Cases
Pinging moderators

**Comment by Shubhamsharma585** [comment]
Hi @rmens I am also a coral user. Have you tried to deploy coral on the sub-directory? Can you please suggest a way to use coral on the sub-dire as 

'http://127.0.0.1:5000/${path}' ==> '[http://127.0.0.1:5000/discussions/${path}'

**Comment by rmens** [comment]
@Shubhamsharma585 Please keep anything that's not related to this feature request out of this issue. Thank you.

**Comment by losowsky** [comment]
Thanks for this suggestion. It's not a priority for our roadmap, but we'd be happy to review an open source contribution to add Teams support; if you look at how the Slack support works, you can use that as a path to adding Teams.
