### ISSUE TITLE
Android Comments Implementation Example

### ISSUE THREAD

**Issue by benetra** [coralproject/talk#4358]
We are trying to implement the Coral Talk for Android Application but We are unable to find a proper documentation for it. Need a proper example to implement in Native application. or Github link of the implementation . 
Clicking on SignIn comment button in WebView not  working whereas Dom setting is enable in the code .
No third party popup is visible in Android Device.
JWT token generated using SSO secret also giving error when accessing in webview (graphql error 401)

**Comment by losowsky** [comment]
Hi there,

Here's the documentation for mobile integration: https://docs.coralproject.net/mobile 

Best wishes

Andrew
