### ISSUE TITLE
Translation not being applied 

### ISSUE THREAD

**Issue by oliver-dvorski** [coralproject/talk#4361]
**Expected behavior:**

`error-repeatPost` translated 

**Actual behavior:**

English version displayed even though another language has been selected in the settings and the translation is available in the file `src/core/server/locales/de/errors.ftl` 
 
**Related Issues:** 

**Versions:**

- NodeJS: v18.12.1
- NPM:8.19.2
- MongoDB: 4.2
- Redis: 3.2
- Browser: Chrome 117
- OS: Windows 10 22H2 with wsl 1
![Bug Coral](https://github.com/coralproject/talk/assets/9038049/d9a6a40d-95ef-4dea-9f0a-81491819cdee)

**Comment by losowsky** [comment]
How strange! We'll look into it, thanks for reporting

**Comment by losowsky** [comment]
Fixed in the new release 8.6.3: https://github.com/coralproject/talk/pull/4385
