### ISSUE TITLE
CORS Error When Clicking Email Verification Button

### ISSUE THREAD

**Issue by XIYO** [coralproject/talk#4370]
**Expected behavior:**  
Clicking the email verification button should trigger the email to be sent.

**Actual behavior:**  
A CORS error occurs.

**Related Issues:**  

**Versions:**

- Talk: 8.5.3 (Running in a Docker container on macOS)
- MongoDB: 7.0.2 (Mac)
- Redis: 7.2.1 (Mac)
- Browser: Edge 117.0.2045.60
- OS: Windows11

![image](https://github.com/coralproject/talk/assets/27078637/beadb403-39b0-44c6-9126-2de0965e06e2)
![image](https://github.com/coralproject/talk/assets/27078637/d745e97b-96d1-4711-be07-ce8ea5599725)

**Comment by losowsky** [comment]
We can't see here but have you correctly set up the Email section of the configuration?

**Comment by XIYO** [comment]
We are using Apple SMTP. 
We tested it without changing the settings since the day the issue was created.

**The day the issue was created**:
🟢Test mail was sent.
🔴Mail verification did not send the mail.

**Today**:
🟢Test mail is sent. (Still normal)
🟡Verification mail was sent a few times.
> After multiple attempts, initially about 10 emails were sent. However, the verification email sending was stopped again. Test emails continue to be sent normally.
> Not sure whether Apple SMTP is the cause or `talk` is the cause. 😵

**And still**:
🔴Clicking `resend verification` results in a `cors` error.

**Log**:
Output the log with `LOGGING_LEVEL=debug`.
(This is the log occurring when `resend verification` is clicked)

```text
{
  "name": "coral",
  "hostname": "fea0802679cb",
  "pid": 1,
  "level": 20,
  "siteID": "c5903ffd-659e-4114-8f42-43f8315e5321",
  "msg": "found associated site from request",
  "time": "2023-10-13T04:02:34.353Z",
  "src": {
    "file": "/usr/src/app/src/core/server/app/middleware/tenant.ts",
    "line": 149,
    "func": "retrieveSiteFromRequest"
  },
  "v": 0
}
{
  "name": "coral",
  "hostname": "fea0802679cb",
  "pid": 1,
  "context": "http",
  "contextID": "56c71460-697d-11ee-8155-cd8bf347addc",
  "tenantID": "f23da82d-0b4f-458b-8496-98684c24d540",
  "level": 20,
  "url": "/api/account/confirm",
  "method": "OPTIONS",
  "statusCode": 200,
  "host": "talk.xiyo.dev",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60",
  "ip": "::ffff:172.19.0.9",
  "responseTime": 81,
  "msg": "http request",
  "time": "2023-10-13T04:02:34.358Z",
  "src": {
    "file": "/usr/src/app/src/core/server/app/middleware/logging.ts",
    "line": 27
  },
  "v": 0
}

```

**Comment by losowsky** [comment]
Thanks. We're not sure what this is about, so will do some investigation.
