### ISSUE TITLE
New commenter approval: Bug or is this As Designed?

### ISSUE THREAD

**Issue by jbotte** [coralproject/talk#4384]
**Expected behavior:**

Admin enables new commenter approval

<img width="586" alt="Screenshot 2023-10-31 at 1 10 16 PM" src="https://github.com/coralproject/talk/assets/2279461/a5bd5b9f-13cf-4f3f-9b30-e481d0170c81">

comments from new users appear as pending, once 2 are approved this no longer applies to said user.

**Actual behavior:**

All users are now being flagged as new users all comments are now pending. Which is an issue when we thousands of commenters. 

**Related Issues:** 

**Versions:**

8.5.3

- NodeJS: Default from docker image
- NPM: Default from docker image
- MongoDB: Default from docker image
- Redis: Default from docker image
- Browser: N/A
- OS: N/A

**Comment by losowsky** [comment]
Hi there, 

Just to check, when you say "All users", does that include users who have not only left two comments, but already had at least two comments approved by moderators? If so, that's not as designed.

**Comment by jbotte** [comment]
@losowsky thanks for checking. Let me run a test on dev server and get back to you.

Our unmoderated count sits at 60k right now with production (there is no way to approve all right?).

Our suspect words list is rather intensive so most of our mods do not check the unmoderated list.

**Comment by losowsky** [comment]
Thanks John. It might just be that you aren't approving most people's comments, so most users are getting caught in the filter. We don't have a "approve all comments" filter sadly, for obvious reasons, but you could do something with the API or Moderation Phases if you wanted to set more complex rules to help approve things / hold them back

**Comment by jbotte** [comment]
Confirmed it works as designed, I will just have to write some script to go and approve things that are in the unmoderated queue. Thanks @losowsky !
