### ISSUE TITLE
broken link in docs 

### ISSUE THREAD

**Issue by bennettp123** [coralproject/talk#4400]
**Expected behavior:**

https://docs.coralproject.net/css#use-css-variables provides a link to CSS variables

**Actual behavior:**

https://docs.coralproject.net/css#use-css-variables —  when you click on the link (https://github.com/coralproject/talk/blob/main/CSS_VARIABLES.md), it returns 404 page not found

**Related Issues:** 

**Versions:**

since #4301

**Comment by losowsky** [comment]
Thanks! We'll fix this soon.

**Comment by losowsky** [comment]
Now released, thanks again for reporting: https://github.com/coralproject/talk/releases/tag/v8.6.3
