### ISSUE TITLE
DSA Anonymous Reporting

### ISSUE THREAD

**Issue by oliver-dvorski** [coralproject/talk#4464]
## Search Terms

- DSA
- Anonymous Report

## Suggestion

Thank you very much for the newly implemented DSA features! We appreciate their timely release.

Would it be possible to implement a feature with which users of a site can anonymously report a comment? It is our understanding that this is a requirement of the DSA, but currently every report is tied to an existing user.

**Comment by losowsky** [comment]
HI Oliver

We're working on an update to add this feature before it goes into effect in February. More soon!

**Comment by losowsky** [comment]
This should be up early next year, you can track it here: https://github.com/coralproject/talk/pull/4469 Thanks for reporting!

**Comment by oliver-dvorski** [comment]
Hi losowsky,

Thank you very much for implementing this feature! I've tested it and have some feedback, if I may present it.

1. When anonymous Users try to Report the same Comment, the first one can successfully report the comment, but every other anonymous User can't, because the system thinks that the second anonymous User is the same as the first one.
2. In *DSA Reports* we see only the first report.

Thank you very much for your effort on this and on the recent Update to Node 18, that's very much appreciated.

**Comment by losowsky** [comment]
Thank you Oliver - it’s just entering pre-release QA today so this is perfect timing for us to fix it!

**Comment by losowsky** [comment]
We were able to replicate in QA and fixed the bug https://github.com/coralproject/talk/pull/4486 Should be released next week, thanks again!

**Comment by oliver-dvorski** [comment]
Thank you!

**Comment by losowsky** [comment]
Released, thanks again Oliver: https://github.com/coralproject/talk/releases/tag/v8.7.1
