### ISSUE TITLE
 INTERNAL_ERROR: Text record must only set "authSource" or "replicaSet"`

### ISSUE THREAD

**Issue by palmicr** [coralproject/talk#4483]
**Expected behavior:**
Running image on AWS FARGATE connecting to MongoDB Atlas Serverless database.

**Actual behavior:**
`WrappedInternalError: INTERNAL_ERROR: Text record must only set "authSource" or "replicaSet"`

![image](https://github.com/coralproject/talk/assets/11208446/9f06d804-8893-4456-b704-71d5ebfa6973)

**Versions:**
Using latest versions.

I believe that this is most likely not a bug but a problem with using Atlas Serverless with mongodb and mongodb-core < 4. Is this correct and if so is there any plans to support serverless?

**Comment by nick-funk** [comment]
Unfortunately, Serverless Mongo is not supported at this time. We also do not have any plans to support it in future.

We test for and support the following types of Mongo DB deployments as our database provider:

- The community Mongo docker container image with tag 4.2 (https://hub.docker.com/_/mongo)
    - tag 5.0.6 also appears to be working, but that is not what we use in our dev environments
- Mongo Atlas (https://www.mongodb.com/atlas/database)
