### ISSUE TITLE
Suspected profanity dialog (?) on account creation

### ISSUE THREAD

**Issue by pablocubico** [coralproject/talk#449]
### Expected behavior
I should be able to register.

### Actual behavior
Can't register because of a "suspected profanity" error (?).
There are also some typos/artifacts on the error message, and some missing translations (screenshot attached).

### Steps to reproduce behavior
Test the registration form on https://blog.coralproject.net/the-empty-box/

Example:

<img width="304" alt="captura de pantalla 2017-03-28 a las 23 24 54" src="https://cloud.githubusercontent.com/assets/340766/24435845/1c294628-140e-11e7-8085-2b3f30a45654.png">

**Comment by kgardnr** [comment]
Hey @pablocubico this is fixed now! Thank you for bringing it to our attention! An emoji was breaking the banned words list, so we're creating a new issue to support emojis.
