### ISSUE TITLE
Support for Hostnames without TLD in "Site permitted domains"

### ISSUE THREAD

**Issue by krestaino** [coralproject/talk#4505]
**Issue:** Coral does not accept non-TLD hostnames (e.g., http://laptop:8500) in "Site permitted domains" under Organization > Site Details. While TLD domains (e.g., https://example.com and http://laptop.local:8500) and localhost (http://localhost:8500) are accepted, hostnames without a TLD yield an "Invalid URL" error. I use Tailscale MagicDNS, where I typically only use hostnames without TLDs.

**Request:** Allow hostnames without a TLD (http://laptop:8500), similar to the allowance for `localhost` currently.

**Expected behavior:** http://laptop:8500 should be a valid URL.

**Actual behavior:** Error: Invalid URL

<img width="678" alt="image" src="https://github.com/coralproject/talk/assets/5562514/7e03982d-875c-4f92-8717-a641567760ea">

**Versions:**

- NodeJS: v14.21.3
- NPM: 8.0.0
- MongoDB: 4.2.24
- Redis: 3.2.12
- Browser: Brave: 1.61.120 / Chromium: 120.0.6099.234 
- OS: macOS 14.3

**Comment by nick-funk** [comment]
We don't support the convenience URL's that Tailscale creates because they are non-standard W3C domains.

However, there should be fallback static IP mappings for these convenience URL's that Tailscale creates for you. You could try using that instead.

**Comment by krestaino** [comment]
Sounds good, I didn't realize they were non-standard W3C domains, so I understand not wanting to support them here. I appreciate the clarity!
