### ISSUE TITLE
Finnish translation: Notification email footer issues

### ISSUE THREAD

**Issue by juhog** [coralproject/talk#4522]
I have a PR ready to be submitted to fix this bug. My colleague has submitted similar Finnish translation fixes before in a few PRs (https://github.com/coralproject/talk/pull/2811, https://github.com/coralproject/talk/pull/3192, https://github.com/coralproject/talk/pull/3515).

**Expected behavior:**

Finnish language notification emails should show the organization name and an unsubscribe link in the email footer.

**Actual behavior:**

Finnish language notification emails are missing both the organization name and the unsubscribe link:
- Organization name is shown as "$organizationName"
- Unsubscribe link is just text, not a link that could be clicked

![email_footer](https://github.com/coralproject/talk/assets/1115979/9580fce2-a84a-4413-ba3c-f8d4d05b34be)

**Comment by kabeaty** [comment]
Hello, thanks for finding this. We welcome the PR that you mention you have ready to be submitted to fix this bug. Please do open it when you get a chance, and we'll get the changes into an upcoming release.

**Comment by losowsky** [comment]
Thanks - we'll take a look.

**Comment by losowsky** [comment]
Now merged so am closing the issue! Thanks for submitting a PR.
