### ISSUE TITLE
connect to a serverless MongoDB cluster.

### ISSUE THREAD

**Issue by georgeroumieh-pon** [coralproject/talk#4554]
**Expected behavior:**
Connected to serverless mongo cluster

**Actual behavior:**
Get an error 
```
 WrappedInternalError: INTERNAL_ERROR: Text record must only set `authSource` or `replicaSet`
    at /Users/george.roumieh@pon.com/code/javascript/ds-talk/server/src/core/server/config.ts:24:15
    at QueryReqWrap.callback (/Users/george.roumieh@pon.com/code/javascript/ds-talk/server/node_modules/.pnpm/mongodb-core@3.2.7/node_modules/mongodb-core/lib/uri_parser.js:98:18)
    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/callback_resolver:49:10)
```
**Related Issues:** 

**Versions:**

- NodeJS: v18.16.0
- NPM: v9.5.1
- MongoDB: v6.0.3

**Comment by losowsky** [comment]
Unfortunately, Serverless Mongo is not supported at this time. We also do not have any plans to support it in future.

We test for and support the following types of Mongo DB deployments as our database provider:

- The community Mongo docker container image with tag 4.2 (https://hub.docker.com/_/mongo)
- tag 5.0.6 also appears to be working, but that is not what we use in our dev environments
- Mongo Atlas (https://www.mongodb.com/atlas/database)
