### ISSUE TITLE
Commenting Username Bug

### ISSUE THREAD

**Issue by tylerfarrar** [coralproject/talk#4579]
![image0](https://github.com/coralproject/talk/assets/164028349/ea1d0bf5-fdfd-4a43-923e-ddac544547e1)
Our Customer is reporting that they are seeing the incorrect username when commenting. It says they are commenting under one username but the comment posts under a different users username. When moderating, the comment appears under the correct username.

**Comment by losowsky** [comment]
Hi Tyler, 

The usernames in your system are handled by your SSO. If it's serving the wrong name then your SSO is providing that to Coral via your JWT claim. Our docs about SSO integration are here: https://docs.coralproject.net/sso including how to update usernames via the claim.

Sorry we can't help any further than that! 

Best

Andrew
