### ISSUE TITLE
Can't able to render the coral thread in a modal if we have multiple action items on a page for opening modal.

### ISSUE THREAD

**Issue by SadhuSantosh** [coralproject/talk#4591]
We are trying to render a coral thread inside a modal which is working fine when we have one action button to open a modal having a commenting thread. But if we use the same button on the page multiple times, the thread is not loading when we click on those buttons and does not giving any error as such in the console. I am using React for the front end, and I am using the button as a component and adding it at multiple places on a page. But the thread is opening only on clicking one of the buttons but not for any other buttons.

**Expected behavior:** It should open the commenting thread every time and anytime when the user clicks on the buttons irrespective of how many times we've added a button on our page.

**Actual behavior:** The commenting thread is opening only for one button and not for any other button clicks on the page 

**Versions:** v7.5.0

**Comment by tessalt** [comment]
Without looking at the code it's hard to know what could be going wrong, but it is definitely possible to have coral running in a modal. What other implementations have done is create a single instance of coral either on page load or the first time a button is clicked, and then subsequent/different button clicks will simply show/hide the modal.
