### ISSUE TITLE
Perspective Filter Toxicity

### ISSUE THREAD

**Issue by CGBLR** [coralproject/talk#4594]
Can we set multiple filters from the Coral dashboard?
If yes, should they be comma and space separated like this -- TOXICITY, INSULT, PROFANITY, THREAT?
![image](https://github.com/coralproject/talk/assets/137059200/02dea752-5b7a-466e-ab0d-11c698c51a2a)

**Comment by losowsky** [comment]
Interesting. Would you set a different threshold for each filter? 

I will also note that the more models you send it to, the slower it would be to return a response before Coral can publish. We've already had occasional issues with some of their speed of response for a single model.

**Comment by CGBLR** [comment]
Ideally, yes for the threshold. But a single threshold for multiple attributes should also be fine.
I'm not sure if we could set multiple attributes from the coral dashboard. Could you please confirm?

**Comment by losowsky** [comment]
You can't currently, as we're concerned about the speed of response for multiple attributes. Can you detail what you're trying to solve for? The general Toxicity model includes all of their other filters afaik.
