### ISSUE TITLE
Comment Activity Email/Notification

### ISSUE THREAD

**Issue by CGBLR** [coralproject/talk#4597]
I don't get emails when a user replies to my comment. 
Is there a configuration I need to setup on my site for Comment Activity Notification?

**Comment by losowsky** [comment]
Hi there

Can you tell me what site you use, and if you're one of the people running the instance of Coral or are a commenter?

Thanks!

**Comment by losowsky** [comment]
I just realized you're the same person who messaged about the Perspective setup on their instance. If you go to Configure>Email, you'll find the email setup configuration.

**Comment by CGBLR** [comment]
Yes, I am the same person. I am logged in to the site as a commenter (cgsso1504).
Here's a sample url with a couple of user comments
https://deccanherald-training-web.quintype.io/india/delhi/supreme-court-to-hear-kejriwals-plea-challenging-arrest-after-april-29-2978604

I didn't get an email alert when user shivakumar.hm replied to cgsso1504.
When I send a Test Mail from the Coral Admin Dashboard it appears in my inbox.

**Comment by losowsky** [comment]
Have you tried different email addresses? It might be that your firewall is blocking it. (Also the latest version moves reply notifications out of email so this might be out of date)

**Comment by CGBLR** [comment]
I've tried it with users on multiple email domains - yopmail, hotmail and one more. 
We're using v 9.0.2 - Is that why we're not getting email notifications on replies?

**Comment by anibalpacheco** [comment]
Can you please @losowsky tell us where is the "reply notification" (this one you said that  was "moved")? I'm trying EVERITHING and also cannot get email notification work.

- email test works ok
- users involved commenter-replier are both generated by sso, both with email field set and emailverified field = true

lost many hours in this topic, read docs many times, gived up, taht's why i'm writting this

**Comment by anibalpacheco** [comment]
found the problem, doc interpretation, never imagine that both things would be not possible, and the "This" word in the doc I was interpreting that was referring to the previous sentence and not to the feature itself. 

![Image](https://github.com/user-attachments/assets/206870b8-e0f3-4730-be16-8d86dfe908cf)
