### ISSUE TITLE
Issue in SSO createCommentMutation v9.0.6

### ISSUE THREAD

**Issue by Shubhamsharma585** [coralproject/talk#4626]
**Expected behavior:**
1. After posting a comment it should post.
2. After switching off live updates graphql query should not trigger continously.

**Actual behavior:**
1. After posting a comment it is only momentary visible as blur
![issue1+2](https://github.com/coralproject/talk/assets/77038696/d0338fd6-903c-4570-a46d-c26ed07b00d2)
![issue1+2](https://github.com/coralproject/talk/assets/77038696/4c30fb57-4fe1-413e-8d74-56464a528c4c)
![Screenshot 2024-05-30 165506](https://github.com/coralproject/talk/assets/77038696/f62e7060-091c-4545-9f0a-d109644130de)
![Screenshot 2024-05-30 165519](https://github.com/coralproject/talk/assets/77038696/5aae5bfa-84fb-460c-b01c-a218984ca932)
 and api call is going in pending. I have used SSO for users other than admin and created accessToken.
2. After switching off live updates graphql query t triggering continously.

**Related Issues:** 

**Versions:** 

- NodeJS: 18.16.0
- PNPM: 8.14.3
- MongoDB: 4.2
- Redis: 3.2
- Browser: chrome
- OS: window 11

**Comment by losowsky** [comment]
Thanks, we'll take a look

**Comment by atsbob** [comment]
Yes this is happening to me as well. Only shows up if I switch to another tab and come back. V9.3.5.

**Comment by tessalt** [comment]
@atsbob could you let us know what versions of node, redis, and mongo you're using?

**Comment by atsbob** [comment]
@tessalt Coral: 9.5.3, MongoDB: 8.0.3 and Redis: 7.4.1. I'll also add that I'm not using SSO.

**Comment by tessalt** [comment]
@atsbob and you're running node > 18.16? Do you get any error messages in the network tab? And just to confirm, you're seeing comments going into the pending queue despite the fact that you do not have "pre-moderate" enabled in the configuration options for either the story or the tenant?

**Comment by atsbob** [comment]
> @atsbob and you're running node > 18.16? Do you get any error messages in the network tab? And just to confirm, you're seeing comments going into the pending queue despite the fact that you do not have "pre-moderate" enabled in the configuration options for either the story or the tenant?

Sorry, I should have mentioned my issue was related to point 2 alone with the Refresh button persistently popping up and graphql constantly pinging even when the live feature is turned off. Do you want me to bring it up as a separate issue instead? 

Also I'm on Node 18.20.4

**Comment by tessalt** [comment]
@atsbob thanks, we'll look into this
