### ISSUE TITLE
Notification for User remains after rejected comment gets approved afterwards

### ISSUE THREAD

**Issue by ihardyslide** [coralproject/talk#4632]
Hi,

I noticed following behaviour which I would consider as issue.
DSA features are enabled.

* User comment gets rejected
* User gets notification about rejection
* Same comment gets approved after internal moderation discussion
* Notification about rejection stays in notification-center of the user which authored the comment

**Expected behavior:**
Notification about rejection gets removed from User notification-center (Bell-Icon) as soon as rejected comment gets approved

**Actual behavior:**
Notification about rejection stays in User notification-center (Bell-Icon), even though the comment is not rejected anymore

**Related Issues:**
/

**Versions:**

- NodeJS: 18.20.3
- NPM: 8.0.0
- MongoDB: 4.2
- Redis: 3.2
- Browser: Chrome 125.0.6422.112
- OS: Debian 11

Thanks & BR

**Comment by losowsky** [comment]
Hi there

Thanks for the report. We chose not to implement this as you describe, because it can feel like gaslighting to the user - the rejection happened and they were notified about it, and then to hide/remove that notification can make them feel like you're hiding what they saw, or make them question if it did.

Hope that makes sense! 

Best

Andrew

**Comment by ihardyslide** [comment]
Hi,

thanks for the info!
We discussed your answer with our moderation team and they agreed.
But they also asked, if the user maybe should get another notification for this case, which says something like "Your rejected comment has now been republished after further consideration."

Would this make sense for you too?

Thx & Br

**Comment by ihardyslide** [comment]
Just bumping because I feel like this was overseen 😄 thx & br

**Comment by losowsky** [comment]
Thanks for the bump! Sorry I missed it. 

That's a good suggestion, I'll add it to our backlog to see if it can easily be added.
