### ISSUE TITLE
Can i post a comment on behalf of commentator (non-admin) with admin accessToken using coral api?

### ISSUE THREAD

**Issue by Shubhamsharma585** [coralproject/talk#4637]
## Search Terms
createComment, comment for non admin users

How i can use admin accessToken for making a comment on behalf of user (user id) in server to server call.  As https://docs.coralproject.net/api/mutations/create-comment is not allowing to make comment for non admin and for admin it is not allowing to provide specific user details.

**Comment by losowsky** [comment]
Hi there,

We don't allow this as it creates complicated legal liability issues around content, as well as an obvious vector for abuse. 

Best wishes

Andrew
