### ISSUE TITLE
Docker tags could be clearer

### ISSUE THREAD

**Issue by mattlinares** [coralproject/talk#4642]
**Expected behavior:**
Docker image tags communicate status of the image.

**Actual behavior:**
There is a `latest` tag on an old image, which makes me wonder if this is actually the recommended release.

https://hub.docker.com/layers/coralproject/talk/latest/images/sha256-b6a250e33ac85b7f91f6f7b80146106be88f867796bd899a277ed932140cf54d?context=explore

https://hub.docker.com/r/coralproject/talk/tags?page=3&page_size=&name=&ordering=

Common sense tells me that I should be deploying the [most recent image](https://hub.docker.com/r/coralproject/talk/tags?page=1&page_size=&name=&ordering=) but I take tags seriously too, so I'm seeking clarification.

**Versions:**

- NodeJS:
- NPM:
- MongoDB:
- Redis:
- Browser:
- OS:

**Comment by tessalt** [comment]
yeah something must be off in a script somewhere, the latest build is 9.0.8
