### ISSUE TITLE
MongoDB v6.0 support

### ISSUE THREAD

**Issue by rigperro** [coralproject/talk#4652]
Hey,

Looking at the package.json in the server folder, Coral is using the Node.js driver for Mongodb (mongodb) version 3.5.9. Looking at the compability matrix in https://www.mongodb.com/docs/drivers/node/current/compatibility/, it looks like at least a version of 3.6 is required for MongoDB v6.0.

MongoDB v5.0 is approaching End of Life in October 2024.

Any word on updating the driver?

Thanks!

**Comment by losowsky** [comment]
Hey, 

Thanks for asking! No firm date yet but we plan to update both Mongo and the driver before MongoDB 5.0 hits EOL. 

Cheers

Andrew
