### ISSUE TITLE
How to get Most commented list

### ISSUE THREAD

**Issue by vignesh-10940** [coralproject/talk#4658]
How to get most commented stories..?

**Comment by losowsky** [comment]
Hi there

Can you give a little more information about what you're trying to do? Some of the things you might be trying to do:

- pull a one-off list on the most commented stories ever / over a particular period on your site, for a report
- have your moderators see what is most commented today, to focus their attention
- show your readers what the most commented stories are, to direct readers to a destination
- something else! 

Each of these has very different answers. Thanks!

**Comment by vignesh-10940** [comment]
We have an idea to show most commented stories for past x days to display in our site.

**Comment by tessalt** [comment]
We have a JSONP endpoint available that will return the top most active stories over 24h 

https://{{ CORAL_DOMAIN }}/api/story/active.js?callback={{ CALLBACK_NAME }}&siteID={{ SITE_ID }}

CORAL_DOMAIN - domain name for the Coral instance
CALLBACK_NAME - name of the function on window (for example, if you have `window.activeStories = function() { /**/ }`, you would set it to `activeStories`)
SITE_ID - Coral Site ID for the site that you want a listing of the active stories on that site

**Comment by losowsky** [comment]
Just to add that this isn't customizable for X days, so if you want that feature, you're welcome to submit it as a contribution: https://github.com/coralproject/talk/blob/develop/CONTRIBUTING.md Thank you!
