### ISSUE TITLE
Can't fetch Comment count for URL in Kannada Language

### ISSUE THREAD

**Issue by nawazsuventure** [coralproject/talk#4662]
I have added whatever is required to fetch the comment count. But it is  **not** fetching the comment count properly for URLs in **Kannada** language.

Example of URL in kannada language:

https://prajavani-training-web.quintype.io/op-ed/olanota/ಕೋವಿಡ್-ಹೆಚ್ಚಳ-ನಾವು-ಜಾಗರೂಕರಾಗಿರಬೇಕು-ಭಯಪಡುವ-ಅಗತ್ಯವಿಲ್ಲ-ಮಾಂಡವೀಯ-2-1275643
![Screenshot 2024-09-11 at 12 15 16 PM](https://github.com/user-attachments/assets/cd11b623-612e-4bfd-a608-31cfb303360a)

Example of URL  English language (working fine):

https://prajavani-training-web.quintype.io/todays-news/test-photo-m14n2-231-1391213
![Screenshot 2024-09-11 at 12 15 37 PM](https://github.com/user-attachments/assets/cc717ff3-cc87-4a7c-bb44-695109d0cac7)
 
 
 Also, I have tried Encoding and Decoding the URL before passing.

**Comment by losowsky** [comment]
Thanks - we've added this to our backlog.

**Comment by losowsky** [comment]
Fixed in our latest version 9.4.0
