### ISSUE TITLE
fresh installation via docker works when accessing localhost:3000, redirects to /install on hosted domain. Docker instructions severely lacking

### ISSUE THREAD

**Issue by MrBryan** [coralproject/talk#4676]
<
**Expected behavior:**

Allow me to sign in to /admin etc  when visiting talk.thetyee.ca

**Actual behavior:**

goes to /install and says tenant already installed

![image](https://github.com/user-attachments/assets/e1ff1af2-b52a-4ecb-a695-fad41a80e429)

Here is the log from docker console:

`mongo-1  | 2024-10-02T20:21:40.846+0000 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongo-1  | 2024-10-02T20:21:40.850+0000 W  ASIO     [main] No TransportLayer configured during NetworkInterface startup
mongo-1  | 2024-10-02T20:21:40.850+0000 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=20f152cb4512
mongo-1  | 2024-10-02T20:21:40.850+0000 I  CONTROL  [initandlisten] db version v4.2.24
mongo-1  | 2024-10-02T20:21:40.850+0000 I  CONTROL  [initandlisten] git version: 5e4ec1d24431fcdd28b579a024c5c801b8cde4e2
mongo-1  | 2024-10-02T20:21:40.850+0000 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
mongo-1  | 2024-10-02T20:21:40.850+0000 I  CONTROL  [initandlisten] allocator: tcmalloc
mongo-1  | 2024-10-02T20:21:40.850+0000 I  CONTROL  [initandlisten] modules: none
mongo-1  | 2024-10-02T20:21:40.851+0000 I  CONTROL  [initandlisten] build environment:
mongo-1  | 2024-10-02T20:21:40.851+0000 I  CONTROL  [initandlisten]     distmod: ubuntu1804
mongo-1  | 2024-10-02T20:21:40.851+0000 I  CONTROL  [initandlisten]     distarch: x86_64
mongo-1  | 2024-10-02T20:21:40.851+0000 I  CONTROL  [initandlisten]     target_arch: x86_64
mongo-1  | 2024-10-02T20:21:40.851+0000 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" } }
mongo-1  | 2024-10-02T20:21:40.851+0000 I  STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongo-1  | 2024-10-02T20:21:40.851+0000 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7325M,cache_overflow=(file_max=0M),session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000,close_scan_interval=10,close_handle_minimum=250),statistics_log=(wait=0),verbose=[recovery_progress,checkpoint_progress],
mongo-1  | 2024-10-02T20:21:41.438+0000 I  STORAGE  [initandlisten] WiredTiger message [1727900501:438162][1:0x7fb46fc06b00], txn-recover: Recovering log 3 through 4
mongo-1  | 2024-10-02T20:21:41.502+0000 I  STORAGE  [initandlisten] WiredTiger message [1727900501:502206][1:0x7fb46fc06b00], txn-recover: Recovering log 4 through 4
mongo-1  | 2024-10-02T20:21:41.578+0000 I  STORAGE  [initandlisten] WiredTiger message [1727900501:578615][1:0x7fb46fc06b00], txn-recover: Main recovery loop: starting at 3/192640 to 4/256
mongo-1  | 2024-10-02T20:21:41.675+0000 I  STORAGE  [initandlisten] WiredTiger message [1727900501:675754][1:0x7fb46fc06b00], txn-recover: Recovering log 3 through 4
mongo-1  | 2024-10-02T20:21:41.733+0000 I  STORAGE  [initandlisten] WiredTiger message [1727900501:733355][1:0x7fb46fc06b00], txn-recover: Recovering log 4 through 4
mongo-1  | 2024-10-02T20:21:41.781+0000 I  STORAGE  [initandlisten] WiredTiger message [1727900501:781954][1:0x7fb46fc06b00], txn-recover: Set global recovery timestamp: (0, 0)
mongo-1  | 2024-10-02T20:21:41.797+0000 I  RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
mongo-1  | 2024-10-02T20:21:41.803+0000 I  STORAGE  [initandlisten] Timestamp monitor starting
mongo-1  | 2024-10-02T20:21:41.805+0000 I  CONTROL  [initandlisten] 
mongo-1  | 2024-10-02T20:21:41.805+0000 I  CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
mongo-1  | 2024-10-02T20:21:41.805+0000 I  CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
mongo-1  | 2024-10-02T20:21:41.805+0000 I  CONTROL  [initandlisten] 
mongo-1  | 2024-10-02T20:21:41.805+0000 I  CONTROL  [initandlisten] 
mongo-1  | 2024-10-02T20:21:41.806+0000 I  CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
mongo-1  | 2024-10-02T20:21:41.806+0000 I  CONTROL  [initandlisten] **        We suggest setting it to 'never'
mongo-1  | 2024-10-02T20:21:41.806+0000 I  CONTROL  [initandlisten] 
mongo-1  | 2024-10-02T20:21:41.845+0000 I  STORAGE  [initandlisten] Flow Control is enabled on this deployment.
mongo-1  | 2024-10-02T20:21:41.846+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo-1  | 2024-10-02T20:21:41.858+0000 I  NETWORK  [listener] Listening on /tmp/mongodb-27017.sock
mongo-1  | 2024-10-02T20:21:41.858+0000 I  NETWORK  [listener] Listening on 0.0.0.0
mongo-1  | 2024-10-02T20:21:41.858+0000 I  NETWORK  [listener] waiting for connections on port 27017
talk-1   | (node:1) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
talk-1   | (Use `node --trace-deprecation ...` to show where the warning was created)
mongo-1  | 2024-10-02T20:21:45.559+0000 I  NETWORK  [listener] connection accepted from 172.18.0.4:57304 #1 (1 connection now open)
mongo-1  | 2024-10-02T20:21:45.562+0000 I  NETWORK  [conn1] received client metadata from 172.18.0.4:57304 conn1: { driver: { name: "nodejs", version: "3.5.9" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.15.0-205.149.5.1.el8uek.x86_64" }, platform: "'Node.js v14.21.3, LE (legacy)" }
talk-1   | {"name":"coral","hostname":"2c0623834af3","pid":1,"level":30,"msg":"mongodb has connected","time":"2024-10-02T20:21:45.565Z","src":{"file":"/usr/src/app/src/core/server/services/mongodb/index.ts","line":41,"func":"createMongoDB"},"v":0}
talk-1   | {"name":"coral","hostname":"2c0623834af3","pid":1,"level":30,"queries":208,"msg":"loaded persisted queries","time":"2024-10-02T20:21:45.633Z","src":{"file":"/usr/src/app/src/core/server/graph/persisted/loader.ts","line":64,"func":"loadPersistedQueries"},"v":0}
talk-1   | {"name":"coral","hostname":"2c0623834af3","pid":1,"level":30,"listenerName":"analytics","msg":"listener was disabled","time":"2024-10-02T20:21:45.653Z","src":{"file":"/usr/src/app/src/core/server/events/publisher.ts","line":118,"func":"register"},"v":0}
talk-1   | (node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 error listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit
talk-1   | {"name":"coral","hostname":"2c0623834af3","pid":1,"level":30,"currentMigrationID":1582929716101,"msg":"there was no pending migrations to run","time":"2024-10-02T20:21:45.683Z","src":{"file":"/usr/src/app/src/core/server/services/migrate/manager.ts","line":169,"func":"executePendingMigrations"},"v":0}
talk-1   | {"name":"coral","hostname":"2c0623834af3","pid":1,"level":30,"msg":"job processing is enabled, starting job processors","time":"2024-10-02T20:21:45.729Z","src":{"file":"/usr/src/app/src/core/server/index.ts","line":307,"func":"process"},"v":0}
talk-1   | {"name":"coral","hostname":"2c0623834af3","pid":1,"level":30,"msg":"not adding authentication to metrics endpoint, credentials not provided","time":"2024-10-02T20:21:45.749Z","src":{"file":"/usr/src/app/src/core/server/app/index.ts","line":286,"func":"createMetricsServer"},"v":0}
talk-1   | (node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 12 error listeners added to [Redis]. Use emitter.setMaxListeners() to increase limit
talk-1   | {"name":"coral","hostname":"2c0623834af3","pid":1,"level":30,"port":9000,"path":"/metrics","msg":"now listening for metrics","time":"2024-10-02T20:21:45.754Z","src":{"file":"/usr/src/app/src/core/server/index.ts","line":334,"func":"process"},"v":0}
talk-1   | {"name":"coral","hostname":"2c0623834af3","pid":1,"env":"production","forceSSL":false,"level":40,"msg":"FORCE_SSL=true should be set when a SSL terminating proxy has been configured","time":"2024-10-02T20:21:45.757Z","src":{"file":"/usr/src/app/src/core/server/app/index.ts","line":240,"func":"configureApplicationHTTPS"},"v":0}
talk-1   | {"name":"coral","hostname":"2c0623834af3","pid":1,"level":30,"port":5000,"msg":"now listening","time":"2024-10-02T20:21:45.945Z","src":{"file":"/usr/src/app/src/core/server/index.ts","line":394,"func":"start"},"v":0}
talk-1   | failed to set logging project id Error: Unable to detect a Project Id in the current environment. 
talk-1   | To learn more about authentication and Google APIs, visit: 
talk-1   | https://cloud.google.com/docs/authentication/getting-started
talk-1   | {"name":"coral","hostname":"2c0623834af3","pid":1,"context":"http","contextID":"2774e1a0-80fc-11ef-b15f-cdb96959c93e","level":50,"url":"/api/install","method":"GET","statusCode":400,"host":"talk.thetyee.ca","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36","ip":"::ffff:172.18.0.1","err":{"message":"TENANT_INSTALLED_ALREADY","name":"TenantInstalledAlreadyError","stack":"src/core/server/app/handlers/api/install.ts:84:19\n","id":"277556d0-80fc-11ef-b15f-cdb96959c93e","context":{"pub":{},"pvt":{}}},"msg":"http error","time":"2024-10-02T20:23:15.399Z","src":{"file":"/usr/src/app/src/core/server/app/middleware/error.ts","line":80,"func":"wrapAndReport"},"v":0}
`

**Related Issues:** 

**Versions:**

USING DOCKER IMAGE, latest!

- NodeJS:
- NPM:
- MongoDB:
- Redis:
- Browser:
- OS:  Oracle 8

**Comment by MrBryan** [comment]
please note I have already completed the configuration and install via localhost, where it is still working
![image](https://github.com/user-attachments/assets/5196c340-684b-4fe7-91f8-ced86f70c7fc)

**Comment by MrBryan** [comment]
docker-compose.yml file:  
![image](https://github.com/user-attachments/assets/70d4c9da-774a-470e-9ac0-c2f4bed63022)

**Comment by MrBryan** [comment]
also - the instructions say to do "docker-compose up", when I needed to do 'docker compose up'

I suspect the host name has to be changed from localhost somewhere but there are really no instructions anywhere for where to set this and other environment variables from docker.  The site documentation says the Docker setup is the preferred way to use Talk, but it has almost no documentation 


![image](https://github.com/user-attachments/assets/af3a934e-7b3c-4291-9bb9-a8bcba7143a7)

**Comment by MrBryan** [comment]
All of the 'redirect url' settings in the admin interface, which can only be accessed from localhost, say localhost:3000 where they should hopefully say talk.thetyee.ca ... but again: there are no instructions for setting config variables when installing / using via Docker 

![image](https://github.com/user-attachments/assets/694a3947-7d23-41e1-a884-e52e6e821d6e)

**Comment by MrBryan** [comment]
bump... anybody alive here?

**Comment by MrBryan** [comment]
@kabeaty ??

**Comment by losowsky** [comment]
Sorry to see you're having issues. We haven't received any other reports by people having trouble installing, so we don't think it's a common issue. We will take a look when we can.

**Comment by MrBryan** [comment]
Thanks for getting back to me. If there’s a write up on any configuration options for the docker edition, that would be very helpful.

**Comment by losowsky** [comment]
Did you refer to our docs? https://docs.coralproject.net/

**Comment by losowsky** [comment]
Just checking in to see if our docs helped, I'll close this issue if I don't hear back shortly. Thanks!

**Comment by MrBryan** [comment]
Hi there, yes, I followed the directions,

I referenced them above in fact when I pointed out what I think was a typo in them : “docker-compose up” which fails. 

“docker compose up” does work as a command ( no hyphen which config file happens to have i think).

(but it fails later for the other reasons mentioned/dumped  in the output above )

**Comment by MrBryan** [comment]
But none of the docs for docker edition that I could find   say anything about options beyond what’s in the default /example  config file

**Comment by MrBryan** [comment]
There are options for older versions of source code versions for the .env file . Should we assume that those can be used in the docker config if formatted that way? Or that environment variables are passed another way into the docker env?

**Comment by tessalt** [comment]
Hi there, it does look like your dockerfile is based on an older version of coral, the `TALK` variables are all deprecated. You would want to base your deployment on the current docs https://docs.coralproject.net/#docker. The docker instructions are not extensive as we do not currently have the resources to dedicate to them, the documents we have are intended for an audience that is familiar with deploying node apps to cloud providers. Sorry we can't be of more help!

**Comment by MrBryan** [comment]
> the `TALK` variables are all deprecated

that was me attempting to override the assumption that we were running from 127.0.0.1 / localhost by any means I could find,  so I mashed those old variables into the example file as a last ditch

>the documents we have are intended for an audience that is familiar with deploying node apps to cloud providers

hmm OK i'll try to find out more about generic variables... I assumed even an advanced user of node would still need to know what the variables particular to this package need to be

**Comment by losowsky** [comment]
I'm sorry we can't help more. @immber used to be on our team and now helps people with commenting installs as a consultant. She might be able to assist.

**Comment by MrBryan** [comment]
thanks @losowsky ... @immber I can't see a way of reaching you but feel free to reach me if you can/ have a moment... bcarney at  thetyee dot ca

**Comment by immber** [comment]
This is occurring because you are trying to use the same Mongo database for both local development and a production deployment on your subdomain. Once the /install has been completed you can not change the value the installed root url easily. As @tessalt mentioned, env vars are no longer how this is stored and updated, the value was stored in mongo when you completed the installation wizard. 

You need a new database and fresh installation of the application for your production domain that is separate from the one where it has been installed on localhost:3000. If you wipe out your mongo db where you installed it on `localhost:3000` or point your production deployment to a fresh mongo database, it will allow you to install it again. You will also need to redo any settings changes you made in the /admin.

**Comment by MrBryan** [comment]
Just wanted to say that fresh databse worked as @immber suggested.
