### ISSUE TITLE
Multi-Tenancy Management

### ISSUE THREAD

**Issue by bastiankistner** [coralproject/talk#4687]
Hi there,

we're currently evaluating Coral for multiple tenants. We've been running a single instance for www.br.de/nachrichten for several years now. We've been asked to add further tenants, which seems to be supported as mentioned in the documentation and in several closed issues. 

So far, your statement was that it's supported but it's not yet implemented to create multiple tenants through a wizard / UI / mutation. 

I just ran a test and have manually cloned a tenant and an initial user with modified IDs, which works well. But is this currently really the only way? Is there anything planned? Or would you be open for a pull request that at least adds a mutation to create further tenants? Otherwise I'd probably implement a custom endpoint that would add the necessary documents to mongodb manually.

I'd highly appreciate any feedback!

Thanks a lot!

## Search Terms

- tenant
- multi tenancy

## Suggestion

- GraphQL mutation(s)
- Dashboard to manage tenants

## Use Cases

Easily create multiple tenants within a single coral instance.

**Comment by tessalt** [comment]
Hi there, we actually do have an API for creating new tenants but it isn't currently documented, I'll try to summarize. The easiest way is to just use the installation wizard like you did for the first tenant: 

1. you need to create a [management signing secret](https://github.com/coralproject/talk/blob/8094b3e0139e5eb790299d5f6a8d92a23ee96097/server/src/core/server/config.ts#L215) and add it to the environment. This is a secret key that will be used to sign a token using HS256
2. generate and sign a jwt with the following properties: 

```
{
   sub: [the domain of the new tenant],
    aud: "installation",
    iat: Date.now(),
    exp: [some expiration date],
}
```
3. route your new tenant's domain to your running coral instance following the steps you used to set up your first tenant 
4. visit `[new tenant domain]/install#accessToken=[your signed jwt]` and follow the installation wizard steps 

You can also do this entirely via API but it's easier with the wizard. You can make a POST request to `[new tenant domain]/api/install` including the body specified [here](https://github.com/coralproject/talk/blob/develop/server/src/core/server/app/handlers/api/install.ts#L102)

**Comment by sofiadipace** [comment]
Hi @tessalt, kann man auch tenants wieder löschen?
