### ISSUE TITLE
CORS issue for email verification requests, and wss:// pointing to internal Docker IP instead of my site URL

### ISSUE THREAD

**Issue by lyonlim** [coralproject/talk#4692]
I installed Coral Talk 9.5.2 using a Docker Compose setup per the recommended method. I also used Reproxy.

I was able to go through the setup process, and had Talk running well on my Jekyll site. However, I noticed two issues.

1. When users register with their email, they wouldn’t get a verification email. The test send email function worked. I checked the network logs, and discovered the /api/../confirm response could not go through due to a CORS issue. Other requests including to the graphql would work just fine and I noticed they have the necessary Access Control Allow Origin etc Headers as well. How do I resolve the issue for this email verification function?

2. The second issue is wss:// requests do not point to my site url, but instead to an internal docker IP. I can’t figure out a way to tell it to use the right site domain.

Can anyone point me in the right direction please?

**Comment by tessalt** [comment]
Hi there, unfortunately I'm not familiar with reproxy but I would assume both issues are related to URLs not being correctly proxied or mapped. The docker-compose file in the documentation is just an example, and will have to be customized to your deployment. Sorry we can't be of more help.
