### ISSUE TITLE
Embed link does not execute js

### ISSUE THREAD

**Issue by jde** [coralproject/talk#47]
When I copy an embed tag from here:

```https://talk-stg.coralproject.net/admin/configure```

And hit it with my browser, the js is shown in the iframe. 

Embed Block:
```
<div id='coralStreamEmbed'></div><script type='text/javascript' src='https://pym.nprapps.org/pym.v1.min.js'></script><script>var pymParent = new pym.Parent('coralStreamEmbed', 'https://talk-stg.coralproject.net/client/embed/stream/bundle.js', {title: 'comments'});</script>
```

This is what I see:

![unspecified-1](https://cloud.githubusercontent.com/assets/259957/20156194/4db3641e-a69d-11e6-98c3-fa75da92a62c.png)

**Comment by jde** [comment]
This may have been caused by shifts in the way we're building/serving the files. If this is the case, let's meet as a team and make a final decision on how we are going to build/serve embeds.

**Comment by davidgljay** [comment]
@wyattjoh I'm following your vision here, it seems like having an index.html causes problems, which is how we were handling this before. How would you like embeds to be handled?

**Comment by davidgljay** [comment]
Is this resolved?

**Comment by jde** [comment]
Resolved.  Sorry for the late close!
