### ISSUE TITLE
DSA-notifications are missing with disabled In-page notifications

### ISSUE THREAD

**Issue by flecki89** [coralproject/talk#4706]
We have users who want to receive comment updates via mail, so we disabled In-page notifications. This will, however, also remove the 🔔-tab which contains notifications about DSA decisions.

We are Europe-based with enabled DSA features and the notifications are legally required.

**Expected behavior:**
Users can see DSA-notifications with In-page notifications turned off.

**Actual behavior:**
Notifications-tab is gone and therefore users have no way to see DSA-notifications

**Related Issues:** 
https://github.com/coralproject/talk/issues/4654

**Versions:**
9.5.3

- NodeJS: 18.20.5
- NPM: 10.8.2
- MongoDB: 7.0.6
- Redis: 
- Browser:
- OS:

**Comment by losowsky** [comment]
Hi there,

We built the notifications feature specifically for European newsrooms to be DSA-compliant. I'm afraid that if you are disabling that feature, then Coral cannot then provide the notifications. If you want the feature to work in some other way, you'll have to fork the code to build your own solution.
