### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by iliakan** [coralproject/talk#4710]
Hi!

I'm thinking to use this system on https://javascript.info and contribute some features... I see some commits, but I also see many issues hanging for years without response.

It makes one wonder if there's someone to review PR's ;)

**Comment by losowsky** [comment]
Absolutely - you'll see that there continual releases, there are only two open PRs (and they are from our infra team, for work that was started and not yet completed) and the only issues open are either ones we can't replicate or feature suggestions. Very much a living project!
