### ISSUE TITLE
Provide enable: (true|false) switch for all plugins

### ISSUE THREAD

**Issue by StephanieDClark** [coralproject/talk#595]
The request is to include a config property named "enable" for all plugins.  This can be passed in through the plugin.config

### Expected behavior
If enabled === true, then the plugin renders as normal.  If enabled === false,then the plugin does nothing.

**Comment by kgardnr** [comment]
Hey @StephanieDClark, we will look at this enhancement in the future. Currently, the mode to turn plugins on or off is to use the plugins.json file. Let me know if that works for you in the interim.

**Comment by StephanieDClark** [comment]
Well, the issue with turning plugins on/off in the plugins.json file is that this requires rebuild/redeployment.  Ideally, we would like to not even have the plugin run if it is not enabled.   

E.g., most pages don't have off-topic, so it doesn't need to even run.

However, for the time being, we will just include a switch in the plugin config.

**Comment by kgardnr** [comment]
OK, great!

**Comment by kgardnr** [comment]
@StephanieDClark I'm going to close this for now and we will look at addressing this in more advanced ways in the future.
