### ISSUE TITLE
Provide Slot below CommentBox, above stream

### ISSUE THREAD

**Issue by StephanieDClark** [coralproject/talk#606]
### Expected behavior
This Slot would be available at the very top of the stream, above the NewCount div.  

This would allow us to add a filter for Off-topic comments, in addition to other design elements, as discussed by @IAmSamHankins and @egrdina .

This slot would generally have filter tabs in it, but could have anything.

**Comment by kgardnr** [comment]
This is resolved in https://github.com/coralproject/talk/pull/654.
