### ISSUE TITLE
Getting: Invalid csrf token

### ISSUE THREAD

**Issue by Charlie73** [coralproject/talk#620]
I'm running talk via an nginx proxy using letsencrypt for HTTPS

The admin site is loading fine over https but all POST requests are meet with the error 'Invalid csrf token'

I figure it is most likely an issue with something being missed out or mangled by the proxy. My nginx location config looks like this:-

        location / {
            proxy_set_header            Host    $host;
            proxy_set_header            X-Real-IP       $remote_addr;
            proxy_set_header            X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass_header           Set-Cookie;
            proxy_pass http://localhost:5000;
            proxy_pass_request_headers on;
        }

What do you guys use for serving up the app with HTTPS in production?

**Comment by kgardnr** [comment]
Hey @Charlie73, thanks for reporting this! What version of Talk are you seeing this with?

**Comment by kgardnr** [comment]
Also can you send us the URL you are using for production?

**Comment by Charlie73** [comment]
Hi @kgardnr I'm using the docker installation method and the docker-compose.yml example from the install page, so it looks like it's using coralproject/talk:1.5

My production url is https://surnamedb.ugcserver.org I'm planning on using talk to replace the comments on http://www.surnamedb.com

Ahhh ha...

Just updated to 1.7 and it's all working now. I should have checked that sorry!

**Comment by kgardnr** [comment]
No worries at all! Would love to hear your feedback as you start using Talk, @Charlie73! Thanks for your interest and support :)

Kim & The Coral Team
