### ISSUE TITLE
Comment Importing

### ISSUE THREAD

**Issue by Charlie73** [coralproject/talk#625]
Are there currently any guidelines or suggestions on the best way to import existing comments into Talk?

**Comment by gabelula** [comment]
Hi @Charlie73 !

We have been working on an import tool (https://github.com/coralproject/talk/tree/import-data/bin) that you can find in the import-data branch. It translated data from a mongodb db to Talk based on a mapping file. So far we do not have any guidelines. 

What is your source comments database?

**Comment by Charlie73** [comment]
Thanks @gabelula 

My comments are stored in a ReThinkDB database, so it's probably going to be a custom migration job. But I think I'm going to just insert them into the database directly and see how that goes... Unless there is an API endpoint that handles the insertion of old comments?

Also where is the best place to chat with you guys about this stuff?

**Comment by gabelula** [comment]
Awesome!

There is an API to insert comments (and users and actions).
https://coralproject.github.io/talk/faq.html#where-are-your-http-api-docs

You can join Slack and talk with us there: https://coralprojectslackin.herokuapp.com/

**Comment by Charlie73** [comment]
Thanks :-)

I have tried to join the slack community but I'm getting 'ura_limit_reached' .

**Comment by jtnelson** [comment]
@Charlie73 you should be able to join the slack community now, let me know if you're still having trouble

**Comment by kgardnr** [comment]
Closing this issue, @Charlie73 let us know if you have additional questions!
