### ISSUE TITLE
Broken/incomplete link on docs

### ISSUE THREAD

**Issue by losowsky** [coralproject/talk#633]
The link here goes nowhere:

https://coralproject.github.io/talk/client-architecture.html#test 

(https://coralproject.github.io/tools.html)

**Comment by Goyapa** [comment]
This issue seems to be fixed!?

If I got to 
https://coralproject.github.io/talk/client-architecture.html#test
and click tools
it now goes to 
https://coralproject.github.io/talk/tools.html
which is better than
https://coralproject.github.io/tools.html

@jde this Issue could be closed
