### ISSUE TITLE
API errors with 1.8

### ISSUE THREAD

**Issue by Charlie73** [coralproject/talk#659]
### Expected behavior
Running the GraphQL query in 1.7 produced the expected results -
```
{
  comments(query: {statuses:[NONE]}) {
    id,
    parent {id},
    user {username, status},
    body,
    status,
    asset {url},
    created_at
  }
}
```

### Actual behavior

But in 1.8 it now produces -

```
{
  "errors": [
    {
      "message": "Cannot query field \"id\" on type \"CommentConnection\".",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    },
...
```

### Steps to reproduce behavior

Just switching between versions in docker

**Comment by jde** [comment]
Hey @Charlie73,

Between 1.7 and 1.8 we cleaned up a lot of issues surrounding how comments were queried and returned. We went from a flat query/response to a more formal CommentQuery / CommentConnection pattern.

You can see the new definition for `comments(query: CommentsQuery!): CommentConnection` here: https://github.com/coralproject/talk/blob/master/graph/typeDefs.graphql#L595 or in the GraphiQL docs.

Thanks for reporting the issue. We have been working hard to communicate breaking changes such as these and very much value questions such as these!

Best,
David
