### ISSUE TITLE
Upgrade path when using Docker containers

### ISSUE THREAD

**Issue by davisshaver** [coralproject/talk#701]
### Expected behavior
Here's the post I wrote last time I updated. https://davisshaver.com/2017/05/17/setting-up-the-coral-projects-talk-product-on-aws/

<details>

```
docker run --rm -p 5000:5000 \
-e TALK_INSTALL_LOCK=true \
-e TALK_JWT_SECRET=LOVETOCOMMENT \
-e TALK_MONGO_URL=mongodb://mongo/talk \
-e TALK_REDIS_URL=redis://redis \
-e TALK_ROOT_URL=https://talk.notphilly.com \
-e TALK_FACEBOOK_APP_ID=5554432162346234 \
-e TALK_FACEBOOK_APP_SECRET=ZUCKISCOOL \
--link talk-redis:redis \
--link talk-mongo:mongo \
coralproject/talk:latest
```

</details>

### Actual behavior
This time I got an error that I needed to run a database migration first.

```
Error: A database migration is required, version required 1496771633, found null. Please run `./bin/cli migration run`
    at Function.verify (/usr/src/app/services/migration.js:171:13)
    at process._tickCallback (internal/process/next_tick.js:109:7)
error Command failed with exit code 1.
```

### Steps to reproduce behavior
See blog post, I am not sure what HEAD had been on my server before I pulled today though :/.

Maybe something like `TALK_AUTO_UPDATE ` could be passed in the docker command?

**Comment by davisshaver** [comment]
Looking into this some more.

I was able to start the upgrade process with the following:

```
docker run --rm -p 5000:5000 \
-e TALK_INSTALL_LOCK=false \
-e TALK_JWT_SECRET=LOVETOCOMMENT \
-e TALK_MONGO_URL=mongodb://mongo/talk \
-e TALK_REDIS_URL=redis://redis \
-e TALK_ROOT_URL=https://talk.notphilly.com \
-e TALK_FACEBOOK_APP_ID=5554432162346234 \
-e TALK_FACEBOOK_APP_SECRET=ZUCKISCOOL \
--link talk-redis:redis \
--link talk-mongo:mongo \
--entrypoint=/bin/bash \
coralproject/talk:latest \
-c "./bin/cli migration run"
```

Seems to be processing now, will confirm soon...

**Comment by davisshaver** [comment]
Ok after staring at the terminal for 10 mins, fixed the command to include `-it` for interactive terminal.

```
docker run -it --rm -p 5000:5000 \
-e TALK_INSTALL_LOCK=false \
-e TALK_JWT_SECRET=LOVETOCOMMENT \
-e TALK_MONGO_URL=mongodb://mongo/talk \
-e TALK_REDIS_URL=redis://redis \
-e TALK_ROOT_URL=https://talk.notphilly.com \
-e TALK_FACEBOOK_APP_ID=5554432162346234 \
-e TALK_FACEBOOK_APP_SECRET=ZUCKISCOOL \
--link talk-redis:redis \
--link talk-mongo:mongo \
--entrypoint=/bin/bash \
coralproject/talk:latest \
-c "./bin/cli migration run"
```

**Comment by davisshaver** [comment]
Closed the issue as the above command results in upgrade! 👍

**Comment by kgardnr** [comment]
Oh awesome, thanks for updating here @davisshaver!

**Comment by wyattjoh** [comment]
It was by design that the update/migration was not done automatically. Some customers may have very large datasets and we didn't want to start something without warning the user that they need to backup their data first.

**Comment by pascalandy** [comment]
Hey folks!

I consider myself solid with Docker and I can't find any docs about how to start this project via Docker. 
It looks the perfect candidate for a docker stack :-P

What am I missing?

**Comment by kgardnr** [comment]
Hey @pascalandy, if you check the main docs here: https://coralproject.github.io/talk/index.html and go to Installation>Docker that should get you started. Let us know if you have recommendations on improvements, etc, or feel free to submit a PR if you'd like!

**Comment by pascalandy** [comment]
Ahh! There you go :)
There is no reference to this anywhere. Maybe add this in the readme :)

Many folks a looking for a quick win via a simple Docker run. 
Cheers!

**Comment by kgardnr** [comment]
Ah, it's linked under Documentation, I'll see if I can bold it or make it stand out more - thank you for the feedback!

**Comment by pascalandy** [comment]
I went in the docs, but could not find anything related to docker. You're welcome!

**Comment by pascalandy** [comment]
Just tried the docker-compose and docker run using port 5000 and 5001 but there is nothing to see. Still don't know how to try this puppy. 

Would make sense to have a repo only for the docker stack. See how I did it for Traefik and 3 webapps - https://github.com/pascalandy/docker-stack-this/tree/master/traefik-manager

**Comment by wyattjoh** [comment]
Have you checked out https://coralproject.github.io/talk/docs/install/docker/ @pascalandy?

**Comment by pascalandy** [comment]
Yes I did and as I'm saying, I can't make the docker-compose or docker run works.
What is supposed to happen once the docker-compose is up ?

> Just tried the docker-compose and docker run using port 5000 and 5001 but there is nothing to see.
