### ISSUE TITLE
Create new "Set up talk developer environment" section under Development Docs

### ISSUE THREAD

**Issue by Goyapa** [coralproject/talk#712]
A slightly edited version of the copy from the Discussion at Slack as entry point:

Hello, @jeff we talked about integrating my writings on medium to the Talk docs.
https://medium.com/@MichMach/contribution-to-oss-2a24447770c9

I asked myself how, which content and where to integrate. 
I started writing at Medium about Talk because I could only find rare information specific to developers and had to search in different places. I would welcome to find something like "Set up talk developer environment" under "Development" right here: 
https://coralproject.github.io/talk/faq.html

The actual path over "Contributing to Talk" is a little misleading and a bit confusing in my opinion. "Contributing to Talk"->"See our Contribution Guide!"->"set up a dev environment"->scroll down "Installation From Source" etc. Sometimes I knew that there was a resource that I needed but can`t remember where to find it! In my opinion, there should be two clear ways to the 
https://coralproject.github.io/talk/index.html
one directly from 
https://github.com/coralproject/talk
and the second from
https://coralproject.net/products/talk.html.
There are very different needs for talk developers and users.

By the way, my writings on Medium are only a draft and need a cleanup and maybe a review and discussion. I would love to enhance and integrate it and improve the general docs. Thanks Michael

jeff
@micmac yes that would be an awesome contribution to make to Talk

**Comment by Goyapa** [comment]
@jtnelson 
Ok, I'll transform my medium post into a pull-request for discussion and review.

**Comment by wyattjoh** [comment]
Few notes on the article.

- We strongly recommend anyone developing Talk use Docker for their databases during development. This ensures that all databases used by all developers are the exact same version, and are isolated from existing datasets that they may have on their computer. This goes for Redis + Mongo as well.
- The environment file is a defined pattern used by anyone who has ever used Heroku before, so it's format should be straightforward, as we also don't use the https://www.npmjs.com/package/node-env-file package

Additionally, beyond setting up the databases and following out installation guide, having a setup guide for each required subsystem, from my opinion, would be out of scope for our own documentation.

**Comment by Goyapa** [comment]
Thank you @wyattjoh for your notes and quick response!

Now that I am reading the docs with your notes in mind it makes much more sense to me.

Maybe this is what took me away from using Docker!?
https://github.com/coralproject/talk/blob/master/INSTALL.md

by the way, this page I found much later.
https://coralproject.github.io/talk/install-docker.html

"We currently support packaging the Talk application via Docker, which automates the dependency install and asset build process. This is the recommended way to deploy the application when used in production."
The first sentence was fine to me and made much sense, but the second hold me from using Docker for a development setup up. 

and in a combination with this
"Installation From Source
This provides information on how to setup the application from source. Note that this is not recommended for production deploys, but will work for development and testing purposes."

I was sure that the development and deployment setup is very different. 

But now I'm sure this could result in a much better development workflow!
Why only using Docker for Redis and MongoDB when the whole development workflow could be with Docker?
@wyattjoh do you have a copy of the Talk Dockerfile?
As I can see there is none in the repository, but maybe I am wrong?

It would be nice to git clone Talk and run Docker and start developing!
Actually, I am figuring out how this could work and let it reflect into the documentation. 
But if you already have a solution then please tell me.

**Comment by wyattjoh** [comment]
Our development environment:

- Docker for Mongo + Redis
- Source for running Talk

This is because Talk already has version management via `yarn.lock`. The Docker file for Talk is removes all the development dependancies, which is why we recommend it for production only.

We are currently in the process of refining the documentation around this process now, and would love to know of any pain points you experience during that process so we can simply + improve them.

**Comment by Goyapa** [comment]
@wyattjoh 
Update: I cleaned up my Medium post
https://medium.com/@MichMach/contribution-to-oss-2a24447770c9
and I am figuring out how to integrate(improve) into existing docs and where are missing links.
https://coralproject.github.io/talk/faq.html (which by the way are already in a good shape)
 
Actually, I ask myself where to integrate my content without messing talk users up with developer content and without too much duplication.
But if duplication is not a big issue, I could copy some existing content and edit them developer specific without worrying about talk users. e.g. ".env" file depending.
Did you have thought about, have any idea or reasons where and how to improve?
Any feedback is very welcome!

I will edit the docs and send a pull-request for further discussions.

**Comment by kgardnr** [comment]
The Core Team will take this on and pull the best pieces that are most useful for our clients, users, and contributors.

Thank you again, @Goyapa!
