### ISSUE TITLE
Enable facebook login for https://talk-stg.coralproject.net

### ISSUE THREAD

**Issue by jde** [coralproject/talk#76]
### Expected behavior

We should be able to login via Facebook from our staging server.

### Actual behavior

![screen shot 2016-11-18 at 11 27 00 am](https://cloud.githubusercontent.com/assets/259957/20437443/f6fa2450-ad81-11e6-8561-c3de782965f5.png)

### Steps to reproduce behavior

Go to https://talk-stg.coralproject.net/
Click Sign In
Click Facebook
Error shows in popup

**Comment by campaignupgrade** [comment]
For anyone else frustrated by this issue, you can find the callback URL in the URL of the error message. 

It will be in the format of `https://your.domain.name/api/v1/auth/facebook/callback`
