### ISSUE TITLE
User IDs included in URLs need to be URI component encoded

### ISSUE THREAD

**Issue by offensivepolitics** [coralproject/talk#789]
### Expected behavior
The admin panel (at the very least) uses the UserID in a URL to ban a community member, but if the userId contains non url safe characters (like forward slash) then the action fails and returns a 404. Given a user ID of "1234/56768" I expect the URL to look like this:
`https://coral-talk/api/v1/users/1234%2F5678/status`
### Actual behavior
Given a user ID of "1234/56768" the admin attempts to use this URL:
`https://coral-talk/api/v1/users/1234/5678/status`

### Steps to reproduce behavior

1. Create a user using the command line
2. Update the user ID to include a forward slash somewhere in the middle, via Mongo
3. Find the user in the admin and ban them, which should produce a 404

We're running into this because we authorize users with an external system via a plugin with  `tokenUserNotFound`, so we use our existing (non URL safe ID) as the talk user ID.

**Comment by kgardnr** [comment]
Thank you for raising this @offensivepolitics! We will review this and get back to you.

**Comment by wyattjoh** [comment]
This should hopefully be resolved once we migrate that rest api to the graph..

**Comment by offensivepolitics** [comment]
Is there a general timeline for that migration @wyattjoh?

**Comment by kgardnr** [comment]
Hey @offensivepolitics! Looking at our roadmap we probably shouldn't count on having this done prior to the August launch unless Greg wants to deprioritize something else.

**Comment by kgardnr** [comment]
Hey @offensivepolitics this is fixed as of 4.0.0!
