### ISSUE TITLE
Another upgrade issue, redis unavailable & possibly not using config

### ISSUE THREAD

**Issue by davisshaver** [coralproject/talk#809]
### Expected behavior
After stopping the Talk container, pulling the new Talk image, and running the Talk container again with the same command as had been previously used should result in the app running again (unless a migration is required).

### Actual behavior
After pulling the new image, with no other changes, get a Redis connection failure error.

<img width="566" alt="screen shot 2017-07-27 at 10 30 19 am" src="https://user-images.githubusercontent.com/1636964/28675717-a82d8506-72b6-11e7-8eb5-503e9184eaf5.png">

### Steps to reproduce behavior
Most of [my notes are here](https://davisshaver.com/2017/05/17/setting-up-the-coral-projects-talk-product-on-aws/) on how I set up the environment

**Comment by davisshaver** [comment]
I experimented by dropping the redis URL config in this command and got the same error, so it seems that the configuration may not be getting picked up?

```
docker run --rm -p 5000:5000 \
-e TALK_INSTALL_LOCK=false \
-e TALK_JWT_SECRET=LOVETOCOMMENT \
-e TALK_MONGO_URL=mongodb://mongo/talk \
-e TALK_REDIS_URL=redis://redis \
-e TALK_ROOT_URL=https://talk.notphilly.com \
-e TALK_FACEBOOK_APP_ID=5554432162346234 \
-e TALK_FACEBOOK_APP_SECRET=ZUCKISCOOL \
--link talk-redis:redis \
--link talk-mongo:mongo \
coralproject/talk:latest
```

**Comment by kgardnr** [comment]
Hi @davisshaver is this what you're seeing with the latest release version, or on master? We had this issue on master actually and merged a fix this morning. I'm wondering if that might fix it?

**Comment by davisshaver** [comment]
How about that! Thanks @kgardnr!! 🎉

**Comment by kgardnr** [comment]
Nice! 🎉 Thanks @davisshaver!
