### ISSUE TITLE
Regex errors in the admin

### ISSUE THREAD

**Issue by offensivepolitics** [coralproject/talk#883]
### Expected behavior
Posting a comment with text of `http://www.google.com/\` and the comment should appear in the moderation panel
### Actual behavior
The moderation panel hangs with the error in this screenshot:
![screen shot 2017-08-28 at 10 45 28 am](https://user-images.githubusercontent.com/60095/29778919-f8956f0e-8bde-11e7-926d-5aed46bfaa6e.png)

This problem occurs even if the backslash is not the final character in the comment.

### Steps to reproduce behavior

1. Posting a comment with this text of `http://www.google.com/\`
2. Visit admin panel

**Comment by alinhle** [comment]
Thanks for your report @offensivepolitics . This should be fixed in v3.3.0.
