### ISSUE TITLE
All comments are shown as flagged in mod queues.

### ISSUE THREAD

**Issue by jde** [coralproject/talk#89]
### Expected behavior

Only comments that have been flagged should show as flagged in the mod queues.

### Actual behavior

All comments are shown as flagged.

### Steps to reproduce behavior

* Create a comment on an asset no one will see to flag.
* Go to the mod queue.
* See that it is flagged.

**Comment by gabelula** [comment]
PR: 
https://github.com/coralproject/talk/pull/94

**Comment by wyattjoh** [comment]
Resolved as #94 was merged.
