### ISSUE TITLE
Top level domains over four characters not supported in talk user creation

### ISSUE THREAD

**Issue by darkpony** [coralproject/talk#891]
### Expected behavior
I can use any length TLD in my email address
lj@some.domain

### Actual behavior
lj@some.domain returns "Not a valid email"

### Steps to reproduce behavior
try to create a new account with an email account with the domain part longer than 4 characters.

**Comment by wyattjoh** [comment]
Thanks for that @darkpony! We're submitting a change that should correct that behaviour soon.
