### ISSUE TITLE
iframe embed headers prevent cross domain iframes

### ISSUE THREAD

**Issue by jde** [coralproject/talk#90]
### Expected behavior

We should be able to embed an iframe anywhere. (In the future we may want to create a whitelist)

### Actual behavior

Embedding iframes across domains causes an error:

'''Refused to display 'https://talk-stg.coralproject.net/embed/stream?initialWidth=1596&childId=co…eamEmbed&parentTitle=&parentUrl=http%3A%2F%2Flocalhost%3A7777%2Fembed.html' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.'''

### Steps to reproduce behavior

* Embed a comment stream across domains.
* Hit the page. Nothing will show.
* Look at the console.

**Comment by wyattjoh** [comment]
This is related to the helmet package that's in use:

https://github.com/helmetjs/helmet

We should create a whitelist of embeddable domains that would add the right headers.

**Comment by jde** [comment]
In order to allow people to control where their community embeds can be places, we can add a White List for allowed domains.  Keeping this issue open to track this problem as we build out the settings.
