### ISSUE TITLE
Add private:true to package.json

### ISSUE THREAD

**Issue by pdehaan** [coralproject/talk#924]
### Expected behavior
Add `"private": true` to package.json to prevent accidental `npm publish`, since it seems the name [**talk**](https://www.npmjs.com/package/talk) is already taken.
Alternatively, if this is something you'd eventually want to publish to npm, you'd need to give the package.json `name` something different.

### Actual behavior
No private.

### Steps to reproduce behavior
n/a

**Comment by wyattjoh** [comment]
I'll submit a PR in a moment!
