### ISSUE TITLE
Audit package.json for unused/missing dependencies

### ISSUE THREAD

**Issue by pdehaan** [coralproject/talk#925]
### Steps to reproduce behavior

1. `npm i depcheck -D`
1. `$(npm bin)/depcheck --ignore-dirs=plugins --ignores=*-loader,babel-*,plugin-api,talk-plugin-*,cli-table,semver,colors,fs-extra,ejs,moment,plugins,pluginsConfig,cross-spawn,did-you-mean,inquirer,node-emoji,graphql-tag,eslint-config-*,depcheck,mocha-*,pre-git`

### Expected behavior

Fewer results.

### Actual behavior

```
$(npm bin)/depcheck --ignore-dirs=plugins --ignores=*-loader,babel-*,plugin-api,talk-plugin-*,cli-table,semver,colors,fs-extra,ejs,moment,plugins,pluginsConfig,cross-spawn,did-you-mean,inquirer,node-emoji,graphql-tag,eslint-config-*,depcheck,mocha-*,pre-git,classnames

Unused dependencies
* postcss-modules
* query-strings

Unused devDependencies
* eslint-module-utils
* supertest

Missing dependencies
* actions
* components
* containers
* coral-admin
* coral-configure
* coral-embed-stream
* coral-framework
* coral-settings
* coral-sign-in
* coral-ui
* graphql-anywhere
* qs
* query-string
* routes
```

Sorry, the command is a bit convoluted. I was trying to go through and explicitly ignore webpack loaders, babel bits, webpack aliases, packages from ./bin/*... But I still notice we have references to "query-strings", "query-string", and "qs".

**Comment by wyattjoh** [comment]
Will take a look into these deps @pdehaan, thanks for reviewing!
