### ISSUE TITLE
Required Configuration Variables?

### ISSUE THREAD

**Issue by abattenburg** [coralproject/talk#947]
In the **Installation** section of the documentation for **Source**, the documentation references _required configuration variables_ located in the **README.md**. However I couldn't find anything in the README or the community forums. Is there somewhere else I should be looking for what to populate my **.env** file with? 

Thank you for your direction and the work on this project -- I'm excited to try it out!

**Comment by wyattjoh** [comment]
Seems this was overlooked in our documentation update @abattenburg! Check out https://coralproject.github.io/talk/docs/running/configuration/ for the configuration! Thanks for the report.
