### ISSUE TITLE
Typo in embed code

### ISSUE THREAD

**Issue by mrflos** [coralproject/talk#953]
### Expected behavior
the url in the embed code should be valid
`<script src="https://mydomain.com/embed.js" ..>`

### Actual behavior
one / is missing so the url isn't valid
`<script src="https:`**/**`mydomain.com/embed.js" ..>`

### Steps to reproduce behavior
just go to admin/configure and select technical parameters
version 3.5.0

**Comment by wyattjoh** [comment]
Can you check @mrflos if your `TALK_ROOT_URL` environment variable contains the `https://`? That portion of the embed is loaded from the environment.

**Comment by mrflos** [comment]
Yes, it contains the full url.. :  
`TALK_ROOT_URL=https://mydomain.com`

Also the second time, it is written correctly:  
```
<div id="coral_talk_14318951661098045"></div>
<script src="https:/mydomain.com/embed.js" async onload="
  Coral.Talk.render(document.getElementById('coral_talk_14318951661098045'), {
    talk: 'https://mydomain.com/'
  });
"></script>
```

**Comment by wyattjoh** [comment]
Great catch! Can you see if the version on this branch resolves your issue? https://github.com/coralproject/talk/pull/954

**Comment by mrflos** [comment]
Yes! It solved my problem! thanks!  
I let you decide when to close the issue.  
Best regards and that was a quick fix! 🎉
