### ISSUE TITLE
Deprecated use of subscriptionManager in cli-serve

### ISSUE THREAD

**Issue by Mustika86** [coralproject/talk#961]
### Actual behavior
When I start up the docker container and cli-serve is ran, I get a warning/error that the deprecated subscriptionManager is used: 

talk_1   | $ ./bin/cli serve -j -w
talk_1   | subscriptionManager is deprecated, use `execute` or `subscribe` directly from `graphql-js`!

I am not sure if that is the reason, but I a am not able to access the webserver via localhost:5000

### Steps to reproduce behavior
User docker-machine and docker-compose up to start talk with the default docker-compose.yml from the [documentation](https://coralproject.github.io/talk/docs/install/docker/)

**Comment by wyattjoh** [comment]
The deprecation message shouldn't interfere with the application starting. When you visit `http://localhost:5000/admin/install` do you see the installation screen? By default, the application does not host the testing routes (`/, /assets/title/...`) in production.

**Comment by wyattjoh** [comment]
We're working to resolve the deprecation messages as we slowly upgrade packages.

**Comment by Mustika86** [comment]
Great! I was able to figure out why I was not able to access the webserver and as expected it was not related to the deprecation message. I use docker-machine and was not forwarding port 5000 in VirtualBox.

**Comment by wyattjoh** [comment]
I'll close this issue then as we already have plans in our roadmap to perform upgrading of those packages.
