### ISSUE TITLE
Default security settings of Helmet 

### ISSUE THREAD

**Issue by offensivepolitics** [coralproject/talk#962]
https://github.com/coralproject/talk/blob/cd100a23cbcd42ebaa7f1ce7ae6e3d92bae771d7/app.js#L29-L31

One of the security default security settings (HSTS) on Helmet has pretty far-reaching and hard-to-reverse consequences when Talk is served from a shared domain. Our main site is of course HTTPS, but several parts are still served under HTTP. I would be hard pressed to find a large publisher who didn't have something similar. Once the HSTS header was received by Chrome clients none of the HTTP portions of our site worked. This is entirely on me for not reading the source close enough. But the cleanup involved is heavy enough that I hope I can save other people the headache.

I don't believe this needs to be changed but perhaps defaults need to be explicit (like frameguard), or spelled out in the docs? Even something like "We use the industry standard library helmet to provide sensible and robust defaults for Expressjs security. Please click here to see what you're signing up for." would help.

**Comment by wyattjoh** [comment]
Excellent points. I'll make a point to resolve this asap.

**Comment by wyattjoh** [comment]
Let me know if the linked PR makes sense @offensivepolitics!

**Comment by offensivepolitics** [comment]
That looks like just what we'd need, thank you @wyattjoh
