### ISSUE TITLE
does Coral Talk require email? 

### ISSUE THREAD

**Issue by darkpony** [coralproject/talk#972]
I know that Coral talk has an option to not validate an EMAIL address but does the Coral system itself always require it? We would like to have 'No Email Required' functionality.

**Comment by kgardnr** [comment]
Currently, the default Talk auth plugin does require email for users to signup. If you wanted to alter that auth plugin to use, say, a username and password, without email, you can certainly do that. We don't currently have removing email addresses as part of our roadmap.

**Comment by kgardnr** [comment]
Let me know if that answers your questions @darkpony! :)

**Comment by darkpony** [comment]
Thank you! Is that a complicated change to make?

**Comment by kgardnr** [comment]
Hmm, after discussing more with the team it might not be as simple as that actually. It goes against our core authentication and privacy decisions we had made previously, so you would have to somehow manage login externally.

Is there a specific reason why you don't want to offer users the ability to login via email (as well as leverage functionality like forgetting their passwords, or receiving email notifications from Talk)?

**Comment by darkpony** [comment]
yes, our founder has been explicit that anonymity is a core principle for our brand. It goes to the heart of our mission and we must have an explicit way to allow 100% anonymous commenting on our platform.  Right now, the current platform  supports an email field but it does nothing with it. It doesn't check or store it.

We want to be able to support an anonymous whistleblower who feels like they could contribute to the conversation but don't want us or anyone else to know who they are.

**Comment by darkpony** [comment]
We are talking thru this on our end, thank you!

**Comment by kgardnr** [comment]
Ok great, thank you @darkpony!! What's the name of your organization? We'd love to have our product folks reach out directly to you and your founder and discuss upcoming needs like this one.
