### ISSUE TITLE
Localization of plugins

### ISSUE THREAD

**Issue by darkpony** [coralproject/talk#975]
We have seen localization of the default info in Coral Talk which is great! If we add custom plugin that has its own copy is there an easy centralized way to take advantage of the existing localization work being used for the default copy?

**Comment by kgardnr** [comment]
Awesome, thanks @darkpony! So each plugin can have its own translation files, here's an example: https://github.com/coralproject/talk/blob/master/plugins/talk-plugin-auth/client/translations.yml

Does that answer your question?

**Comment by darkpony** [comment]
thank you, makes sense!

**Comment by kgardnr** [comment]
Great, thank you @darkpony!
