### ISSUE TITLE
Remove facebook login

### ISSUE THREAD

**Issue by darkpony** [coralproject/talk#976]
We would like to remove the facebook login option.  Is there an easy way to do this with out doing a rewrite of the login component?

**Comment by kgardnr** [comment]
Hi @darkpony! The facebook auth is a plugin, so you can simply remove it from your `plugins.json` file and that should work.

https://github.com/coralproject/talk/blob/master/plugins.default.json

If you don't have a `plugins.json` file, it will default to the above default plugins file. So if you create a new `plugins.json` file, you can mix and match whatever plugins make sense for your use case.
