### ISSUE TITLE
Can we custom style a comment?

### ISSUE THREAD

**Issue by darkpony** [coralproject/talk#977]
we would like to give a single comment (a featured comment) a custom background color or some other visual cue. Is this possible without writing a custom plugin?

**Comment by kgardnr** [comment]
Hey @darkpony, Talk allows you to use a Custom CSS file, you can link to this in the Admin via Configure>Tech Settings. All (or at least the majority of, it's a WIP) Talk elements have css classes, so you can style them easily to fit your needs.
