### ISSUE TITLE
All comments in queues are showing as Anonymous

### ISSUE THREAD

**Issue by jde** [coralproject/talk#98]
### Actual behavior

Comments created by logged in users are showing as anonymous in the moderation queues.

The moderation queue feed isn't returning the user information for the author_ids:

https://talk-stg.coralproject.net/api/v1/queue/comments/pending

![screenshot 2016-11-28 11 42 40](https://cloud.githubusercontent.com/assets/259957/20677046/da3cc26a-b55f-11e6-9378-dd220373af00.png)

### Steps to reproduce behavior

Log into https://talk-stg.coralproject.net/admin with an admin account.
Note that all the comments are anonymous.
Note that the author_id's are present but the users are not coming back in the response.

**Comment by davidgljay** [comment]
Addressed in PR https://github.com/coralproject/talk/pull/113
