### ISSUE TITLE
EmbedLink component contains only one forward slash after http (e.g. http:/<host>)

### ISSUE THREAD

**Issue by jtnelson** [coralproject/talk#992]
I just got the latest Talk docker image and completed initial configuration via the web interface. On the "Configure" route (admin/configure) in the "<> Tech Settings", the "Embed Comment Stream" EmbedLink component only has one forward slash in the src attribute of the script tag populated by the embedText prop: <script src="http:/localhost:5000/embed.js"... It's a small issue, but could trip up some people evaluating the platform. Great work on the project; this is important work!

**Comment by wyattjoh** [comment]
It seems likely that the `TALK_ROOT_URL` was misconfigured. Can you post the contents of the `docker-compose.yml` file?

**Comment by kgardnr** [comment]
@jtnelson is this still an issue? Can you give us more details?
