### ISSUE TITLE
mobile media query text overflow gets truncated.

### ISSUE THREAD

**Issue by MrPhilbert** [coralproject/talk#993]
### Expected behavior
Text should reflow within its border on mobile devices

### Actual behavior
Text expands passed its border on the right and gets truncated.

### Steps to reproduce behavior
Observe comments on WaPo on mobile device (Galaxy Note 4 in my case).

**Comment by okbel** [comment]
@MrPhilbert Do you have a screenshot? Did you try this with a standalone iframe url? To check if this is on our side or on the page that its been embeded.
